 /*************************************************************************
                         Copyright Statement
                        VISTEON CONFIDENTIAL

  This is an unpublished work, which contains trade secrets, created in
  2022. Visteon Corporation owns all rights to this work and intends
  to maintain it in confidence to preserve its trade secret status. Visteon
  Corporation reserves the right, under the copyright laws of the United
  States or those of any other country that may have jurisdiction, to
  protect this work as an unpublished copyright work in the event of an
  inadvertent or deliberate unauthorized publication. Visteon Corporation
  also reserves its rights under the copyright laws to protect this work
  as a published work, when appropriate. Those having access to this work
  may not copy it, use it or disclose the information contained in it
  without the written authorization of Visteon Corporation.

  @file      ui\toyota\ui.toyota.dk.config\pharsar
  @author    gkullapp
  @brief     Declaration of warning enum.(Auto gen)
  @date      Dec 30, 2024

****************************************************************************/
#ifndef PHARSAR_HPP_
#define PHARSAR_HPP_

#include "MainPckg/HelperAPI/HelperAPI.h"
#include "DMsPckg/ButtonsPckg/ButtonsPckg.h"
#include "GlobalDmAccessors/GlobalDmAccessors.h" 
 class warning_enum{
        public:
          HMI_wrnType warnid_map[652] =
           {
            HMI_wrnType::WRN_NORM_BRLV_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_TFUEL_01 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_EPB_03 ,
            HMI_wrnType::WRN_NORM_EPB_04 ,
            HMI_wrnType::WRN_NORM_EPB_05 ,
            HMI_wrnType::WRN_NORM_EPB_08 ,
            HMI_wrnType::WRN_NORM_EPB_10 ,
            HMI_wrnType::WRN_NORM_EPB_11 ,
            HMI_wrnType::WRN_NORM_EPB_12 ,
            HMI_wrnType::WRN_NORM_EPB_13 ,
            HMI_wrnType::WRN_NORM_EPB_14 ,
            HMI_wrnType::WRN_NORM_EPB_15 ,
            HMI_wrnType::WRN_NORM_EPB_16 ,
            HMI_wrnType::WRN_NORM_EPB_17,
            HMI_wrnType::WRN_NORM_EPB_18,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_WASLEV_02 ,
            HMI_wrnType::WRN_NORM_BVOOPE_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_MLGT_01 ,
            HMI_wrnType::WRN_NORM_TPWSR_01 ,
            HMI_wrnType::WRN_NORM_TPWSR_02 ,
            HMI_wrnType::WRN_NORM_TPWSR_03 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_LEDHEA_01 ,
            HMI_wrnType::WRN_NORM_HEALEV_02 ,
            HMI_wrnType::WRN_NORM_HEALEV_03 ,
            HMI_wrnType::WRN_NORM_GRISHU_02 ,
            HMI_wrnType::WRN_NORM_AVAS_02 ,
            HMI_wrnType::WRN_NORM_ALOA_03 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_TRWIP_01 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_CVTOIL_02 ,
            HMI_wrnType::WRN_NORM_CVTOIL_03 ,
            HMI_wrnType::WRN_NORM_ATMAL_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_MCBW_02 ,
            HMI_wrnType::WRN_NORM_TPWS_01 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_FUECAP_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_ROLAWA_01 ,
            HMI_wrnType::WRN_NORM_ROLAWA_02 ,
            HMI_wrnType::WRN_NORM_ROLAWA_03 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_ONACCN_03 ,
            HMI_wrnType::WRN_NORM_BATLOW_02 ,
            HMI_wrnType::WRN_NORM_CHAMAL_02 ,
            HMI_wrnType::WRN_NORM_CHAMAL_03 ,
            HMI_wrnType::WRN_NORM_POWMAN_02 ,
            HMI_wrnType::WRN_NORM_SOCLOW_02 ,
            HMI_wrnType::WRN_NORM_SOCLOW_03 ,
            HMI_wrnType::WRN_NORM_BATINS_02 ,
            HMI_wrnType::WRN_NORM_BATINS_03 ,
            HMI_wrnType::WRN_NORM_BATINS_04 ,
            HMI_wrnType::WRN_NORM_BATINS_05 ,
            HMI_wrnType::WRN_NORM_ONACCP_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_BOS_02 ,
            HMI_wrnType::WRN_NORM_BOS_03 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_DSC_02 ,
            HMI_wrnType::WRN_NORM_DSC_03 ,
            HMI_wrnType::WRN_NORM_DSC_04 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_MAICER_09 ,
            HMI_wrnType::WRN_NORM_MAICER_10 ,
            HMI_wrnType::WRN_NORM_MAICER_11 ,
            HMI_wrnType::WRN_NORM_MAICER_12 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_ISA_02 ,
            HMI_wrnType::WRN_NORM_ISA_04 ,
            HMI_wrnType::WRN_NORM_TCBM_01 ,
            HMI_wrnType::WRN_NORM_TCBM_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_PROSRV_PROSRV_02 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_03 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_04 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_05 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_08 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_09 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_10 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_11 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_12 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_13 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_22 ,
            HMI_wrnType::WRN_PROSRV_PROSRV_23 ,
            HMI_wrnType::WRN_NORM_BATCOO_02 ,
            HMI_wrnType::WRN_NORM_BATCOO_03 ,
            HMI_wrnType::WRN_NORM_LDA_02 ,
            HMI_wrnType::WRN_NORM_LDA_03 ,
            HMI_wrnType::WRN_NORM_LDA_06 ,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_LTA_02 ,
            HMI_wrnType::WRN_NORM_LTA_03 ,
            HMI_wrnType::WRN_NORM_LTA_07 ,
            HMI_wrnType::WRN_NORM_LCA_02 ,
            HMI_wrnType::WRN_NORM_LCA_03 ,
            HMI_wrnType::WRN_NORM_LCA_04 ,
            HMI_wrnType::WRN_NORM_LCA_05 ,
            HMI_wrnType::WRN_NORM_LCA_15 ,
            HMI_wrnType::WRN_NORM_LCA_16 ,
            HMI_wrnType::WRN_NORM_LCA_17 ,
            HMI_wrnType::WRN_NORM_LCA_20 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_CHADYN_01 ,
            HMI_wrnType::WRN_NORM_CHADYN_02 ,
            HMI_wrnType::WRN_NORM_TOWWAR_02 ,
            HMI_wrnType::WRN_NORM_TOWWAR_03 ,
            HMI_wrnType::WRN_NORM_TOWWAR_05 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_ICYRA_01 ,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_DRIPOW_02 ,
            HMI_wrnType::WRN_NORM_DRIPOW_03 ,
            HMI_wrnType::WRN_NORM_DRIPOW_04,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_PEXI_02 ,
            HMI_wrnType::WRN_NORM_RESADJ_09 ,
            HMI_wrnType::WRN_NORM_RESADJ_10 ,
            HMI_wrnType::WRN_NORM_RESADJ_11 ,
            HMI_wrnType::WRN_NORM_RESADJ_12 ,
            HMI_wrnType::WRN_NORM_RESADJ_13 ,
            HMI_wrnType::WRN_NORM_RESADJ_14 ,
            HMI_wrnType::WRN_NORM_RESADJ_15 ,
            HMI_wrnType::WRN_NORM_TSMODE_02 ,
            HMI_wrnType::WRN_NORM_UNIOVE_02 ,
            HMI_wrnType::WRN_NORM_UNIOVE_04 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_TDOOR_01 ,
            HMI_wrnType::WRN_NORM_TDOOR_02 ,
            HMI_wrnType::WRN_NORM_TDOOR_03 ,
            HMI_wrnType::WRN_NORM_ACCHOL_02 ,
            HMI_wrnType::WRN_NORM_ACCHOL_03 ,
            HMI_wrnType::WRN_NORM_ACCHOL_05 ,
            HMI_wrnType::WRN_NORM_MAICER_09_RESADJ_09 ,
            HMI_wrnType::WRN_NORM_MAICER_09_RESADJ_10 ,
            HMI_wrnType::WRN_NORM_MAICER_09_RESADJ_11 ,
            HMI_wrnType::WRN_NORM_MAICER_09_RESADJ_12 ,
            HMI_wrnType::WRN_NORM_MAICER_09_RESADJ_13 ,
            HMI_wrnType::WRN_NORM_MAICER_09_RESADJ_14 ,
            HMI_wrnType::WRN_NORM_MAICER_09_RESADJ_15 ,
            HMI_wrnType::WRN_NORM_MAICER_11_RESADJ_09 ,
            HMI_wrnType::WRN_NORM_MAICER_11_RESADJ_10 ,
            HMI_wrnType::WRN_NORM_MAICER_11_RESADJ_11 ,
            HMI_wrnType::WRN_NORM_MAICER_11_RESADJ_12 ,
            HMI_wrnType::WRN_NORM_MAICER_11_RESADJ_13 ,
            HMI_wrnType::WRN_NORM_MAICER_11_RESADJ_14 ,
            HMI_wrnType::WRN_NORM_MAICER_11_RESADJ_15 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_MFLID_MFLID_01 ,
            HMI_wrnType::WRN_NORM_MFLID_02 ,
            HMI_wrnType::WRN_NORM_MFLID_03 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_DOOR_UNLMOD_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND1 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND2 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND3 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND4 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND5 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND6 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND7 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND8 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND9 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND10 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND11 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND12 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND13 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND14 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND15 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND16 ,
            HMI_wrnType::WRN_NORM_SYSMAL_HVIND17 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_GPF_MEV01_02 ,
            HMI_wrnType::WRN_NORM_GPF_MEV01_03 ,
            HMI_wrnType::WRN_NORM_GPF_MEV01_04 ,
            HMI_wrnType::WRN_NORM_GPF_MEV01_05 ,
            HMI_wrnType::WRN_NORM_GPF_MEV01_06 ,
            HMI_wrnType::WRN_NORM_GPF_MEV01_07 ,
            HMI_wrnType::WRN_NORM_GPF_MEV01_08 ,
            HMI_wrnType::WRN_NORM_VCOPE_02 ,
            HMI_wrnType::WRN_NORM_VCOPE_03 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_TSMODE_VM01_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_FCTA_01 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_SEA_VM01_02 ,
            HMI_wrnType::WRN_NORM_SEA_VM02_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_CLESON_02 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ02 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ03 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ04 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ05 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ06 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ07 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ08 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ09 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ10 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_REQ11 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_GWM08_REQ02 ,
            HMI_wrnType::WRN_NORM_TPMS_VM02_GWM08_REQ01 ,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_EXWUOC_04 ,
            HMI_wrnType::WRN_NORM_EXWUOC_06 ,
            HMI_wrnType::WRN_NORM_EXWUOC_10 ,
            HMI_wrnType::WRN_NORM_EXWUOC_16 ,
            HMI_wrnType::WRN_NORM_EXWUOC_17 ,
            HMI_wrnType::WRN_NORM_EXWUOC_18 ,
            HMI_wrnType::WRN_NORM_PBD_02 ,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_TMN_02 ,
            HMI_wrnType::WRN_NORM_TMN_03 ,
            HMI_wrnType::WRN_NORM_PEDPRO_03 ,
            HMI_wrnType::WRN_NORM_PEDPRO_04 ,
            HMI_wrnType::WRN_NORM_LEAUNF_02 ,
            HMI_wrnType::WRN_NORM_LEAUNF_04 ,
            HMI_wrnType::WRN_NORM_HCS_02 ,
            HMI_wrnType::WRN_NORM_HCS_03 ,
            HMI_wrnType::WRN_NORM_HCS_04 ,
            HMI_wrnType::WRN_NORM_HCS_05 ,
            HMI_wrnType::WRN_NORM_HCS_06 ,
            HMI_wrnType::WRN_NORM_HCS_07 ,
            HMI_wrnType::WRN_NORM_HCS_08 ,
            HMI_wrnType::WRN_NORM_HCS_09 ,
            HMI_wrnType::WRN_NORM_HCS_10 ,
            HMI_wrnType::WRN_NORM_HCS_11 ,
            HMI_wrnType::WRN_NORM_SCB_02 ,
            HMI_wrnType::WRN_NORM_ITS_02 ,
            HMI_wrnType::WRN_NORM_ITS_06 ,
            HMI_wrnType::WRN_NORM_ITS_MEV01_02 ,
            HMI_wrnType::WRN_NORM_ITS_MEV01_04 ,
            HMI_wrnType::WRN_NORM_ITS_MEV01_05 ,
            HMI_wrnType::WRN_NORM_ITS_MEV01_06 ,
            HMI_wrnType::WRN_NORM_MAPACC_02 ,
            HMI_wrnType::WRN_NORM_OAA_03 ,
            HMI_wrnType::WRN_NORM_OAA_04 ,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_LCA_30 ,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_NLOCK_02 ,
            HMI_wrnType::WRN_NORM_ATFWRN_02 ,
            HMI_wrnType::WRN_NORM_LTA_04,
            HMI_wrnType::WRN_NORM_LTA_05,
            HMI_wrnType::WRN_NORM_LTA_06,
            HMI_wrnType::WRN_NORM_LTA_08,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_PCL_02,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_LDA_04,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_TRANSPORT_TPACP_REQ02,
            HMI_wrnType::WRN_NORM_DRS_02,
            HMI_wrnType::WRN_NORM_DRS_03,
            HMI_wrnType::WRN_NORM_PLOCK_02,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_02,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_03,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_04,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_05,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_06,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_07,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_08,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_09,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_10,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_11,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_12,
            HMI_wrnType::WRN_NORM_ADUOFF_VM01_13,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::WRN_NORM_ADUOFF_VM02_02,
            HMI_wrnType::WRN_NORM_ADUOFF_VM02_03,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None,
            HMI_wrnType::None
    };
};
#endif
