# *********************************************************************************************************************
# Company:             Johnson Controls Inc.
# ---------------------------------------------------------------------------------------------------------------------
# Copyright:           This software is JCI property.
#                      Duplication or disclosure without JCI written authorization is prohibited.
# ---------------------------------------------------------------------------------------------------------------------
# Project:             E40_Platform
# Language:            Apache ANT Properties
# ---------------------------------------------------------------------------------------------------------------------
#      DO NOT CHANGE THIS FILE! IT HAS BEEN GENERATED. ANY CHANGES WILL BE OVERWRITTEN AT THE NEXT GENERATION!
# ---------------------------------------------------------------------------------------------------------------------
# Generated on Tue Aug 06 13:07:41 IST 2024 by the JCI UML Generation chain from the "E40_Platform" model.
# ---------------------------------------------------------------------------------------------------------------------
# Entity:              LIB_STMEngine (Library)
# Description:         None
# Owner:               STM_ENGINE (Package)
# ---------------------------------------------------------------------------------------------------------------------
# Rhapsody version:    9.0.1
# Generator version:   V3.0.27
# Generator date:      11/12/2014 12:04:26,40
# ---------------------------------------------------------------------------------------------------------------------
package.name=STM_ENGINE
package.path=A2T_TC_out/A2T_TC_FWK/STM_ENGINE/
package.unit.file.path=A2T_TC_out/A2T_TC_FWK/STM_ENGINE/STM_ENGINE.sbs
name=A2T_TC.A2T_TC_FWK.STM_ENGINE.LIB_STMEngine
stereotype=Library
directory=A2T_TC_out/A2T_TC_FWK/STM_ENGINE/LIB_STMEngine
description=""

