/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_identifiers.h                                 
**                                                                            
** Description:    This file contains the language identifier interfaces      
**                 Autogenerated by LanguageEncoder.exe Version : 1.1.0.22.          
**                 Do not handmodify this file								  
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_LANGUAGE_IDENTIFIERS_H
#define HMI_LANGUAGE_IDENTIFIERS_H
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#ifndef WIN32
#include "wchar.h"
#endif

/*============================================================================
** T Y P E   D E F I N I T I O N S                                                  
**==========================================================================*/
#ifndef LNG_UNICODE
   #define LNG_UNICODE
#endif /* LNG_UNICODE */

/* Release label major version 4 */
/* Release label minor version 12 */
#define HMI_LANG_CORE_TOOL_LABEL                  "LANG_TOOL_LABEL::rel-UI-CORE-ICEAPPLE-4.12"
#define HMI_LANG_CORE_TOOL_MAJOR_VERSION          4
#define HMI_LANG_CORE_TOOL_MINOR_VERSION          12
#define HMI_LANG_CORE_TOOL_VERSION                ((HMI_LANG_CORE_TOOL_MAJOR_VERSION * 100) + HMI_LANG_CORE_TOOL_MINOR_VERSION)

#define   HMI_LANGUAGE_FRENCH_FEAT
#define   HMI_LANGUAGE_ENGLISH_UK_FEAT
#define   HMI_LANGUAGE_ITALIAN_FEAT
#define   HMI_LANGUAGE_GERMAN_FEAT
#define   HMI_LANGUAGE_SPANISH_FEAT
#define   HMI_LANGUAGE_DUTCH_FEAT
#define   HMI_LANGUAGE_PORTUGUESE_FEAT
#define   HMI_LANGUAGE_TURKISH_FEAT
#define   HMI_LANGUAGE_POLISH_FEAT
#define   HMI_LANGUAGE_KOREAN_FEAT
#define   HMI_LANGUAGE_SWEDISH_FEAT
#define   HMI_LANGUAGE_FINNISH_FEAT
#define   HMI_LANGUAGE_BULGARIAN_FEAT
#define   HMI_LANGUAGE_SLOVENIAN_FEAT
#define   HMI_LANGUAGE_GREEK_FEAT
#define   HMI_LANGUAGE_HUNGARIAN_FEAT
#define   HMI_LANGUAGE_SLOVAK_FEAT
#define   HMI_LANGUAGE_CZECH_FEAT
#define   HMI_LANGUAGE_DANISH_FEAT
#define   HMI_LANGUAGE_ESTONIAN_FEAT
#define   HMI_LANGUAGE_LATVIAN_FEAT
#define   HMI_LANGUAGE_LITHUANIAN_FEAT
#define   HMI_LANGUAGE_ROMANIAN_FEAT
#define   HMI_LANGUAGE_PORTUGUESE_BRAZILIAN_FEAT
#define   HMI_LANGUAGE_RUSSIAN _FEAT
#define   HMI_LANGUAGE_CROATIAN_FEAT
#define   HMI_LANGUAGE_CHINESE_MANDARIN_FEAT
#define   HMI_LANGUAGE_ARABIC_FEAT
#define   HMI_LANGUAGE_SPANISH_LATIN_AMERICAN_FEAT
#define   HMI_LANGUAGE_IRANIAN_FEAT
#define   HMI_LANGUAGE_HEBREW_FEAT
#define   HMI_LANGUAGE_HINDI_FEAT
#define   HMI_LANGUAGE_INDONESIAN_FEAT
#define   HMI_LANGUAGE_JAPANESE_FEAT
#define   HMI_LANGUAGE_NORWEGIAN_FEAT
#define   HMI_LANGUAGE_ALBANESE_FEAT
#define   HMI_LANGUAGE_SERBIAN_FEAT
#define   HMI_LANGUAGE_UKRAINIAN_FEAT

typedef enum
{
   HMI_LANGUAGE_FRENCH,
   HMI_LANGUAGE_ENGLISH_UK,
   HMI_LANGUAGE_ITALIAN,
   HMI_LANGUAGE_GERMAN,
   HMI_LANGUAGE_SPANISH,
   HMI_LANGUAGE_DUTCH,
   HMI_LANGUAGE_PORTUGUESE,
   HMI_LANGUAGE_TURKISH,
   HMI_LANGUAGE_POLISH,
   HMI_LANGUAGE_KOREAN,
   HMI_LANGUAGE_SWEDISH,
   HMI_LANGUAGE_FINNISH,
   HMI_LANGUAGE_BULGARIAN,
   HMI_LANGUAGE_SLOVENIAN,
   HMI_LANGUAGE_GREEK,
   HMI_LANGUAGE_HUNGARIAN,
   HMI_LANGUAGE_SLOVAK,
   HMI_LANGUAGE_CZECH,
   HMI_LANGUAGE_DANISH,
   HMI_LANGUAGE_ESTONIAN,
   HMI_LANGUAGE_LATVIAN,
   HMI_LANGUAGE_LITHUANIAN,
   HMI_LANGUAGE_ROMANIAN,
   HMI_LANGUAGE_PORTUGUESE_BRAZILIAN,
   HMI_LANGUAGE_RUSSIAN ,
   HMI_LANGUAGE_CROATIAN,
   HMI_LANGUAGE_CHINESE_MANDARIN,
   HMI_LANGUAGE_ARABIC,
   HMI_LANGUAGE_SPANISH_LATIN_AMERICAN,
   HMI_LANGUAGE_IRANIAN,
   HMI_LANGUAGE_HEBREW,
   HMI_LANGUAGE_HINDI,
   HMI_LANGUAGE_INDONESIAN,
   HMI_LANGUAGE_JAPANESE,
   HMI_LANGUAGE_NORWEGIAN,
   HMI_LANGUAGE_ALBANESE,
   HMI_LANGUAGE_SERBIAN,
   HMI_LANGUAGE_UKRAINIAN,
   LNG_MAX_LANGUAGE_COUNT
} HMI_LANGUAGE_T;

#define HM_LANG_MAX_STRING_SIZE         34
#define T_No                            0x0000
#define sid_Blank_0_0                   0x0001
#define TXTID_10205_R1_FUEL_ECONOMY_L1  0x0002
#define TXTID_10205_R2_FUEL_HISTORY_L1  0x000F
#define TXTID_10205_R3_HOLD_L1          0x001C
#define TXTID_10205_R4_to_Reset_L1      0x0021
#define TXTID_10205_R5_Trip_A_Trip_B_L1 0x002A
#define TXTID_10205_R6_hours_L1         0x003A
#define TXTID_10205_R7_TPMS_L1          0x0040
#define TXTID_10205_R8_months_L1        0x0045
#define TXTID_10205_R9_day_L1           0x004C
#define TXTID_10205_R10_WARNINGS_L1     0x0050
#define TXTID_10205_R11_SETTINGS_L1     0x0059
#define TXTID_10205_R12_From_Language_sheet_L1                                              0x0062
#define TXTID_10205_R13_Brightness_L1   0x0069
#define TXTID_10205_R14_Clock_Settings_L1                                         0x0074
#define TXTID_10205_R15_DIMMING_CONTROL_L1                                          0x0083
#define TXTID_10205_R16_Increase_or_L1  0x0093
#define TXTID_10205_R17_decrease_brightness_L1                                              0x009F
#define TXTID_10205_R18_CLOCK_SETTINGS_L1                                         0x00B3
#define TXTID_10205_R19_Format_L1       0x00C2
#define TXTID_10205_R20_Confirm_Reset_L1                                        0x00C9
#define TXTID_10205_R21_Cancel_L1       0x00D7
#define TXTID_10205_R22_Reset_L1        0x00DE
#define TXTID_HEADER_Service_Interval_L1                                        0x00E4
#define TXTID_HEADER_Oil_Change_Interval_L1                                           0x00F5
#define TXTID_HEADER_Service_Due_Interval_L1                                            0x0109
#define TXTID_HEADER_COLON_L1           0x011E
#define TXTID_HEADER_12_HR_L1           0x0120
#define TXTID_HEADER_24_HR_L1           0x0126
#define TXTID_HEADER_Time_L1            0x012C
#define TXTID_HEADER_AM_L1              0x0133
#define TXTID_HEADER_PM_L1              0x0136
#define TXTID_HEADER_SET_L1             0x0139
#define TXTID_HEADER_Time_Format_L1     0x013D
#define TXTID_HEADER_CLEAN_L1           0x0149
#define TXTID_HEADER_DIESEL_FILTER_L1   0x014F
#define TXTID_HEADER_12_Hour_L1         0x015D
#define TXTID_HEADER_24_Hour_L1         0x0165
#define TXTID_HEADER_SERVICE_IN_L1      0x016D
#define TXTID_HEADER_AVERAGE_L1         0x0178
#define TXTID_HEADER_TIRE_PRESSURE_L1   0x0180
#define TXTID_HEADER_PRESSURE_REF_ONGOING_L1                                            0x018E
#define TXTID_HEADER_TYRE_PRESSURE_SET_L1                                         0x01A3
#define TXTID_HEADER_SET_TPW_LAUNCHED_L1                                        0x01B5
#define TXTID_HEADER_TYRE_PRESSURE_SET_TPW_L1                                             0x01C6
#define TXTID_HEADER_SERVICE_PAGE_TITLE_L1                                          0x01DC
#define TXTID_HEADER_OIL_IN_L1          0x01EF
#define TXTID_HEADER_HOLD_OK_TO_RESET_L1                                        0x01F6
#define TXTID_HEADER_TRIP_COMPUTER_A_L1 0x0207
#define TXTID_HEADER_TRIP_COMPUTER_B_L1 0x0217
#define TXTID_HEADER_AVE_L1             0x0227
#define TXTID_HEADER_TRIP_A_L1          0x022B
#define TXTID_HEADER_TRIP_B_L1          0x0232
#define TXTID_OK                        0x0239
#define TXTID_LOW                       0x023C
#define TXTID_PRESSURE                  0x0240
#define TXTID_SENSOR                    0x0249
#define TXTID_CHECK_1                   0x0250
#define TXTID_10207_6                   0x0256
#define TXTID_10205_R32_DIMMING_CONTROL 0x0268
#define TXTID_10205_R26_TYRE_PRESSURE   0x0278
#define TXTID_10205_R5_Trip_A           0x0286
#define TXTID_10205_R12_Trip_B          0x028D
#define TXTID_10205_R40_FUEL_HISTORY    0x0290
#define TXTID_10205_R41_DAYS            0x029D
#define TXTID_10203_9_FTR_RIGHT_TRIP_A_B_UNIT                                             0x02A2
#define TXTID_10203_2_FTR_RIGHT_DTE_UNIT                                        0x02A5
#define TXTID_10101_1_FTR_LEFT_ODO_UNIT 0x02A8
#define TXTID_10101_20T1_NOR_MODE_SPEED_UNIT                                            0x02AB
#define TXTID_10203_5_MNU_FE_AVG_UNIT_1 0x02B0
#define TXTID_10203_5_MNU_FE_AVG_UNIT_2 0x02B5
#define TXTID_10207_3_SERVICE_DUE_DISTANCE_UNIT                                               0x02BD
#define TXTID_10203_8_MNU_TRIPA_SPEED_UNIT                                          0x02C0
#define TXTID_10203_9_MNU_TRIPA_DISTANCE_UNIT                                             0x02C3
#define TXTID_10101_13_ERROR_PROG_L1    0x02C6
#define TXTID_10101_17_CHECK_L1         0x034C
#define TXTID_10101_18_CHECK_ANTI_THEFT_L1                                          0x04CD
#define TXTID_10101_23_CHECK_L1         0x06CE
#define TXTID_10101_24_CHECK_L1         0x0740
#define TXTID_10101_3_BATTERY_L1        0x07B2
#define TXTID_10101_4_BRAKING_SYSTEM_L1 0x09E9
#define TXTID_10101_5_ENGINE_FAILURE_L1 0x0BE9
#define TXTID_10101_8_CHECK_L1          0x0DD9
#define TXTID_10101_9_CHECK_L1          0x0E4B
#define TXTID_10109_40_0_REAR_BELT_L1   0x0F61
#define TXTID_10109_41_1_REAR_BELT_L1   0x1189
#define TXTID_10109_42_2_REAR_BELTS_L1  0x137E
#define TXTID_10109_43_3_REAR_BELTS_L1  0x1587
#define TXTID_10109_7_UNBUCKLING_L1     0x1777
#define TXTID_10207_2_SERVICE_L1        0x197A
#define TXTID_10207_3_SERVICE_DUE_L1    0x1C22
#define TXTID_10207_4_SERVICE_DUE_L1    0x1E2C
#define TXTID_10210_1_KEYCARD_L1        0x1EDA
#define TXTID_10217_1_CLEAN_L1          0x20D9
#define TXTID_10602_1_POWER_STEERING_L1 0x22A8
#define TXTID_10602_4_POWER_STEERING_L1 0x242E
#define TXTID_10602_9_POWER_STEERING_L1 0x24A0
#define TXTID_10603_4_CHECK_L1          0x2593
#define TXTID_10603_6_POWER_STEERING_L1 0x2605
#define TXTID_10603_7_POWER_STEERING_L1 0x2684
#define TXTID_10701_2_PARKING_BRAKE_L1  0x26F6
#define TXTID_10704_1_CHECK_HILL_START_L1                                         0x2928
#define TXTID_10801_1_SELECT_L1         0x2B67
#define TXTID_10801_2_SELECT_L1         0x2D02
#define TXTID_10801_3_SELECT_L1         0x2F08
#define TXTID_10801_6_PRESS_CLUTCH_L1   0x3097
#define TXTID_10801_7_NEUTRAL_L1        0x32E2
#define TXTID_10801_9_PRESS_CLUTCH_L1   0x33CC
#define TXTID_10801_1A_SELECT_L1        0x343E
#define TXTID_10801_2A_SELECT_L1        0x354D
#define TXTID_10802_1_KEYCARD_L1        0x35BF
#define TXTID_10802_11_NO_KEYCARD_L1    0x3738
#define TXTID_10802_12_KEYCARD_L1       0x398E
#define TXTID_10802_13_KEYCARD_L1       0x3A76
#define TXTID_10802_14_CHECK_L1         0x3AE8
#define TXTID_10802_15_CHECK_L1         0x3B5A
#define TXTID_10802_16_CHECK_L1         0x3BCC
#define TXTID_10802_2_PLEASE_L1         0x3C3E
#define TXTID_10802_3_PRESS_BRAKE_L1    0x3DC1
#define TXTID_10802_4_PRESS_CLUTCH_L1   0x3FE2
#define TXTID_10802_5_TURN_STEERING_L1  0x40F7
#define TXTID_10802_6_PLEASE_REMOVE_L1  0x4353
#define TXTID_10802_7_PLEASE_REMOVE_L1  0x4492
#define TXTID_10802_9_PRESS_AND_HOLD_L1 0x4504
#define TXTID_20102_1_STOP_AND_START_L1 0x4732
#define TXTID_20102_12_IGNITION_OFF_L1  0x48AA
#define TXTID_20102_14_AUTO_STOP_L1     0x4AAB
#define TXTID_20102_15_SELECT_P_THEN_L1 0x4C3E
#define TXTID_20102_3_STOP_AND_START_L1 0x4E56
#define TXTID_20102_4_CHECK_L1          0x4EDB
#define TXTID_20102_5_PRESS_CLUTCH_L1   0x4F65
#define TXTID_20102_6_PRESS_BRAKE_L1    0x4FD7
#define TXTID_20102_7_CLUTCH_L1         0x5049
#define TXTID_20102_8_PUT_IN_L1         0x5145
#define TXTID_20201_1_CHECK_L1          0x51BB
#define TXTID_20201_2_CHECK_ANTI_L1     0x522D
#define TXTID_20201_3_ENGINE_FAILURE_L1 0x53EB
#define TXTID_20201_4_ENGINE_FAILURE_L1 0x545D
#define TXTID_20210_3_LPG_INJECTION_L1  0x54CF
#define TXTID_20301_1_CHECK_L1          0x561F
#define TXTID_20301_11_CHECK_L1         0x5724
#define TXTID_20301_12_GEARBOX_L1       0x5796
#define TXTID_20301_14_COOL_GEARBOX_L1  0x595F
#define TXTID_20301_5_AUTO_GEARBOX_L1   0x5BEF
#define TXTID_20301_6_GEARLEVER_L1      0x5DB7
#define TXTID_20308_10_GEARLEVER_L1     0x5E46
#define TXTID_20308_16_GEARBOX_L1       0x5EB8
#define TXTID_20403_1_CHECK_L1          0x5F98
#define TXTID_20403_4_ESC_L1            0x6021
#define TXTID_20406_1_TRACTION_CONTROL_L1                                         0x60C8
#define TXTID_20406_2_TRACTION_CONTROL_L1                                         0x62BD
#define TXTID_20601_1_CRUISE_CONTROL_L1 0x635C
#define TXTID_20601_2_CRUISE_CONTROL_L1 0x6523
#define TXTID_20601_4_CHECK_L1          0x65B2
#define TXTID_20601_5_MEMORISED_L1      0x6672
#define TXTID_20601_6_CRUISE_CONTROL_L1 0x6823
#define TXTID_20602_1_SPEED_LIMITER_L1  0x6895
#define TXTID_20602_2_SPEED_LIMITER_L1  0x6AAC
#define TXTID_20602_4_CHECK_L1          0x6B64
#define TXTID_20602_5_MEMORISED_L1      0x6C28
#define TXTID_20602_6_SPEED_LIMITER_L1  0x6C99
#define TXTID_30101_1_CHECK_L1          0x6D0B
#define TXTID_30103_1_BRAKING_SYSTEM_L1 0x6DAF
#define TXTID_30103_2_BRAKING_SYSTEM_L1 0x6E21
#define TXTID_30106_1_CHECK_L1          0x6E93
#define TXTID_30201_1_CHECK_TYRE_L1     0x6F74
#define TXTID_30201_1T_CHECK_TYRE_L1    0x71B3
#define TXTID_30201_1_PRESSURE_SENSORS_L2                                         0x7225
#define TXTID_30201_1T_PRESSURE_SENSORS_L2                                          0x742F
#define TXTID_30201_10_CHECK_TYRE_L1    0x749F
#define TXTID_30201_10T_CHECK_TYRE_L1   0x765D
#define TXTID_30201_15_PRESSURE_REF_L1  0x76CF
#define TXTID_30201_17_TYRE_PRESSURE_L1 0x7B0B
#define TXTID_30201_7_ADJUST_L1         0x7ECA
#define TXTID_30201_8_PUNCTURE_L1       0x80A6
#define TXTID_30202_10_SET_TPW_L1       0x81D4
#define TXTID_30202_11_RECALIBRATE_L1   0x84AC
#define TXTID_30202_11T_RECALIBRATE_L1  0x8660
#define TXTID_30202_5_INFLATE_TYRES_L1  0x86D2
#define TXTID_30202_6_CHECK_L1          0x892B
#define TXTID_30202_6T_CHECK_L1         0x8A11
#define TXTID_30202_7_CHECK_L1          0x8A83
#define TXTID_30202_7T_CHECK_L1         0x8AF5
#define TXTID_30202_8_TPW_L1            0x8B67
#define TXTID_30202_8T_TPW_L1           0x8C0F
#define TXTID_30202_9_TYRE_PRESSURE_L1  0x8C81
#define TXTID_50101_1_CHECK_L1          0x8FCC
#define TXTID_50101_3_CHECK_L1          0x9084
#define TXTID_50101_4_CHECK_L1          0x90F6
#define TXTID_70107_1_AUTO_DOOR_LOCK_L1 0x9168
#define TXTID_70107_3_AUTO_DOOR_LOCK_L1 0x93C8
#define TXTID_70114_1_REAR_ELECTRIC_L1  0x9456
#define TXTID_70114_2_REAR_ELECTRIC_L1  0x96AD
#define TXTID_70207_1_BOOT_L1           0x9760
#define TXTID_70207_2_BOOT_L1           0x98D1
#define TXTID_70207_3_DOOR_L1           0x9943
#define TXTID_70207_4_DOOR_L1           0x9A2E
#define TXTID_70503_1_STEERING_WHEEL_L1 0x9AA2
#define TXTID_70503_2_CHECK_ANTI_THEFT_L1                                         0x9BF6
#define TXTID_70503_4_RISK_OF_L1        0x9C83
#define TXTID_90102_8_CHECK_L1          0x9D46
#define TXTID_90502_1_BATTERY_LOW_L1    0x9DB8
#define TXTID_10101_13_ERROR_PROG_L2    0x9FE0
#define TXTID_10101_17_VEHICLE_L2       0xA00A
#define TXTID_10101_18_SYSTEM_L2        0xA14A
#define TXTID_10101_23_VEHICLE_L2       0xA31A
#define TXTID_10101_24_VEHICLE_L2       0xA392
#define TXTID_10101_3_CHARGING_FAULT_L2 0xA405
#define TXTID_10101_4_FAULT_L2          0xA579
#define TXTID_10101_5_HAZARD_L2         0xA6EC
#define TXTID_10101_8_VEHICLE_L2        0xA877
#define TXTID_10101_9_INJECTION_L2      0xA8EA
#define TXTID_10109_40_FASTENED_L2      0xAA6E
#define TXTID_10109_41_FASTENED_L2      0xAC19
#define TXTID_10109_42_FASTENED_L2      0xACFC
#define TXTID_10109_43_FASTENED_L2      0xADD3
#define TXTID_10109_7_REAR_BELT_L2      0xAE57
#define TXTID_10207_3_L2                0xB057
#define TXTID_10207_4_L2                0xB17F
#define TXTID_10210_1_BATTERY_LOW_L2    0xB354
#define TXTID_10217_1_DIESEL_FILTER_L2  0xB522
#define TXTID_10602_1_FAULT_L2          0xB6F1
#define TXTID_10602_4_FAULT_L2          0xB86D
#define TXTID_10602_9_FAULT_L2          0xB8DD
#define TXTID_10603_4_POWER_STEERING_L2 0xBA2A
#define TXTID_10603_6_FAULT_L2          0xBAA5
#define TXTID_10603_7_FAULT_L2          0xBB1D
#define TXTID_10701_2_ON_L2             0xBB8D
#define TXTID_10704_1_ASSISTANCE_L2     0xBCF8
#define TXTID_10801_1_NEUTRAL_L2        0xBF20
#define TXTID_10801_2_PARK_L2           0xC028
#define TXTID_10801_3_NEUTRAL_L2        0xC1E7
#define TXTID_10801_6_PLUS_START_L2     0xC2EC
#define TXTID_10801_7_PLUS_START_L2     0xC451
#define TXTID_10801_9_PLUS_START_L2     0xC4DA
#define TXTID_10801_1A_NEUTRAL_L2       0xC54C
#define TXTID_10801_2A_PARK_L2          0xC640
#define TXTID_10802_1_NOT_RECOGNISED_L2 0xC6AE
#define TXTID_10802_11_PRESS_AND_HOLD_L2                                        0xC8B8
#define TXTID_10802_12_NOT_DETECTED_L2  0xCADD
#define TXTID_10802_13_NOT_DETECTED_L2  0xCC94
#define TXTID_10802_14_VEHICLE_L2       0xCD06
#define TXTID_10802_15_VEHICLE_L2       0xCD79
#define TXTID_10802_16_VEHICLE_L2       0xCDEC
#define TXTID_10802_2_INSERT_CARD_L2    0xCE5F
#define TXTID_10802_3_PLUS_START_L2     0xD00F
#define TXTID_10802_4_PLUS_START_L2     0xD0CD
#define TXTID_10802_5_WHEEL_PLUS_START_L2                                         0xD17A
#define TXTID_10802_6_KEYCARD_L2        0xD27C
#define TXTID_10802_7_KEYCARD_L2        0xD33E
#define TXTID_10802_9_START_L2          0xD3AE
#define TXTID_20102_1_ACTIVATED_L2      0xD4D5
#define TXTID_20102_12_L2               0xD612
#define TXTID_20102_14_UNAVAILABLE_L2   0xD6CB
#define TXTID_20102_15_PRESS_START_L2   0xD8BA
#define TXTID_20102_3_DEACTIVATED_L2    0xDA13
#define TXTID_20102_4_STOP_AND_START_L2 0xDBAC
#define TXTID_20102_5_PLUS_START_L2     0xDC70
#define TXTID_20102_6_PLUS_START_L2     0xDCE2
#define TXTID_20102_7_L2                0xDD54
#define TXTID_20102_8_NEUTRAL_L2        0xDDFE
#define TXTID_20201_1_INJECTION_SYSTEM_L2                                         0xDE6B
#define TXTID_20201_2_POLLUTION_SYSTEM_L2                                         0xDEEB
#define TXTID_20201_3_HAZARD_L2         0xE0CF
#define TXTID_20201_4_HAZARD_L2         0xE141
#define TXTID_20210_3_FAULT_L2          0xE1B3
#define TXTID_20301_1_AUTO_GEARBOX_L2   0xE31A
#define TXTID_20301_11_AUTO_GEARBOX_L2  0xE4D3
#define TXTID_20301_12_RISK_OF_BREAKAGE_L2                                          0xE545
#define TXTID_20301_14_TEMPORARY_STOP_L2                                        0xE736
#define TXTID_20301_5_OVERHEATING_L2    0xE98F
#define TXTID_20301_6_TO_P_L2           0xEB10
#define TXTID_20308_10_TO_N_L2          0xEB9C
#define TXTID_20308_16_OVERHEATING_L2   0xEC01
#define TXTID_20403_1_ESC_L2            0xED28
#define TXTID_20403_4_OFF_L2            0xEDD9
#define TXTID_20406_1_OFF_L2            0xEEB9
#define TXTID_20406_2_ON_L2             0xEF87
#define TXTID_20601_4_CRUISE_CONTROL_L2 0xF06A
#define TXTID_20602_4_SPEED_LIMITER_L2  0xF1B9
#define TXTID_20602_5_L2                0xF358
#define TXTID_30101_1_ABS_L2            0xF3DD
#define TXTID_30103_1_FAULT_L2          0xF465
#define TXTID_30103_2_FAULT_L2          0xF4D7
#define TXTID_30106_1_BRAKING_SYSTEM_L2 0xF549
#define TXTID_30201_10_PRESSURE_SENSORS_L2                                          0xF6A3
#define TXTID_30201_10T_PRESSURE_SENSORS_L2                                           0xF861
#define TXTID_30201_7_TYRE_PRESSURE_L2  0xF8D3
#define TXTID_30201_8_L2                0xFA6D
#define TXTID_30202_11_SET_TPW_L2       0xFAB6
#define TXTID_30202_11T_SET_TPW_L2      0xFB9D
#define TXTID_30202_5_AND_SET_TPW_L2    0xFC0F
#define TXTID_30202_6_TPW_L2            0xFD75
#define TXTID_30202_6T_TPW_L2           0xFDFD
#define TXTID_30202_7_TPW_L2            0xFE6B
#define TXTID_30202_7T_TPW_L2           0xFED9
#define TXTID_30202_8_NOT_AVAILABLE_L2  0xFF47
#define TXTID_30202_8T_NOT_AVAILABLE_L2 0x100B2
#define TXTID_50101_1_AIRBAG_L2         0x1012E
#define TXTID_50101_3_AIRBAG_L2         0x10278
#define TXTID_50101_4_AIRBAG_L2         0x10307
#define TXTID_70107_1_ON_L2             0x10396
#define TXTID_70107_3_OFF_L2            0x104FD
#define TXTID_70114_1_WINDOWS_LOCKED_L2 0x10681
#define TXTID_70114_2_WINDOWS_UNLOCKED_L2                                         0x1086F
#define TXTID_70207_1_OPEN_L2           0x10A68
#define TXTID_70207_2_OPEN_L2           0x10B9A
#define TXTID_70207_3_OPEN_L2           0x10C2E
#define TXTID_70207_4_OPEN_L2           0x10D07
#define TXTID_70503_1_NOT_LOCKED_L2     0x10D98
#define TXTID_70503_2_SYSTEM_L2         0x10F62
#define TXTID_70503_4_STEERING_LOCKING_L2                                         0x10FD5
#define TXTID_90102_8_VEHICLE_L2        0x110B3
#define TXTID_90502_1_START_ENGINE_L2   0x11126
#define TXTID_30201_15_ONGOING_L2       0x11376
#define TXTID_30201_17_L2               0x113E8
#define TXTID_30202_10_LAUNCHED_L2      0x11498
#define TXTID_30202_9_SET_TPW_L2        0x1150A
/* Total Language Table Size = 69.37kBytes */
#define HM_LANG_MAX_PAGE                1
#define HM_LANG_MAX_SID                 0x11579u
#define HM_LANG_COMMON_MAX_SID          0x02C3u
#define HM_END_OF_SID                   (0xFFFFFFFFu)
#define HM_LANG_BUFFER_MAX_SIZE         (0x1157Cu)        /* This is the language database size */
typedef UINT32 LANG_SID_T;

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        08/12/09     JKANOZA                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                               
/* end of file =============================================================*/ 
#endif /* HMI_LANGUAGE_IDENTIFIERS_H */
