/** \brief Adc.h
 **
 ** Interface Adc
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

#ifndef ADC_H_INCLUDED
#define ADC_H_INCLUDED

/*==================[inclusions]============================================*/

#include <Adc_Types.h>
#include <Adc_Cfg.h>
#include <Adc_Irq.h>

/*==================[macros]================================================*/

/*---------------------[ADC Driver services IDs]----------------------------*/
/** \brief Service Id definition of the init service */
#define ADC_API_INIT                        (uint8)0U
/** \brief Service Id definition of the deinit service */
#define ADC_API_DEINIT                      (uint8)1U
/** \brief Service Id definition of the start group conversion service */
#define ADC_API_START_GROUP_CONVERSION      (uint8)2U
/** \brief Service Id definition of the stop group conversion service */
#define ADC_API_STOP_GROUP_CONVERSION       (uint8)3U
/** \brief Service Id definition of the read group service */
#define ADC_API_READ_GROUP                  (uint8)4U
/** \brief Service Id definition of the enable hardware trigger service */
#define ADC_API_ENABLE_HARDWARE_TRIGGER     (uint8)5U
/** \brief Service Id definition of the disable hardware trigger service */
#define ADC_API_DISABLE_HARDWARE_TRIGGER    (uint8)6U
/** \brief Service Id definition of the enable group notification service */
#define ADC_API_ENABLE_GROUP_NOTIFICATION   (uint8)7U
/** \brief Service Id definition of the disable group notification service */
#define ADC_API_DISABLE_GROUP_NOTIFICATION  (uint8)8U
/** \brief Service Id definition of the get group status service */
#define ADC_API_GET_GROUP_STATUS            (uint8)9U
/** \brief Service Id definition of the get version info service */
#define ADC_API_GET_VERSION_INFO            (uint8)10U
/** \brief Service Id definition of the get stream last pointer service */
#define ADC_API_GET_STREAM_LAST_POINTER     (uint8)11U
/** \brief Service Id definition of setup result buffer service */
#define ADC_API_SETUP_RESULT_BUFFER         (uint8)12U

/*------------------[Development errors]-------------------------------------*/
/** \brief API service called without module initialization */
#define ADC_E_UNINIT                        (uint8)0x0AU
/** \brief API service called while a conversion is ongoing */
#define ADC_E_BUSY                          (uint8)0x0BU
/** \brief API service called while no conversion was running */
#define ADC_E_IDLE                          (uint8)0x0CU
/** \brief ADC driver and hardware already initialized. */
#define ADC_E_ALREADY_INITIALIZED           (uint8)0x0DU
/** \brief API Adc_Init service called with an invalid configuration */
#define ADC_E_PARAM_CONFIG                  (uint8)0x0EU
/** \brief API service called with invalid data buffer pointer, NULL_PTR passed **/
#define ADC_E_PARAM_POINTER                 (uint8)0x14U
/** \brief API Adc_StopGroupConversion service called with an invalid group ID value */
#define ADC_E_PARAM_GROUP                   (uint8)0x15U
/** \brief API service called for a group configured in continuous mode */
#define ADC_E_WRONG_CONV_MODE               (uint8)0x16U
/** \brief API service called for a group not configured for the necessary trigger mode */
#define ADC_E_WRONG_TRIGG_SRC               (uint8)0x17U
/** \brief API service called for a group configured not to have notification */
#define ADC_E_NOTIF_CAPABILITY              (uint8)0x18U
/** \brief  Function called while result buffer pointer is not initialized */
#define ADC_E_BUFFER_UNINIT                 (uint8)0x19U

/*-------------[Vendor-specific development errors]-------------------------*/
/** The driver is not operable, because a version mismatch was detected. */
#define ADC_E_VERSION                       (uint8)0xA0U

/*------------------[AUTOSAR module version identification]---------*/

#if (defined ADC_AR_RELEASE_MAJOR_VERSION) /* to prevent double declaration */
#error ADC_AR_RELEASE_MAJOR_VERSION already defined
#endif /* if (defined ADC_AR_RELEASE_MAJOR_VERSION) */

/** AUTOSAR release major version */
#define ADC_AR_RELEASE_MAJOR_VERSION 4U


#if (defined ADC_AR_RELEASE_MINOR_VERSION) /* to prevent double declaration */
#error ADC_AR_RELEASE_MINOR_VERSION already defined
#endif /* if (defined ADC_AR_RELEASE_MINOR_VERSION) */

/** AUTOSAR release minor version */
#define ADC_AR_RELEASE_MINOR_VERSION 0U


#if (defined ADC_AR_RELEASE_PATCH_VERSION) /* to prevent double declaration */
#error ADC_AR_RELEASE_PATCH_VERSION already defined
#endif /* if (defined ADC_AR_RELEASE_PATCH_VERSION) */

/** AUTOSAR release revision version */
#define ADC_AR_RELEASE_PATCH_VERSION 3U

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#define ADC_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include "MemMap.h"

/** \brief Adc_DeInit
 **
 ** Returns all ADC HW Units to a state comparable to their power on reset state.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_DeInit(void);


/** \brief Adc_DisableGroupNotification
 **
 ** Disables the notification mechanism for the requested ADC Channel group.
 **
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_DisableGroupNotification
(
  VAR(Adc_GroupType, AUTOMATIC) Group
);


/** \brief Adc_DisableHardwareTrigger
 **
 ** Disables the hardware trigger for the requested ADC Channel group.
 **
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_DisableHardwareTrigger
(
  VAR(Adc_GroupType, AUTOMATIC) Group
);


/** \brief Adc_EnableGroupNotification
 **
 ** Enables the notification mechanism for the requested ADC Channel group.
 **
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_EnableGroupNotification
(
  VAR(Adc_GroupType, AUTOMATIC) Group
);


/** \brief Adc_EnableHardwareTrigger
 **
 ** Enables the hardware trigger for the requested ADC Channel group.
 **
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_EnableHardwareTrigger
(
  VAR(Adc_GroupType, AUTOMATIC) Group
);


/** \brief Adc_GetGroupStatus
 **
 ** Returns the conversion status of the requested ADC Channel group.
 **
 ** \return Conversion status for the requested group.
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 **
 */
extern FUNC(Adc_StatusType, AUTOMATIC) Adc_GetGroupStatus
(
  VAR(Adc_GroupType, AUTOMATIC) Group
);


/** \brief Adc_GetStreamLastPointer
 **
 ** Returns the number of valid samples per channel, stored in the result buffer.
 ** Reads a pointer, pointing to a position in the group result buffer. With the
 ** pointer position, the  results of all group channels of the last completed
 ** conversion round can be accessed.
 ** With the pointer and the return value, all valid group conversion results can
 ** be accessed (the user has to take the layout of the result buffer into account).
 **
 ** \return Number of valid samples per channel.
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 ** \param [out] PtrToSamplePtr   Pointer to result buffer pointer.
 **
 */
extern FUNC(Adc_StreamNumSampleType, AUTOMATIC) Adc_GetStreamLastPointer
(
  VAR(Adc_GroupType, AUTOMATIC) Group,
  P2VAR(P2VAR(Adc_ValueGroupType, AUTOMATIC, AUTOMATIC), AUTOMATIC, AUTOMATIC) PtrToSamplePtr
);


/** \brief Adc_GetVersionInfo
 **
 ** Returns the version information of this module.
 **
 ** \param [out] versioninfo   Pointer to where to store the version information of
 ** this module.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_GetVersionInfo
(
  P2VAR(Std_VersionInfoType, AUTOMATIC, AUTOMATIC) versioninfo
);


/** \brief Adc_Init
 **
 ** Initializes the ADC hardware units and driver.
 **
 ** \param [in] ConfigPtr   Pointer to configuration set in Variant PB
 ** (Variant PC  requires a NULL_PTR).
 **
 */
extern FUNC(void, AUTOMATIC) Adc_Init
(
  P2CONST(Adc_ConfigType, AUTOMATIC, AUTOMATIC) ConfigPtr
);


/** \brief Adc_ReadGroup
 **
 ** Reads the group conversion result of the last completed conversion round of
 ** the requested group and stores the channel values starting at the DataBufferPtr
 ** address. The group channel values are stored in ascending channel number order
 ** (in contrast to the storage layout of the result buffer if streaming access is
 ** configured).
 **
 ** \return E_OK:  results are available and written to the data buffer
 ** E_NOT_OK: no results are available or development error occurred
 ** 
 ** 
 ** \param [in] Group   Numeric ID of requested ADC channel group.
 ** \param [in] DataBufferPtr   ADC results of all channels of the selected group
 ** are stored in the data buffer addressed with the pointer.
 **
 */
extern FUNC(Std_ReturnType, AUTOMATIC) Adc_ReadGroup
(
  VAR(Adc_GroupType, AUTOMATIC) Group,
  P2VAR(Adc_ValueGroupType, AUTOMATIC, AUTOMATIC) DataBufferPtr
);


/** \brief Adc_SetupResultBuffer
 **
 ** Initializes ADC driver with the group specific result buffer start address
 ** where the conversion results will be stored. The application has to ensure that
 ** the application  buffer, where DataBufferPtr points to, can hold all the
 ** conversion results of the specified group. The initialization with
 ** Adc_SetupResultBuffer is required after reset, before a group conversion can be
 ** started.
 **
 ** \return E_OK:  result buffer pointer initialized correctly
 ** E_NOT_OK:  operation failed or development error occurred
 ** 
 ** 
 ** \param [in] Group   Numeric ID of requested ADC channel group.
 ** \param [in] DataBufferPtr   pointer to result data buffer
 **
 */
extern FUNC(Std_ReturnType, AUTOMATIC) Adc_SetupResultBuffer
(
  VAR(Adc_GroupType, AUTOMATIC) Group,
  P2VAR(Adc_ValueGroupType, AUTOMATIC, AUTOMATIC) DataBufferPtr
);


/** \brief Adc_StartGroupConversion
 **
 ** Starts the conversion of all channels of the requested ADC Channel group.
 **
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_StartGroupConversion
(
  VAR(Adc_GroupType, AUTOMATIC) Group
);


/** \brief Adc_StopGroupConversion
 **
 ** Stops the conversion of the requested ADC Channel group.
 **
 ** \param [in] Group   Numeric ID of requested ADC Channel group.
 **
 */
extern FUNC(void, AUTOMATIC) Adc_StopGroupConversion
(
  VAR(Adc_GroupType, AUTOMATIC) Group
);

#define ADC_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include "MemMap.h"

/*==================[end of file]===========================================*/

#endif /*!defined(ADC_H_INCLUDED)*/
