
#ifndef TS_BIT_LIB_H
#define TS_BIT_LIB_H

/** \brief AUTOSAR BSW Basic Software Modules
 **
 ** This file contains global macro definitions for the manipulation
 ** of bits.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/


/*==================[inclusions]=============================================*/

#include <Std_Types.h>         /* AUTOSAR standard types */
#include <TSAtomic_Lib_Arch.h> /* target specific macros */
#include <TSBit_Lib_Arch.h>    /* target specific bit manipulation macros */

/*==================[macros]=================================================*/


/* gcc is not able to handle these macros */
#if ( defined(__GHS_VERSION_NUMBER) || defined(__ICCARM__) )
/*------------------[TS_WRITE_BITS_TO_BYTE]--------------------------------------*/

#if (defined TS_WRITE_BITS_TO_BYTE) /* guard to prevent double definition */
#error TS_WRITE_BITS_TO_BYTE already defined
#endif /* if (defined TS_WRITE_BITS_TO_BYTE) */
/**
 ** Macro for writing one ore more bits in a sub-byte of a register. It is
 ** recommended to use this macro for writing set and clear bits located in a
 ** separate byte of a register without modifying the rest of that register.
 **
 ** Using this macro prevents a RMW operation on such registers thus providing
 ** better performance and preventing lost update problems when using concurrent
 ** accesses on such registers.
 ** 
 ** \param name         name of register, lowercase (e.g. usartn_sscr)
 ** \param unRegister   register variable which should be set (must be of union type)
 ** \param byte         sub-byte in TS_WRITE_BITS_TO_BYTE#unRegister (0, 1, ...)
 ** \param ...          one or more bit assignment(s) in TS_WRITE_BITS_TO_BYTE#byte 
 **                      of TS_WRITE_BITS_TO_BYTE#unRegister (format: ".u1BIT1 = 1, .u1BIT2 = 1")
 ** 
 ** \note The macro will write only the given byte of TS_WRITE_BITS_TO_BYTE#unRegister
 **       with the given bit mask. All remaining bits in that register
 **       byte which are not given will be written to '0'!
 **
 ** Usage example:
 **   
 **   // Set SGn_CR0:AMICLR to clear SGn_CR1:AMINT
 **   // (only byte0 of SGn_CR0 is written to preserve settings in byte1)
 **   TS_WRITE_BITS_TO_BYTE(sgn_cr0, SG0.unCR0, .u1AMICLR = 1);
 **/ 
/* MISRA-1 */ /* PRQA S 1030 3 */ /* variable argument list is supported in ARM. */
/* MISRA-1 */ /* PRQA S 881 4 */ /* Evaluation order of "##" does not affect the result of the operation. */
/* MISRA-1 */ /* PRQA S 3458 3 */ /* macro used as statement block. */
#define TS_WRITE_BITS_TO_BYTE(name, unRegister, byte, ...)      \
   { (*( un_L3_##name##_t *)&( unRegister )).stcFieldBytes.stcByte##byte## = \
   ( stc_##name##_field_byte##byte##_t ) { __VA_ARGS__ }; }

/*------------------[TS_WRITE_BITS_TO_REG]--------------------------------------*/

#if (defined TS_WRITE_BITS_TO_REG) /* guard to prevent double definition */
#error TS_WRITE_BITS_TO_REG already defined
#endif /* if (defined TS_WRITE_BITS_TO_REG) */
/**
 ** Macro for writing one ore more bits in a register by one register
 ** write operation. It is recommended to use this macro to initialize
 ** full registers with constant bit settings and to use this macro to set
 ** and clear bits located in a dedicated set/clear register.
 **
 ** Using this macro prevents RMW operations on registers thus providing
 ** better performance and preventing lost update problems when using concurrent
 ** accesses on such registers.
 ** 
 ** \param name         name of register, lowercase (e.g. usartn_sscr)
 ** \param unRegister   register variable which should be set (must be of union type)
 ** \param ...          one or more bit assignment(s) in TS_WRITE_BITS_TO_REG#unRegister
 **                       (format: ".u1BIT1 = 1, .u1BIT2 = 1")
 ** 
 ** \note The macro will write the full TS_WRITE_BITS_TO_REG#unRegister with the given bit mask.
 **       All remaining bits in TS_WRITE_BITS_TO_REG#unRegister which are not given will
 **       be written to '0'!
 **
 ** Usage example:
 **   
 **   // Set ADCn_CSC1:INTC and ADCn_CSC1:PAUSC to clear ADCn_CS1:INT and ADCn_CS1:PAUS bits
 **   TS_WRITE_BITS_TO_REG(adcn_csc1, ADC0.unCSC1, .u1INTC = 1, .u1PAUSC = 1);
 **   TS_WRITE_BITS_TO_REG(sysc_rstcntr, SYSC.unRSTCNTR, .u8SWRST  = SWRST_trigger_value);
 **/ 
/* MISRA-1 */ /* PRQA S 1030 4 */ /* variable argument list is supported in ARM. */
/* MISRA-1 */ /* PRQA S 881 4 */ /* Evaluation order of "# #" does not affect the result of the operation. */
/* MISRA-1 */ /* PRQA S 3458 3 */ /* macro used as statement block. */
/* MISRA-1 */ /* PRQA S 3410 2*/ /* Since using a macro argument against type, can not  add the parentheses. */
#define TS_WRITE_BITS_TO_REG(name, unRegister, ...)   \
             { unRegister.stcField = (mcal_stc_##name##_field_t) { __VA_ARGS__ }; } 

#endif /* #if ( defined(__GHS_VERSION_NUMBER) || defined(__ICCARM__) ) */

#endif /* ifndef TS_BIT_LIB_H */
/*==================[end of file]============================================*/
