

[VMF_185]
; connection to Joerg's Notebook Win7 192.168.1.185
device_type=TCP
local_port=42131		          ; local listening port
local_groups=1, 2,03,4-22	      ; vmf-groups comma separated
remote_ip=192.168.1.185 	      ; ip address of remote-vmf mi server
remote_port=42130	              ; port of remote-vmf mi server (vmf messages are send to that ; ip and port)

