
[VMF_TTY]
; connection via character device
device_type=CHAR                 ; VMQ character device
local_device=COM1                ; mi transfer messages are read from that device and send to vmf 
local_groups=1-119,127-250     	 ; vmf-groups comma separated
remote_device=COM1               ; remote device name  - received vmf messages are send to this device 
allow_backfire=1                 ; allow backfiring
compression=1                    ; lzrw compression   
