/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_identifiers.h                                 
**                                                                            
** Description:    This file contains the language identifier interfaces      
**                 Autogenerated by LanguageEncoder.exe Version : 1.1.0.22.          
**                 Do not handmodify this file								  
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_LANGUAGE_IDENTIFIERS_H
#define HMI_LANGUAGE_IDENTIFIERS_H
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#ifndef WIN32
#include "wchar.h"
#endif

/*============================================================================
** T Y P E   D E F I N I T I O N S                                                  
**==========================================================================*/
#ifndef LNG_UNICODE
   #define LNG_UNICODE
#endif /* LNG_UNICODE */

/* Release label major version 4 */
/* Release label minor version 12 */
#define HMI_LANG_CORE_TOOL_LABEL                  "LANG_TOOL_LABEL::rel-UI-CORE-ICEAPPLE-4.12"
#define HMI_LANG_CORE_TOOL_MAJOR_VERSION          4
#define HMI_LANG_CORE_TOOL_MINOR_VERSION          12
#define HMI_LANG_CORE_TOOL_VERSION                ((HMI_LANG_CORE_TOOL_MAJOR_VERSION * 100) + HMI_LANG_CORE_TOOL_MINOR_VERSION)

#define   HMI_LANGUAGE_ARABIC_FEAT
#define   HMI_LANGUAGE_BRAZILIAN_PORTUGUESE_FEAT
#define   HMI_LANGUAGE_ENGLISH_FEAT
#define   HMI_LANGUAGE_FRENCH_FEAT
#define   HMI_LANGUAGE_INDONESIAN_BAHASA_FEAT
#define   HMI_LANGUAGE_MALAYSIAN_BAHASA_FEAT
#define   HMI_LANGUAGE_PORTUGUESE_FEAT
#define   HMI_LANGUAGE_SPANISH_FEAT
#define   HMI_LANGUAGE_THAI_FEAT
#define   HMI_LANGUAGE_TURKISH_FEAT

typedef enum
{
   HMI_LANGUAGE_ARABIC,
   HMI_LANGUAGE_BRAZILIAN_PORTUGUESE,
   HMI_LANGUAGE_ENGLISH,
   HMI_LANGUAGE_FRENCH,
   HMI_LANGUAGE_INDONESIAN_BAHASA,
   HMI_LANGUAGE_MALAYSIAN_BAHASA,
   HMI_LANGUAGE_PORTUGUESE,
   HMI_LANGUAGE_SPANISH,
   HMI_LANGUAGE_THAI,
   HMI_LANGUAGE_TURKISH,
   LNG_MAX_LANGUAGE_COUNT
} HMI_LANGUAGE_T;

#define HM_LANG_MAX_STRING_SIZE         80
#define Home_Apple_CarPlay              0x0000
#define Info_Time                       0x000E
#define Info_Date                       0x0011
#define User_Off_Info_Time              0x0015
#define Scr_Tuner_Freq_Main             0x0018
#define Scr_Tuner_Prog_Station_Name     0x001B
#define Scr_Tuner_AM                    0x001E
#define Button_Tuner_AM                 0x0021
#define Scr_Tuner_AST                   0x0024
#define Scr_Tuner_kHz                   0x0028
#define Scr_Tuner_MHz                   0x002C
#define Settings_BT_Device_Name         0x0030
#define Numeric_0                       0x0033
#define Numeric_1                       0x0035
#define Numeric_2                       0x0037
#define Numeric_3                       0x0039
#define Numeric_4                       0x003B
#define Numeric_5                       0x003D
#define Numeric_6                       0x003F
#define Numeric_7                       0x0041
#define Numeric_8                       0x0043
#define Numeric_9                       0x0045
#define Phone_Incoming_Call_Number      0x0047
#define Phone_Incoming_Call_Name        0x004A
#define Src_Bluetooth_NowPlaying        0x004D
#define Src_Ipod_NowPlaying             0x0050
#define Popup_Gen_Language_SuccessChange_Line2                                              0x0055
#define Settings_System_Discoverable_ON_L2_90                                             0x0058
#define Popup_Phone_Passkey_Match_text_Line1                                            0x005B
#define Popup_Pairing_In_Progress_L1    0x005E
#define Settings_BT_Max_Device_Deletion_L2                                          0x0061
#define Popup_Phone_Deleted_L1          0x0064
#define Popup_Disconnection_For_New_L1  0x0067
#define Popup_Support_Wireless_AA_L2    0x006A
#define Popup_Connecting_AA_L1          0x006D
#define Popup_Connecting_CP_L1          0x0070
#define Popup_AAConnection_InProgress_L1                                        0x0073
#define Popup_Switch_From_To_L1         0x0076
#define Popup_Android_Terminate_Android_L3                                          0x0079
#define Popup_Apple_Terminate_Apple_L3  0x007D
#define Popup_Android_Active_Disconnect_L2                                          0x0080
#define Popup_Apple_Active_Disconnect_L2                                        0x0083
#define Setting_WiFi_Network_Name       0x0086
#define SBN_RVC_Call_Number_Name        0x0089
#define Scr_ETM_HW_Version_Number       0x008C
#define Scr_ETM_Software_HOST_Number    0x008F
#define Scr_ETM_Software_VIP_Number     0x0092
#define Scr_ETM_Software_VCID_Number    0x0095
#define Scr_ETM_Software_VSW            0x0098
#define Scr_ETM_Software_VSW_Number     0x009D
#define Scr_ETM_Vehicle_VIN_Number      0x00A0
#define Scr_GPS_Signal_Strength_Number  0x00A3
#define Scr_GPS_Signal_Coordinates_Number                                         0x00A6
#define Scr_WiFi_SSID_Number            0x00A9
#define Scr_Operation_Mode_N            0x00AC
#define Scr_WiFi_IP_Netmask_Number      0x00AE
#define Set_Blank                       0x00B1
#define Home_Radio                      0x00B2
#define Home_Phone                      0x00E1
#define Home_Android_Auto               0x0129
#define Home_Media                      0x015B
#define Home_BT_Audio                   0x019C
#define Home_Device_List                0x01E5
#define Home_Settings                   0x0289
#define User_Off_Info_Date_SUNDAY       0x02E4
#define User_Off_Info_Date_MONDAY       0x0327
#define User_Off_Info_Date_TUESDAY      0x0375
#define User_Off_Info_Date_WEDNESDAY    0x03BE
#define User_Off_Info_Date_THURSDAY     0x0410
#define User_Off_Info_Date_FRIDAY       0x0463
#define User_Off_Info_Date_SATURDAY     0x04AE
#define User_Off_Info_Date_SUN          0x04EF
#define User_Off_Info_Date_MON          0x051C
#define User_Off_Info_Date_TUE          0x054A
#define User_Off_Info_Date_WED          0x0573
#define User_Off_Info_Date_THU          0x059A
#define User_Off_Info_Date_FRI          0x05C2
#define User_Off_Info_Date_SAT          0x05EB
#define User_Off_Info_Date_20_SEP_2019  0x0612
#define Scr_Tuner_Preset_Freq           0x0633
#define Scr_Tuner_Preset_Num            0x0655
#define Scr_Tuner_FM                    0x0677
#define Button_Tuner_FM                 0x0696
#define Scr_Tuner_Seek                  0x06B4
#define Scr_Tuner_Autostore_in_progress 0x0742
#define Scr_Tuner_No_Stations_Found     0x085E
#define Brws_Phonebook_Downloading      0x091D
#define Scr_Phone_Contacts              0x0A42
#define Brws_Phone_No_Contact           0x0A9B
#define Scr_Phone_Call_Log              0x0BA1
#define Brws_Phone_No_Call_logs         0x0C24
#define Brws_Phone_All                  0x0D14
#define Brws_Phone_Dialled              0x0D50
#define Brws_Phone_Received             0x0D9C
#define Brws_Phone_Missed               0x0DEA
#define Scr_Phone_Dial_Pad              0x0E3B
#define Brws_Phone_123                  0x0EA5
#define Brws_Phone_A                    0x0EC9
#define Brws_Phone_B                    0x0EDE
#define Brws_Phone_C                    0x0EF3
#define Brws_Phone_D                    0x0F08
#define Brws_Phone_E                    0x0F1D
#define Brws_Phone_F                    0x0F32
#define Brws_Phone_G                    0x0F47
#define Brws_Phone_H                    0x0F5C
#define Brws_Phone_I                    0x0F71
#define Brws_Phone_J                    0x0F86
#define Brws_Phone_K                    0x0F9B
#define Brws_Phone_L                    0x0FB0
#define Brws_Phone_M                    0x0FC5
#define Brws_Phone_N                    0x0FDA
#define Brws_Phone_O                    0x0FEF
#define Brws_Phone_P                    0x1004
#define Brws_Phone_Q                    0x1019
#define Brws_Phone_R                    0x102E
#define Brws_Phone_S                    0x1043
#define Brws_Phone_T                    0x1058
#define Brws_Phone_U                    0x106D
#define Brws_Phone_V                    0x1082
#define Brws_Phone_W                    0x1097
#define Brws_Phone_X                    0x10AC
#define Brws_Phone_Y                    0x10C1
#define Brws_Phone_Z                    0x10D6
#define Phone_Incoming_Call             0x10EB
#define Phone_Outgoing_Call             0x115F
#define Phone_Ongoing_Call              0x11BE
#define Phone_Mute_Call                 0x123B
#define Phone_Unmute_Call               0x127C
#define Phone_Keypad                    0x12D7
#define Phone_End_Call                  0x1321
#define Phone_Hold_Call                 0x1383
#define Phone_Resume_Call               0x13C1
#define Phone_Swap_Call                 0x1414
#define Phone_Handsfree_Call            0x145E
#define Phone_Use_Phone_Call            0x14AD
#define Phone_Add_Call                  0x1513
#define Phone_Merge_Call                0x1550
#define Phone_On_Hold_Call              0x159B
#define Phone_Incoming_Call_Conference  0x1629
#define Phone_Incoming_Call_Manage      0x169C
#define Phone_Incoming_Call_Manage_Conference_Call                                                  0x16EE
#define Phone_Incoming_Call_Call_Ended  0x1824
#define Phone_Active_Call_In_Progress   0x18A4
#define Phone_Active_Call_On_Hold       0x1947
#define Phone_ConferenceCall_Participants                                         0x19C3
#define Phone_Incoming_Call_PrivateNumber                                         0x1A3C
#define Src_USB_NowPlaying              0x1ABC
#define Brws_Col1_Title_Browse          0x1ADD
#define Brws_Media_Audiobooks           0x1B21
#define Brws_Media_Podcasts             0x1B8C
#define Brws_Media_Folders              0x1BCA
#define Brws_Media_My_Music             0x1C1C
#define Brws_Media_Playlists            0x1C80
#define Brws_Media_Composers            0x1CEE
#define Brws_Media_Genres               0x1D4F
#define Brws_Media_Artists              0x1D8D
#define Brws_Media_Albums               0x1DD9
#define Brws_Media_Songs                0x1E1B
#define Brws_Media_Videos               0x1E69
#define Scr_Media_Video_Warning         0x1EAD
#define Brws_Media_iTunesRadio          0x2083
#define Brws_Media_ListEmpty            0x20CD
#define Brws_Media_Heading_Genre_1      0x214C
#define Brws_Media_Heading_Genre_2      0x216A
#define Brws_Media_Heading_Genre_3      0x2204
#define Brws_Media_Heading_Genre_4      0x2304
#define Brws_Media_Heading_Artist_1     0x2468
#define Brws_Media_Heading_Artist_2     0x248B
#define Brws_Media_Heading_Artist_3     0x2534
#define Brws_Media_Heading_Album_1      0x263C
#define Brws_Media_Heading_Album_2      0x266B
#define Brws_Media_Heading_Song         0x2711
#define Brws_Media_Heading_Playlist_1   0x2733
#define Brws_Media_Heading_Playlist_2   0x276D
#define Brws_Media_Heading_Composer_1   0x2846
#define Brws_Media_Heading_Composer_2   0x2864
#define Brws_Media_Heading_Composer_3   0x28FF
#define Brws_Media_Heading_Folder_1     0x29FF
#define Brws_Media_Heading_Folder_2     0x2A1D
#define Brws_Media_Heading_Folder_3     0x2AF7
#define Brws_Media_Heading_Audiobook    0x2C37
#define Brws_Media_Heading_Podcast      0x2C60
#define Brws_Media_Heading_RecentlyPlayed                                         0x2C7E
#define Settings_All_Settings           0x2D08
#define Settings_General                0x2DBB
#define Settings_Display                0x2DF4
#define Settings_Clock                  0x2E43
#define Settings_Bluetooth              0x2E7E
#define Settings_Audio                  0x2EA5
#define Settings_WiFi                   0x2ED5
#define Settings_Vehicle                0x2EFE
#define Settings_General_Title          0x2F4F
#define Settings_General_Language       0x2FF5
#define Settings_General_English        0x302D
#define Settings_General_Brazilian_Portuguese                                             0x3088
#define Settings_General_Spanish        0x3146
#define Settings_General_Indonesian_Bahasa                                          0x31A4
#define Settings_General_Malaysian_Bahasa                                         0x3251
#define Settings_General_French         0x32EF
#define Settings_General_Arabic         0x3344
#define Settings_General_Portuguese     0x3388
#define Settings_General_Turkish        0x33E8
#define Settings_General_Thai           0x342D
#define Popup_Gen_Lang_Confirm_Line1    0x347B
#define Popup_Gen_Lang_Confirm_Line2    0x35D6
#define Popup_Yes_Button                0x3706
#define Popup_No_Button                 0x372E
#define Popup_Gen_Language_Change_Line1 0x3759
#define Popup_Gen_Language_SuccessChange_Line1                                              0x3889
#define Popup_Gen_Language_Change_Error_L1                                          0x39C0
#define Popup_Genl_Language_Change_Error_L2                                           0x3B54
#define Settings_Gen_Factory_Reset      0x3C2A
#define Settings_Gen_Factory_Reset_Line1                                        0x3CAE
#define Settings_Gen_Factory_Reset_Line2                                        0x3F3D
#define Settings_Gen_Factory_Reset_Line3                                        0x4178
#define Settings_General_Confirm_Button 0x42FC
#define Popup_Gen_Factory_Reset_Process 0x434B
#define Popup_Gen_Factory_Reset_Complete                                        0x455F
#define Popup_Gen_Factory_Reset_Failed_L1                                         0x462C
#define Popup_Gen_Factory_Reset_Failed_L2                                         0x478A
#define Settings_General_About          0x47CA
#define Settings_General_About_Current_Version                                              0x481C
#define Settings_Display_Title          0x4916
#define Settings_Disp_User_Off          0x49E3
#define Settings_Disp_User_Off_Heading  0x4A75
#define Settings_Disp_User_Off_Line1    0x4BB4
#define Settings_Disp_User_Off_Line2    0x4DE4
#define Settings_Disp_User_Off_Mode     0x4FC1
#define Settings_Disp_User_Off_Mode_Heading                                           0x505A
#define Settings_Disp_User_Off_Mode_Line1                                         0x51B6
#define Settings_Disp_User_Off_Mode_Line2                                         0x542B
#define Settings_Disp_User_Off_Mode_Line3                                         0x556D
#define Settings_Disp_Brightness        0x5763
#define Settings_Disp_Brightness_Heading                                        0x57C1
#define Settings_Disp_Brightness_Unavailable                                            0x57DF
#define Settings_Clock_Title            0x5A01
#define Settings_Clock_Sync_To_GPS      0x5ABD
#define Settings_Clock_Sync_Date_Time_To_GPS                                            0x5B4D
#define Settings_Clock_Date             0x5C77
#define Settings_Clock_Set_Date         0x5CB3
#define Settings_Clock_Date_Format      0x5D30
#define Settings_Clock_DD_MM_YY         0x5DAD
#define Settings_Clock_MM_DD_YY         0x5E06
#define Settings_Clock_Set_Button       0x5E5F
#define Settings_Clock_JAN              0x5E97
#define Settings_Clock_FEB              0x5EC5
#define Settings_Clock_MAR              0x5EF4
#define Settings_Clock_APR              0x5F22
#define Settings_Clock_MAY              0x5F55
#define Settings_Clock_JUN              0x5F7C
#define Settings_Clock_JUL              0x5FA9
#define Settings_Clock_AUG              0x5FD9
#define Settings_Clock_SEP              0x600F
#define Settings_Clock_OCT              0x6040
#define Settings_Clock_NOV              0x6074
#define Settings_Clock_DEC              0x60A3
#define Settings_Clock_Time             0x60D4
#define Settings_Clock_Set_Time         0x6105
#define Settings_Clock_Time_Format      0x616D
#define Settings_Clock_12_Hour          0x61E4
#define Settings_Clock_24_Hour          0x6229
#define Settings_Clock_AM               0x626D
#define Settings_Clock_PM               0x628F
#define Setting_Clock_Time_Zone         0x62B0
#define Time_Zone_Niue                  0x6322
#define Time_Zone_Cook_Island           0x6412
#define Time_Zone_San_Jose              0x6541
#define Time_Zone_Easter_Island         0x6640
#define Time_Zone_Columbia              0x6784
#define Time_Zone_Panama                0x6887
#define Time_Zone_Peru                  0x696B
#define Time_Zone_Venezuela             0x6A4D
#define Time_Zone_Amazon                0x6BAA
#define Time_Zone_Paraguay              0x6C97
#define Time_Zone_Argentina             0x6D89
#define Time_Zone_Brasilia              0x6E8B
#define Time_Zone_Chile                 0x6F83
#define Time_Zone_Paraguay_Summer       0x7061
#define Time_Zone_Uruguay               0x7183
#define Time_Zone_Brasilia_Summer       0x7285
#define Time_Zone_Fernando_de_Noronha   0x73A8
#define Time_Zone_Greenwich_Mean_Time_Zone                                          0x7505
#define Time_Zone_Western_European      0x7614
#define Time_Zone_Central_European      0x7760
#define Time_Zone_West_Africa           0x78A0
#define Time_Zone_Central_Africa        0x79E9
#define Time_Zone_Central_European_Summer                                         0x7B06
#define Time_Zone_Eastern_European      0x7C3E
#define Time_Zone_South_Africa          0x7D83
#define Time_Zone_East_Africa           0x7EC3
#define Time_Zone_Eastern_European_Summer                                         0x8000
#define Time_Zone_Heard_McDonald_Island 0x818C
#define Time_Zone_Mawson_Station        0x832F
#define Time_Zone_India_Standard        0x847A
#define Time_Zone_Nepal                 0x8596
#define Time_Zone_Cocos_Island          0x8678
#define Time_Zone_Christmas_Island      0x87A4
#define Time_Zone_Davis                 0x88E2
#define Time_Zone_Australian_Western    0x89C5
#define Time_Zone_Casey                 0x8B2F
#define Time_Zone_Central_Western       0x8C1D
#define Time_Zone_Australian_Central    0x8D77
#define Time_Zone_Australian_Eastern    0x8EDD
#define Time_Zone_Lord_Howe             0x904B
#define Time_Zone_Lord_Howe_Daylight    0x9141
#define Time_Zone_Norfolk               0x92A6
#define Time_Zone_New_Zealand           0x93B7
#define Time_Zone_Chatham               0x94F4
#define Time_Zone_New_Zealand_Daylight  0x9627
#define Time_Zone_Tokelau               0x978E
#define Time_Zone_Chatham_Daylight      0x988D
#define GPS_Error_Content_L1            0x99DA
#define GPS_Error_Content_L2            0x9ADD
#define GPS_Error_Content_L3            0x9D45
#define Settings_BT_Title               0x9F8C
#define Settings_BT_Visibility          0xA058
#define Settings_System_Discoverable    0xA0DF
#define Settings_System_Discoverable_Disabled_L1                                                0xA1B0
#define Settings_System_Discoverable_Disabled_L2                                                0xA3C6
#define Settings_System_Discoverable_OFF_L1                                           0xA46F
#define Settings_System_Discoverable_OFF_L11                                            0xA6CC
#define Settings_System_Discoverable_OFF_L2                                           0xA8F1
#define Settings_System_Discoverable_ON_L1                                          0xAA45
#define Settings_System_Discoverable_ON_L11                                           0xAC57
#define Settings_System_Discoverable_ON_L2_Sec                                              0xAE0D
#define Settings_System_Discoverable_ON_L3                                          0xAE59
#define Settings_System_Discoverable_ON_L31                                           0xB06B
#define Settings_BT_Add_Device          0xB27D
#define Settings_BT_Scan_for_Devices_Button                                           0xB2FE
#define Settings_BT_Stop_Scan_Button    0xB3A6
#define Settings_No_Device_Found        0xB42A
#define Settings_BT_Devices_List        0xB519
#define Settings_BT_No_Device_Available 0xB571
#define Settings_BT_Device_List_Loading 0xB655
#define Popup_Please_Wait_In_Progress_L1                                        0xB79E
#define Popup_Please_Wait_In_Progress_L2                                        0xB826
#define Popup_Phone_Passkey_Match_text_Line2                                            0xB898
#define Popup_Phone_Passkey_Match_text_Line3                                            0xBA2D
#define Popup_Phone_Passkey_Match_text_Line4                                            0xBB61
#define Popup_Pairing_In_Progress_L2    0xBCB5
#define Popup_Phone_Connecing_L1        0xBD84
#define Popup_Phone_Connecing_L2        0xBDA7
#define Popup_Phone_Connected_L1        0xBE3A
#define Popup_Phone_Connected_L2        0xBE58
#define Popup_Phone_Connection_Failed_L1                                        0xBEB3
#define Popup_Phone_Connection_Failed_L2                                        0xBED1
#define Popup_Phone_Connection_Failed_L3                                        0xBF8B
#define Popup_Phone_Disconnecing_L1     0xBFEB
#define Popup_Phone_Disconnecing_L2     0xC009
#define Popup_Phone_Disconnected_L1     0xC0C9
#define Popup_Phone_Disconnected_L2     0xC0E7
#define Popup_Phone_Disconnection_Failed                                        0xC166
#define Settings_BT_Max_Device_L1       0xC24B
#define Settings_BT_Max_Device_L2       0xC3AE
#define Settings_BT_Max_Device_Deletion_L1                                          0xC51F
#define Popup_Phone_Deleted_L2          0xC68E
#define Popup_Phone_Deletion_Failed     0xC6F6
#define Popup_BTDisconnection_For_New_L1                                        0xC7B9
#define Popup_BTDisconnection_For_New_L2                                        0xC8FB
#define Popup_BTDisconnection_For_New_L3                                        0xCA45
#define Popup_OK_Button                 0xCB9F
#define Popup_Cancel_Button             0xCBC7
#define Popup_Support_Wireless_AA_L1    0xCC09
#define Popup_Support_Wireless_CPY_L1   0xCD98
#define Popup_Support_Wireless_CPY_L2   0xCF37
#define Popup_Connect_AA_Button         0xCF55
#define Popup_Connecting_AA_L2          0xD04C
#define Popup_Connecting_CP_L2          0xD17B
#define Popup_Connected_AA_Delete_L1    0xD2C7
#define Popup_Connected_AA_Delete_L2    0xD43C
#define Popup_Connected_CPY_Delete_L1   0xD5F1
#define Popup_Connected_CPY_Delete_L2   0xD69F
#define Popup_AAConnection_InProgress_L2                                        0xD80B
#define Popup_AAConnection_InProgress_L3                                        0xD9BA
#define Popup_AA_will_Disconnect_L1     0xDA19
#define Popup_AA_will_Disconnect_L2     0xDB86
#define Popup_AA_will_Disconnect_L3     0xDC3E
#define Popup_RFCOMM_AA_Disconnect_L1   0xDCAC
#define Popup_RFCOMM_AA_Disconnect_L2   0xDCE8
#define Popup_RFCOMM_AA_Disconnect_L3   0xDE38
#define Popup_RFCOMM_AA_Switch_L1       0xDE56
#define Popup_RFCOMM_AA_Switch_L2       0xDFAD
#define Popup_CPY_will_Disconnect_L1    0xE009
#define Popup_CPY_will_Disconnect_L2    0xE16D
#define Popup_CPY_will_Disconnect_L3    0xE1C0
#define Popup_AA_first_Connection_L1    0xE1DE
#define Popup_AA_first_Connection_L2    0xE402
#define Popup_HomeScreen_Navigation_L1  0xE5AC
#define Popup_HomeScreen_Navigation_L2  0xE782
#define Popup_AA_connect_via_USB_L1     0xE8C8
#define Popup_AA_connect_via_USB_L2     0xEA56
#define Popup_AA_connect_via_USB_BT_L1  0xEB69
#define Popup_AA_connect_via_USB_BT_L2  0xED1A
#define Popup_AA_connect_via_USB_BT_L3  0xEEF1
#define Popup_AA_connect_via_USB_BT_Button                                          0xEF3D
#define Popup_CPY_connect_via_USB_L1    0xEFD9
#define Popup_CPY_connect_via_USB_L2    0xF193
#define Popup_CPY_connect_via_USB_BT_L1 0xF2CE
#define Popup_CPY_connect_via_USB_BT_L2 0xF452
#define Popup_CPY_connect_via_USB_BT_L3 0xF660
#define Scr_Compatible_Devices          0xF695
#define Scr_Android_Devices             0xF74B
#define Scr_Apple_Devices               0xF7DE
#define Scr_No_Android_Devices_L1       0xF866
#define Scr_No_Android_Devices_L2       0xF9A3
#define Scr_No_Apple_Devices_L1         0xFA91
#define Scr_No_Apple_Devices_L2         0xFBEF
#define Scr_Switch_From                 0xFC8E
#define Popup_AA_Error_Check_time_L1    0xFD1E
#define Popup_AA_Error_Check_time_L2    0xFEAC
#define Popup_AA_Error_Check_time_L3    0xFF4C
#define Popup_AA_Error_USB_Ping_Request_Failure_L1                                                  0x10082
#define Popup_AA_Error_USB_Ping_Request_Failure_L2                                                  0x101C9
#define Popup_AA_Error_WiFi_Start_Failure_Use_USB_L1                                                    0x1033E
#define Popup_AA_Error_WiFi_Start_Failure_Use_USB_L2                                                    0x10489
#define Popup_AA_Error_WiFi_Failure_Use_USB_L1                                              0x1063A
#define Popup_AA_Error_WiFi_Failure_Use_USB_L2                                              0x107B8
#define Popup_AA_Error_WiFi_Failure_Use_USB_L3                                              0x1085A
#define Popup_AA_Error_WiFi_Ping_RTT_Failure__L1                                                0x10A62
#define Popup_AA_Error_WiFi_Ping_RTT_Failure__L2                                                0x10C4B
#define Popup_AA_Error_WiFi_Ping_RTT_Failure__L3                                                0x10DF8
#define Popup_AA_Error_WiFi_Version_Failure__L1                                               0x10FE5
#define Popup_AA_Error_WiFi_Version_Failure__L2                                               0x1118F
#define Popup_AA_Error_WiFi_Version_Failure__L3                                               0x113B4
#define Popup_AA_Error_WiFi_Ping_Request_Failure__L1                                                    0x115C1
#define Popup_AA_Error_WiFi_Ping_Request_Failure__L2                                                    0x11708
#define Popup_AA_Error_WiFi_Ping_Request_Failure__L3                                                    0x11862
#define Popup_AA_Warning_Batt_Low_L1    0x118E1
#define Popup_AA_Warning_Batt_Low_L2    0x11A2E
#define Popup_AA_Notification_Wireless_L1                                         0x11B5E
#define Popup_AA_Notification_Wireless_L2                                         0x11D0B
#define Popup_AA_HUAccessPoint_Error_L1 0x11E6B
#define Popup_AA_HUAccessPoint_Error_L2 0x11F8E
#define Popup_AA_TCPConnection_Error_L1 0x12155
#define Popup_AA_TCPConnection_Error_L2 0x1217D
#define Popup_AA_BluetoothAuthenticationn_Error_L1                                                  0x1239E
#define Popup_AA_BluetoothAuthenticationn_Error_L2                                                  0x124C3
#define Popup_AA_MobileSideIssue_Error_L1                                         0x126C6
#define Popup_AA_MobileSideIssue_Error_L2                                         0x128AF
#define Popup_AA_MobileSideIssue_Error_L3                                         0x12A31
#define Popup_CPY_Error_Connection_L1   0x12B53
#define Popup_Switch_From_To_L2         0x12D2C
#define Popup_Switch_From_To_L3         0x12E66
#define Popup_Switch_From_To_L4         0x12F15
#define Popup_Please_Wait               0x12FCD
#define Popup_MaxDev_Android_L1         0x13014
#define Popup_MaxDev_Android_L2         0x130C6
#define Popup_MaxDev_CarPlayConnected_L1                                        0x13271
#define Popup_MaxDev_CarPlayConnected_L2                                        0x1334E
#define Popup_MaxDev_Apple_L1           0x134D3
#define Popup_MaxDev_Apple_L2           0x13674
#define Popup_BT_Terminate_BT_L1        0x1384A
#define Popup_BT_Terminate_BT_L2        0x139EE
#define Popup_BT_Terminate_BT_L3        0x13AF0
#define Popup_BT_Terminate_AA_L1        0x13B9D
#define Popup_BT_Terminate_AA_L2        0x13D82
#define Popup_BT_Terminate_CP_L1        0x13F51
#define Popup_BT_Terminate_CP_L2        0x13FD7
#define Popup_Android_Terminate_BT_L1   0x141AD
#define Popup_Android_Terminate_BT_L2   0x143A5
#define Popup_Android_Terminate_BT_L3   0x144E4
#define Popup_Android_Terminate_Android_L1                                          0x14506
#define Popup_Android_Terminate_Android_L2                                          0x1455E
#define Popup_Apple_Terminate_BT_L1     0x1469D
#define Popup_Apple_Terminate_BT_L2     0x14863
#define Popup_Apple_Terminate_BT_L3     0x148EB
#define Popup_Apple_Terminate_Apple_L1  0x1490A
#define Popup_Apple_Terminate_Apple_L2  0x14964
#define Popup_Android_Active_Disconnect_L1                                          0x14AAC
#define Popup_Apple_Active_Disconnect_L1                                        0x14AFD
#define Popup_AA_PairDevice_Apple_Connected_L1                                              0x14B56
#define Popup_AA_PairDevice_Apple_Connected_L2                                              0x14BAD
#define Popup_AA_PairDevice_BT_Connected_L1                                           0x14CE7
#define Popup_AA_PairDevice_BT_Connected_L2                                           0x14E8E
#define Popup_DeviceSupports_Wired_AA_L1                                        0x14ED0
#define Popup_DeviceSupports_Wired_AA_L2                                        0x14F34
#define Popup_DeviceSupports_Wired_AA_L3                                        0x150FF
#define Popup_Reconnection_Request_Error_L1                                           0x152ED
#define Popup_Reconnection_Request_Error_L2                                           0x1549D
#define Settings_Audio_Title            0x1558F
#define Settings_Audio_Balance_Fade     0x15633
#define Settings_Audio_Balance          0x156DD
#define Settings_Audio_Fade             0x15723
#define Settings_Audio_Front            0x15760
#define Settings_Audio_Rear             0x1579E
#define Settings_Audio_Center           0x157E3
#define Settings_Audio_Equalizer        0x15821
#define Settings_Audio_Bass             0x15887
#define Settings_Audio_Mid_Range        0x158B8
#define Settings_Audio_Treble           0x158EC
#define Settings_Audio_Flat             0x15922
#define Settings_Audio_Pop              0x15952
#define Settings_Audio_Jazz             0x1597F
#define Settings_Audio_Rock             0x159AE
#define Settings_Audio_Voice            0x159DD
#define Settings_Audio_Classic          0x15A0B
#define Settings_Audio_Custom           0x15A55
#define Settings_Audio_Volume           0x15A9B
#define Settings_Audio_Media            0x15ADD
#define Settings_Audio_Phone            0x15B09
#define Settings_Audio_Ringtone         0x15B2C
#define Settings_Audio_Notification     0x15B88
#define Settings_Audio_SDVC             0x15BDD
#define Settings_Audio_SDVC_EXP         0x15C1C
#define Settings_Audio_SDVC_Line1       0x15D60
#define Settings_Audio_SDVC_Line2       0x15EEC
#define Settings_Audio_SDVC_Line3       0x16099
#define Settings_Audio_SDVC_Line4       0x16254
#define Setting_WiFi_Title              0x16350
#define Setting_WiFi_Password           0x163F6
#define Setting_WiFi_Network            0x16461
#define Setting_WiFi_Sub_Password       0x16521
#define Setting_WiFi_SetNew             0x16578
#define Popup_Password_Please_Wait      0x165ED
#define Popup_Password_Set_Successfully 0x16630
#define Popup_Password_Set_Error_L1     0x167AC
#define Popup_Password_Set_Error_L2     0x169A3
#define Settings_WiFi_Information_L1    0x16A4D
#define Settings_WiFi_Information_L2    0x16C64
#define Settings_WiFi_Confirmation_L1   0x16DF4
#define Settings_WiFi_Confirmation_L2   0x16F4E
#define Setting_Vehicle_Title           0x16FFB
#define Setting_Vehicle_Heading_DRL     0x170BB
#define Setting_Vehicle_DRL             0x170F7
#define Setting_Vehicle_DRL_Content_L1  0x171F8
#define Setting_Vehicle_DRL_Content_L2  0x17428
#define Setting_Vehicle_DRL_Content_L3  0x17650
#define Popup_Vehicle_DRL_Error         0x17888
#define Setting_Vehicle_Alerts          0x179E5
#define Setting_Vehicle_No_Alerts_Present                                         0x17A52
#define Setting_Vehicle_Shift_to_P      0x17B07
#define Setting_Vehicle_Shift_to_P_or_N 0x17BFC
#define Setting_Vehicle_Key_fob_Battery 0x17D4B
#define Welcome_screen_message_1        0x17E69
#define Welcome_screen_message_2        0x17ECF
#define Welcome_screen_message_3        0x18101
#define Popup_Vehicle_Alert_Shift_to_P  0x1838B
#define Popup_Turn_On_Ignition          0x18404
#define Popup_Display_OFF               0x18596
#define Popup_OKGoogle_BT               0x1868B
#define Popup_Siri_BT                   0x1872D
#define Popup_End_Button                0x18762
#define Popup_No_Network_Service        0x18790
#define SBN_USB_Reading                 0x18853
#define SBN_USB_Disconnected            0x188CD
#define SBN_USB_No_Response             0x18961
#define SBN_Ipod_Reading                0x18A22
#define SBN_Ipod_Disconnected           0x18A9E
#define SBN_USB_Device_Empty            0x18B34
#define SBN_USB_Device_Error            0x18BF1
#define SBN_Ipod_Device_Empty           0x18CC3
#define SBN_USB_iPod_Invalid_File       0x18D40
#define SBN_Device_Unsupported          0x18DD7
#define SBN_HUB_Unsupported             0x18EAC
#define SBN_AA_Connected                0x18F56
#define SBN_CPY_Connected               0x19038
#define SBN_Connection_Failed           0x190F9
#define SBN_Phonebook_Download_Failed   0x191F1
#define SBN_Indexing_In_Progress_Please_Wait                                            0x1937A
#define SBN_Alert_Shift_To_P_           0x1952F
#define SBN_Alert_Shift_To_P_or_N       0x19576
#define SBN_Alert_Key_Fob_Battery_Low   0x19670
#define SBN_Device_Connected            0x196EC
#define SBN_Device_Disconnected         0x1975E
#define SBN_One_Hour_Mode_Active        0x19804
#define SBN_Low_Battery_Voltage         0x198F3
#define SBN_High_Battery_Voltage        0x19A3A
#define SBN_Switch_Android_Auto         0x19B81
#define SBN_Switch_Apple_CarPLay        0x19D24
#define SBN_Switch_Button               0x19ED3
#define SBN_Cancel_Button               0x19F07
#define SBN_Ignore_Button               0x19F25
#define SBN_Feature_Unavailable         0x19F66
#define SBN_BT_Browse_Change            0x1A18C
#define Scr_RVC_Check_Surrounding       0x1A382
#define SBN_Decline_Button              0x1A4C0
#define SBN_Answer_Button               0x1A50A
#define Scr_Engineering_Menu_Title      0x1A552
#define Scr_ETM_Hardware_Version        0x1A5FA
#define Scr_ETM_Sub_HW_Version          0x1A690
#define Scr_ETM_Software_Version        0x1A6F6
#define Scr_ETM_Software_HOST           0x1A794
#define Scr_ETM_Software_VIP            0x1A7C1
#define Scr_ETM_Software_VCID           0x1A7EB
#define Scr_ETM_Vehicle_Information     0x1A816
#define Scr_ETM_Vehicle_VIN1            0x1A8C8
#define Scr_ETM_External_Interfaces     0x1A9BD
#define Scr_External_Interfaces_SWC     0x1AA5D
#define Scr_External_Interfaces_Tuner_Antenna                                             0x1AB3D
#define Scr_External_Interfaces_RVC     0x1ABBA
#define Scr_External_Interfaces_Microphone                                          0x1AC89
#define Scr_External_Interfaces_GPS_Antenna                                           0x1ACE1
#define Scr_ETM_GPS_Details             0x1AD56
#define Scr_GPS_Signal_Strength         0x1ADD8
#define Scr_GPS_Signal_Coordinates      0x1AE93
#define Scr_ETM_Radio                   0x1AF16
#define Scr_ETM_Statio_Name             0x1AF37
#define Scr_ETM_Frequency               0x1AFC9
#define Scr_ETM_Signal_Strength         0x1B02B
#define Scr_ETM_Seek_Threshold          0x1B0CE
#define Scr_ETM_Multi_Path              0x1B166
#define Scr_ETM_Current_Volume_Level    0x1B1DE
#define Scr_ETM_USB_Video               0x1B2BB
#define Scr_ETM_Track_Name              0x1B30C
#define Scr_ETM_Video_Format            0x1B38E
#define Scr_ETM_Video_Codec             0x1B41E
#define Scr_ETM_Video_Resolution        0x1B4AC
#define Scr_ETM_Video_Framerate         0x1B557
#define Scr_ETM_USB_Audio               0x1B61B
#define Scr_ETM_BT_Audio                0x1B676
#define Scr_ETM_Bitrate                 0x1B6B4
#define Scr_ETM_Sampling_Rate           0x1B722
#define Scr_ETM_Volume_in_dB            0x1B7CB
#define Scr_ETM_Folder_Name             0x1B861
#define Scr_ETM_Track_Format            0x1B8E7
#define Scr_ETM_AVRCP_Version           0x1B979
#define Scr_ETM_Addressed_Media_Player  0x1B9FC
#define Scr_ETM_Supported_Feature       0x1BA7A
#define Scr_ETM_Play_Pause              0x1BB26
#define Scr_ETM_Next_Track              0x1BBA1
#define Scr_ETM_Previous_Track          0x1BC25
#define Scr_ETM_Fast_Forward            0x1BCB3
#define Scr_ETM_Fast_Rewind             0x1BD3E
#define Scr_ETM_Shuffle                 0x1BDD9
#define Scr_ETM_Repeat                  0x1BEDD
#define Scr_ETM_Progress_Bar            0x1BF70
#define Scr_ETM_Album_Art               0x1C061
#define Scr_ETM_Song_Name               0x1C0DF
#define Scr_ETM_Album_Name              0x1C15C
#define Scr_ETM_Artist_Name             0x1C1E0
#define Scr_ETM_Test_Mode               0x1C263
#define Scr_Test_Mode_Speaker           0x1C2D8
#define Scr_Test_Mode_Display           0x1C36E
#define Scr_Test_Mode_Mic               0x1C404
#define Scr_Test_Mode_Touch             0x1C489
#define Scr_ETM_Start_Button            0x1C511
#define Scr_Test_Speaker_LF             0x1C552
#define Scr_Test_Speaker_RF             0x1C5CE
#define Scr_Test_Speaker_LR             0x1C649
#define Scr_Test_Speaker_RR             0x1C6CE
#define Scr_Speaker_Line1               0x1C75F
#define Scr_Speaker_Line2               0x1C878
#define Scr_Speaker_Line3               0x1C8DA
#define Scr_Mic_Playing_Back            0x1C9D3
#define Scr_Mic_Test_Complete           0x1CA5F
#define Scr_Touch_Help_Text             0x1CB0A
#define Scr_Touch_Test_Complete         0x1CC68
#define Scr_ETM_WiFi_Configuration      0x1CCFC
#define Scr_WiFi_SSID                   0x1CDAC
#define Scr_ETM_Edit_Button             0x1CDDB
#define Scr_WiFi_Operation_Mode         0x1CE1C
#define Scr_Operation_Mode_AC           0x1CEFD
#define Scr_WiFi_Channel                0x1CF1B
#define Scr_WiFi_Channel_Number         0x1CF5B
#define Scr_WiFi_IP_Netmask             0x1CF82
#define Scr_ETM_Software_Update         0x1D090
#define Scr_SW_Update_Fetching_Data     0x1D123
#define Popup_SW_Update_ConnectUSB_L1   0x1D1FA
#define Popup_SW_Update_ConnectUSB_L2   0x1D338
#define Popup_SW_Update_No_Valid_Package                                        0x1D405
#define Scr_SW_Update_Current_Version   0x1D562
#define Scr_SW_Update_Available_Version 0x1D5F7
#define Popup_SW_Update_Turn_Ignition_On                                        0x1D708
#define Scr_SW_Update_Start_Text_L1     0x1D7C6
#define Scr_SW_Update_Start_Text_L2     0x1D8DE
#define Scr_ETM_Continue_Button         0x1D9F6
#define Popup_SW_Update_Analyze_L1      0x1DA51
#define Popup_SW_Update_Analyze_L2      0x1DAAA
#define Popup_SW_Update_Analyze_L3      0x1DBF7
#define Popup_SW_Update_Analyze_L4      0x1DCEE
#define Popup_SW_Update_Restart_L1      0x1DE14
#define Popup_SW_Update_Restart_L2      0x1DE41
#define Popup_SW_Update_Restart_L3      0x1E002
#define Popup_SW_Update_Restart_L4      0x1E02A
#define Popup_SW_Analysis_No_Valid_Package_L1                                             0x1E074
#define Popup_SW_Analysis_No_Valid_Package_L2                                             0x1E16D
#define Scr_ETM_Sys_Logger              0x1E218
#define Scr_Sys_Logger_Begin            0x1E283
#define Scr_Sys_Logger_Progress         0x1E364
#define Scr_ETM_Stop_Button             0x1E49D
#define Popup_TFT_Derating_Popup_L1     0x1E4DB
#define Popup_TFT_Derating_Popup_L2     0x1E5FF
#define Popup_TFT_Derating_Popup_L3     0x1E7DF
#define Popup_TFT_Derating_Popup_L4     0x1E908
#define Popup_Amp_Derating_Popup_L1     0x1E9DB
#define Popup_Amp_Derating_Popup_L2     0x1EA03
#define Popup_Amp_Derating_Popup_L3     0x1EBBB
#define Popup_Amp_Derating_Popup_L4     0x1ED38
#define Popup_VIN_CAN_Missing_L1        0x1ED60
#define Popup_VIN_CAN_Missing_L2        0x1EEFA
#define Popup_VIN_CAN_Missing_L3        0x1F00C
#define Popup_VIN_CAN_Missing_L4        0x1F198
#define Popup_VIN_CAN_Mismatch_L1       0x1F254
#define Popup_VIN_CAN_Mismatch_L2       0x1F332
#define Popup_PowerMode_CR_L1           0x1F42C
/* Total Language Table Size = 125.42kBytes */
#define HM_LANG_MAX_PAGE                1
#define HM_LANG_MAX_SID                 0x1F580u
#define HM_LANG_COMMON_MAX_SID          0x00B1u
#define HM_END_OF_SID                   (0xFFFFFFFFu)
#define HM_LANG_BUFFER_MAX_SIZE         (0x1F5B1u)        /* This is the language database size */
typedef UINT32 LANG_SID_T;

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        08/12/09     JKANOZA                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                               
/* end of file =============================================================*/ 
#endif /* HMI_LANGUAGE_IDENTIFIERS_H */
