#ifndef TEST_FT_UPDD_NEWVERSION_UPDCDD_CFG_H_
#define TEST_FT_UPDD_NEWVERSION_UPDCDD_CFG_H_

#define SPARSE_DECODER_EXT_NAME  "simg"

#define FILL_CHAR_OFF_SIZE (4)
#define FILL_CHAR_OFF_THR  (FILL_CHAR_OFF_SIZE - 1)

#endif /* TEST_FT_UPDD_NEWVERSION_UPDCDD_CFG_H_ */
