/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2010. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**============================================================================
**
** Name:           hmi_gfx02_image_data.c
**
** Description:    This file is used by the application code to determine
**                 where graphic pixel data generated by the GDT tool
**                 should reside in memory.  The two choices are internal
**                 flash or external flash (accessed via the QSPI
**                 peripheral).  Details on how to make the selection are
**                 available below.
**
** Organization:   Driver Information Software Section,
**                 DI Core Engineering Department
**
**============================================================================
**
**==========================================================================*/
#define HMI_GFX02_IMAGE_DATA_C

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "system.h"
#include "hmi_gfx_mgr02_layout.h"

/*
** For files in external flash memory, #include them as in the example below.
** Note the use of #pragmas.
*/

#ifndef WIN32
   typedef UINT8  GFX_IMG_DATA_T ;
   typedef UINT16 GFX_IMG_DATA16_T ;
   typedef UINT32 GFX_IMG_DATA32_T ;
#else
   typedef UINT8  GFX_IMG_DATA_T;
   typedef UINT16 GFX_IMG_DATA16_T;
   typedef UINT32 GFX_IMG_DATA32_T;
#endif

#define GFX_IMG_DATA_PREFIX
#define GFX_IMG_DATA_SUFFIX 

#include "img_tt_1_ovg.dat"
#include "img_tt_2_ovg.dat"
#include "img_tt_3_ovg.dat"
#include "img_tt_4_ovg.dat"
#include "img_tt_5_ovg.dat"
#include "img_tt_6_ovg.dat"
#include "img_tt_7_ovg.dat"
#include "img_tt_8_ovg.dat"
#include "img_tt_9_ovg.dat"
#include "img_tt_10_ovg.dat"
#include "img_tt_11_ovg.dat"
#include "img_tt_12_ovg.dat"
#include "img_tt_13_ovg.dat"
#include "img_tt_14_ovg.dat"
#include "img_tt_15_ovg.dat"
#include "img_tt_16_ovg.dat"

#ifdef GFX_MGR02_CHECKSUM_ENABLED
#include "hmi_gfx_mgr02_checksum.dat"
#endif

#undef GFX_IMG_DATA_PREFIX

#if defined(MATLAB_MEX_FILE)||defined(WIN32)
	#define GFX_IMG_DATA_PREFIX
#else
	#pragma push
	#pragma section "QSPI0_FLASH"
	#define GFX_IMG_DATA_PREFIX   __declspec(section "QSPI0_FLASH")
#endif

/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** CMS Rev 1        01/13/10     JKANOZA
** Initial revision.
**
**==========================================================================*/

/* end of file =============================================================*/

