/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_identifiers.h                                 
**                                                                            
** Description:    This file contains the language identifier interfaces      
**                 Autogenerated by LanguageEncoder.exe Version : 1.1.0.22.          
**                 Do not handmodify this file								  
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_LANGUAGE_IDENTIFIERS_H
#define HMI_LANGUAGE_IDENTIFIERS_H
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#ifndef WIN32
#include "wchar.h"
#endif

/*============================================================================
** T Y P E   D E F I N I T I O N S                                                  
**==========================================================================*/
#ifndef LNG_UNICODE
   #define LNG_UNICODE
#endif /* LNG_UNICODE */

/* Release label major version 4 */
/* Release label minor version 12 */
#define HMI_LANG_CORE_TOOL_LABEL                  "LANG_TOOL_LABEL::rel-UI-CORE-ICEAPPLE-4.12"
#define HMI_LANG_CORE_TOOL_MAJOR_VERSION          4
#define HMI_LANG_CORE_TOOL_MINOR_VERSION          12
#define HMI_LANG_CORE_TOOL_VERSION                ((HMI_LANG_CORE_TOOL_MAJOR_VERSION * 100) + HMI_LANG_CORE_TOOL_MINOR_VERSION)

#define   HMI_LANGUAGE_JAPANESE_FEAT
#define   HMI_LANGUAGE_US_ENGLISH_FEAT
#define   HMI_LANGUAGE_GERMAN_FEAT
#define   HMI_LANGUAGE_FRENCH_FEAT
#define   HMI_LANGUAGE_SPANISH_FEAT
#define   HMI_LANGUAGE_ITALIAN_FEAT
#define   HMI_LANGUAGE_RUSSIAN_FEAT
#define   HMI_LANGUAGE_PORTUGUESE_FEAT
#define   HMI_LANGUAGE_THAI_FEAT
#define   HMI_LANGUAGE_INDONESIA_FEAT
#define   HMI_LANGUAGE_TURKISH_FEAT
#define   HMI_LANGUAGE_ARABIC_FEAT
#define   HMI_LANGUAGE_UKRAINIAN_FEAT
#define   HMI_LANGUAGE_CHINESE_FEAT
#define   HMI_LANGUAGE_VIETNAMESE_FEAT
#define   HMI_LANGUAGE_NO_LANGUAGE_FEAT

typedef enum
{
   HMI_LANGUAGE_JAPANESE,
   HMI_LANGUAGE_US_ENGLISH,
   HMI_LANGUAGE_GERMAN,
   HMI_LANGUAGE_FRENCH,
   HMI_LANGUAGE_SPANISH,
   HMI_LANGUAGE_ITALIAN,
   HMI_LANGUAGE_RUSSIAN,
   HMI_LANGUAGE_PORTUGUESE,
   HMI_LANGUAGE_THAI,
   HMI_LANGUAGE_INDONESIA,
   HMI_LANGUAGE_TURKISH,
   HMI_LANGUAGE_ARABIC,
   HMI_LANGUAGE_UKRAINIAN,
   HMI_LANGUAGE_CHINESE,
   HMI_LANGUAGE_VIETNAMESE,
   HMI_LANGUAGE_NO_LANGUAGE,
   LNG_MAX_LANGUAGE_COUNT
} HMI_LANGUAGE_T;

#define HM_LANG_MAX_STRING_SIZE         45
#define TXT_WNG_ADAS_022_1_L2           0x0000
#define TXT_WNG_ADAS_022_1_L3           0x0001
#define TXT_WNG_ADAS_022_1_L4           0x0002
#define TXT_WNG_ADAS_022_2_L2           0x0003
#define TXT_WNG_ADAS_022_2_L3           0x0004
#define TXT_WNG_ADAS_022_2_L4           0x0005
#define TXT_WNG_ADAS_022_3_L3           0x0006
#define TXT_WNG_ADAS_022_3_L4           0x0007
#define TXT_WNG_ADAS_023_1_L2           0x0008
#define TXT_WNG_ADAS_023_1_L3           0x0009
#define TXT_WNG_ADAS_023_1_L4           0x000A
#define TXT_WNG_ADAS_023_2_L2           0x000B
#define TXT_WNG_ADAS_023_2_L3           0x000C
#define TXT_WNG_ADAS_023_2_L4           0x000D
#define TXT_WNG_ADAS_024_L3             0x000E
#define TXT_WNG_ADAS_024_L4             0x000F
#define TXT_WNG_ADAS_051_L4             0x0010
#define TXT_WNG_ADAS_070_L4             0x0011
#define TXT_WNG_ADAS_071_L2             0x0012
#define TXT_WNG_ADAS_071_L3             0x0013
#define TXT_WNG_ADAS_071_L4             0x0014
#define TXT_WNG_NORM_001_L4             0x0015
#define TXT_WNG_NORM_002_L3             0x0016
#define TXT_WNG_NORM_002_L4             0x0017
#define TXT_WNG_NORM_003_L4             0x0018
#define TXT_WNG_NORM_004_L4             0x0019
#define TXT_WNG_NORM_006_L4             0x001A
#define TXT_WNG_NORM_007_1_L3           0x001B
#define TXT_WNG_NORM_007_1_L4           0x001C
#define TXT_WNG_NORM_007_2_L3           0x001D
#define TXT_WNG_NORM_007_2_L4           0x001E
#define TXT_WNG_NORM_007_3_L3           0x001F
#define TXT_WNG_NORM_007_3_L4           0x0020
#define TXT_WNG_NORM_007_4_L3           0x0021
#define TXT_WNG_NORM_007_4_L4           0x0022
#define TXT_WNG_NORM_007_5_L4           0x0023
#define TXT_WNG_NORM_007_6_L3           0x0024
#define TXT_WNG_NORM_007_6_L4           0x0025
#define TXT_WNG_NORM_007_7_L4           0x0026
#define TXT_WNG_NORM_007_9_L4           0x0027
#define TXT_WNG_NORM_007_11_L4          0x0028
#define TXT_WNG_NORM_008_1_L4           0x0029
#define TXT_WNG_NORM_008_3_L4           0x002A
#define TXT_WNG_NORM_008_4_L4           0x002B
#define TXT_WNG_NORM_008_5_L4           0x002C
#define TXT_WNG_NORM_008_6_L4           0x002D
#define TXT_WNG_NORM_008_7_L4           0x002E
#define TXT_WNG_NORM_008_10_L4          0x002F
#define TXT_WNG_NORM_008_13_L4          0x0030
#define TXT_WNG_NORM_009_L3             0x0031
#define TXT_WNG_NORM_009_L4             0x0032
#define TXT_WNG_NORM_010_L3             0x0033
#define TXT_WNG_NORM_010_L4             0x0034
#define TXT_WNG_NORM_012_L3             0x0035
#define TXT_WNG_NORM_012_L4             0x0036
#define TXT_WNG_NORM_013_1_L3           0x0037
#define TXT_WNG_NORM_013_1_L4           0x0038
#define TXT_WNG_NORM_013_2_L3           0x0039
#define TXT_WNG_NORM_013_2_L4           0x003A
#define TXT_WNG_NORM_013_3_L3           0x003B
#define TXT_WNG_NORM_013_3_L4           0x003C
#define TXT_WNG_NORM_014_L3             0x003D
#define TXT_WNG_NORM_014_L4             0x003E
#define TXT_WNG_NORM_015_L4             0x003F
#define TXT_WNG_NORM_016_L4             0x0040
#define TXT_WNG_NORM_017_L3             0x0041
#define TXT_WNG_NORM_017_L4             0x0042
#define TXT_WNG_NORM_018_1_L4           0x0043
#define TXT_WNG_NORM_018_2_L4           0x0044
#define TXT_WNG_NORM_019_1_L3           0x0045
#define TXT_WNG_NORM_019_1_L4           0x0046
#define TXT_WNG_NORM_019_2_L4           0x0047
#define TXT_WNG_NORM_021_L3             0x0048
#define TXT_WNG_NORM_021_L4             0x0049
#define TXT_WNG_NORM_022_1_L3           0x004A
#define TXT_WNG_NORM_022_1_L4           0x004B
#define TXT_WNG_NORM_022_2_L4           0x004C
#define TXT_WNG_NORM_022_3_L4           0x004D
#define TXT_WNG_NORM_022_4_L4           0x004E
#define TXT_WNG_NORM_022_5_L4           0x004F
#define TXT_WNG_NORM_022_6_L3           0x0050
#define TXT_WNG_NORM_022_6_L4           0x0051
#define TXT_WNG_NORM_022_7_L4           0x0052
#define TXT_WNG_NORM_022_8_L4           0x0053
#define TXT_WNG_NORM_022_9_L4           0x0054
#define TXT_WNG_NORM_022_10_1_L4        0x0055
#define TXT_WNG_NORM_022_10_2_L4        0x0056
#define TXT_WNG_NORM_022_11_L3          0x0057
#define TXT_WNG_NORM_022_11_L4          0x0058
#define TXT_WNG_NORM_023_1_L3           0x0059
#define TXT_WNG_NORM_023_1_L4           0x005A
#define TXT_WNG_NORM_023_3_L4           0x005B
#define TXT_WNG_NORM_023_4_L3           0x005C
#define TXT_WNG_NORM_023_4_L4           0x005D
#define TXT_WNG_NORM_023_5_L3           0x005E
#define TXT_WNG_NORM_023_5_L4           0x005F
#define TXT_WNG_NORM_023_6_L3           0x0060
#define TXT_WNG_NORM_023_6_L4           0x0061
#define TXT_WNG_NORM_023_7_1_L4         0x0062
#define TXT_WNG_NORM_023_7_2_L4         0x0063
#define TXT_WNG_NORM_023_8_L4           0x0064
#define TXT_WNG_NORM_023_9_L4           0x0065
#define TXT_WNG_NORM_023_10_L4          0x0066
#define TXT_WNG_NORM_023_11_L3          0x0067
#define TXT_WNG_NORM_023_11_L4          0x0068
#define TXT_WNG_NORM_024_1_L3           0x0069
#define TXT_WNG_NORM_024_1_L4           0x006A
#define TXT_WNG_NORM_024_2_L3           0x006B
#define TXT_WNG_NORM_024_2_L4           0x006C
#define TXT_WNG_NORM_025_L4             0x006D
#define TXT_WNG_NORM_026_L4             0x006E
#define TXT_WNG_NORM_027_L4             0x006F
#define TXT_WNG_NORM_028_L4             0x0070
#define TXT_WNG_NORM_029_L4             0x0071
#define TXT_WNG_NORM_030_L3             0x0072
#define TXT_WNG_NORM_030_L4             0x0073
#define TXT_WNG_NORM_031_1_L3           0x0074
#define TXT_WNG_NORM_031_1_L4           0x0075
#define TXT_WNG_NORM_031_2_L4           0x0076
#define TXT_WNG_NORM_031_3_L4           0x0077
#define TXT_WNG_NORM_032_L4             0x0078
#define TXT_WNG_NORM_033_L3             0x0079
#define TXT_WNG_NORM_033_L4             0x007A
#define TXT_WNG_NORM_034_L4             0x007B
#define TXT_WNG_NORM_035_L4             0x007C
#define TXT_WNG_NORM_036_1_L4           0x007D
#define TXT_WNG_NORM_036_2_L4           0x007E
#define TXT_WNG_NORM_036_3_L4           0x007F
#define TXT_WNG_NORM_038_L3             0x0080
#define TXT_WNG_NORM_038_L4             0x0081
#define TXT_WNG_NORM_039_L4             0x0082
#define TXT_WNG_NORM_042_1_L4           0x0083
#define TXT_WNG_NORM_043_1_L3           0x0084
#define TXT_WNG_NORM_043_1_L4           0x0085
#define TXT_WNG_NORM_043_2_L2           0x0086
#define TXT_WNG_NORM_043_2_L3           0x0087
#define TXT_WNG_NORM_043_2_L4           0x0088
#define TXT_WNG_NORM_046_L3             0x0089
#define TXT_WNG_NORM_046_L4             0x008A
#define TXT_WNG_NORM_047_5_L4           0x008B
#define TXT_WNG_NORM_048_L4             0x008C
#define TXT_WNG_NORM_049_L4             0x008D
#define TXT_WNG_NORM_050_1_L4           0x008E
#define TXT_WNG_NORM_050_2_L4           0x008F
#define TXT_WNG_NORM_050_3_L4           0x0090
#define TXT_WNG_NORM_050_4_L4           0x0091
#define TXT_WNG_NORM_050_5_L4           0x0092
#define TXT_WNG_NORM_050_6_L3           0x0093
#define TXT_WNG_NORM_050_6_L4           0x0094
#define TXT_WNG_NORM_050_7_L4           0x0095
#define TXT_WNG_NORM_050_8_L4           0x0096
#define TXT_WNG_NORM_050_9_L3           0x0097
#define TXT_WNG_NORM_050_9_L4           0x0098
#define TXT_WNG_NORM_051_1_L3           0x0099
#define TXT_WNG_NORM_051_1_L4           0x009A
#define TXT_WNG_NORM_051_3_1_L4         0x009B
#define TXT_WNG_NORM_051_3_2_L4         0x009C
#define TXT_WNG_NORM_051_4_L4           0x009D
#define TXT_WNG_NORM_051_5_L4           0x009E
#define TXT_WNG_NORM_052_1_L4           0x009F
#define TXT_WNG_NORM_052_2_L3           0x00A0
#define TXT_WNG_NORM_052_2_L4           0x00A1
#define TXT_WNG_NORM_052_3_L4           0x00A2
#define TXT_WNG_NORM_053_1_L4           0x00A3
#define TXT_WNG_NORM_053_2_L4           0x00A4
#define TXT_WNG_NORM_053_3_L4           0x00A5
#define TXT_WNG_NORM_053_4_L4           0x00A6
#define TXT_WNG_NORM_053_5_L4           0x00A7
#define TXT_WNG_NORM_054_1_L4           0x00A8
#define TXT_WNG_NORM_054_2_L4           0x00A9
#define TXT_WNG_NORM_055_1_L3           0x00AA
#define TXT_WNG_NORM_055_1_L4           0x00AB
#define TXT_WNG_NORM_055_2_1_L3         0x00AC
#define TXT_WNG_NORM_055_2_1_L4         0x00AD
#define TXT_WNG_NORM_055_2_2_L3         0x00AE
#define TXT_WNG_NORM_055_2_2_L4         0x00AF
#define TXT_WNG_NORM_055_3_L3           0x00B0
#define TXT_WNG_NORM_055_3_L4           0x00B1
#define TXT_WNG_NORM_056_1_L4           0x00B2
#define TXT_WNG_NORM_056_3_L4           0x00B3
#define TXT_WNG_NORM_056_5_L4           0x00B4
#define TXT_WNG_NORM_056_6_L4           0x00B5
#define TXT_WNG_NORM_057_2_L4           0x00B6
#define TXT_WNG_NORM_058_L4             0x00B7
#define TXT_WNG_NORM_060_1_L4           0x00B8
#define TXT_WNG_NORM_060_2_L4           0x00B9
#define TXT_WNG_NORM_061_1_L4           0x00BA
#define TXT_WNG_NORM_061_3_L4           0x00BB
#define TXT_WNG_NORM_061_4_L1           0x00BC
#define TXT_WNG_NORM_061_4_L2           0x00C9
#define TXT_WNG_NORM_061_4_L3           0x00CA
#define TXT_WNG_NORM_061_4_L4           0x00CB
#define TXT_WNG_NORM_061_5_L1           0x00CC
#define TXT_WNG_NORM_061_5_L2           0x00D8
#define TXT_WNG_NORM_061_5_L3           0x00D9
#define TXT_WNG_NORM_061_5_L4           0x00DA
#define TXT_WNG_NORM_063_1_L3           0x00DB
#define TXT_WNG_NORM_063_1_L4           0x00DC
#define TXT_WNG_NORM_063_2_L4           0x00DD
#define TXT_WNG_NORM_069_1_L3           0x00DE
#define TXT_WNG_NORM_069_1_L4           0x00DF
#define TXT_WNG_NORM_069_2_L4           0x00E0
#define TXT_WNG_NORM_069_5_L3           0x00E1
#define TXT_WNG_NORM_069_5_L4           0x00E2
#define TXT_WNG_NORM_069_6_L4           0x00E3
#define TXT_WNG_NORM_069_7_L4           0x00E4
#define TXT_WNG_NORM_069_8_L2           0x00E5
#define TXT_WNG_NORM_069_8_L3           0x00E6
#define TXT_WNG_NORM_069_8_L4           0x00E7
#define TXT_WNG_NORM_069_9_L4           0x00E8
#define TXT_WNG_NORM_069_12_L3          0x00E9
#define TXT_WNG_NORM_069_12_L4          0x00EA
#define TXT_WNG_NORM_071_1_L4           0x00EB
#define TXT_WNG_NORM_071_2_L4           0x00EC
#define TXT_WNG_NORM_071_4_L4           0x00ED
#define TXT_WNG_NORM_071_5_L4           0x00EE
#define TXT_WNG_NORM_072_1_L4           0x00EF
#define TXT_WNG_NORM_072_2_L4           0x00F0
#define TXT_WNG_NORM_072_3_L4           0x00F1
#define TXT_WNG_NORM_073_1_L3           0x00F2
#define TXT_WNG_NORM_073_1_L4           0x00F3
#define TXT_WNG_NORM_073_2_L4           0x00F4
#define TXT_WNG_NORM_073_3_L3           0x00F5
#define TXT_WNG_NORM_073_3_L4           0x00F6
#define TXT_WNG_NORM_079_1_L4           0x00F7
#define TXT_WNG_NORM_079_2_L4           0x00F8
#define TXT_WNG_NORM_081_1_L4           0x00F9
#define TXT_WNG_NORM_082_L4             0x00FA
#define TXT_WNG_NORM_083_L3             0x00FB
#define TXT_WNG_NORM_083_L4             0x00FC
#define TXT_WNG_NORM_084_L4             0x00FD
#define TXT_COMMON_4                    0x00FE
#define TXT_COMMON_3                    0x0100
#define TXT_COMMON_2                    0x0102
#define TXT_COMMON_1                    0x0104
#define TXT_SETTING_ADAS_LDW            0x0106
#define TXT_SETTING_ADAS_FCM            0x010A
#define TXT_SETTING_ADAS_BSW            0x010E
#define TXT_SETTING_ADAS_RCTA           0x0112
#define TXT_SETTING_ADAS_LCDN           0x0117
#define TXT_SETTING_ADAS_ASC            0x011C
#define TXT_SETTING_BT_SEL_DEV1         0x0120
#define TXT_SETTING_BT_SEL_DEV2         0x0122
#define TXT_SETTING_TPMS                0x0124
#define TXT_SETTING_TPMS_IDSET_SNS1     0x0129
#define TXT_SETTING_TPMS_IDSET_SNS2     0x012B
#define TXT_SETTING_REST_1H             0x012D
#define TXT_SETTING_REST_1H30M          0x0132
#define TXT_SETTING_REST_2H             0x0137
#define TXT_SETTING_REST_2H30M          0x013C
#define TXT_SETTING_REST_3H             0x0141
#define TXT_SETTING_REST_3H30M          0x0146
#define TXT_SETTING_REST_4H             0x014B
#define TXT_SETTING_LANG_JAPANESE       0x0150
#define TXT_SETTING_LANG_ENGLISH        0x0159
#define TXT_SETTING_LANG_GERMAN         0x0161
#define TXT_SETTING_LANG_FRENCH         0x0169
#define TXT_SETTING_LANG_SPANISH        0x0172
#define TXT_SETTING_LANG_ITALIAN        0x017A
#define TXT_SETTING_LANG_RUSSIAN        0x0183
#define TXT_SETTING_LANG_PORTUGUESE     0x018B
#define TXT_SETTING_LANG_THAI           0x0195
#define TXT_SETTING_LANG_INDONESIAN     0x019A
#define TXT_SETTING_LANG_TURKISH        0x01A8
#define TXT_SETTING_LANG_ARABIC         0x01AF
#define TXT_SETTING_LANG_UKRAINIAN      0x01B5
#define TXT_SETTING_LANG_CHINESE        0x01C1
#define TXT_SETTING_LANG_VIETNAMESE     0x01C7
#define TXT_SETTING_LANG_MESSAGE_OFF    0x01D8
#define TXT_SETTING_UNIT_FUEL_KML       0x01DC
#define TXT_SETTING_UNIT_FUEL_L100      0x01E1
#define TXT_SETTING_UNIT_FUEL_MPG_US    0x01E9
#define TXT_SETTING_UNIT_FUEL_MPG_UK    0x01F1
#define TXT_SETTING_UNIT_TEMP_C         0x01F9
#define TXT_SETTING_UNIT_TEMP_F         0x01FC
#define TXT_SER_REMIN_CUR_SCHED_01      0x01FF
#define TXT_SER_REMIN_CUR_SCHED_02      0x0203
#define TXT_SER_REMIN_CUR_SCHED_03      0x0209
#define TXT_SER_REMIN_CUR_SCHED_04      0x020F
#define TXT_SER_REMIN_CUR_SCHED_05      0x0215
#define TXT_SER_REMIN_CUR_SCHED_06      0x021B
#define TXT_SER_REMIN_CUR_SCHED_07      0x0221
#define TXT_SER_REMIN_CUR_SCHED_08      0x0227
#define TXT_SER_REMIN_CUR_SCHED_09      0x022D
#define TXT_SER_REMIN_CUR_SCHED_10      0x0233
#define TXT_SER_REMIN_CUR_SCHED_11      0x0239
#define TXT_SER_REMIN_CUR_SCHED_12      0x023F
#define TXT_SER_REMIN_CUR_SCHED_13      0x0244
#define TXT_SER_REMIN_CUR_SCHED_14      0x0249
#define TXT_SER_REMIN_CUR_SCHED_15      0x024E
#define TXT_SER_REMIN_CUR_SCHED_16      0x0254
#define TXT_SER_REMIN_CUR_SCHED_17      0x025A
#define TXT_SER_REMIN_CUR_SCHED_18      0x025E
#define TXT_SER_REMIN_CUR_SCHED_19      0x0265
#define TXT_SER_REMIN_CUR_SCHED_20      0x026C
#define TXT_SER_REMIN_SETTINGS_CLEAR    0x0272
#define TXT_SID_IDLESTOP                0x0278
#define TXT_SID_AFE_UNIT_KM_L           0x027D
#define TXT_SID_AFE_UNIT_L_100KM        0x0280
#define TXT_SID_AFE_UNIT_MPG            0x0283
#define TXT_SID_AVG_SPD_UNIT_KM_H       0x0287
#define TXT_SID_AVG_SPD_UNIT_MPH        0x028C
#define TXT_SID_ODO_UNIT_KM             0x0290
#define TXT_SID_ODO_UNIT_MILES          0x0293
#define TXT_SID_DTE_UNIT_KM             0x0299
#define TXT_SID_DTE_UNIT_MILES          0x029C
#define TXT_ETM_MODE_TITLE              0x029F
#define TXT_ETM_TITLE                   0x02A8
#define TXT_BUZZER_TITLE                0x02AC
#define TXT_INDICATION_TITLE            0x02B8
#define TXT_ETM_SW_VER_TITLE            0x02C8
#define TXT_APL_SW_VER_TITLE            0x02D6
#define TXT_BOOT_SW_VER_TITLE           0x02E4
#define TXT_SETTING_TRIP                0x02F3
#define TXT_SETTING_SPEEDUNIT1          0x02F8
#define TXT_SETTING_SPEEDUNIT2          0x02FB
#define TXT_SETTING_IDLING_STOP_TIME    0x02FE
#define TXT_SID_ECO                     0x0301
#define TXT_SID_TRIP                    0x0305
#define TXT_SID_TBT_DEST_UNIT_HOUR      0x0308
#define TXT_SID_TBT_DEST_UNIT_MINITES   0x030A
#define TXT_SID_TBT_POINT_DIST_UNIT_KM  0x030C
#define TXT_SID_TBT_POINT_DIST_UNIT_MILES                                         0x030F
#define TXT_SID_TBT_POINT_DIST_UNIT_M   0x0312
#define TXT_SID_TBT_POINT_DIST_UNIT_YARD                                        0x0314
#define TXT_SID_TBT_POINT_DIST_UNIT_FOOT                                        0x0319
#define TXT_SID_TBT_POINT_DIST_UNIT_FEET                                        0x031E
#define TXT_SID_TBT_POINT_DIST_UNIT_1_2_MILES                                             0x0323
#define TXT_SID_TBT_POINT_DIST_UNIT_1_4_MILES                                             0x032D
#define TXT_SID_TBT_POINT_DIST_UNIT_2_4_MILES                                             0x0337
#define TXT_SID_TBT_POINT_DIST_UNIT_3_4_MILES                                             0x0341
#define TXT_SETTING_STAT_NON            0x034B
#define TXT_BLANK_SID                   0x034D
#define TXT_SID_BAR_1                   0x034F
#define TXT_SID_BAR_5                   0x0351
#define TXT_SID_BAR_6                   0x0357
#define TXT_SID_WRNG_SCR_UNIT_KM        0x035E
#define TXT_SID_WRNG_SCR_UNIT_MILES     0x0361
#define TXT_WNG_ADAS_022_1_L1           0x0364
#define TXT_WNG_ADAS_022_2_L1           0x03EC
#define TXT_WNG_ADAS_022_3_L1           0x04EA
#define TXT_WNG_ADAS_022_3_L2           0x05B7
#define TXT_WNG_ADAS_023_1_L1           0x0600
#define TXT_WNG_ADAS_023_2_L1           0x0630
#define TXT_WNG_ADAS_024_L1             0x0660
#define TXT_WNG_ADAS_024_L2             0x074E
#define TXT_WNG_ADAS_051_L1             0x0788
#define TXT_WNG_ADAS_051_L2             0x0852
#define TXT_WNG_ADAS_051_L3             0x08E5
#define TXT_WNG_ADAS_070_L1             0x0919
#define TXT_WNG_ADAS_070_L2             0x09C2
#define TXT_WNG_ADAS_070_L3             0x0AC1
#define TXT_WNG_ADAS_071_L1             0x0AF9
#define TXT_WNG_NORM_001_L1             0x0B27
#define TXT_WNG_NORM_001_L2             0x0C23
#define TXT_WNG_NORM_001_L3             0x0D19
#define TXT_WNG_NORM_002_L1             0x0D3C
#define TXT_WNG_NORM_002_L2             0x0E2B
#define TXT_WNG_NORM_003_L1             0x0E61
#define TXT_WNG_NORM_003_L2             0x0F48
#define TXT_WNG_NORM_003_L3             0x0FD3
#define TXT_WNG_NORM_004_L1             0x0FEF
#define TXT_WNG_NORM_004_L2             0x10F5
#define TXT_WNG_NORM_004_L3             0x1197
#define TXT_WNG_NORM_006_L1             0x11D6
#define TXT_WNG_NORM_006_L2             0x12E1
#define TXT_WNG_NORM_006_L3             0x1387
#define TXT_WNG_NORM_007_1_L1           0x13A1
#define TXT_WNG_NORM_007_1_L2           0x14AD
#define TXT_WNG_NORM_007_2_L1           0x1506
#define TXT_WNG_NORM_007_2_L2           0x160B
#define TXT_WNG_NORM_007_3_L1           0x164C
#define TXT_WNG_NORM_007_3_L2           0x167C
#define TXT_WNG_NORM_007_4_L1           0x169E
#define TXT_WNG_NORM_007_4_L2           0x16CC
#define TXT_WNG_NORM_007_5_L1           0x16E6
#define TXT_WNG_NORM_007_5_L2           0x17CF
#define TXT_WNG_NORM_007_5_L3           0x187E
#define TXT_WNG_NORM_007_6_L1           0x1899
#define TXT_WNG_NORM_007_6_L2           0x1998
#define TXT_WNG_NORM_007_7_L1           0x19E9
#define TXT_WNG_NORM_007_7_L2           0x1AAC
#define TXT_WNG_NORM_007_7_L3           0x1BB3
#define TXT_WNG_NORM_007_8_L1           0x1C13
#define TXT_WNG_NORM_007_8_L2           0x1CBB
#define TXT_WNG_NORM_007_8_L3           0x1DB0
#define TXT_WNG_NORM_007_8_L4           0x1E78
#define TXT_WNG_NORM_007_9_L1           0x1ED6
#define TXT_WNG_NORM_007_9_L2           0x1FCD
#define TXT_WNG_NORM_007_9_L3           0x20DF
#define TXT_WNG_NORM_007_10_L1          0x21CB
#define TXT_WNG_NORM_007_10_L2          0x222B
#define TXT_WNG_NORM_007_10_L3          0x230A
#define TXT_WNG_NORM_007_10_L4          0x23D6
#define TXT_WNG_NORM_007_11_L1          0x23F5
#define TXT_WNG_NORM_007_11_L2          0x2491
#define TXT_WNG_NORM_007_11_L3          0x253D
#define TXT_WNG_NORM_008_1_L1           0x2561
#define TXT_WNG_NORM_008_1_L2           0x262D
#define TXT_WNG_NORM_008_1_L3           0x26D6
#define TXT_WNG_NORM_008_2_L1           0x26EE
#define TXT_WNG_NORM_008_2_L2           0x27E3
#define TXT_WNG_NORM_008_2_L3           0x28C8
#define TXT_WNG_NORM_008_2_L4           0x2967
#define TXT_WNG_NORM_008_3_L1           0x2985
#define TXT_WNG_NORM_008_3_L2           0x2A63
#define TXT_WNG_NORM_008_3_L3           0x2B2B
#define TXT_WNG_NORM_008_4_L1           0x2B4D
#define TXT_WNG_NORM_008_4_L2           0x2C48
#define TXT_WNG_NORM_008_4_L3           0x2CD8
#define TXT_WNG_NORM_008_5_L1           0x2D0A
#define TXT_WNG_NORM_008_5_L2           0x2DD4
#define TXT_WNG_NORM_008_5_L3           0x2E5C
#define TXT_WNG_NORM_008_6_L1           0x2E6E
#define TXT_WNG_NORM_008_6_L2           0x2F3A
#define TXT_WNG_NORM_008_6_L3           0x3011
#define TXT_WNG_NORM_008_7_L1           0x306D
#define TXT_WNG_NORM_008_7_L2           0x3105
#define TXT_WNG_NORM_008_7_L3           0x31C6
#define TXT_WNG_NORM_008_8_L1           0x31F2
#define TXT_WNG_NORM_008_8_L2           0x32F4
#define TXT_WNG_NORM_008_8_L3           0x3443
#define TXT_WNG_NORM_008_8_L4           0x3548
#define TXT_WNG_NORM_008_9_L1           0x35D1
#define TXT_WNG_NORM_008_9_L2           0x35FF
#define TXT_WNG_NORM_008_9_L3           0x362D
#define TXT_WNG_NORM_008_9_L4           0x3657
#define TXT_WNG_NORM_008_10_L1          0x3675
#define TXT_WNG_NORM_008_10_L2          0x374E
#define TXT_WNG_NORM_008_10_L3          0x37E0
#define TXT_WNG_NORM_008_11_L1          0x37F2
#define TXT_WNG_NORM_008_11_L2          0x38DB
#define TXT_WNG_NORM_008_11_L3          0x39E1
#define TXT_WNG_NORM_008_11_L4          0x3A84
#define TXT_WNG_NORM_008_13_L1          0x3AE3
#define TXT_WNG_NORM_008_13_L2          0x3B11
#define TXT_WNG_NORM_008_13_L3          0x3B3F
#define TXT_WNG_NORM_008_14_L1          0x3B51
#define TXT_WNG_NORM_008_14_L2          0x3C33
#define TXT_WNG_NORM_008_14_L3          0x3D47
#define TXT_WNG_NORM_008_14_L4          0x3DD7
#define TXT_WNG_NORM_008_15_L1          0x3E0C
#define TXT_WNG_NORM_008_15_L2          0x3E3A
#define TXT_WNG_NORM_008_15_L3          0x3E68
#define TXT_WNG_NORM_008_15_L4          0x3E90
#define TXT_WNG_NORM_009_L1             0x3EA6
#define TXT_WNG_NORM_009_L2             0x3F56
#define TXT_WNG_NORM_010_L1             0x3F76
#define TXT_WNG_NORM_010_L2             0x4059
#define TXT_WNG_NORM_012_L1             0x4084
#define TXT_WNG_NORM_012_L2             0x414E
#define TXT_WNG_NORM_013_1_L1           0x41E9
#define TXT_WNG_NORM_013_1_L2           0x42D5
#define TXT_WNG_NORM_013_2_L1           0x4329
#define TXT_WNG_NORM_013_2_L2           0x4357
#define TXT_WNG_NORM_013_3_L1           0x4375
#define TXT_WNG_NORM_013_3_L2           0x43A3
#define TXT_WNG_NORM_014_L1             0x43C1
#define TXT_WNG_NORM_014_L2             0x4440
#define TXT_WNG_NORM_015_L1             0x44A6
#define TXT_WNG_NORM_015_L2             0x4535
#define TXT_WNG_NORM_015_L3             0x457B
#define TXT_WNG_NORM_016_L1             0x4595
#define TXT_WNG_NORM_016_L2             0x4664
#define TXT_WNG_NORM_016_L3             0x4702
#define TXT_WNG_NORM_017_L1             0x471E
#define TXT_WNG_NORM_017_L2             0x47C0
#define TXT_WNG_NORM_018_1_L1           0x4823
#define TXT_WNG_NORM_018_1_L2           0x48DA
#define TXT_WNG_NORM_018_1_L3           0x496A
#define TXT_WNG_NORM_018_2_L1           0x497C
#define TXT_WNG_NORM_018_2_L2           0x49AA
#define TXT_WNG_NORM_018_2_L3           0x49D6
#define TXT_WNG_NORM_019_1_L1           0x49E8
#define TXT_WNG_NORM_019_1_L2           0x4AFB
#define TXT_WNG_NORM_019_2_L1           0x4B3E
#define TXT_WNG_NORM_019_2_L2           0x4C0B
#define TXT_WNG_NORM_019_2_L3           0x4CAC
#define TXT_WNG_NORM_021_L1             0x4CEC
#define TXT_WNG_NORM_021_L2             0x4DA2
#define TXT_WNG_NORM_022_1_L1           0x4E07
#define TXT_WNG_NORM_022_1_L2           0x4EC4
#define TXT_WNG_NORM_022_2_L1           0x4FB5
#define TXT_WNG_NORM_022_2_L2           0x509A
#define TXT_WNG_NORM_022_2_L3           0x5194
#define TXT_WNG_NORM_022_3_L1           0x51AD
#define TXT_WNG_NORM_022_3_L2           0x525B
#define TXT_WNG_NORM_022_3_L3           0x5348
#define TXT_WNG_NORM_022_4_L1           0x537C
#define TXT_WNG_NORM_022_4_L2           0x5471
#define TXT_WNG_NORM_022_4_L3           0x558E
#define TXT_WNG_NORM_022_5_L1           0x55DA
#define TXT_WNG_NORM_022_5_L2           0x5687
#define TXT_WNG_NORM_022_5_L3           0x573B
#define TXT_WNG_NORM_022_6_L1           0x5762
#define TXT_WNG_NORM_022_6_L2           0x57F6
#define TXT_WNG_NORM_022_7_L1           0x5845
#define TXT_WNG_NORM_022_7_L2           0x596F
#define TXT_WNG_NORM_022_7_L3           0x5A10
#define TXT_WNG_NORM_022_8_L1           0x5A52
#define TXT_WNG_NORM_022_8_L2           0x5AE9
#define TXT_WNG_NORM_022_8_L3           0x5B9B
#define TXT_WNG_NORM_022_9_L1           0x5BE9
#define TXT_WNG_NORM_022_9_L2           0x5C3B
#define TXT_WNG_NORM_022_9_L3           0x5CBF
#define TXT_WNG_NORM_022_10_1_L1        0x5D2A
#define TXT_WNG_NORM_022_10_1_L2        0x5D76
#define TXT_WNG_NORM_022_10_1_L3        0x5DEB
#define TXT_WNG_NORM_022_10_2_L1        0x5E48
#define TXT_WNG_NORM_022_10_2_L2        0x5E9C
#define TXT_WNG_NORM_022_10_2_L3        0x5F0F
#define TXT_WNG_NORM_022_11_L1          0x5F88
#define TXT_WNG_NORM_022_11_L2          0x6072
#define TXT_WNG_NORM_023_1_L1           0x6116
#define TXT_WNG_NORM_023_1_L2           0x61EE
#define TXT_WNG_NORM_023_3_L1           0x6274
#define TXT_WNG_NORM_023_3_L2           0x6352
#define TXT_WNG_NORM_023_3_L3           0x63CF
#define TXT_WNG_NORM_023_4_L1           0x63FE
#define TXT_WNG_NORM_023_4_L2           0x649F
#define TXT_WNG_NORM_023_5_L1           0x64C1
#define TXT_WNG_NORM_023_5_L2           0x655E
#define TXT_WNG_NORM_023_6_L1           0x6580
#define TXT_WNG_NORM_023_6_L2           0x65EC
#define TXT_WNG_NORM_023_7_1_L1         0x661F
#define TXT_WNG_NORM_023_7_1_L2         0x66C9
#define TXT_WNG_NORM_023_7_1_L3         0x6744
#define TXT_WNG_NORM_023_7_2_L1         0x677C
#define TXT_WNG_NORM_023_7_2_L2         0x67C6
#define TXT_WNG_NORM_023_7_2_L3         0x6841
#define TXT_WNG_NORM_023_8_L1           0x6883
#define TXT_WNG_NORM_023_8_L2           0x68D5
#define TXT_WNG_NORM_023_8_L3           0x6918
#define TXT_WNG_NORM_023_9_L1           0x694E
#define TXT_WNG_NORM_023_9_L2           0x6993
#define TXT_WNG_NORM_023_9_L3           0x69E0
#define TXT_WNG_NORM_023_10_L1          0x69FA
#define TXT_WNG_NORM_023_10_L2          0x6A28
#define TXT_WNG_NORM_023_10_L3          0x6A50
#define TXT_WNG_NORM_023_11_L1          0x6A6A
#define TXT_WNG_NORM_023_11_L2          0x6B13
#define TXT_WNG_NORM_024_1_L1           0x6B36
#define TXT_WNG_NORM_024_1_L2           0x6BF3
#define TXT_WNG_NORM_024_2_L1           0x6C25
#define TXT_WNG_NORM_024_2_L2           0x6C91
#define TXT_WNG_NORM_025_L1             0x6CD8
#define TXT_WNG_NORM_025_L2             0x6D9C
#define TXT_WNG_NORM_025_L3             0x6E2C
#define TXT_WNG_NORM_026_L1             0x6E3E
#define TXT_WNG_NORM_026_L2             0x6F34
#define TXT_WNG_NORM_026_L3             0x6F7C
#define TXT_WNG_NORM_027_L1             0x6F8E
#define TXT_WNG_NORM_027_L2             0x708C
#define TXT_WNG_NORM_027_L3             0x715A
#define TXT_WNG_NORM_028_L1             0x716C
#define TXT_WNG_NORM_028_L2             0x726F
#define TXT_WNG_NORM_028_L3             0x7350
#define TXT_WNG_NORM_029_L1             0x7411
#define TXT_WNG_NORM_029_L2             0x743F
#define TXT_WNG_NORM_029_L3             0x746D
#define TXT_WNG_NORM_030_L1             0x7495
#define TXT_WNG_NORM_030_L2             0x7521
#define TXT_WNG_NORM_031_1_L1           0x757E
#define TXT_WNG_NORM_031_1_L2           0x760B
#define TXT_WNG_NORM_031_2_L1           0x767A
#define TXT_WNG_NORM_031_2_L2           0x7730
#define TXT_WNG_NORM_031_2_L3           0x77D0
#define TXT_WNG_NORM_031_3_L1           0x780D
#define TXT_WNG_NORM_031_3_L2           0x7878
#define TXT_WNG_NORM_031_3_L3           0x78BE
#define TXT_WNG_NORM_032_L1             0x78D0
#define TXT_WNG_NORM_032_L2             0x79D3
#define TXT_WNG_NORM_032_L3             0x7AC3
#define TXT_WNG_NORM_033_L1             0x7AE9
#define TXT_WNG_NORM_033_L2             0x7BB6
#define TXT_WNG_NORM_034_L1             0x7C01
#define TXT_WNG_NORM_034_L2             0x7C6B
#define TXT_WNG_NORM_034_L3             0x7CE3
#define TXT_WNG_NORM_035_L1             0x7D03
#define TXT_WNG_NORM_035_L2             0x7DA7
#define TXT_WNG_NORM_035_L3             0x7E41
#define TXT_WNG_NORM_036_1_L1           0x7E63
#define TXT_WNG_NORM_036_1_L2           0x7F30
#define TXT_WNG_NORM_036_1_L3           0x7F60
#define TXT_WNG_NORM_036_2_L1           0x7F7F
#define TXT_WNG_NORM_036_2_L2           0x7FAD
#define TXT_WNG_NORM_036_2_L3           0x7FC3
#define TXT_WNG_NORM_036_3_L1           0x7FD7
#define TXT_WNG_NORM_036_3_L2           0x808D
#define TXT_WNG_NORM_036_3_L3           0x8118
#define TXT_WNG_NORM_038_L1             0x812A
#define TXT_WNG_NORM_038_L2             0x8238
#define TXT_WNG_NORM_039_L1             0x82B1
#define TXT_WNG_NORM_039_L2             0x83D0
#define TXT_WNG_NORM_039_L3             0x84A3
#define TXT_WNG_NORM_042_1_L1           0x84F3
#define TXT_WNG_NORM_042_1_L2           0x857E
#define TXT_WNG_NORM_042_1_L3           0x85A2
#define TXT_WNG_NORM_042_2_L1           0x85B6
#define TXT_WNG_NORM_042_2_L2           0x8616
#define TXT_WNG_NORM_042_2_L3           0x869A
#define TXT_WNG_NORM_042_2_L4           0x86C4
#define TXT_WNG_NORM_043_1_L1           0x86E0
#define TXT_WNG_NORM_043_1_L2           0x8793
#define TXT_WNG_NORM_043_2_L1           0x87C5
#define TXT_WNG_NORM_043_3_L1           0x885B
#define TXT_WNG_NORM_043_3_L2           0x8986
#define TXT_WNG_NORM_043_3_L3           0x8A9C
#define TXT_WNG_NORM_043_3_L4           0x8B98
#define TXT_WNG_NORM_046_L1             0x8BCF
#define TXT_WNG_NORM_046_L2             0x8CC0
#define TXT_WNG_NORM_047_1_L1           0x8D4B
#define TXT_WNG_NORM_047_1_L2           0x8E30
#define TXT_WNG_NORM_047_1_L3           0x8EF0
#define TXT_WNG_NORM_047_1_L4           0x9020
#define TXT_WNG_NORM_047_2_L1           0x9074
#define TXT_WNG_NORM_047_2_L2           0x91E9
#define TXT_WNG_NORM_047_2_L3           0x9347
#define TXT_WNG_NORM_047_2_L4           0x94D1
#define TXT_WNG_NORM_047_3_L1           0x950A
#define TXT_WNG_NORM_047_3_L2           0x9611
#define TXT_WNG_NORM_047_3_L3           0x96FD
#define TXT_WNG_NORM_047_3_L4           0x97F2
#define TXT_WNG_NORM_047_4_L1           0x9863
#define TXT_WNG_NORM_047_4_L2           0x9988
#define TXT_WNG_NORM_047_4_L3           0x9A93
#define TXT_WNG_NORM_047_4_L4           0x9B81
#define TXT_WNG_NORM_047_5_L1           0x9BBC
#define TXT_WNG_NORM_047_5_L2           0x9C46
#define TXT_WNG_NORM_047_5_L3           0x9CE4
#define TXT_WNG_NORM_048_L1             0x9D06
#define TXT_WNG_NORM_048_L2             0x9DB4
#define TXT_WNG_NORM_048_L3             0x9E8A
#define TXT_WNG_NORM_049_L1             0x9E9C
#define TXT_WNG_NORM_049_L2             0x9F5F
#define TXT_WNG_NORM_049_L3             0x9FE3
#define TXT_WNG_NORM_050_1_L1           0xA009
#define TXT_WNG_NORM_050_1_L2           0xA10E
#define TXT_WNG_NORM_050_1_L3           0xA197
#define TXT_WNG_NORM_050_2_L1           0xA1BF
#define TXT_WNG_NORM_050_2_L2           0xA2C3
#define TXT_WNG_NORM_050_2_L3           0xA2EF
#define TXT_WNG_NORM_050_3_L1           0xA317
#define TXT_WNG_NORM_050_3_L2           0xA38D
#define TXT_WNG_NORM_050_3_L3           0xA3B9
#define TXT_WNG_NORM_050_4_L1           0xA3DD
#define TXT_WNG_NORM_050_4_L2           0xA452
#define TXT_WNG_NORM_050_4_L3           0xA4CA
#define TXT_WNG_NORM_050_5_L1           0xA4E6
#define TXT_WNG_NORM_050_5_L2           0xA54A
#define TXT_WNG_NORM_050_5_L3           0xA5BE
#define TXT_WNG_NORM_050_6_L1           0xA5D2
#define TXT_WNG_NORM_050_6_L2           0xA62F
#define TXT_WNG_NORM_050_7_L1           0xA678
#define TXT_WNG_NORM_050_7_L2           0xA74A
#define TXT_WNG_NORM_050_7_L3           0xA815
#define TXT_WNG_NORM_050_8_L1           0xA834
#define TXT_WNG_NORM_050_8_L2           0xA8D4
#define TXT_WNG_NORM_050_8_L3           0xA931
#define TXT_WNG_NORM_050_9_L1           0xA949
#define TXT_WNG_NORM_050_9_L2           0xA9E3
#define TXT_WNG_NORM_051_1_L1           0xAA26
#define TXT_WNG_NORM_051_1_L2           0xAAFB
#define TXT_WNG_NORM_051_3_1_L1         0xAB21
#define TXT_WNG_NORM_051_3_1_L2         0xABE5
#define TXT_WNG_NORM_051_3_1_L3         0xAC1F
#define TXT_WNG_NORM_051_3_2_L1         0xAC3B
#define TXT_WNG_NORM_051_3_2_L2         0xAC7E
#define TXT_WNG_NORM_051_3_2_L3         0xACAA
#define TXT_WNG_NORM_051_4_L1           0xACC6
#define TXT_WNG_NORM_051_4_L2           0xAD0D
#define TXT_WNG_NORM_051_4_L3           0xAD39
#define TXT_WNG_NORM_051_5_L1           0xAD55
#define TXT_WNG_NORM_051_5_L2           0xAD9B
#define TXT_WNG_NORM_051_5_L3           0xADD7
#define TXT_WNG_NORM_052_1_L1           0xADF1
#define TXT_WNG_NORM_052_1_L2           0xAE7C
#define TXT_WNG_NORM_052_1_L3           0xAEDB
#define TXT_WNG_NORM_052_2_L1           0xAEFD
#define TXT_WNG_NORM_052_2_L2           0xAF75
#define TXT_WNG_NORM_052_3_L1           0xAFCB
#define TXT_WNG_NORM_052_3_L2           0xB05C
#define TXT_WNG_NORM_052_3_L3           0xB0AE
#define TXT_WNG_NORM_053_1_L1           0xB0C0
#define TXT_WNG_NORM_053_1_L2           0xB128
#define TXT_WNG_NORM_053_1_L3           0xB154
#define TXT_WNG_NORM_053_2_L1           0xB17A
#define TXT_WNG_NORM_053_2_L2           0xB263
#define TXT_WNG_NORM_053_2_L3           0xB33D
#define TXT_WNG_NORM_053_3_L1           0xB359
#define TXT_WNG_NORM_053_3_L2           0xB409
#define TXT_WNG_NORM_053_3_L3           0xB498
#define TXT_WNG_NORM_053_4_L1           0xB4EE
#define TXT_WNG_NORM_053_4_L2           0xB535
#define TXT_WNG_NORM_053_4_L3           0xB561
#define TXT_WNG_NORM_053_5_L1           0xB587
#define TXT_WNG_NORM_053_5_L2           0xB645
#define TXT_WNG_NORM_053_5_L3           0xB71D
#define TXT_WNG_NORM_054_1_L1           0xB7B0
#define TXT_WNG_NORM_054_1_L2           0xB885
#define TXT_WNG_NORM_054_1_L3           0xB8F3
#define TXT_WNG_NORM_054_2_L1           0xB90C
#define TXT_WNG_NORM_054_2_L2           0xB93A
#define TXT_WNG_NORM_054_2_L3           0xB95E
#define TXT_WNG_NORM_055_1_L1           0xB972
#define TXT_WNG_NORM_055_1_L2           0xB9C3
#define TXT_WNG_NORM_055_2_1_L1         0xBA09
#define TXT_WNG_NORM_055_2_1_L2         0xBA84
#define TXT_WNG_NORM_055_2_2_L1         0xBB12
#define TXT_WNG_NORM_055_2_2_L2         0xBB61
#define TXT_WNG_NORM_055_3_L1           0xBC06
#define TXT_WNG_NORM_055_3_L2           0xBC53
#define TXT_WNG_NORM_056_1_L1           0xBC9C
#define TXT_WNG_NORM_056_1_L2           0xBCED
#define TXT_WNG_NORM_056_1_L3           0xBD15
#define TXT_WNG_NORM_056_2_L1           0xBD29
#define TXT_WNG_NORM_056_2_L2           0xBDB5
#define TXT_WNG_NORM_056_2_L3           0xBE2A
#define TXT_WNG_NORM_056_2_L4           0xBE4A
#define TXT_WNG_NORM_056_3_L1           0xBE5C
#define TXT_WNG_NORM_056_3_L2           0xBEC2
#define TXT_WNG_NORM_056_3_L3           0xBF8A
#define TXT_WNG_NORM_056_4_L1           0xBFE7
#define TXT_WNG_NORM_056_4_L2           0xC08E
#define TXT_WNG_NORM_056_4_L3           0xC0F4
#define TXT_WNG_NORM_056_4_L4           0xC12A
#define TXT_WNG_NORM_056_5_L1           0xC140
#define TXT_WNG_NORM_056_5_L2           0xC1EB
#define TXT_WNG_NORM_056_5_L3           0xC241
#define TXT_WNG_NORM_056_6_L1           0xC25A
#define TXT_WNG_NORM_056_6_L2           0xC31E
#define TXT_WNG_NORM_056_6_L3           0xC421
#define TXT_WNG_NORM_057_1_L1           0xC488
#define TXT_WNG_NORM_057_1_L2           0xC50A
#define TXT_WNG_NORM_057_1_L3           0xC624
#define TXT_WNG_NORM_057_1_L4           0xC689
#define TXT_WNG_NORM_057_2_L1           0xC6A8
#define TXT_WNG_NORM_057_2_L2           0xC73B
#define TXT_WNG_NORM_057_2_L3           0xC7AE
#define TXT_WNG_NORM_058_L1             0xC7C9
#define TXT_WNG_NORM_058_L2             0xC85B
#define TXT_WNG_NORM_058_L3             0xC918
#define TXT_WNG_NORM_060_1_L1           0xC958
#define TXT_WNG_NORM_060_1_L2           0xCA14
#define TXT_WNG_NORM_060_1_L3           0xCA97
#define TXT_WNG_NORM_060_2_L1           0xCABD
#define TXT_WNG_NORM_060_2_L2           0xCB0B
#define TXT_WNG_NORM_060_2_L3           0xCB84
#define TXT_WNG_NORM_061_1_L1           0xCBAA
#define TXT_WNG_NORM_061_1_L2           0xCC64
#define TXT_WNG_NORM_061_1_L3           0xCD44
#define TXT_WNG_NORM_061_2_L1           0xCD79
#define TXT_WNG_NORM_061_2_L2           0xCE1B
#define TXT_WNG_NORM_061_2_L3           0xCED9
#define TXT_WNG_NORM_061_2_L4           0xCF37
#define TXT_WNG_NORM_061_3_L1           0xCF4D
#define TXT_WNG_NORM_061_3_L2           0xCFD7
#define TXT_WNG_NORM_061_3_L3           0xD07E
#define TXT_WNG_NORM_061_6_L1           0xD0B2
#define TXT_WNG_NORM_061_6_L2           0xD12D
#define TXT_WNG_NORM_061_6_L3           0xD1CA
#define TXT_WNG_NORM_061_6_L4           0xD258
#define TXT_WNG_NORM_063_1_L1           0xD27E
#define TXT_WNG_NORM_063_1_L2           0xD2E2
#define TXT_WNG_NORM_063_2_L1           0xD341
#define TXT_WNG_NORM_063_2_L2           0xD3C6
#define TXT_WNG_NORM_063_2_L3           0xD3FD
#define TXT_WNG_NORM_069_1_L1           0xD41F
#define TXT_WNG_NORM_069_1_L2           0xD463
#define TXT_WNG_NORM_069_2_L1           0xD483
#define TXT_WNG_NORM_069_2_L2           0xD546
#define TXT_WNG_NORM_069_2_L3           0xD5F2
#define TXT_WNG_NORM_069_3_L1           0xD6B1
#define TXT_WNG_NORM_069_3_L2           0xD72E
#define TXT_WNG_NORM_069_3_L3           0xD799
#define TXT_WNG_NORM_069_3_L4           0xD849
#define TXT_WNG_NORM_069_4_L1           0xD85F
#define TXT_WNG_NORM_069_4_L2           0xD8C0
#define TXT_WNG_NORM_069_4_L3           0xD93D
#define TXT_WNG_NORM_069_4_L4           0xD9FF
#define TXT_WNG_NORM_069_5_L1           0xDA48
#define TXT_WNG_NORM_069_5_L2           0xDA7D
#define TXT_WNG_NORM_069_6_L1           0xDAB0
#define TXT_WNG_NORM_069_6_L2           0xDBDC
#define TXT_WNG_NORM_069_6_L3           0xDCEC
#define TXT_WNG_NORM_069_7_L1           0xDDBF
#define TXT_WNG_NORM_069_7_L2           0xDE60
#define TXT_WNG_NORM_069_7_L3           0xDF10
#define TXT_WNG_NORM_069_8_L1           0xDF9E
#define TXT_WNG_NORM_069_9_L1           0xDFCC
#define TXT_WNG_NORM_069_9_L2           0xE0A6
#define TXT_WNG_NORM_069_9_L3           0xE122
#define TXT_WNG_NORM_069_10_L1          0xE13C
#define TXT_WNG_NORM_069_10_L2          0xE17C
#define TXT_WNG_NORM_069_10_L3          0xE1C3
#define TXT_WNG_NORM_069_10_L4          0xE1EE
#define TXT_WNG_NORM_069_11_L1          0xE200
#define TXT_WNG_NORM_069_11_L2          0xE276
#define TXT_WNG_NORM_069_11_L3          0xE2BF
#define TXT_WNG_NORM_069_11_L4          0xE2F6
#define TXT_WNG_NORM_069_12_L1          0xE308
#define TXT_WNG_NORM_069_12_L2          0xE362
#define TXT_WNG_NORM_071_1_L1           0xE385
#define TXT_WNG_NORM_071_1_L2           0xE474
#define TXT_WNG_NORM_071_1_L3           0xE4EE
#define TXT_WNG_NORM_071_2_L1           0xE519
#define TXT_WNG_NORM_071_2_L2           0xE599
#define TXT_WNG_NORM_071_2_L3           0xE608
#define TXT_WNG_NORM_071_3_L1           0xE63A
#define TXT_WNG_NORM_071_3_L2           0xE6C7
#define TXT_WNG_NORM_071_3_L3           0xE754
#define TXT_WNG_NORM_071_3_L4           0xE825
#define TXT_WNG_NORM_071_4_L1           0xE86A
#define TXT_WNG_NORM_071_4_L2           0xE908
#define TXT_WNG_NORM_071_4_L3           0xE9EB
#define TXT_WNG_NORM_071_5_L1           0xEA8A
#define TXT_WNG_NORM_071_5_L2           0xEAB8
#define TXT_WNG_NORM_071_5_L3           0xEAF5
#define TXT_WNG_NORM_072_1_L1           0xEB21
#define TXT_WNG_NORM_072_1_L2           0xEC1A
#define TXT_WNG_NORM_072_1_L3           0xECFD
#define TXT_WNG_NORM_072_2_L1           0xED3B
#define TXT_WNG_NORM_072_2_L2           0xEE37
#define TXT_WNG_NORM_072_2_L3           0xEF1D
#define TXT_WNG_NORM_072_3_L1           0xEF5D
#define TXT_WNG_NORM_072_3_L2           0xF061
#define TXT_WNG_NORM_072_3_L3           0xF0F5
#define TXT_WNG_NORM_072_4_KM_L1        0xF143
#define TXT_WNG_NORM_072_4_KM_L2        0xF20B
#define TXT_WNG_NORM_072_4_KM_L3        0xF302
#define TXT_WNG_NORM_072_4_KM_L4        0xF459
#define TXT_WNG_NORM_072_4_MILES_L1     0xF4A6
#define TXT_WNG_NORM_072_4_MILES_L2     0xF4EA
#define TXT_WNG_NORM_072_4_MILES_L3     0xF569
#define TXT_WNG_NORM_072_4_MILES_L4     0xF681
#define TXT_WNG_NORM_072_5_L1           0xF6C9
#define TXT_WNG_NORM_072_5_L2           0xF712
#define TXT_WNG_NORM_072_5_L3           0xF7B5
#define TXT_WNG_NORM_072_5_L4           0xF864
#define TXT_WNG_NORM_072_6_KM_L1        0xF876
#define TXT_WNG_NORM_072_6_KM_L2        0xF8A4
#define TXT_WNG_NORM_072_6_KM_L3        0xF90B
#define TXT_WNG_NORM_072_6_KM_L4        0xFA0A
#define TXT_WNG_NORM_072_6_MILES_L1     0xFA48
#define TXT_WNG_NORM_072_6_MILES_L2     0xFA76
#define TXT_WNG_NORM_072_6_MILES_L3     0xFAE3
#define TXT_WNG_NORM_072_6_MILES_L4     0xFBFB
#define TXT_WNG_NORM_072_7_L1           0xFC43
#define TXT_WNG_NORM_072_7_L2           0xFCE3
#define TXT_WNG_NORM_072_7_L3           0xFD80
#define TXT_WNG_NORM_072_7_L4           0xFE9E
#define TXT_WNG_NORM_073_1_L1           0xFEC1
#define TXT_WNG_NORM_073_1_L2           0xFF41
#define TXT_WNG_NORM_073_2_L1           0xFFD9
#define TXT_WNG_NORM_073_2_L2           0x1007D
#define TXT_WNG_NORM_073_2_L3           0x1018E
#define TXT_WNG_NORM_073_3_L1           0x10208
#define TXT_WNG_NORM_073_3_L2           0x102E2
#define TXT_WNG_NORM_079_1_L1           0x1030B
#define TXT_WNG_NORM_079_1_L2           0x10416
#define TXT_WNG_NORM_079_1_L3           0x10486
#define TXT_WNG_NORM_079_2_L1           0x104B6
#define TXT_WNG_NORM_079_2_L2           0x1053F
#define TXT_WNG_NORM_079_2_L3           0x10588
#define TXT_WNG_NORM_080_1_L1           0x105AD
#define TXT_WNG_NORM_080_1_L2           0x106A2
#define TXT_WNG_NORM_080_1_L3           0x10798
#define TXT_WNG_NORM_080_1_L4           0x10831
#define TXT_WNG_NORM_080_2_L1           0x10879
#define TXT_WNG_NORM_080_2_L2           0x108DA
#define TXT_WNG_NORM_080_2_L3           0x1095D
#define TXT_WNG_NORM_080_2_L4           0x109A1
#define TXT_WNG_NORM_081_1_L1           0x109BA
#define TXT_WNG_NORM_081_1_L2           0x109E8
#define TXT_WNG_NORM_081_1_L3           0x10A12
#define TXT_WNG_NORM_081_2_L1           0x10A26
#define TXT_WNG_NORM_081_2_L2           0x10AB2
#define TXT_WNG_NORM_081_2_L3           0x10B15
#define TXT_WNG_NORM_081_2_L4           0x10B5F
#define TXT_WNG_NORM_081_3_L1           0x10B72
#define TXT_WNG_NORM_081_3_L2           0x10CAA
#define TXT_WNG_NORM_081_3_L3           0x10DBC
#define TXT_WNG_NORM_081_3_L4           0x10E90
#define TXT_WNG_NORM_082_L1             0x10EE3
#define TXT_WNG_NORM_082_L2             0x10FF5
#define TXT_WNG_NORM_082_L3             0x110EA
#define TXT_WNG_NORM_083_L1             0x11146
#define TXT_WNG_NORM_083_L2             0x1118F
#define TXT_WNG_NORM_084_L1             0x111D5
#define TXT_WNG_NORM_084_L2             0x112E0
#define TXT_WNG_NORM_084_L3             0x11362
#define TXT_WNG_NORM_085_L1             0x1137A
#define TXT_WNG_NORM_085_L2             0x114A9
#define TXT_WNG_NORM_085_L3             0x115AA
#define TXT_WNG_NORM_085_L4             0x116B6
#define TXT_COMMON_ON                   0x11736
#define TXT_COMMON_OFF                  0x11782
#define TXT_COMMON_RESET                0x117D5
#define TXT_SETTING_DISPLAY             0x11864
#define TXT_SETTING_SUBSPD              0x1193A
#define TXT_SETTING_ADAS                0x11A72
#define TXT_SETTING_ADAS_FCM_MUTE       0x11B86
#define TXT_SETTING_ADAS_FCM_DIST       0x11C0E
#define TXT_SETTING_ADAS_FCM_DIST_NEAR  0x11C9B
#define TXT_SETTING_ADAS_FCM_DIST_MID   0x11CF9
#define TXT_SETTING_ADAS_FCM_DIST_FAR   0x11D63
#define TXT_SETTING_ADAS_CORNERSENS     0x11DBC
#define TXT_SETTING_ADAS_CORNERSENS_FRONT                                         0x11EA1
#define TXT_SETTING_ADAS_CORNERSENS_REAR                                        0x11F1C
#define TXT_SETTING_ADAS_CORNERSENS_REAR_HITCH                                              0x11F8F
#define TXT_SETTING_ADAS_LCDN_FAST      0x12013
#define TXT_SETTING_ADAS_LCDN_STD       0x120A4
#define TXT_SETTING_ADAS_LCDN_SLOW      0x12117
#define TXT_SETTING_BT                  0x12199
#define TXT_SETTING_BT_SEL              0x12255
#define TXT_SETTING_BT_REGIST           0x1234B
#define TXT_SETTING_BT_INITIALIZE       0x12461
#define TXT_SETTING_TPMS_RESET          0x12588
#define TXT_SETTING_TPMS_IDSET          0x12662
#define TXT_SETTING_MULTI_INT           0x1270D
#define TXT_SETTING_MULTI_INT_NAVI      0x127F9
#define TXT_SETTING_MULTI_INT_MEDIA     0x12895
#define TXT_SETTING_MULTI_INT_CALL      0x12906
#define TXT_SETTING_ACCLIGHT            0x1296E
#define TXT_SETTING_ETG                 0x12A6C
#define TXT_SETTING_REST                0x12B29
#define TXT_SETTING_TURN_SND            0x12C42
#define TXT_SETTING_TURN_SND_SND1       0x12D77
#define TXT_SETTING_TURN_SND_SND2       0x12DED
#define TXT_SETTING_OPE_SND             0x12E63
#define TXT_SETTING_LANG_COOP           0x12F4D
#define TXT_SETTING_LANG                0x13070
#define TXT_SETTING_UNIT                0x1316F
#define TXT_SETTING_UNIT_FUEL           0x131ED
#define TXT_SETTING_UNIT_TEMP           0x132DD
#define TXT_SETTING_SERVICEREMINDER     0x13366
#define TXT_SETTING_FACTORYRESET        0x13417
#define TXT_SETTING_BT_STAT             0x134F9
#define TXT_SETTING_BT_STAT_WAITING     0x13577
#define TXT_SETTING_BT_STAT_SUCCESS     0x13608
#define TXT_SETTING_BT_STAT_FAIL        0x13689
#define TXT_SETTING_BT_STAT_INITIALIZING                                        0x1370E
#define TXT_SETTING_BT_PASSKEY          0x137D1
#define TXT_SID_MAINTENANCE_DATEUNIT    0x13860
#define TXT_SID_AVG                     0x138B6
#define TXT_NO_WARNING                  0x138F2
#define TXT_MENUTITLE_ECO_AUTO          0x139D5
#define TXT_MENUTITLE_ECO_MANUAL        0x13B01
#define TXT_MENUTITLE_ECO_DRIVE_ASSIST  0x13C2E
#define TXT_MENUTITLE_ECO_DRIVE_RATIO   0x13D3D
#define TXT_MENUTITLE_ECO_SCORE         0x13E6E
#define TXT_MENUTITLE_DRIVE_INFO_RANGE  0x13F24
#define TXT_MENUTITLE_DRIVE_INFO_AYC    0x14019
#define TXT_MENUTITLE_DRIVE_INFO_TPMS   0x1415C
#define TXT_MENUTITLE_DRIVE_INFO_ENEFLOW                                        0x142B0
#define TXT_MENUTITLE_NAVIGATION        0x143A4
#define TXT_MENUTITLE_DIRECTION         0x143E4
#define TXT_MENUTITLE_WARNING           0x14465
#define TXT_MENUTITLE_SETTING           0x144E4
#define TXT_COMMON_SELECT               0x1457B
#define TXT_COMMON_BACK                 0x145FB
#define TXT_COMMON_AUTO                 0x14673
#define TXT_COMMON_MANUAL               0x14709
#define TXT_SETTING_BT_REGIST_ON        0x14791
#define TXT_SETTING_DEV_FORGET          0x148C3
#define TXT_SETTING_FORGET              0x14941
#define TXT_SETTING_IONGEN              0x14981
#define TXT_SETTING_FUEL                0x149C5
#define TXT_SETTING_TEMP                0x14B80
#define TXT_SETTING_DISPLAY_STANDARD    0x14CB0
#define TXT_SETTING_DISPLAY_SPORTS      0x14D15
#define TXT_SETTING_DISPLAY_ADVANCE     0x14D7A
#define TXT_SETTING_ADAS_PRK_SNR        0x14DDF
#define TXT_SETTING_IFE_DISP_SETTING    0x14E34
#define TXT_SETTING_DEV_REGIST          0x15001
#define TXT_SETTING_DEV_SELECT          0x1508E
#define TXT_SETTING_RST_MODE            0x15106
#define TXT_SETTING_FUEL_AUTO           0x151DD
#define TXT_SETTING_FUEL_MANUAL         0x15329
#define TXT_SETTING_DTE                 0x15475
#define TXT_SETTING_AVE_SPD_AUTO        0x154B5
#define TXT_SETTING_AVE_SPD_MANUAL      0x155D0
#define TXT_SETTING_038                 0x156EB
#define TXT_INSTRUCTION_PUSH_TO_SET     0x15727
#define TXT_SETTING_VEHICLE_INFO        0x1583C
#define TXT_SETTING_MEDIA               0x15948
#define TXT_MENUTITLE_OCS_REMAINNING_DIST_L1                                            0x15988
#define TXT_MENUTITLE_OCS_REMAINNING_DIST_L2                                            0x15A68
#define TXT_MENUTITLE_OCS               0x15B6A
/* Total Language Table Size = 87.08kBytes */
#define HM_LANG_MAX_PAGE                1
#define HM_LANG_MAX_SID                 0x15C4Eu
#define HM_LANG_COMMON_MAX_SID          0x0361u
#define HM_END_OF_SID                   (0xFFFFFFFFu)
#define HM_LANG_BUFFER_MAX_SIZE         (0x15C52u)        /* This is the language database size */
typedef UINT32 LANG_SID_T;

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        08/12/09     JKANOZA                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                               
/* end of file =============================================================*/ 
#endif /* HMI_LANGUAGE_IDENTIFIERS_H */
