/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2023. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 2/24/2023
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_SPEEDODIAL_TV2_BASEID              (0)
#define GFX_RSBR_1_TV2_BASEID                  (1)
#define GFX_RSBR_2_TV2_BASEID                  (2)
#define GFX_RSBR_3_TV2_BASEID                  (3)
#define GFX_TBT_1_TV2_BASEID                   (4)
#define GFX_TBT_2_TV2_BASEID                   (5)
#define GFX_TBT_4_TV2_BASEID                   (6)
#define GFX_TBT_5_TV2_BASEID                   (7)
#define GFX_TBT_1_0_TV2_BASEID                 (8)
#define GFX_TBT_2_0_TV2_BASEID                 (9)
#define GFX_TBT_4_0_TV2_BASEID                 (10)
#define GFX_TBT_5_0_TV2_BASEID                 (11)
#define GFX_CAR_TV2_BASEID                     (12)
#define GFX_RING_TV2_BASEID                    (13)
#define GFX_DOOR_FL_TV2_BASEID                 (14)
#define GFX_DOOR_FR_TV2_BASEID                 (15)
#define GFX_DOOR_RL_TV2_BASEID                 (16)
#define GFX_DOOR_RR_TV2_BASEID                 (17)
#define GFX_HOOD_TV2_BASEID                    (18)
#define GFX_TRUNK_TV2_BASEID                   (19)
#define GFX_SUNROOF_TV2_BASEID                 (20)
#define GFX_IMG_PRESSCLUTCH_0_TV2_BASEID       (21)
#define GFX_IMG_PRESSCLUTCH_1_TV2_BASEID       (22)
#define GFX_IMG_PRESSCLUTCH_2_TV2_BASEID       (23)
#define GFX_IMG_PRESSCLUTCH_3_TV2_BASEID       (24)
#define GFX_IMG_PRESSCLUTCH_4_TV2_BASEID       (25)
#define GFX_IMG_PRESSCLUTCH_5_TV2_BASEID       (26)
#define GFX_IMG_PRESSCLUTCH_6_TV2_BASEID       (27)
#define GFX_IMG_PRESSCLUTCH_7_TV2_BASEID       (28)
#define GFX_MINIBG_TV2_BASEID                  (29)
#define GFX_NOM_0_TV2_BASEID                   (30)
#define GFX_NOM_40_TV2_BASEID                  (31)
#define GFX_NOM_80_TV2_BASEID                  (32)
#define GFX_NOM_120_TV2_BASEID                 (33)
#define GFX_NOM_160_TV2_BASEID                 (34)
#define GFX_NOM_200_TV2_BASEID                 (35)
#define GFX_NOM_240_TV2_BASEID                 (36)
#define GFX_RGBTEST_TV2_BASEID                 (37)
#define GFX_RGBTEST_0_TV2_BASEID               (38)
#define GFX_RGBTEST_1_TV2_BASEID               (39)
#define GFX_RGBTEST_2_TV2_BASEID               (40)
#define GFX_RGBTEST_3_TV2_BASEID               (41)
#define GFX_RGBTEST_4_TV2_BASEID               (42)
#define GFX_TRIPMENU_TV2_BASEID                (43)
#define GFX_IMG_AH_TT_TV2_BASEID               (44)
#define GFX_IMG_BG_SPEEDO_TV2_BASEID           (45)
#define GFX_REGENGAUGE_TV2_BASEID              (46)
#define GFX_IMG_BG_REGEN_TV2_BASEID            (47)
#define GFX_IMG_COMPASS_TV2_BASEID             (48)
#define GFX_IMG_AH_TT_0_TV2_BASEID             (49)
#define GFX_IMG_AH_TT_0_0_TV2_BASEID           (50)
#define GFX_IMG_AH_TT_0_1_TV2_BASEID           (51)
#define GFX_IMG_AH_TT_0_2_TV2_BASEID           (52)
#define GFX_IMG_MERGEDBG_TV2_BASEID            (53)
#define GFX_IMG_BG_GUAGESALONE_TV2_BASEID      (54)
#define GFX_IMG_POWER_BASE_TV2_BASEID          (55)
#define GFX_IMG_TORQUE_BASE_TV2_BASEID         (56)
#define GFX_IMG_COMPRESSION_TEST_TV2_BASEID    (57)
#define GFX_NEW_IMAGES_1_TV2_BASEID            (58)
#define GFX_WDGT_PRERENDER_IMG_BASEID          (59)
#define GFX_WDG_ROOT_MAIN_IMG_BASEID           (60)
#define GFX_RSBR_IMG_BASEID                    (0)
#define GFX_TBT_IMG_BASEID                     (1)
#define GFX_TBT_0_IMG_BASEID                   (2)
#define GFX_WARNINGAREA_IMG_BASEID             (3)
#define GFX_DOORWARNING_IMG_BASEID             (4)
#define GFX_CENTERAREA_IMG_BASEID              (5)
#define GFX_PRESSCLUTCH_IMG_BASEID             (6)
#define GFX_MINIPOPUP_IMG_BASEID               (7)
#define GFX_SPEEDO_IMG_BASEID                  (8)
#define GFX_RGBTESTCONTAINER_IMG_BASEID        (9)
#define GFX_TBT_IMAGES_IMG_BASEID              (10)
#define GFX_MAINMENU_IMG_BASEID                (11)
#define GFX_REGEN_IMG_BASEID                   (12)
#define GFX_WDG_COMPASS_IMG_BASEID             (13)
#define GFX_WDG_IGN_ON_IMG_BASEID              (14)
#define GFX_WDG_MENUCONTENTS_IMG_BASEID        (15)
#define GFX_WDG_POW_TORQ_MENU_IMG_BASEID       (16)
#define GFX_WDGT_TXT_AUTOMATION_IMG_BASEID     (17)
#define GFX_SAMPLETEXT_0_BASEID                (0)
#define GFX_TXT_SID_NAME_BASEID                (1)
#define GFX_TXT_SID_TEST_BASEID                (2)
#define GFX_SAMPLETEXT_BASEID                  (3)
#define GFX_INVALID_BASEID                     (0)
#define GFX_FILL_BG_BASEID                     (0)
#define GFX_FILL_MAIN_SCR_BASEID               (1)
#define GFX_FS_BG_BASEID                       (2)
#define GFX_WDGT_PRERENDER_BASEID              (0)
#define GFX_RSBR_BASEID                        (1)
#define GFX_TBT_BASEID                         (2)
#define GFX_TBT_0_BASEID                       (3)
#define GFX_WARNINGAREA_BASEID                 (4)
#define GFX_DOORWARNING_BASEID                 (5)
#define GFX_CENTERAREA_BASEID                  (6)
#define GFX_PRESSCLUTCH_BASEID                 (7)
#define GFX_MINIPOPUP_BASEID                   (8)
#define GFX_SPEEDO_BASEID                      (9)
#define GFX_RGBTESTCONTAINER_BASEID            (10)
#define GFX_TBT_IMAGES_BASEID                  (11)
#define GFX_MAINMENU_BASEID                    (12)
#define GFX_REGEN_BASEID                       (13)
#define GFX_WDG_COMPASS_BASEID                 (14)
#define GFX_WDG_ROOT_MAIN_BASEID               (15)
#define GFX_WDG_IGN_ON_BASEID                  (16)
#define GFX_WDG_MENUCONTENTS_BASEID            (17)
#define GFX_WDG_POW_TORQ_MENU_BASEID           (18)
#define GFX_WDGT_TXT_AUTOMATION_BASEID         (19)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS          (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS          (3U)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS          (61)
#define GFX_MGR02_NUM_3D_MDL_LAYERS            (0)
#define GFX_MGR02_NUM_USER_LAYERS              (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS   (18)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS           (4)

#define GFX_MGR02_NUM_OF_SVGS                  (0)

#define GFX_MGR02_NUM_OF_SVG_CLIPS             (0)
#define GFX_MGR02_NUM_OF_FILLS                 (3)
#define GFX_MGR02_NUM_OF_TILES                 (0)
#define GFX_MGR02_NUM_VIDEO_LAYERS             (0)
#define GFX_MGR02_DYNAMIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS                 (20)

#define GFX_MGR02_NUM_VISIBLE_AREA      (12U)

/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (800)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (480)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_RING_ANIM                                  = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_0_ANIM                     = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_1_ANIM                     = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_2_ANIM                     = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_3_ANIM                     = GFX_MGR02_SET_OBJ(4,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_4_ANIM                     = GFX_MGR02_SET_OBJ(5,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_5_ANIM                     = GFX_MGR02_SET_OBJ(6,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_6_ANIM                     = GFX_MGR02_SET_OBJ(7,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_PRESSCLUTCH_7_ANIM                     = GFX_MGR02_SET_OBJ(8,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_MINIBG_ANIM                                = GFX_MGR02_SET_OBJ(9,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_COMPASS_ANIM                           = GFX_MGR02_SET_OBJ(10,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_AH_TT_0_2_ANIM                         = GFX_MGR02_SET_OBJ(11,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_MERGEDBG_ANIM                          = GFX_MGR02_SET_OBJ(12,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_POWER_BASE_ANIM                        = GFX_MGR02_SET_OBJ(13,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SAMPLETEXT_ANIM                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SAMPLETEXT_0_ANIM                          = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_SID_NAME_ANIM                          = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_SID_TEST_ANIM                          = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDGT_PRERENDER_ANIM                        = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_MINIPOPUP_ANIM                             = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_COMPASS_ANIM                           = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_ROOT_MAIN_ANIM                         = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDGT_TXT_AUTOMATION_ANIM                   = GFX_MGR02_SET_OBJ(4,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_DWDG_PRIMARY_AREA_ANIM                     = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_CLUTCH_ANIM                                = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS      (14)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS         (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS       (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS        (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS       (0)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS       (0)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS       (4)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS     (5)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS      (2)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS     (0)

#define GFX_MGR02_STEXTS_BUFFER_SIZE (14)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_SAMPLETEXT_0,
   GFX_TXT_SID_NAME,
   GFX_TXT_SID_TEST,
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (3)
#define GFX_MGR02_NUM_OF_STEXTS      (1)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (1)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (543)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (0)
#define GFX_MGR02_MAX_PATH_CMD_BUF_LENGTH   (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   GFX_DWDG_CENTERSCRN_SEL                        = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET)
  ,GFX_DWDGT_GAUGE                                = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DWIDGET)
  ,GFX_DWDG_MAIN                                  = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_DWIDGET)
  ,GFX_DWDG_PRIMARY_AREA                          = GFX_MGR02_SET_OBJ(3,GFX_MGR02_TYPE_DWIDGET)
  ,GFX_DWDG_CONTENTSELECTION                      = GFX_MGR02_SET_OBJ(4,GFX_MGR02_TYPE_DWIDGET)
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS          (5)

 /*  Dynamic widget indices */
 /*  GFX_DWDG_CENTERSCRN_SEL indices */
#define GFX_DWDG_CENTERSCRN_SEL_IDX_WARNINGAREA                        (0)
#define GFX_DWDG_CENTERSCRN_SEL_IDX_MAINMENU                        (1)
 /*  GFX_DWDGT_GAUGE indices */
#define GFX_DWDGT_GAUGE_IDX_SPEEDO                        (0)
#define GFX_DWDGT_GAUGE_IDX_REGEN                        (1)
 /*  GFX_DWDG_MAIN indices */
#define GFX_DWDG_MAIN_IDX_WDG_IGN_ON                        (0)
 /*  GFX_DWDG_PRIMARY_AREA indices */
#define GFX_DWDG_PRIMARY_AREA_IDX_WDG_MENUCONTENTS                        (0)
 /*  GFX_DWDG_CONTENTSELECTION indices */
#define GFX_DWDG_CONTENTSELECTION_IDX_WDG_POW_TORQ_MENU                        (0)

/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_CLUTCH                                     = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES           (1)

 /*  Dynamic Images indices */
 /*  GFX_CLUTCH indices */
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_0                        (0)
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_1                        (1)
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_2                        (2)
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_3                        (3)
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_4                        (4)
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_5                        (5)
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_6                        (6)
#define GFX_CLUTCH_IDX_IMG_PRESSCLUTCH_7                        (7)


#define GFX_FILL_BG_1                             GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_BG_SPEEDO_1                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_SPEEDO_1                              GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_BG_SPEEDO_2                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_SPEEDODIAL_1                          GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NOM_0_1                               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NOM_40_1                              GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NOM_80_1                              GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NOM_120_1                             GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NOM_160_1                             GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NOM_200_1                             GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NOM_240_1                             GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_REGEN_1                               GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_BG_REGEN_1                        GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_REGENGAUGE_1                          GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RSBR_4                                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RSBR_1_1                              GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RSBR_2_1                              GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RSBR_3_1                              GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_CENTERAREA_1                          GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_WARNINGAREA_1                         GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_DOORWARNING_1                         GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_CAR_1                                 GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_DOOR_FL_1                             GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_DOOR_FR_1                             GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_DOOR_RL_1                             GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_DOOR_RR_1                             GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_HOOD_1                                GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TRUNK_1                               GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_SUNROOF_1                             GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_MAINMENU_1                            GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TRIPMENU_1                            GFX_MGR02_SET_OBJ(20 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_PRESSCLUTCH_1                         GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RGBTESTCONTAINER_1                    GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RGBTEST_5                             GFX_MGR02_SET_OBJ(21 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RGBTEST_0_1                           GFX_MGR02_SET_OBJ(22 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RGBTEST_1_1                           GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RGBTEST_2_1                           GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RGBTEST_3_1                           GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_RGBTEST_4_1                           GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_IMAGES_1                          GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_3                                 GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_1_1                               GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_2_1                               GFX_MGR02_SET_OBJ(28 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_4_1                               GFX_MGR02_SET_OBJ(29 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_5_1                               GFX_MGR02_SET_OBJ(30 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_0_1                               GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_1_0_1                             GFX_MGR02_SET_OBJ(31 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_2_0_1                             GFX_MGR02_SET_OBJ(32 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_4_0_1                             GFX_MGR02_SET_OBJ(33 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_TBT_5_0_1                             GFX_MGR02_SET_OBJ(34 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_AH_TT_1                           GFX_MGR02_SET_OBJ(35 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_AH_TT_0_3                         GFX_MGR02_SET_OBJ(36 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_AH_TT_0_0_1                       GFX_MGR02_SET_OBJ(37 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_AH_TT_0_1_1                       GFX_MGR02_SET_OBJ(38 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_BG_GUAGESALONE_1                  GFX_MGR02_SET_OBJ(39 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_FILL_MAIN_SCR_2                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_WDG_IGN_ON_1                          GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_WDG_MENUCONTENTS_1                    GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_WDG_POW_TORQ_MENU_1                   GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_TORQUE_BASE_1                     GFX_MGR02_SET_OBJ(40 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_COMPRESSION_TEST_1                GFX_MGR02_SET_OBJ(41 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_FILL_MAIN_SCR_1                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_COMPRESSION_TEST_2                GFX_MGR02_SET_OBJ(42 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NEW_IMAGES_1_1                        GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_FS_BG_1                               GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES         (43)
#define GFX_MGR02_NUM_SVG_INSTANCES            (0)
#define GFX_MGR02_NUM_FILL_INSTANCES           (1)
#define GFX_MGR02_NUM_TILE_INSTANCES           (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES           (11)
#define GFX_MGR02_NUM_TEXT_INSTANCES           (0)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_MAIN                                   = (0)
  ,GFX_SCR_ROOT_MENU                              = (1)
  ,GFX_SCR_MAIN_MENU                              = (2)
  ,GFX_SCR_STD_TRIP                               = (3)
  ,GFX_SCR_SAMPLE                                 = (4)
  ,GFX_SCR_TEST                                   = (5)
  ,GFX_SCR_TXT_AUTOMATION                         = (6)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS                  (7)
#define GFX_MGR02_LAYER0_DAR_SIZE                 (1)
#define GFX_MGR02_WIDGET0_DAR_SIZE                (46)
#define GFX_MGR02_WIDGET1_DAR_SIZE                (3)
#define GFX_MGR02_WIDGET2_DAR_SIZE                (3)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (4)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX           (54)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_MAIN_BG_COLOR                               (0x000000FF)
#define GFX_SCR_ROOT_MENU_BG_COLOR                          (0x000000FF)
#define GFX_SCR_MAIN_MENU_BG_COLOR                          (0x000000FF)
#define GFX_SCR_STD_TRIP_BG_COLOR                           (0x000000FF)
#define GFX_SCR_SAMPLE_BG_COLOR                             (0x000000FF)
#define GFX_SCR_TEST_BG_COLOR                               (0x000000FF)
#define GFX_SCR_TXT_AUTOMATION_BG_COLOR                     (0x000000FF)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x000000FF)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (5)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1U)
#define GFX_MGR02_NUM_PRIORITY            (5)
#define GFX_MGR02_UNICODE              (1)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (254)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (0)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (0)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_ARGB4444)
#define GFX_MGR02_TV2_WINDOWS
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (1)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_TRAVEO2
#define GFX_MGR02_COMPRESSION_ENABLED
#define GFX_MGR02_OPTIMIZED_FONTROM
#define GFX_MGR02_RENDER_NONE
#define GFX_MGR02_FONT_GSUB_TABLE_ENABLED
#define GFX_MGR02_FONT_GPOS_TABLE_ENABLED
/*
** Traveo2 - Instructin buffer size in bytes
*/
#define GFX_MGR02_IRIS_MEMTASK0_IBUFF_SIZE             1024
#define GFX_MGR02_IRIS_MEMTASK1_IBUFF_SIZE             1024
#define GFX_MGR02_IRIS_MEMTASK2_IBUFF_SIZE             1024
#define GFX_MGR02_IRIS_WINTASK0_IBUFF_SIZE             1024
#define GFX_MGR02_IRIS_WINTASK1_IBUFF_SIZE             1024
#define GFX_MGR02_IRIS_WINTASK2_IBUFF_SIZE             1024
#define GFX_MGR02_IRIS_WINTASK3_IBUFF_SIZE             1024

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        2/24/2023     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
