/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  osStacks.h
Module Short Name:  osStacks.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OSSTACKS_H
#define OSSTACKS_H
/* file: C:\Users\EGANESAN\Documents\TI\AM62P\i2c\new_i2cisr_config\main_isr/osStacks.ld */
/* automatically generated by mOS Configurator xls v1.0 */
/* Generation time: 2/19/2024 9:51:31 AM */
/* vAutosar SIP Stack Generation */
/* Implementation: S6J3xx */


#include "Os.h"


#define osdInitTask_BOT osBottomOfStack(osTaskStackOsApplication0)
#define osdInitTask_TOP osAssignStack(osTaskStackOsApplication0)

#define osdOsTask_MemSer_BOT osBottomOfStack(osTaskStackOsApplication1)
#define osdOsTask_MemSer_TOP osAssignStack(osTaskStackOsApplication1)

#define osdTaskName_1_BOT osBottomOfStack(osTaskStackOsApplication2)
#define osdTaskName_1_TOP osAssignStack(osTaskStackOsApplication2)

#define osdTaskName_2_BOT osBottomOfStack(osTaskStackOsApplication3)
#define osdTaskName_2_TOP osAssignStack(osTaskStackOsApplication3)

#define osdIdleTask_BOT osBottomOfStack(osTaskStackOsApplication4)
#define osdIdleTask_TOP osAssignStack(osTaskStackOsApplication4)

#define osdFIQStack_BOT osBottomOfStack(osFIQStack)
#define osdFIQStack_TOP osAssignStack(osFIQStack)


#define osdIRQCat1Stack_BOT osBottomOfStack(osIRQCat1Stack)
#define osdIRQCat1Stack_TOP osAssignStack(osIRQCat1Stack)


#define osdSystemStack_BOT osBottomOfStack(osSystemStack)
#define osdSystemStack_TOP osAssignStack(osSystemStack)


#define osdOsIsr_SystemTimer_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdOsIsr_SystemTimer_TOP osAssignStack(osLevelStackCore0Level1)

#define osdCan_0_Int0ISR_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdCan_0_Int0ISR_TOP osAssignStack(osLevelStackCore0Level1)

#define osdCan_1_Int0ISR_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdCan_1_Int0ISR_TOP osAssignStack(osLevelStackCore0Level1)

#define osdCdd_IpcIrqMbxFromA53SS_0_0_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdCdd_IpcIrqMbxFromA53SS_0_0_TOP osAssignStack(osLevelStackCore0Level1)

#define osdSpi_IrqUnitMcuMcspi0TxRx_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdSpi_IrqUnitMcuMcspi0TxRx_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuI2c_InterruptHandler_BOT osBottomOfStack(osLevelStackCore0Level2)
#define osdMcuI2c_InterruptHandler_TOP osAssignStack(osLevelStackCore0Level2)



osqStack1 extern osqStack2 osStackDataType osqStack3 osFIQStack [64]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osIRQCat1Stack [128]; /* PRQA S 777 */ /* PRQA S 4152 */


osqStack1 extern osqStack2 osStackDataType osqStack3 osSystemStack [256]; /* PRQA S 777 */ /* PRQA S 4152 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level0 [128]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level1 [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level2 [512]; /* PRQA S 777 */ /* PRQA S 4152 */



osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication0 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication1 [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication2 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication3 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication4 [512]; /* PRQA S 777 */ /* PRQA S 4152 */




#endif    /* */
/* end of file */
/****************************************************************
Created Time: 2/19/2024 9:51:31 AM
****************************************************************/
