/*
 * uds_mgr_secuirty.c
 *
 *  Created on: May 15, 2020
 *      Author: MMK
 */

#include "uds_mgr_doip_security.h"
#include "uds_mgr_doip_error.h"
#include "system.h"


#define UDS_VIP_BOOTLOADER_MMK 1

UINT16 Fbl_Mad_Counter = 0u;
static UINT8 LockedStatus = 0u;
/**  Private Variables  **/
static UINT8   security_sts;
/*============================================================================
 ** Function Name:    FblSec_Init
 **
 ** Visibility:       Public
 **
 ** Description:      This function is used to initialize the security module.
 **
 ** Invocation:       Invoked by FBL
 **
 **
 ** Return:           UINT8
 **                   FBL_OK 	- Success
 **                   FBL_FAIL 	- Failed
 **
 ** Critical Section: None.
 **==========================================================================*/
UINT8 FblSec_Init(void)
{
	security_sts = FBL_SECURITY_NOT_DONE;
	return FBL_OK;

}

void FblSec_SetSeedValue(UINT16 value)
{
   Fbl_Mad_Counter = value;
}

UINT16 FblSec_GetSeedInitialValue(void)
{
	UINT32 Fbl_App_Random_Number;
    U16 u16CounterL;

	Fbl_App_Random_Number = random();//FblApp_GetBooApplicationRandomNumber();
	printf("***FblSec_GetSeedInitialValue [0x%lu] \n", Fbl_App_Random_Number);
    u16CounterL = random();//Rnd_GetCounterValue();
    printf("***FblSec_GetSeedInitialValue [0x%x] \n", u16CounterL);
    u16CounterL = (U16)((FBLSEC_CONSTA * u16CounterL) + (FBLSEC_CONSTB ^ u16CounterL) + FBLSEC_CONST1);

    return (U16)(((U16)Fbl_App_Random_Number) ^ u16CounterL);
}

/*static void FblSec_RefreshMadCounter(void)
{

	Fbl_Mad_Counter = random();
    Fbl_Mad_Counter = (U16)Rnd_CalculateRandomNb(Fbl_Mad_Counter); //TODO: ???

}*/

/*============================================================================
 ** Function Name:    DoIPSec_RequestSeed
 **
 ** Visibility:       Public
 **
 ** Description:      This function used to request seed for security access
 **
 ** Invocation:       Invoked by FBL
 **
 ** Inputs            UINT8 compId 	- Component ID
 **					  UINT8 *pSeedBuffer - Buffer to copy the seed
 **					  UINT32 len	- Length of the buffer
 **
 **
 ** Return:           UINT8
 **                   FBL_OK 				- Success
 **                   FBL_INVALID_PARAM 	- Invalid Parameter
 **
 ** Critical Section: None.
 **==========================================================================*/
UINT8 DoIPSec_RequestSeed(UINT8 *pSeedBuffer, UINT32 len)
{
	UINT8 status = FBL_INVALID_PARAM;

	if((NULL != pSeedBuffer) && (FBL_SEC_SEED_LEN == len))
	{

       /* Generate new Seed */
       /* (Seed "random" generation) */
      /* FblSec_RefreshMadCounter();*/
#ifdef UDS_VIP_BOOTLOADER_MMK
	   /* STD-SEC-TS.0201(1) */
       /* The SecretSeed is generated by concatenate PUN, SecLev, SessNum and SecuredSrvData. */

		LockedStatus = 0xFFu;
		memset(pSeedBuffer, LockedStatus, len);

	    /* STD-SEC-TS.0202(1) */
        /* The SecuritySeed is an encryption of SecretSeed. This encryption algorithm is */
        /* EncryptStaticKey. */
        /* If EncryptStaticKey is an asymmetrical encryption function, StaticKey is a public key */
	 /*	DwlRsaUds_EncryptSeed(pSeedBuffer, Fbl_Seed); */

		/* STD-SEC-TS.0203(2) */
        /* The UDS_Server compute the SessionKey as the first 16th bytes of the hash */
        /* for SecretSeed. Hash function shall be SHA-1 or MD5 */
        /* Rationale SessionKey is used as a key for an symmetrical encryption function. */
        /* The standard AES function can uses 16 bytes key. */
     /*   DwlRsaUds_ComputeSessionKey(Fbl_Seed); */
#endif
        status = FBL_OK;
	}

	/* Store the compId as pending, if successfull */
	if(FBL_OK == status)
	{
		security_sts  = FBL_SECURITY_PENDING;
	}
	else
	{
		security_sts = FBL_SECURITY_REQ_SEED_FAILED;
	}

	return status;
}


/*============================================================================
 ** Function Name:    DoIPSec_VerifyKey
 **
 ** Visibility:       Public
 **
 ** Description:      This function used to verify the security key sent by
 **					  the tester
 **
 ** Invocation:       Invoked by FBL
 **
 ** Inputs            UINT8 *pKeyBuffer - Buffer that contains the key
 **					  UINT32 len - Length of the buffer
 **
 **
 ** Return:           UINT8
 **                   FBL_OK 				- Success
 **                   FBL_FAIL 				- Failed
 **                   FBL_INVALID_PARAM 	- Invalid Parameter
 **
 ** Critical Section: None.
 **==========================================================================*/
UINT8 DoIPSec_VerifyKey(const UINT8 *pKeyBuffer, UINT32 len, UINT8 *pFingerPrint)
{
	UINT8 status = FBL_INVALID_PARAM;

	if((NULL != pKeyBuffer) && (FBL_SEC_KEY_LEN == len))
	{

        /*  Check Tool_Key validity (Security Algorithm  */
        /*  Or Appli_Key securities inhibitions */
        /* QACJ 0488: adimovvl: Pointer arithmetic is checked and it is correct */
        status = DwlRsaUds_VerifyToolKeyValidity((UINT8 *)pKeyBuffer, (UINT8 *)pFingerPrint);

	}

	if(FALSE != status)
	{
		/* Make the pending component to active component */
		security_sts = FBL_SECURITY_SUCCESS;
		status = FBL_OK;
	}
	else
	{
		security_sts = FBL_SECURITY_KEY_FAILED;
		status = FBL_FAIL;
	}

	return status;
}



/*============================================================================
 ** Function Name:    FblSec_VerifySecurityAccess
 **
 ** Visibility:       Public
 **
 ** Description:      This function used to verify the security access to
 **					  program the component ID
 **
 ** Invocation:       Invoked by FBL
 **
 ** Inputs            UINT8 compId 	- Component ID
 **
 **
 ** Return:           UINT8
 **                   FBL_OK 				- Success
 **                   FBL_FAIL 				- Failed
 **                   FBL_INVALID_PARAM 	- Invalid Parameter
 **
 ** Critical Section: None.
 **==========================================================================*/
UINT8 FblSec_VerifySecurityAccess(void)
{
	UINT8 status = FBL_INVALID_PARAM;

		if(security_sts == FBL_SECURITY_SUCCESS)
		{
			status = FBL_OK;
		}
		else
		{
			security_sts = FBL_SECURITY_NOT_DONE;
			status = FBL_FAIL;
		}

	return FBL_OK; ///< Modified temporarily
}


/*============================================================================
 ** Function Name:    FblSec_ClearSecurityAccess
 **
 ** Visibility:       Public
 **
 ** Description:      This function used to clear the security access
 **
 ** Invocation:       Invoked by FBL
 **
 **
 **
 ** Return:           UINT8
 **                   FBL_OK 				- Success
 **
 ** Critical Section: None.
 **==========================================================================*/
UINT8 FblSec_ClearSecurityAccess(void)
{
	security_sts = FBL_SECURITY_NOT_DONE;

	return FBL_OK;
}
