/** \brief Adc_Types.h
 **
 ** Interface Adc_Types. This interface declares all types of ADC.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

#ifndef ADC_TYPES_H_INCLUDED
#define ADC_TYPES_H_INCLUDED

/*==================[inclusions]============================================*/

#include <Std_Types.h>
#include <TSStd_Types.h>

/*==================[macros]================================================*/

/** \brief ADC_GROUP_ID_TO_GROUP_INDEX
 **
 ** The macro decodes a group id to the index of the group in the group config
 ** array (Adc_GroupConfigs).
 **
 ** \param [in] GroupId   The group id that shall be decoded.
 ** \return The group index that was decoded.
 **
 */
/* Deviation of MISRA-C:2004 Rule 19.7:
   A function could probably be used instead of this function-like macro.
   Justification: The macro can be used for error checks in scope of preprocessor directives. */
/* PRQA S 3453 1 */
#define ADC_GROUP_ID_TO_GROUP_INDEX(GroupId)      ((GroupId) & 0xFFuL)

/** \brief ADC_GROUP_ID_TO_NO_OF_CHANNELS
 **
 ** The macro decodes a group id to the number of channels in that group.
 **
 ** \param [in] GroupId   The group id that shall be decoded.
 ** \return The number of channels that was decoded.
 **
 */
/* Deviation of MISRA-C:2004 Rule 19.7:
   A function could probably be used instead of this function-like macro.
   Justification: The macro can be used for error checks in scope of preprocessor directives. */
/* PRQA S 3453 1 */
#define ADC_GROUP_ID_TO_NO_OF_CHANNELS(GroupId)   (((GroupId) >> 8u) & 0xFFuL)

/** \brief ADC_GROUP_ID_TO_NO_OF_SAMPLES
 **
 ** The macro decodes a group id to the number of samples for each channel in that
 ** group.
 **
 ** \param [in] GroupId   The group id that shall be decoded.
 ** \return The number of samples that was decoded.
 **
 */
/* Deviation of MISRA-C:2004 Rule 19.7:
   A function could probably be used instead of this function-like macro.
   Justification: The macro can be used for error checks in scope of preprocessor directives. */
/* PRQA S 3453 1 */
#define ADC_GROUP_ID_TO_NO_OF_SAMPLES(GroupId)    ((GroupId) >> 16u)

/*---------[AUTOSAR vendor identification]---------------------------------*/
#if (defined ADC_VENDOR_ID) /* to prevent double declaration */
#error ADC_VENDOR_ID is already defined
#endif /* if (defined ADC_VENDOR_ID) */

/** \brief AUTOSAR vendor identification */
#define ADC_VENDOR_ID TS_VENDOR_ID_CYPRESS

/*-------- [AUTOSAR module identification]----------------------------------*/
#if (defined ADC_MODULE_ID) /* to prevent double declaration */
#error ADC_MODULE_ID already defined
#endif /* if (defined ADC_MODULE_ID) */

/** \brief AUTOSAR module identification */
#define ADC_MODULE_ID 123U

/*==================[type definitions]======================================*/

/** \brief typedef Adc_VoidFctPtrType
 **
 ** Type definition of a void function pointer. 
 */
typedef P2FUNC(void, TYPEDEF, Adc_VoidFctPtrType)(void);

/** \brief typedef Adc_ChannelType
 **
 ** Numeric ID of a physical ADC channel.
 ** Range: 0..63 
 */
typedef uint8 Adc_ChannelType;

/** \brief typedef  Adc_GroupType
 **
 ** Numeric ID of an ADC channel group. It encodes
 ** - the index to the array of groups (Adc_GroupConfigs) in bits 0..7,
 ** - the number of channels in the group in bits 8..15 and
 ** - the number of samples per channel in bits 16..31.
 ** The individual items can be decoded by ADC_GROUP_ID_TO_GROUP_INDEX,
 ** ADC_GROUP_ID_TO_NO_OF_CHANNELS and ADC_GROUP_ID_TO_NO_OF_SAMPLES.
 */
typedef uint32 Adc_GroupType;

/** \brief typedef  Adc_GroupPriorityType
 **
 ** Priority level of a group (as to be configured in HW). Highest priority is 0.
 ** Range: 0..15 
 */
typedef uint8 Adc_GroupPriorityType;

/** \brief typedef  Adc_ValueGroupType
 **
 ** Type for reading the converted values of a channel group (raw, without further
 ** scaling, alignment according precompile switch ADC_RESULT_ALIGNMENT).
 */
typedef uint16 Adc_ValueGroupType;

/** \brief typedef  Adc_StreamNumSampleType
 **
 ** Type for configuring the number of group conversions in streaming access mode
 ** (in single access mode, parameter is 1). 
 */
typedef uint16 Adc_StreamNumSampleType;

/** \brief enum Adc_StatusType
 **
 ** Current status of the conversion of the requested ADC Channel group.
 */
typedef enum adc_statustype_enum
{
  ADC_IDLE,
  ADC_BUSY,
  ADC_COMPLETED,
  ADC_STREAM_COMPLETED
} Adc_StatusType;

/** \brief enum Adc_TriggerSourceType
 **
 ** Type for configuring the trigger source for an ADC Channel group.
 */
typedef enum adc_triggersourcetype_enum
{
  ADC_TRIGG_SRC_SW,
  ADC_TRIGG_SRC_HW
} Adc_TriggerSourceType;

/** \brief enum Adc_GroupConvModeType
 **
 ** Type for configuring the conversion mode of an ADC Channel group.
 */
typedef enum adc_groupconvmodetype_enum
{
  ADC_CONV_MODE_ONESHOT,
  ADC_CONV_MODE_CONTINUOUS
} Adc_GroupConvModeType;

/** \brief enum Adc_GroupAccessModeType
 **
 ** Type for configuring the access mode to group conversion results.
 */
typedef enum adc_groupaccessmodetype_enum
{
  ADC_ACCESS_MODE_SINGLE,
  ADC_ACCESS_MODE_STREAMING
} Adc_GroupAccessModeType;

/** \brief enum Adc_StreamBufferModeType
 **
 ** Type for configuring the streaming access mode buffer type.
 */
typedef enum adc_streambuffermodetype_enum
{
  ADC_STREAM_BUFFER_LINEAR,
  ADC_STREAM_BUFFER_CIRCULAR
} Adc_StreamBufferModeType;

/** \brief enum Adc_ResultAlignmentType
 **
 ** Type for alignment (left/right alignment) of ADC raw results. Adc_ReadGroup and
 ** the stream handling will obey this setting.
 */
typedef enum adc_resultalignmenttype_enum
{
  ADC_ALIGN_LEFT,
  ADC_ALIGN_RIGHT
} Adc_ResultAlignmentType;

/** \brief enum Adc_GroupReplacementType
 **
 ** Replacement mechanism, which is used on ADC group level, if a group conversion
 ** is interrupted by a group which has a higher priority.
 */
typedef enum adc_groupreplacementtype_enum
{
  ADC_GROUP_REPL_ABORT_RESTART,
  ADC_GROUP_REPL_SUSPEND_RESUME
} Adc_GroupReplacementType;

/** \brief struct Adc_HwUnitConfigType
 **
 ** Configuration structure containing configuration items that apply to the whole
 ** HW unit.
 */
typedef struct adc_hwunitconfigtype_struct
{
  /** Base address of the register set associated to the HW unit. */
  CONST(uint32, TYPEDEF) RegisterBase;
  /** Number of logical channels in a HW unit. */
  CONST(uint8, TYPEDEF)  LogicalChannelNumber;
  /** Value for register ADC12Bn_CT. */
  CONST(uint16, TYPEDEF) ComparisonTime;
  /** Default comparison time to be set on Adc_DeInit(). */
  CONST(uint16, TYPEDEF) DefaultComparisonTime;
  /** Values for the four sampling time registers (ADC12Bn_STi). */
  CONST(uint16, TYPEDEF) SampTimes[4];
  /** Default sampling time to be set for each sampling time register on Adc_DeInit(). */
  CONST(uint16, TYPEDEF) DefaultSampTime;
  /** Values for the eight range comparator upper threshold registers (ADC12Bn_RCOH0~7). */
  CONST(uint16, TYPEDEF) RangeComparatorUpperThresholds[8];
  /** Values for the eight range comparator lower threshold registers (ADC12Bn_RCOL0~7). */
  CONST(uint16, TYPEDEF) RangeComparatorLowerThresholds[8];
} Adc_HwUnitConfigType;

/** \brief struct Adc_ChannelConfigType
 **
 ** This type contains the configuration parameters for a physical channel.
 */
typedef struct adc_channelconfigtype_struct
{
  /** Index of the logical channel, i.e. one of 64 possible channels per HW unit
      (value 'i' of register name ADC12Bn_CHCTRLi and others). */
  CONST(Adc_ChannelType, TYPEDEF) LogicalChannelId;
  /** Index of the physical channel, i.e. which input signal should be converted
      (value to be written into ADC12Bn_CHCTRLi:ANIN). */
  CONST(Adc_ChannelType, TYPEDEF) PhysicalChannelId;
  /** Index of the sampling time setting (as configured for the HW unit) for 
      this channel. */
  CONST(uint8, TYPEDEF) SampTimeId;
  /** Limit checking enabled (value to be written into ADC12Bn_CHCTRLi:RCEN). */
  CONST(boolean, TYPEDEF) RangeComparatorEnable;
  /** Range comparator selection (value to be written into 
      ADC12Bn_CHCTRLi:RCSEL). */
  CONST(uint8, TYPEDEF) RangeComparatorSelection;
  /** Range comparator inverted range selection (value to be written into
      ADC12Bn_CHCTRLi:RCINVSEL). */
  CONST(uint8, TYPEDEF) RangeComparatorInvertedRangeSelection;
} Adc_ChannelConfigType;

/** \brief struct Adc_StreamInfoType
 **
 ** This type is used to store management information on one stream.
 */
typedef struct adc_streaminfotype_struct
{
  /** Pointer to the beginning of the buffer. The pointer will not be updated when
   the stream is filled. */
  P2VAR(Adc_ValueGroupType, TYPEDEF, AUTOMATIC) BufferBasePtr;
  /** Index of the element that was added last time.
   <0 When no element was added. */
  VAR(sint32, TYPEDEF) LastPushedIndex;
  /** Number of valid elements in the stream. */
  VAR(uint8, TYPEDEF) ValidElementCount;
} Adc_StreamInfoType;

/** \brief struct Adc_GroupConfigType
 **
 ** Structure that contains the configuration for a single group.
 */
typedef struct adc_groupconfigtype_struct
{
  /** ID of the first logical channel (in the HW) - the one
   that is triggered - on the HW unit that belongs to this group. */
  CONST(Adc_ChannelType, TYPEDEF) FirstLogicalChannelId;
  /** ID of the last logical channel (in the HW) - the one
   that is triggered - on the HW unit that belongs to this group. */
  CONST(Adc_ChannelType, TYPEDEF) LastLogicalChannelId;
  /** Index of the config (in Adc_ChannelConfig) of the first logical channel 
   of this group. This channel will actually be triggered. */
  CONST(uint16, TYPEDEF) FirstLogicalChannelConfigIndex;
  /** Index of the config (in Adc_ChannelConfig) of the last logical channel 
   of this group. This channel will actually be triggered. */
  CONST(uint16, TYPEDEF) LastLogicalChannelConfigIndex;
  /** Number of channels of the group. */
  CONST(uint8, TYPEDEF) NumberOfChannels;
  /** Priority to set in HW register (0 is highest). */
  CONST(Adc_GroupPriorityType, TYPEDEF) GroupHwPriority;
  /** Access mode to group conversion results. */
  CONST(Adc_GroupAccessModeType, TYPEDEF) GroupAccessMode;
  /** Group conversion done interrupt. */
  CONST(boolean, TYPEDEF) GroupIntDoneEnable;
  /** Group range comparator interrupt. */
  CONST(boolean, TYPEDEF) GroupIntRangeEnable;
  /** Data protection of the channels in the group. */
  CONST(uint8, TYPEDEF) DataProtection;
  /** Conversion mode of the group. */
  CONST(Adc_GroupConvModeType, TYPEDEF) GroupConvMode;
  /** Replacement mechanism, which is used on ADC group level, if a group
      conversion is interrupted by a group which has a higher priority. */
  CONST(Adc_GroupReplacementType, TYPEDEF) GroupReplacement;
  /** Pointer to the configuration of the used HW unit (defined in the array
   Adc_HwUnitConfigs). The referenced HW unit contains the group. */
  CONSTP2CONST(Adc_HwUnitConfigType, TYPEDEF, AUTOMATIC) HwUnitConfigPtr;
  /** Group notification pointer. */
  CONST(Adc_VoidFctPtrType, TYPEDEF) NotificationPtr;
  /** Pointer to an object of the array of group notification enable settings.
      The referred element contains the setting whether a notification should
      be called on group conversion completion. */
  CONSTP2VAR(boolean, TYPEDEF, AUTOMATIC) NotificationEnableSettingPtr;
  /** Streaming access mode to buffer. */
  CONST(Adc_StreamBufferModeType, TYPEDEF) StreamBufferMode;
  /** Pointer to an object of the array of stream infos (Adc_StreamInfos).
      The referred element contains the stream info for this group. */
  CONSTP2VAR(Adc_StreamInfoType, TYPEDEF, AUTOMATIC) StreamInfoPtr;
  /** Number of samples that can be stored for each channel within the stream.
      (I.e. length of the stream in conversion rounds.) */
  CONST(Adc_StreamNumSampleType, TYPEDEF) StreamNumSamples;
  /** Trigger source for the group. */
  CONST(Adc_TriggerSourceType, TYPEDEF) TriggerSource;
} Adc_GroupConfigType;

/** \brief struct Adc_ConfigType
 **
 ** Data structure containing the set of configuration parameters required for
 ** initializing the ADC Driver and ADC HW Unit(s).
 */
typedef struct adc_configtype_struct
{
  /** Number of elements in the array Adc_GroupConfigs. */
  CONST(uint8, TYPEDEF) GroupConfigsNumber;
  /** Length (in elements) of the array of HW units (Adc_HwUnitConfigs). */
  CONST(uint8, TYPEDEF) HwUnitConfigsNumber;
  /** Alignment of Adc_ValueGroupType as configured. */
  CONST(Adc_ResultAlignmentType, TYPEDEF) ResultAlignment;
} Adc_ConfigType;

/*==================[external function declarations]========================*/

/*==================[end of file]===========================================*/

#endif /*!defined(ADC_TYPES_H_INCLUDED)*/

