#ifndef GPT_PUBLIC_H
#define GPT_PUBLIC_H

/** \brief AUTOSAR Gpt GPT Driver
 **
 ** This file contains the implementation of the AUTOSAR module Gpt type
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]============================================*/
#include <Std_Types.h>           /* AUTOSAR standard types */
#include <TSAutosar.h>           /* Cypress specific standard types */
#include <Gpt_Version.h>         /* GPT driver Version check type defines */

/*==================[macros]================================================*/
/* AUTOSAR version number check */
#if (GPT_AR_RELEASE_MAJOR_VERSION != 4U)               /* Autosar release major version check */
#error "AUTOSAR AR release major number mismatch"
#endif

#if (GPT_AR_RELEASE_MINOR_VERSION != 0U)              /* Autosar release minor version check */
#error "AUTOSAR AR release minor number mismatch"
#endif

#if (GPT_AR_RELEASE_REVISION_VERSION != 3U)           /* Autosar release revision version check */
#error "AUTOSAR AR release revision number mismatch"
#endif

#if (GPT_SW_MAJOR_VERSION != 1U)                      /* Software major version check */
#error "AUTOSAR SW major number mismatch"
#endif

#if (GPT_SW_MINOR_VERSION != 0U)                      /* Software minor version check */
#error "AUTOSAR SW minor number mismatch"
#endif

#if !(GPT_SW_PATCH_VERSION >= 0U)                      /* Software patch version check */
#error "AUTOSAR SW patch version number mismatch"
#endif


/** \brief size optimized boolean
 **
 ** Gpt use uint8 for boolean represantation
*/
#define GPT_FALSE                0U
#define GPT_TRUE                 1U

/** \brief defines for working with channelConfigFlags
**
** (new) defines, defining masks and symbolic names for the values of the bits in the flag field
** can be used instead
*/
/* configuration flag */
/* bit 0 = channel mode */
#define GPT_MODE_ONESHOT         0x00U    /* operates one time only */
#define GPT_MODE_CONTINUOUS      0x01U    /* operates continuously */
/* bit 1 = wakeup source enabled */
#define GPT_WAKEUPSOURCE_FALSE   0x00U    /* channel is not a wakeup source */
#define GPT_WAKEUPSOURCE_TRUE    0x02U    /* channel is a wakeup source */
/* bit 2 = debug enabled */
#define GPT_DEBUG_FALSE          0x00U    /* channel debug is disabled */
#define GPT_DEBUG_TRUE           0x04U    /* channel debug is enabled */
/* bit 3 = debug register implemented */
#define GPT_DBGR_FALSE           0x00U    /* DBGR is unimplemented */
#define GPT_DBGR_TRUE            0x08U    /* DBGR is implemented */

/* Status flag */
#define GPT_NOTIFY_EN            0x02U    /* Notification is enabled */
#define GPT_WAKEUP_EN            0x04U    /* Wakeup is enabled */

/* Apb I/F flag */
#define GPT_FRT_BIT              0x01U    /* bit position of Free-RunTimer */
#define GPT_BTM_BIT              0x02U    /* bit position of BaseTimer     */
#define GPT_RLT_BIT              0x04U    /* bit position of ReloadTimer   */

/* Defines interrupt occurred flag for Gpt_ChannelInterruptOccurredType */
#define GPT_NO_INTERRUPT_DETECT  0x00U    /* no interrupt detect */
#define GPT_INTERRUPT_DETECT     0x01U    /* interrupt detect    */

/* Defines hardware peripheral for Gpt_TimerType */
#define GPT_FRT                  0x00U    /* Free-Run Timer       */
#define GPT_BTIMER               0x01U    /* Base Timer           */
#define GPT_RLT                  0x02U    /* Reload Timer         */
#define GPT_TIMERMAX             0x03U    /* number of peripheral */

/* Defines bit width of each hardware peripheral for Gpt_HwTimerType */
#define GPT_FRT32                0x00U    /* 32bit Free-Run Timer */
#define GPT_BTIMER16             0x01U    /* 16bit Base Timer     */
#define GPT_BTIMER32             0x02U    /* 32bit Base Timer     */
#define GPT_RLT32                0x03U    /* 32bit Reload Timer   */

/* Defines source clock for Gpt_ClockType */
#define GPT_CLK_EXT              0x00U    /* external clock */
#define GPT_CLK_INT              0x01U    /* internal clock */

/* Defines return value for Gpt_ReturnType */
#define GPT_NOT_OK               0x00U    /* not OK */
#define GPT_OK                   0x01U    /* OK     */

/* Defines state of driver for Gpt_DriverStateValueType */
#define GPT_DRIVER_UNINITIALIZE  0x00U    /* uninitialization */
#define GPT_DRIVER_INITIALIZE    0x01U    /* initialization   */

/* Defines state values for Gpt_ChannelStateValueType */
#define GPT_STATE_INITIALIZED    0x01U    /* state of initialization */
#define GPT_STATE_RUNNING        0x02U    /* state of running        */
#define GPT_STATE_STOPPED        0x03U    /* state of stopped        */
#define GPT_STATE_EXPIRED        0x04U    /* state of expired        */

/*==================[type definitions]======================================*/
/** \brief Gpt_ChannelType is the public type for the channel ID
 **
 ** Gpt_ChannelType is defined in terms of the internal Gpt_ChannelIdType.
*/
typedef uint8 Gpt_ChannelType;

/* Gpt_ChannelStateFlagType defines notification/wakeup flag of each channel*/
typedef uint8 Gpt_ChannelStateFlagType;

/** \brief Gpt_ValueType is the type that holds a channel time value
 **
 ** Gpt_ValueType is must be at least as big as the largest counter or compare
 ** register. It is therefore architecture- and possibly derivative-specific.
*/
typedef uint32 Gpt_ValueType;

/** \brief Gpt_ModeType holds one of the two values GPT_MODE_SLEEP and GPT_MODE_NORMAL.
 **
 ** Gpt_ModeType is defined as an enum type so that the symbols are available in the
 ** debugger. It is only ever used as a parameter, so the size of the variable is
 ** unimportant. The two values are deliberately set apart and non-zero so that
 ** the most common errors in API calls can be detected.
*/
typedef enum
{
  GPT_MODE_NORMAL = 3U,    /* normal mode */
  GPT_MODE_SLEEP  = 5U     /* sleep mode  */
} Gpt_ModeType;

/* Gpt_ChannelInterruptOccurredType defines interrupt occurred flag */
typedef uint8 Gpt_ChannelInterruptOccurredType;

/* Gpt_ChannelStateValueType defines state values of each channel */
typedef uint8 Gpt_ChannelStateValueType;

/* Gpt_TimerType defines hardware peripheral */
typedef uint8 Gpt_TimerType;

/* Gpt_HwTimerType defines bit width of each hardware peripheral */
typedef uint8 Gpt_HwTimerType;

/* Gpt_ClockType defines source clock */
typedef uint8 Gpt_ClockType;

/* Gpt_ReturnType defines return value */
typedef uint8 Gpt_ReturnType;

/* Gpt_NotificationFunctionType defines function defination of notification */
typedef P2FUNC(void, GPT_APPL_CODE, Gpt_NotificationFunctionType)(void);

/* Gpt_DriverStateValueType defines state of driver */
typedef uint8 Gpt_DriverStateValueType;

/* Gpt_DriverStateType is structure of driver state and mode */
typedef struct
{
  Gpt_DriverStateValueType   driverInitialised;   /* status of initialization */
  Gpt_ModeType               driverStateFlags;    /* status of sleep */
} Gpt_DriverStateType;

/* Gpt_ChannelStateType is structure of channel's state */
typedef struct
{
  Gpt_ChannelInterruptOccurredType   channelInterruptOccurred;  /* status of interrupt */
  Gpt_ChannelStateFlagType           channelStateFlags;         /* status of notification/wakeup */
  Gpt_ChannelStateValueType          state;                     /* status of channel   */
  Gpt_ValueType                      interval;                  /* interval time       */
} Gpt_ChannelStateType;

typedef struct Gpt_ChannelConfigStruct Gpt_ChannelConfigType;

typedef P2FUNC(void,           GPT_CODE, Gpt_drvVoidFct_t             )(P2CONST(Gpt_ChannelConfigType, AUTOMATIC, GPT_CONST) Channel, uint8 apbflag);
typedef P2FUNC(void,           GPT_CODE, Gpt_drvVoidAndPassValueFct_t )(P2CONST(Gpt_ChannelConfigType, AUTOMATIC, GPT_CONST) Channel, Gpt_ValueType Interval, uint8 apbflag);
typedef P2FUNC(Gpt_ValueType,  GPT_CODE, Gpt_drvValueFctAndPassValue_t)(P2CONST(Gpt_ChannelConfigType, AUTOMATIC, GPT_CONST) Channel, Gpt_ValueType Interval);
typedef P2FUNC(Gpt_ReturnType, GPT_CODE, Gpt_drvResultFct_t           )(P2CONST(Gpt_ChannelConfigType, AUTOMATIC, GPT_CONST) Channel);
typedef P2FUNC(Gpt_ReturnType, GPT_CODE, Gpt_drvResultFctAndPassInfo_t)(P2CONST(Gpt_ChannelConfigType, AUTOMATIC, GPT_CONST) Channel, P2CONST(Gpt_DriverStateType, AUTOMATIC, GPT_APPL_DATA)  DriverStatusPtr, P2CONST(Gpt_ChannelStateType, AUTOMATIC, GPT_APPL_DATA) ChannelStatusPtr);

/* Gpt_drvFctTable_t defins function table structure. */
typedef struct Gpt_drvFctTable_s
{
  Gpt_drvVoidFct_t                 drvInitFct;                       /* initialize channel function    */
  Gpt_drvVoidAndPassValueFct_t     drvStartFct;                      /* start timer function           */
  Gpt_drvVoidFct_t                 drvCancelFct;                     /* cancel timer function          */
  Gpt_drvVoidFct_t                 drvReloadFct;                     /* reload timer function          */
  Gpt_drvValueFctAndPassValue_t    drvGetTimeElapsedContinuousFct;   /* get elapsed timer function     */
  Gpt_drvValueFctAndPassValue_t    drvGetTimeElapsedOneShotFct;      /* get elapsed timer function     */
  Gpt_drvValueFctAndPassValue_t    drvGetTimeRemainContinuousFct;    /* get remaining timer function   */
  Gpt_drvValueFctAndPassValue_t    drvGetTimeRemainOneShotFct;       /* get remaining timer function   */
  Gpt_drvVoidFct_t                 drvDeInitFct;                     /* de-initialize channel function */
  Gpt_drvResultFct_t               drvCheckInterruptFlagFct;         /* check interrupt flag function  */
  Gpt_drvResultFctAndPassInfo_t    drvCheckRegisterFct;              /* check register function        */
} Gpt_drvFctTable_t;

/* Gpt_GetTblType defines function defination of get table pointer. */
typedef P2FUNC(P2CONST(Gpt_drvFctTable_t, AUTOMATIC, GPT_CONST), GPT_CODE, Gpt_GetTblType)(void);

/** \brief Gpt_ChannelConfigType holds the configuration for a single channel
 ** This structure holds a channel's configuration:
 ** in order to reinforce the connection between the macros and the structure.
*/
struct Gpt_ChannelConfigStruct
{
  volatile CONSTP2VAR(uint32, GPT_CONST, REGSPACE)  BaseAddr;           /* base address */
  CONST( uint8, GPT_CONST )                         Prescaler;          /* prescaler */
  CONST( Gpt_ClockType, GPT_CONST )                 SourceClock;        /* source clock */
  CONST( Gpt_HwTimerType, GPT_CONST )               TimerWide;          /* width of timer counter */
  CONST( Gpt_TimerType, GPT_CONST )                 timerfct;           /* periheral of timer */
  CONST( Gpt_NotificationFunctionType, GPT_CONST )  notifyFunction;     /* pointer of notification function */
  volatile CONSTP2VAR(uint32, GPT_CONST, REGSPACE)  SubBaseAddr;        /* base address (Btimer32bit add channel, RLT SSSR) */
  CONST( Gpt_ValueType, GPT_CONST )                 timerMax;           /* max timer value */
  CONST( uint8, GPT_CONST )                         ChannelConfigFlags; /* mode flag */
  CONST( uint8, GPT_CONST )                         ChannelNumber;      /* channel number */
  Gpt_GetTblType                                    getFuncTable;       /* peripheral function table pointer */
};

/** \brief Gpt_ConfigType is the type associated with the config data structure.
 **
 ** This data type is public, but the underlying structure is private.
*/
typedef struct
{
  P2CONST(Gpt_ChannelConfigType, AUTOMATIC, GPT_CONST)     channels;    /* channel's configuration information */
  uint8                                                    nChannels;   /* number of channel */
  uint8                                                    ApbIfFlag;   /* APB interface flag */
} Gpt_ConfigType;


/* Type of Base Timer Register Map */
typedef struct
{
  uint16 Pcsr;          /* PCSR register   */
  uint16 Dummy1;        /* reserved        */
  uint16 Pdut;          /* PDUT register   */
  uint16 Dummy2;        /* reserved        */
  uint16 Tmr;           /* TMR register    */
  uint16 Dummy3;        /* reserved        */
  uint16 Tmcr;          /* TMCR register   */
  uint16 Dummy4;        /* reserved        */
  uint8  Stc;           /* STC register    */
  uint8  Tmcr2;         /* TMCR2 register  */
  uint16 Dummy5;        /* reserved        */
  uint8  Stcc;          /* STCC register   */
  uint8  Dummy6;        /* reserved        */
  uint16 Dummy7;        /* reserved        */
  uint8  Stcs;          /* STCS register   */
  uint8  Dummy8;        /* reserved        */
  uint16 Dummy9;        /* reserved        */
  uint16 Psdr;          /* PSDR register   */
  uint16 Dummy10;       /* reserved        */
  uint16 Adtr;          /* ADTR register   */
  uint16 Dummy11;       /* reserved        */
  uint16 Debug;         /* DEBUG register  */
  uint16 Dummy12;       /* reserved        */
  uint32 Dummy13;       /* reserved        */
  uint16 Etcdr;         /* ETCDR register  */
  uint16 Dummy14;       /* reserved        */
  uint8  Bt_Btsel;      /* BTSEL register  */
  uint8  Dummy15;       /* reserved        */
  uint16 Dummy16;       /* reserved        */
  uint16 Bt_Btsssr;     /* BTSSSR register */
  uint16 Dummy17;       /* reserved        */
} Gpt_BtType;

/* Type of Free-Run Timer Register Map */
typedef struct
{
  uint32 Cpclrb_Cpclr;  /* CPCLRB/CPCLR register */
  uint32 Tcdt;          /* TCDT register         */
  uint32 Tccs;          /* TCCS register         */
  uint32 Teccs;         /* TECCS register        */
  uint32 Tccsc;         /* TCCSC register        */
  uint32 Tccss;         /* TCCSS register        */
  uint16 Debug;         /* DEBUG register        */
  uint16 Dummy;         /* reserved              */
} Gpt_FrtType;


/* Type of Reload Timer Register Map */
typedef struct
{
  uint32 Dmacfg;        /* RLTn_DMACFG register */
  uint32 Dummy8;        /* reserved             */
  uint32 Tmcsr;         /* RLTn_TMCSR register  */
  uint32 Dummy9;        /* reserved             */
  uint32 Tmrlr;         /* RLTn_TMRLR register  */
  uint32 Tmr;           /* RLTn_TMR register    */
} Gpt_RltType;

/* Type of TSEL and SSSR Register Map */
typedef struct
{
  uint32 Tsel;          /* RLT_TSEL register */
  uint32 SSSR;          /* RLT_SSSR register */
} Gpt_RltSssrType;


/*==================[external function declarations]========================*/
/*==================[internal function declarations]========================*/
/*==================[external constants]====================================*/
/*==================[internal constants]====================================*/
/*==================[external data]=========================================*/
/*==================[internal data]=========================================*/
/*==================[external function definitions]=========================*/
/*==================[internal function definitions]=========================*/

#endif
/*==================[end of file]===========================================*/
