/** \brief Pwm_Init.h
 **
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

#ifndef PWM_INIT_H_INCLUDED
#define PWM_INIT_H_INCLUDED

/*==================[inclusions]============================================*/

#include <Pwm_Types.h>
#include "pwm.h"
/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#define PWM_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>

/** \brief Pwm_Init
 **
 ** Service for PWM driver initialization.
 **
 ** \param [in] ConfigPtr   Pointer to configuration set
 **
 */
extern FUNC(void, AUTOMATIC) Pwm_Init
(
  P2CONST(Pwm_ConfigType, AUTOMATIC, AUTOMATIC) ConfigPtr
);

#define PWM_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>

/*==================[internal constants]====================================*/

/*==================[internal data]=========================================*/

/*==================[end of file]===========================================*/

#endif /*!defined(PWM_INIT_H_INCLUDED)*/

