
#ifndef WDG_66_IA_H
#define WDG_66_IA_H 1

/** \brief AUTOSAR Wdg Driver
 **
 ** This file contains or includes all external identifiers of
 ** the AUTOSAR module Wdg.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]=============================================*/

#include <Wdg_66_IA_Version.h>
#include <Wdg_66_IA_Cfg.h>
#include <Wdg_66_IA_Cfg_Arch.h>
#include <Wdg_66_IA_Api.h>

/*==================[version check]==========================================*/

/*------------------[AUTOSAR configuration AR version number check]----------*/

#if !WDG_66_IA_AR_VERSION_CHECK( WDG_66_IA_GEN_AR_RELEASE_MAJOR_VERSION, WDG_66_IA_GEN_AR_RELEASE_MINOR_VERSION,    \
                                WDG_66_IA_GEN_AR_RELEASE_REVISION_VERSION)
#  error AUTOSAR WDG configuration AR version number mismatch
#endif

/*------------------[AUTOSAR configuration SW version number check]----------*/

#if !defined( WDG_66_IA_GEN_SW_MAJOR_VERSION)
#  error WDG_66_IA_GEN_SW_MAJOR_VERSION not defined
#elif !defined( WDG_66_IA_GEN_SW_MINOR_VERSION)
#  error WDG_66_IA_GEN_SW_MINOR_VERSION not defined
#elif !defined( WDG_66_IA_GEN_SW_PATCH_VERSION)
#  error WDG_66_IA_GEN_SW_PATCH_VERSION not defined
#elif !WDG_66_IA_SW_VERSION_CHECK( WDG_66_IA_GEN_SW_MAJOR_VERSION, WDG_66_IA_GEN_SW_MINOR_VERSION,    \
                                  WDG_66_IA_GEN_SW_PATCH_VERSION)
#  error AUTOSAR WDG configuration SW version number mismatch
#endif

/*------------------[AUTOSAR configuration additional check]-----------------*/

#if !defined(WDG_66_IA_GEN_MODULE_ID)
#  error WDG_66_IA_GEN_MODULE_ID not defined
#elif !defined(WDG_66_IA_GEN_VENDOR_ID)
#  error WDG_66_IA_GEN_VENDOR_ID not defined
#elif !defined(WDG_66_IA_GEN_VENDOR_API_INFIX)
#  error WDG_66_IA_GEN_VENDOR_API_INFIX not defined
#elif !WDG_66_IA_EXTRA_CHECK( WDG_66_IA_GEN_MODULE_ID, WDG_66_IA_GEN_VENDOR_ID,   \
                           WDG_66_IA_GEN_VENDOR_API_INFIX)
#  error AUTOSAR WDG configuation additional checks failed
#endif

/*==================[macros]=================================================*/
/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* if !defined( WDG_66_IA_H ) */
/*==================[end of file]============================================*/
