/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2013. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**============================================================================
**
** Name:           ux_shmi_uimain.h
**
** Description:    
**
** Organization:   UI Frameworks & Tools, Visteon
**
**============================================================================
**
**==========================================================================*/
#ifndef ux_shmi_uimain_h
#define ux_shmi_uimain_h

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "ux_safehmi_item.h"
#include "ux_safehmi_image.h"
#include "ux_safehmi_canvas.h"
#include "ux_safehmi_rectangle.h"


/*============================================================================
** I N T E R N A L   M A C R O   A N D   T Y P E   D E F I N I T I O N S
**==========================================================================*/

#define ui_main (UX_SHMI_PLAYER::root)
#define UX_SHMI_MAX_DESIGN_DEPTH (3)


namespace UX_SHMI_PLAYER
{
/*============================================================================
** I N T E R N A L   F U N C T I O N   P R O T O T Y P E S
**==========================================================================*/

enum class SHMI_ELEMENTS
{
	SHMI_RIDE_MODES,
	SHMI_ROAD_ACTIVE,
	SHMI_ROAD_INACTIVE,
	SHMI_ROAD_REQ,
	SHMI_SPORT_REQ,
	SHMI_SPORT_INACTIVE,
	SHMI_SPORT_ACTIVE,
	SHMI_OFFROAD_REQ,
	SHMI_OFFROAD_OVERRIDE_REQ,
	SHMI_OFFROAD_OVERRIDE_ACTIVE,
	SHMI_OFFROAD_INACTIVE,
	SHMI_OFFROAD_ACTIVE,
	SHMI_CUSTOM_OFFROAD_REQ,
	SHMI_CUSTOM_OFFROAD_OVERRIDE_REQ,
	SHMI_CUSTOM_OFFROAD_OVERRIDE_ACTIVE,
	SHMI_CUSTOM_OFFROAD_INACTIVE,
	SHMI_CUSTOM_OFFROAD_ACTIVE,
	SHMI_CUSTOMA_REQ,
	SHMI_CUSTOMA_INACTIVE,
	SHMI_CUSTOMA_ACTIVE,
	SHMI_CUSTOMB_REQ,
	SHMI_CUSTOMB_INACTIVE,
	SHMI_CUSTOMB_ACTIVE,
	SHMI_RAIN_REQ,
	SHMI_RAIN_INACTIVE,
	SHMI_RAIN_ACTIVE,
	SHMI_ECO_REQ,
	SHMI_ECO_INACTIVE,
	SHMI_ECO_ACTIVE,
	SHMI_ERROR_MODE_0,
	SHMI_ICON_AUX,
	SHMI_TURBINE,
	SHMI_PARKING_BRAKE,
	SHMI_AUX_LIGHTS,
	SHMI_REAR_FOG_LIGHT,
	SHMI_LOW_FUEL,
	SHMI_SERVICE_INTERVAL,
	SHMI_CHECK_ENGINE,
	SHMI_HIGHT_BEAM,
	SHMI_AUTOMATIC_HIGH_BEAM,
	SHMI_LEFT_TURN_INDICATOR,
	SHMI_RIGHT_TURN_INDICATOR,
	SHMI_LOW_TIRE_PRESSURE,
	SHMI_COOLANT_TEMP,
	SHMI_LOW_OIL_PRESSURE,
	SHMI_GENERAL_PURPOSE_FAULT,
	SHMI_VEHICLE_HOLD_CONTROL,
	SHMI_TRACTION_CONTROL_0,
	SHMI_HEATED_GRIPS_FAULT,
	SHMI_HEATED_GRIPS_3,
	SHMI_HEATED_GRIPS_2,
	SHMI_HEATED_GRIPS_1,
	SHMI_HEATED_GRIPS_0,
	SHMI_SHMI_REGION_1,
	SHMI_LOW_BATTERY_VOLTAGE,
	SHMI_ABS_0,
	SHMI_TRACTION_CONTROL_FAULT,
	SHMI_LOAD_SHED,
	SHMI_TOTAL_ITEMS
};
extern int32_t GetItemX(const SHMI_ELEMENTS assetID);
extern int32_t GetItemY(const SHMI_ELEMENTS assetID);
extern int32_t GetItemFlipbookIndex(const SHMI_ELEMENTS assetID);//Added for FTP. Not autogenerated
extern bool GetItemVisibility(const SHMI_ELEMENTS assetID);
extern void SetItemVisibility(const SHMI_ELEMENTS assetID, const bool p_val);
extern void SetItemX(const SHMI_ELEMENTS assetID, const int32_t p_val);
extern void SetItemY(const SHMI_ELEMENTS assetID, const int32_t p_val);
extern void SetItemFlipbookIndex(const SHMI_ELEMENTS assetID, const int32_t p_val);



class Canvasroot : public ux_safehmi_canvas
{
public:
    Canvasroot(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren) :ux_safehmi_canvas(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren)
    {
       
       
    }
    
};

extern class Canvasroot root;
class Itemride_modes : public ux_safehmi_item
{
public:
    Itemride_modes(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible, 
	          const uint32_t pcolor, const int32_t pchildcount, const ux_safehmi_item ** const pchildren, const sHMI_ObjType ptype) :ux_safehmi_item(px, py, pwidth, pheight, 
                                                             pvisible, pcolor, pchildcount, pchildren, ptype)
    {
       SetFlipbookIndex(0);
    }
    
};


class Imageroad_active : public ux_safehmi_image
{
public:
    Imageroad_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageroad_inactive : public ux_safehmi_image
{
public:
    Imageroad_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageroad_req : public ux_safehmi_image
{
public:
    Imageroad_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagesport_req : public ux_safehmi_image
{
public:
    Imagesport_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagesport_inactive : public ux_safehmi_image
{
public:
    Imagesport_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagesport_active : public ux_safehmi_image
{
public:
    Imagesport_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageoffroad_req : public ux_safehmi_image
{
public:
    Imageoffroad_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageoffroad_override_req : public ux_safehmi_image
{
public:
    Imageoffroad_override_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageoffroad_override_active : public ux_safehmi_image
{
public:
    Imageoffroad_override_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageoffroad_inactive : public ux_safehmi_image
{
public:
    Imageoffroad_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageoffroad_active : public ux_safehmi_image
{
public:
    Imageoffroad_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustom_offroad_req : public ux_safehmi_image
{
public:
    Imagecustom_offroad_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustom_offroad_override_req : public ux_safehmi_image
{
public:
    Imagecustom_offroad_override_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustom_offroad_override_active : public ux_safehmi_image
{
public:
    Imagecustom_offroad_override_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustom_offroad_inactive : public ux_safehmi_image
{
public:
    Imagecustom_offroad_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustom_offroad_active : public ux_safehmi_image
{
public:
    Imagecustom_offroad_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustoma_req : public ux_safehmi_image
{
public:
    Imagecustoma_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustoma_inactive : public ux_safehmi_image
{
public:
    Imagecustoma_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustoma_active : public ux_safehmi_image
{
public:
    Imagecustoma_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustomb_req : public ux_safehmi_image
{
public:
    Imagecustomb_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustomb_inactive : public ux_safehmi_image
{
public:
    Imagecustomb_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecustomb_active : public ux_safehmi_image
{
public:
    Imagecustomb_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagerain_req : public ux_safehmi_image
{
public:
    Imagerain_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagerain_inactive : public ux_safehmi_image
{
public:
    Imagerain_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagerain_active : public ux_safehmi_image
{
public:
    Imagerain_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageeco_req : public ux_safehmi_image
{
public:
    Imageeco_req(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageeco_inactive : public ux_safehmi_image
{
public:
    Imageeco_inactive(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageeco_active : public ux_safehmi_image
{
public:
    Imageeco_active(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageerror_mode_0 : public ux_safehmi_image
{
public:
    Imageerror_mode_0(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageicon_aux : public ux_safehmi_image
{
public:
    Imageicon_aux(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageturbine : public ux_safehmi_image
{
public:
    Imageturbine(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageparking_brake : public ux_safehmi_image
{
public:
    Imageparking_brake(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageaux_lights : public ux_safehmi_image
{
public:
    Imageaux_lights(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagerear_fog_light : public ux_safehmi_image
{
public:
    Imagerear_fog_light(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagelow_fuel : public ux_safehmi_image
{
public:
    Imagelow_fuel(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageservice_interval : public ux_safehmi_image
{
public:
    Imageservice_interval(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecheck_engine : public ux_safehmi_image
{
public:
    Imagecheck_engine(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagehight_beam : public ux_safehmi_image
{
public:
    Imagehight_beam(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageautomatic_high_beam : public ux_safehmi_image
{
public:
    Imageautomatic_high_beam(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageleft_turn_indicator : public ux_safehmi_image
{
public:
    Imageleft_turn_indicator(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageright_turn_indicator : public ux_safehmi_image
{
public:
    Imageright_turn_indicator(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagelow_tire_pressure : public ux_safehmi_image
{
public:
    Imagelow_tire_pressure(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagecoolant_temp : public ux_safehmi_image
{
public:
    Imagecoolant_temp(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagelow_oil_pressure : public ux_safehmi_image
{
public:
    Imagelow_oil_pressure(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegeneral_purpose_fault : public ux_safehmi_image
{
public:
    Imagegeneral_purpose_fault(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagevehicle_hold_control : public ux_safehmi_image
{
public:
    Imagevehicle_hold_control(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagetraction_control_0 : public ux_safehmi_image
{
public:
    Imagetraction_control_0(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageheated_grips_fault : public ux_safehmi_image
{
public:
    Imageheated_grips_fault(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageheated_grips_3 : public ux_safehmi_image
{
public:
    Imageheated_grips_3(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageheated_grips_2 : public ux_safehmi_image
{
public:
    Imageheated_grips_2(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageheated_grips_1 : public ux_safehmi_image
{
public:
    Imageheated_grips_1(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageheated_grips_0 : public ux_safehmi_image
{
public:
    Imageheated_grips_0(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Itemshmi_region_1 : public ux_safehmi_item
{
public:
    Itemshmi_region_1(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible, 
	          const uint32_t pcolor, const int32_t pchildcount, const ux_safehmi_item ** const pchildren, const sHMI_ObjType ptype) :ux_safehmi_item(px, py, pwidth, pheight, 
                                                             pvisible, pcolor, pchildcount, pchildren, ptype)
    {
       SetFlipbookIndex(0);
    }
    
};


class Imagelow_battery_voltage : public ux_safehmi_image
{
public:
    Imagelow_battery_voltage(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageabs_0 : public ux_safehmi_image
{
public:
    Imageabs_0(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagetraction_control_fault : public ux_safehmi_image
{
public:
    Imagetraction_control_fault(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageload_shed : public ux_safehmi_image
{
public:
    Imageload_shed(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};



}
/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** CMS Rev 1.0      16-Jan-2016  emanoj1
** Creation.
**
**==========================================================================*/
#endif

/* end of file =============================================================*/
