/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_image_data.h
**                                                                            
** Description:    This file contains the image data autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 4/1/2025
**                 Total Image ROM size = [1942964 bytes]   
**                 Total RLE Savings    = [0 bytes]
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_IMAGE_DATA_H
#define HMI_GFX_MGR02_IMAGE_DATA_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** externs for all the image tables generated.
*/
extern UINT32 const lc_tt_daytime_ovg_data[5184];
extern UINT32 const lc_tt_fog_ovg_data[5184];
extern UINT32 const lc_tt_autohlight_ovg_data[5184];
extern UINT32 const lc_tt_fuel_ovg_data[5184];
extern UINT32 const lc_tt_awl_ovg_data[5184];
extern UINT32 const lc_tt_abs_rear_ovg_data[5184];
extern UINT32 const lc_tt_mil_ovg_data[5184];
extern UINT32 const lc_tt_dyntraction_ovg_data[5184];
extern UINT32 const lc_tt_limperf_ovg_data[5184];
extern UINT32 const lc_tt_limrecup_ovg_data[5184];
extern UINT32 const lc_abs_ovg_data[5184];
extern UINT32 const lc_img_bmwlogo_ovg_data[118400];
extern UINT32 const lc_tt_highbeam_ovg_data[5184];
extern UINT32 const lc_tt_autohlfailure_ovg_data[5184];
extern UINT32 const lc_tt_indleft_ovg_data[5184];
extern UINT32 const lc_tt_indright_ovg_data[5184];
extern UINT32 const lc_img_gear1_ovg_data[13780];
extern UINT32 const lc_img_gear2_ovg_data[13780];
extern UINT32 const lc_img_gear3_ovg_data[13780];
extern UINT32 const lc_img_gear4_ovg_data[13780];
extern UINT32 const lc_img_gear5_ovg_data[13780];
extern UINT32 const lc_img_gear6_ovg_data[13780];
extern UINT32 const lc_img_gearn_ovg_data[13780];
extern UINT32 const lc_img_gearp_ovg_data[13780];
extern UINT32 const lc_img_gearr_ovg_data[13780];
extern UINT32 const lc_img_spd_1left_ovg_data[9540];
extern UINT32 const lc_img_spd_1mid_ovg_data[9540];
extern UINT32 const lc_img_spd_2_ovg_data[9540];
extern UINT32 const lc_img_spd_3_ovg_data[9540];
extern UINT32 const lc_img_spd_4_ovg_data[9540];
extern UINT32 const lc_img_spd_5_ovg_data[9540];
extern UINT32 const lc_img_spd_6_ovg_data[9540];
extern UINT32 const lc_img_spd_7_ovg_data[9540];
extern UINT32 const lc_img_spd_8_ovg_data[9540];
extern UINT32 const lc_img_spd_9_ovg_data[9540];
extern UINT32 const lc_img_spd_1right_ovg_data[9540];
extern UINT32 const lc_img_kmh_ovg_data[1323];
extern UINT32 const lc_img_mph_ovg_data[1134];
extern UINT32 const lc_img_ridemode_1_ovg_data[1116];
extern UINT32 const lc_img_ridemode_2_ovg_data[1116];
extern UINT32 const lc_img_ridemode_3_ovg_data[1116];
extern UINT32 const lc_img_ridemode_1atten_ovg_data[2160];
extern UINT32 const lc_img_ridemode_2atten_ovg_data[2160];
extern UINT32 const lc_img_ridemode_3atten_ovg_data[2160];
extern UINT32 const lc_img_ridemode_atten_ovg_data[1116];
extern UINT32 const lc_img_ridemode_pro_ovg_data[2736];
extern UINT32 const lc_img_ridemode_pro_atten_ovg_data[3780];
extern UINT32 const lc_img_nospeed_ovg_data[31164];
extern UINT32 const lc_img_spd_0_ovg_data[9540];

/*
** mapping for image data which is repeating
*/
#define lc_img_spd_0_0_data                                  (lc_img_spd_0_ovg_data)
#define lc_img_spd_1right_0_data                             (lc_img_spd_1right_ovg_data)
#define lc_img_ridemode_pro_0_data                           (lc_img_ridemode_pro_ovg_data)

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_IMAGE_DATA_H */
