/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2025. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 4/1/2025
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_TT_DAYTIME_SWR_BASEID                    (0)
#define GFX_TT_FOG_SWR_BASEID                        (1)
#define GFX_TT_AUTOHLIGHT_SWR_BASEID                 (2)
#define GFX_TT_FUEL_SWR_BASEID                       (3)
#define GFX_TT_AWL_SWR_BASEID                        (4)
#define GFX_TT_ABS_REAR_SWR_BASEID                   (5)
#define GFX_TT_MIL_SWR_BASEID                        (6)
#define GFX_TT_DYNTRACTION_SWR_BASEID                (7)
#define GFX_TT_LIMPERF_SWR_BASEID                    (8)
#define GFX_TT_LIMRECUP_SWR_BASEID                   (9)
#define GFX_ABS_SWR_BASEID                           (10)
#define GFX_IMG_BMWLOGO_SWR_BASEID                   (11)
#define GFX_TT_HIGHBEAM_SWR_BASEID                   (12)
#define GFX_TT_AUTOHLFAILURE_SWR_BASEID              (13)
#define GFX_TT_INDLEFT_SWR_BASEID                    (14)
#define GFX_TT_INDRIGHT_SWR_BASEID                   (15)
#define GFX_IMG_GEAR1_SWR_BASEID                     (16)
#define GFX_IMG_GEAR2_SWR_BASEID                     (17)
#define GFX_IMG_GEAR3_SWR_BASEID                     (18)
#define GFX_IMG_GEAR4_SWR_BASEID                     (19)
#define GFX_IMG_GEAR5_SWR_BASEID                     (20)
#define GFX_IMG_GEAR6_SWR_BASEID                     (21)
#define GFX_IMG_GEARN_SWR_BASEID                     (22)
#define GFX_IMG_GEARP_SWR_BASEID                     (23)
#define GFX_IMG_GEARR_SWR_BASEID                     (24)
#define GFX_IMG_SPD_1LEFT_SWR_BASEID                 (25)
#define GFX_IMG_SPD_1MID_SWR_BASEID                  (26)
#define GFX_IMG_SPD_2_SWR_BASEID                     (27)
#define GFX_IMG_SPD_3_SWR_BASEID                     (28)
#define GFX_IMG_SPD_4_SWR_BASEID                     (29)
#define GFX_IMG_SPD_5_SWR_BASEID                     (30)
#define GFX_IMG_SPD_6_SWR_BASEID                     (31)
#define GFX_IMG_SPD_7_SWR_BASEID                     (32)
#define GFX_IMG_SPD_8_SWR_BASEID                     (33)
#define GFX_IMG_SPD_9_SWR_BASEID                     (34)
#define GFX_IMG_SPD_1RIGHT_SWR_BASEID                (35)
#define GFX_IMG_KMH_SWR_BASEID                       (36)
#define GFX_IMG_MPH_SWR_BASEID                       (37)
#define GFX_IMG_RIDEMODE_1_SWR_BASEID                (38)
#define GFX_IMG_RIDEMODE_2_SWR_BASEID                (39)
#define GFX_IMG_RIDEMODE_3_SWR_BASEID                (40)
#define GFX_IMG_RIDEMODE_1ATTEN_SWR_BASEID           (41)
#define GFX_IMG_RIDEMODE_2ATTEN_SWR_BASEID           (42)
#define GFX_IMG_RIDEMODE_3ATTEN_SWR_BASEID           (43)
#define GFX_IMG_RIDEMODE_ATTEN_SWR_BASEID            (44)
#define GFX_IMG_RIDEMODE_PRO_SWR_BASEID              (45)
#define GFX_IMG_RIDEMODE_PRO_ATTEN_SWR_BASEID        (46)
#define GFX_IMG_NOSPEED_SWR_BASEID                   (47)
#define GFX_IMG_SPD_0_SWR_BASEID                     (48)
#define GFX_IMG_SPD_0_0_SWR_BASEID                   (49)
#define GFX_IMG_SPD_1RIGHT_0_SWR_BASEID              (50)
#define GFX_IMG_RIDEMODE_PRO_0_SWR_BASEID            (51)
#define GFX_INVALID_BASEID                           (0)
#define GFX_BACKGROUND_TR_SCREEN_BASEID              (0)
#define GFX_BACKGROUND_FILL_SCREENS_1_BASEID         (1)
#define GFX_BACKGROUND_FILL_SCREENS_1_0_BASEID       (2)
#define GFX_BACKGROUND_FILL_SCREENS_1_1_BASEID       (3)
#define GFX_BACKGROUND_FILL_SCREENS_1_2_BASEID       (4)
#define GFX_BACKGROUND_FILL_SCREENS_1_3_BASEID       (5)
#define GFX_INVALID_WDG_IMAGE_BASEID                 (0)
#define GFX_WDGT_MAIN_BASEID                         (0)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS                (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS          (0U)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS                (52)
#define GFX_MGR02_NUM_3D_MDL_LAYERS                  (0)
#define GFX_MGR02_NUM_USER_LAYERS                    (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS         (0)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS                 (0)

#define GFX_MGR02_NUM_OF_SVGS                        (0)

#define GFX_MGR02_NUM_OF_SVG_CLIPS                   (0)
#define GFX_MGR02_NUM_OF_FILLS                       (6)
#define GFX_MGR02_NUM_OF_TILES                       (0)
#define GFX_MGR02_NUM_VIDEO_LAYERS                   (0)
#define GFX_MGR02_DYNAMIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS                       (1)

#define GFX_MGR02_NUM_VISIBLE_AREA      (2U)

/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (1440)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (800)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_IMG_BMWLOGO_ANIM                                 = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_SWR|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_RIDEMODE_PRO_ANIM                            = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_SWR|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDGT_MAIN_ANIM                                   = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_SWR|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS            (2)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS               (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS             (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS              (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS             (0)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS             (0)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS             (0)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS           (1)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS            (0)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS           (0)

#define GFX_MGR02_STEXTS_BUFFER_SIZE (0)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (0)
#define GFX_MGR02_NUM_OF_STEXTS      (0)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (0)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (0)
#define GFX_MGR02_MAX_PATH_CMD_BUF_LENGTH   (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   __GFX_EMPTY_LIST_DWDG
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS                (0)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_DIMAGE_TELLATE                                   = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_DAYTME                                 = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_AUTOHLIGHT                             = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_GEAR                                      = GFX_MGR02_SET_OBJ(3,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_SPEED_RIGHT                               = GFX_MGR02_SET_OBJ(4,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_SPEED_MIDDLE                              = GFX_MGR02_SET_OBJ(5,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_SPEED_LEFT                                = GFX_MGR02_SET_OBJ(6,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_SPD_UNIT                                  = GFX_MGR02_SET_OBJ(7,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_RIDEMODE_123                              = GFX_MGR02_SET_OBJ(8,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_NOSPEED                                   = GFX_MGR02_SET_OBJ(9,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_FOG                                    = GFX_MGR02_SET_OBJ(10,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_FUEL                                   = GFX_MGR02_SET_OBJ(11,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_AWL                                    = GFX_MGR02_SET_OBJ(12,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_ABS_REAR                               = GFX_MGR02_SET_OBJ(13,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_MIL                                    = GFX_MGR02_SET_OBJ(14,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_DYN_TRAC                               = GFX_MGR02_SET_OBJ(15,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_LIM_PERF                               = GFX_MGR02_SET_OBJ(16,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_LIM_RECUP                              = GFX_MGR02_SET_OBJ(17,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_IND_LEFT                               = GFX_MGR02_SET_OBJ(18,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMAGE_TT_IND_RIGHT                              = GFX_MGR02_SET_OBJ(19,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES                 (20)

#define GFX_BACKGROUND_FILL_SCREENS_1_4                 GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_BACKGROUND_TR_SCREEN_1                      GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_ABS_1                                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_BACKGROUND_FILL_SCREENS_1_0_1               GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_BACKGROUND_FILL_SCREENS_1_1_1               GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_BACKGROUND_FILL_SCREENS_1_2_1               GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_BACKGROUND_FILL_SCREENS_1_3_1               GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_DAYTIME_1                                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_HIGHBEAM_1                               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_FOG_1                                    GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_AUTOHLIGHT_1                             GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_AUTOHLFAILURE_1                          GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_FUEL_1                                   GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_AWL_1                                    GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_ABS_REAR_1                               GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_MIL_1                                    GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_DYNTRACTION_1                            GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_LIMPERF_1                                GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_LIMRECUP_1                               GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_INDLEFT_1                                GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_TT_INDRIGHT_1                               GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEAR1_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEAR2_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEAR3_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEAR4_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEAR5_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEAR6_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEARN_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEARP_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_GEARR_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_0_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_1LEFT_1                             GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_2_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_3_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_4_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_5_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_6_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_7_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_8_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_9_1                                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_1RIGHT_0_1                          GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_0_0_1                               GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_1RIGHT_1                            GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_2_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_3_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_4_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_5_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_6_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_7_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_8_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_9_2                                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_1MID_1                              GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_1RIGHT_2                            GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_2_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_3_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_4_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_5_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_6_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_7_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_8_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SPD_9_3                                 GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_KMH_1                                   GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_MPH_1                                   GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_NOSPEED_1                               GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_PRO_0_1                        GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_1_1                            GFX_MGR02_SET_OBJ(20 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_2_1                            GFX_MGR02_SET_OBJ(20 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_3_1                            GFX_MGR02_SET_OBJ(20 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_PRO_ATTEN_1                    GFX_MGR02_SET_OBJ(21 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_1ATTEN_1                       GFX_MGR02_SET_OBJ(22 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_2ATTEN_1                       GFX_MGR02_SET_OBJ(22 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_3ATTEN_1                       GFX_MGR02_SET_OBJ(22 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_RIDEMODE_ATTEN_1                        GFX_MGR02_SET_OBJ(20 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES               (23)
#define GFX_MGR02_NUM_SVG_INSTANCES                  (0)
#define GFX_MGR02_NUM_FILL_INSTANCES                 (6)
#define GFX_MGR02_NUM_TILE_INSTANCES                 (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES                 (0)
#define GFX_MGR02_NUM_TEXT_INSTANCES                 (0)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_ANIM1SCREEN                                      = (0)
  ,GFX_MAINSCREEN                                       = (1)
  ,GFX_FAILSAFESCREEN                                   = (2)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS                        (3)
#define GFX_MGR02_LAYER0_DAR_SIZE                       (28)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG     (1)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX                 (28)

/*
** Macro definitions for screen background colors
*/
#define GFX_ANIM1SCREEN_BG_COLOR                            (0xFF000000UL)
#define GFX_MAINSCREEN_BG_COLOR                             (0xFF000000UL)
#define GFX_FAILSAFESCREEN_BG_COLOR                         (0xFF000000UL)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x00000000u)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (0)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1U)
#define GFX_MGR02_NUM_PRIORITY            (3)
#define GFX_MGR02_UNICODE              (1)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (0)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (0)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (0)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_ARGB8888)
#define GFX_MGR02_BMW_WINDOWS
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (1)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_SOFTWARE
#define GFX_MGR02_RENDER_NONE

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        4/1/2025     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
