/* file: C:/Karthik/NissanL21B/di.gen.nissan.cmfb.ic.bsw/Appl/GenData/tcb.h */
/* automatically generated by genArmCortexR.exe, Version: 7.00 BETA */
/* Configuration file: C:/Users/KSHANMU4/AppData/Local/Temp/Cfg_Gen-1483514697575-0/OsProxyFiles-1483515052513-0/Os_ActiveEcuC.arxml */
/* Generation time: Wed Jan 04 13:01:21 2017 */
/* Unlimited license CBD1400814 for Visteon Corporation, Evaluation License */
/* Implementation: S6J32xx */
/* Version of general code: 9.01.06 */
/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with message 0883,
 * but there is a double include prevention and therefore the message is considered to be wrong. */
#if ! defined __TCB_H__   /* PRQA S 0883 EOF */ 
#define __TCB_H__
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 7
#define osdVrmGenMinRelNum 0
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdNumberOfAlarmsOnHiResCounter 0

#define osdUseHighResolutionTimer 0

#define osdHwTimerNeeded_ReloadTimer 0
#define osdHwTimerNeeded_FreeRunningTimer 0

#define osdHardwareTimerNeeded 0
#define osdGetCurrentTimeHighResHybridIdx -1
#define osdGetCurrentTimeHighResMonoIdx -1
#define osdGetCurrentTimeStdIdx -1
#define osdSetTIPAbsMaxGtSemiCountIdx -1
#define osdSetTIPAbsMaxLeSemiCountIdx -1
#define osdSetTIPRelMaxGtSemiCountIdx -1
#define osdSetTIPRelMaxLeSemiCountIdx -1
#define osdClearTIPAbsIdx -1
#define osdClearTIPRelIdx -1
#define osdHandleCounterInterruptHiResIdx -1
#define osdHandleCounterInterruptStdIdx -1
#define osdInsertMinHeapHiResIdx -1
#define osdInsertMinHeapStdIdx 0
#define osdORTIDebug 1
#define osdORTIVersion  not used anymore!
#define osdORTIStdVersion 220
#define osdORTIEnabled 1
#define osdNumberOfScheduleTables 2
#define osdNumberOfHiResSchedTabs 0
#define osdScheduleTableSyncUsed 0
#define osdNumberOfSTExpiryPoints 3
#define osdNumberOfSTSetEvent 1
#define osdNumberOfSTActivateTask 2
#define osdNumberOfSTEntries 5
#define osdCallTimingHooks 0
#define osdTimingHooksFileName ""
#define osdNumberOfConfiguredIRQs 48
#define osdNumberOfConfiguredFIQs 0
#define osdNumberOfConfiguredEXCs 4
#define osdNumberOfIRQs 512
#define osdNumberOfFIQs 32
#define osdNumberOfExceptions 8
#define CC ECC2
#define STATUS_LEVEL EXTENDED_STATUS
#define osdByteSize 8U
#define osdCompiler osdCompilerGreenhillsArmCortexR
#define osdFPUSupport 1
#define osdFullPreempt 0
#define osdLib 0
#define osdMixedPreempt 1
#define osdNeedCI707_00026_Workaround 0
#define osdNeedCI707_00027_Workaround 0
#define osdNeedIOCTypes 0
#define osdNonPreempt 0
#define osdNumApplErrorHooks 0
#define osdNumApplShutdownHooks 0
#define osdNumApplStartupHooks 0
#define osdNumberOfAllResources 3
#define osdNumberOfApplMPURegions 1
#define osdNumberOfAvailableCores 1
#define osdNumberOfBasicTasks 6
#define osdNumberOfExtendedTasks 16
#define osdNumberOfGlobalMPURegions 10
#define osdNumberOfIOCCommunications 0
#define osdNumberOfInternalResources 0
#define osdNumberOfInterruptResources 0
#define osdNumberOfPriorities 17
#define osdNumberOfQueuedIOCCallbacks 0
#define osdNumberOfQueuedIOCCommunications 0
#define osdNumberOfTaskResources 3
#define osdRTSize 1
#define osdReducedStatusChecks 0
#define osdRegionIndexForStackWindow 11
#define osdResAccessMaskBits 32
#define osdSC SC3
#define osdSysErrorHook 1
#define osdSysShutdownHook 1
#define osdSysStartupHook 1
#define osdSystemApplIDCore0 1
#define osdTimingProtectionUsed 0
#define osdUseIOC 0
#define osdMaxNumberOfCat2ISRLevels 3
#define osdNumberOfAllTasks 22
#define osdNumberOfCat2ISRs 49
#define osdNumberOfNonTrustedFunctions 0
#define osdNumberOfPeripheralRegions 0
#define osdNumberOfTrustedFunctions 1
#define osdUseTrustedFunctionStubs 0
#define osdNumberOfAlarms 61
#define osdNumberOfAlarmCallback 0
#define osdNumberOfAlarmSetEvent 58
#define osdNumberOfAlarmActivateTask 2
#define osdNumberOfAlarmIncrementCounter 1
#define osdNumberOfCounters 2
#define osdNumberOfSWCounters 2
#define osdNumberOfSWAndSRCounters 2
#define osdNumberOfApplications 2
#define osdStackCheck 1
#define osdStackUsageMeasurement 1

#define osdTypeHeaderInclude 1

#define osdEnableAssertions 1

#define osdGetServiceIdMacros 1
#define osdParameterAccessMacros 0

#define osdTimingMeasurement 0
#define osdProtectAndMeasureAll 0
#define osdAsSelected 0
#define osdOnlyMeasureAll 0

#define osdProtReactKillTaskIsrAllowed  0
#define osdProtReactKillApplAllowed     0
#define osdProtReactKillApplRestAllowed 0
#define osdDerivative osdS6J32xx
#define osdStackCheckPattern 0xaaaaaaaaUL
#define osdExceptionDetails 1
#define osdPreAlarmHook         0
#define osdStackAreaID                11
#define osdApplSpecificHooksUsed 0
#define osdMPURegion0NeedsReprogramming 1
#define osdMPURegion1NeedsReprogramming 0
#define osdMPURegion2NeedsReprogramming 0
#define osdMPURegion3NeedsReprogramming 0
#define osdMPURegion4NeedsReprogramming 0
#define osdMPURegion5NeedsReprogramming 0
#define osdMPURegion6NeedsReprogramming 0
#define osdMPURegion7NeedsReprogramming 0
#define osdMPURegion8NeedsReprogramming 0
#define osdMPURegion9NeedsReprogramming 0
#define osdMPURegion10NeedsReprogramming 0
#define osdMPURegion11NeedsReprogramming 1
#define osdMPURegion12NeedsReprogramming 0
#define osdMPURegion13NeedsReprogramming 0
#define osdMPURegion14NeedsReprogramming 0
#define osdMPURegion15NeedsReprogramming 0
#define osdNumberOfMPURegions 16
#define osdMPURegionFirstUsed 0
#define osdMPURegionLastUsed 11
#define osdMaxNestingNepth 3

#define osdErrorHook 1
#define osdPreTaskHook 1
#define osdPostTaskHook 1
#define osdShutdownHook 1
#define osdProtectionHook 1

  #define osdKillTaskIsrPossible 0
  #define osdKillApplPossible 0
#define osdNumberOfProcesses (osdNumberOfAllTasks+osdNumberOfCat2ISRs)

#endif /* ! defined __TCB_H__ */
