/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2017. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**============================================================================
**
** Name:           ux_safehmi_types.h
**
** Description:    Types
**
** Organization:   GUI Software Section, Visteon
**
**============================================================================
**
**==========================================================================*/
#ifndef UX_SAFEHMI_TYPES_H
#define UX_SAFEHMI_TYPES_H

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include <cwchar>
#include <cstdint>

/*============================================================================
** T Y P E   D E F I N I T I O N S
**==========================================================================*/

#define UX_SHMI_MAX_SCENE_DEPTH (3U)

#ifdef SHMI_DEBUG
#define SHMI_ERROR(format, ...)        \
  (void)printf(format, ##__VA_ARGS__); \
  (void)printf("  -  file:%s function:%s line:%d\n", __FILE__, __FUNCTION__, __LINE__)
#define SHMI_INFO(format, ...) (void)printf(format, ##__VA_ARGS__)
#else
#define SHMI_ERROR(format, ...)
#define SHMI_INFO(format, ...)
#endif



namespace UX_SHMI_PLAYER
{
  /// <summary>
  /// Failed to initialize safeHMI engine
  /// </summary>
  const uint8_t SHMI_NOT_INITIALIZED    = 0x01U;
  /// <summary>
  /// Failed to render the elements. This may be due to any failure case occured durig rendering
  /// 1. Wrong image data
  /// 2. Out of bounds
  /// 3. Trying to render when initialization failed
  /// 4. Any failure case while calling screen API
  /// </summary>
  const uint8_t SHMI_RENDER_FAILURE     = 0x02U;
  /// <summary>
  /// QNX screen_post_window API failed
  /// </summary>
  const uint8_t SHMI_SWAP_FAILURE       = 0x04U;
  /// <summary>
  /// Unable to retrieve the screen buffer
  /// </summary>
  const uint8_t SHMI_DST_BUFFER_INVALID = 0x08U;
  /// <summary>
  /// Invalid image data. Image data corrupted(Autogenerated image data should not be changed )
  /// </summary>
  const uint8_t SHMI_INVALID_IMG        = 0x10U;
  /// <summary>
  /// Image/Rectangle Element boundary out of range
  /// </summary>
  const uint8_t SHMI_OUT_OF_BOUNDS      = 0x20U;
#ifdef SHMI_DEBUG
  typedef double float64_t;
#endif
  /// <summary>
  /// structure to represent QNX display information
  /// </summary>
  typedef struct
  {
    int32_t display_id; /*!< QNX Display ID. - 1 for invalid */
    /// <summary>
    /// QNX Display type
    /// | Valid input of display type |
    /// | :---------------: |
    /// | SCREEN_DISPLAY_TYPE_INTERNAL = 0x7660 |
    /// | SCREEN_DISPLAY_TYPE_COMPOSITE = 0x7661 |
    /// | SCREEN_DISPLAY_TYPE_SVIDEO = 0x7662 |
    /// | SCREEN_DISPLAY_TYPE_COMPONENT_YPbPr = 0x7663 |
    /// | SCREEN_DISPLAY_TYPE_COMPONENT_RGB = 0x7664 |
    /// | SCREEN_DISPLAY_TYPE_COMPONENT_RGBHV = 0x7665 |
    /// | SCREEN_DISPLAY_TYPE_DVI = 0x7666 |
    /// | SCREEN_DISPLAY_TYPE_HDMI = 0x7667 |
    /// | SCREEN_DISPLAY_TYPE_DISPLAYPORT = 0x7668 |
    /// | SCREEN_DISPLAY_TYPE_OTHER = 0x7669 |
    /// | 0 - For invalid |
    /// </summary>
    int32_t display_type;
    /// <summary>
    /// Single integer that indicates the distance from the bottom that is used when ordering window groups amongest each other;
    /// </summary>
    int32_t zorder;
    /// <summary>
    /// Single integer that contains the pipeline ID; a property of a window object.
    /// Layers are exposed as pipelines to display controllers.
    /// </summary>
    int32_t pipeline;
    /// <summary>
    /// Specifies the x position of the window
    /// </summary>
    int32_t x_pos;
    /// <summary>
    /// Specifies the y position of the window
    /// </summary>
    int32_t y_pos;
  } shmi_qnx_disp_info;

  /// <summary>
  /// Supported elements for safehmi layout
  /// </summary>
  enum class sHMI_ObjType
  {
    eCanvas,    /*!< Canvas Element*/
    eItem,      /*!< Item */
    eImage,     /*!< Image Element */
    eRectangle, /*!< Rectangle Element */
    eInvalid    /*!< Invalid object type*/
  };

  /*============================================================================
  ** E N T R Y   P O I N T S
  **==========================================================================*/

  /*============================================================================
  ** D A T A   A C C E S S   S E R V I C E S
  **==========================================================================*/
} // namespace UX_SHMI_PLAYER
/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
**  CMS Rev 1.0      20-Jun-2020  arajase2
**  Source code is leveraged from QMLPlayer. QMLPlayer RTC baseline - ss-UI-CORE-EARLY-HMI-1.3.1
**
**==========================================================================*/
/* end of file =============================================================*/
#endif
