/* Undefine all field names (disable by setting VCAST_DO_NOT_UNDEF_FIELDS) */
#undef CoreParam
#undef AppParam
#undef ActiveISRId
#undef pLastObjRef
#undef pActiveObjRef
#undef ActiveTaskIndex
#undef RequestedTaskIndex
#undef ActiveTaskPriority
#undef RequestedTaskPriority
#undef ResOccVirtualPrioBits
#undef TaskPriorityBits
#undef RequestScheduler
#undef LockDispatcher
#undef IntSaveDisableRequestCounter
#undef IntSaveStatus
#undef IntSaveGlobal
#undef CurrentContext
#undef OsIntSaveDisableRequestCounter
#undef State
#undef State
#undef AccessId
#undef TaskStartAddress
#undef TaskStackStartAddress
#undef TaskStackSize
#undef TaskPriority
#undef TaskMaxActivationCount
#undef TaskCategory
#undef pObjRef
#undef pAppRef
#undef TasksType
#undef TasksID
#undef TaskParamRef
#undef ObjId
#undef CoreId
#undef ObjType
#undef AccessId
#undef pAppRef
#undef StackStartAddress
#undef StackSize
#undef StackRegAttribute
#undef StackRegnSizeAndEnable
#undef AppId
#undef AccessId
#undef AccessLevel
#undef pCoreRef
#undef pObjListRef
#undef pHookRef
#undef WaitEventMask
#undef SetEventMask
#undef StackAddress
#undef State
#undef ActivationCnt
#undef ResCnt
#undef CoreId
#undef IsAsrCore
#undef NumOfApp
#undef pAppListRef
#undef pOsCoreAppRef
#undef pOsCoreObjRef
#undef pHookRef
#undef pCoreSysRef
#undef StartHook
#undef PreHook
#undef PostHook
#undef ShutdownHook
#undef ErrorHook
#undef StackStartAddress
#undef StackSize
#undef StackRegAttribute
#undef StackRegnSizeAndEnable
