/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2017 -2018. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**==========================================================================*/

/*============================================================================
**
** Name:           View_Telltale_Cfg.h
**
** Description:    This is an autogenerated file. Do not hand modify...
**                  
** Organization:   Driver Information Software Section,
**                 Visteon
**
**============================================================================
**
**==========================================================================*/

#ifndef VIEW_TELLTALE_CFG_H
#define VIEW_TELLTALE_CFG_H

//============================================================================================
//NOTE: DONOT DELETE THE BELOW DEFINITIONS-                                                   
// USE THE BELOW DEFINITONS TO UPDATE  'cTtOutputTableList'                                   
//============================================================================================
#define cTT_HARDWARE_DRIVEN       (0x01)                                                      
#define cTT_HARDWARE_DRIVEN_SAFE  (0x03)                                                      
#define cTT_TFT_DRIVEN            (0x02)                                                      
#define cTT_NOT_AVAILABLE         (0x00)                                                      
#define UnusedPin                 (255u)                                                      
                                                                                              
#define cTtOutputTableList  {\
/*TT_ABS_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_AIRBAG_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_BRAKE_RED_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_BRAKE_HOLD_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_BRAKE_YELLOW_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_PARKING_BRAKE_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_TRACTION_CTRL_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_VCS_OFF_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ABS_INDEX_US*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_BRAKE_RED_INDEX_US*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_PARKING_BRAKE_INDEX_US*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SAF_RES4_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SAF_RES5_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SAF_RES6_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SAF_RES7_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SAF_RES8_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ADAS_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_AUTO_HIGH_BEAM_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_BRAKE_HOLD_STANDBY_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_FUEL_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_FFOG_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_HEAD_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_HIGH_BEAM_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_PCS_OFF_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_READY_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_RFOG_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SEAT_BELT_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_TAIL_LIGHT_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_TURN_HAZARD_RIGHT_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_TURN_HAZARD_LEFT_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_EWT_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LO_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SHADED_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_HI_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_HI_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_INFRA*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_VEHICLE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_COMBINATION*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SSS_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SSS_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LCA_LEFT_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LCA_LEFT_GRAY*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LCA_LEFT_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LCA_RIGHT_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LCA_RIGHT_GRAY*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LCA_RIGHT_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LTA_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LTA_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LTA_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_CCT_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_CCT_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_CCT_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_RCCT_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_RCCT_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_RCCT_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_WHITE_LV4*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_WHITE_LV3*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_WHITE_LV2*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_WHITE_LV1*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_GREEN_LV4*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_GREEN_LV3*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_GREEN_LV2*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ACCDT_GREEN_LV1*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SL_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SL_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_SL_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_AUTO_LSD_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_DRIVEMODE_SPORT*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_DRIVEMODE_ECO*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_DRIVEMODE_CUSTOM*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_DRIVEMODE_RANGE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_DRIVEMODE_REARCOMFORT*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_DRIVEMODE_SNOW*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_DRIVEMODE_TRACK*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LDA_RED*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LDA_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LDA_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LDA_OFF_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_LDA_OFF_WHITE*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_ECOLAMP*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_PS_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_PKBOPER_TXT*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_PKBOPER_IMG*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_TPMS_INDEX*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_EBPWIND_RED_US*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_EBPWIND_RED*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_FMSR_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_FMFR_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_MULWL_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_HCS_ACCESS_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_HCS_LIFT_GREEN*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
/*TT_HCS_LIFT_AMBER*/   {cTT_TFT_DRIVEN,    cTT_NOT_AVAILABLE},\
}
#endif

