/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in 2009. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_anim_engine_cfg.h                                    
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated by GDT . Do not handmodify this file. 
                    Generated on MM/DD/YYYY - 3/3/2014
Organization     :  DI/Audio Software Section,                                 
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#ifndef HMI_GFX_ANIM_ENGINE_CFG_H
#define HMI_GFX_ANIM_ENGINE_CFG_H
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/
                                                                               
#define GFX_NEW_ANIMATIONS_1_FRAME1               (0)
#define GFX_MAL_ANIM_TEST1_NUM_FRAMES             (1)

#define GFX_DATA_ANIM_TEST1_FRAME1                (0)
#define GFX_DATA_ANIM_TEST1_FRAME3                (1)
#define GFX_DATA_ANIM_TEST1_NUM_FRAMES            (2)

#define GFX_ANIM_WELCOME_FRAME1                   (0)
#define GFX_ANIM_WELCOME_FRAME5                   (1)
#define GFX_ANIM_WELCOME_FRAME2                   (2)
#define GFX_ANIM_WELCOME_FRAME3                   (3)
#define GFX_ANIM_WELCOME_FRAME4                   (4)
#define GFX_ANIM_WELCOME_NUM_FRAMES               (5)

#define GFX_NEW_ANIMATIONS_5_FRAME1               (0)
#define GFX_NEW_ANIMATIONS_5_FRAME2               (1)
#define GFX_NEW_ANIMATIONS_5_FRAME3               (2)
#define GFX_NEW_ANIMATIONS_5_NUM_FRAMES           (3)

#define GFX_SCR_MAL_FRAME1                        (0)
#define GFX_SCR_MAL_NUM_FRAMES                    (1)

#define GFX_VG_FNT_ANIM_FRAME1                    (0)
#define GFX_VG_FNT_ANIM_FRAME2                    (1)
#define GFX_VG_FNT_ANIM_NUM_FRAMES                (2)

#define GFX_DYN_AREA_ANIM_FRAME1                  (0)
#define GFX_DYN_AREA_ANIM_NUM_FRAMES              (1)

#define GFX_DYN_MAL_ANIM_FRAME1                   (0)
#define GFX_DYN_MAL_ANIM_NUM_FRAMES               (1)

#define GFX_COMPASS_ROATATION_FRAME2              (0)
#define GFX_COMPASS_ROATATION_FRAME4              (1)
#define GFX_COMPASS_ROATATION_NUM_FRAMES          (2)

#define GFX_NEEDLE_ROTATE_FRAME1                  (0)
#define GFX_NEEDLE_ROTATE_FRAME2                  (1)
#define GFX_NEEDLE_ROTATE_NUM_FRAMES              (2)

#define GFX_NISSAN_ANIM_FRAME1                    (0)
#define GFX_NISSAN_ANIM_FRAME2                    (1)
#define GFX_NISSAN_ANIM_NUM_FRAMES                (2)

#define GFX_TACHOMETER_DEC1                       (0)
#define GFX_TACHOMETER_INC1                       (1)
#define GFX_TACHOMETER_DEC2                       (2)
#define GFX_TACHOMETER_INC2                       (3)
#define GFX_TACHOMETER_DEC3                       (4)
#define GFX_TACHOMETER_INC3                       (5)
#define GFX_TACHOMETER_DEC4                       (6)
#define GFX_TACHOMETER_INC5                       (7)
#define GFX_TACHOMETER_65PLUS                     (8)
#define GFX_NISSAN_W02_ANIM_FRAME35               (9)
#define GFX_NISSAN_W02_ANIM_FRAME36               (10)
#define GFX_NISSAN_W02_ANIM_FRAME37               (11)
#define GFX_NISSAN_W02_ANIM_FRAME38               (12)
#define GFX_NISSAN_W02_ANIM_FRAME39               (13)
#define GFX_NISSAN_W02_ANIM_NUM_FRAMES            (14)


enum
{
    GFX_MAL_ANIM_TEST1
   ,GFX_DATA_ANIM_TEST1
   ,GFX_ANIM_WELCOME
   ,GFX_NEW_ANIMATIONS_5
   ,GFX_SCR_MAL
   ,GFX_VG_FNT_ANIM
   ,GFX_DYN_AREA_ANIM
   ,GFX_DYN_MAL_ANIM
   ,GFX_COMPASS_ROATATION
   ,GFX_NEEDLE_ROTATE
   ,GFX_NISSAN_ANIM
   ,GFX_NISSAN_W02_ANIM
   ,__GFX_NUM_ANIMATIONS
};
#define GFX_NUM_ANIMATIONS                        (12)
#define GFX_DYN_DATA_ANIMATIONS
#define GFX_BASE_ANIM_RATE_MSEC                   (167)
#define GFX_ANIM_GOTO_COUNT_ARRAY_SIZE            (4)

#define GFX_BASE_ANIM_RATE_SCALE                  (10)

extern UINT32 hmi_gfx_anim_engine_user_defined_interpolate(UINT32 p_cur_step, UINT32 p_max_step);
extern UINT32 hello_handler(UINT32 p_cur_step, UINT32 p_max_step);
extern UINT32 my_handler(UINT32 p_cur_step, UINT32 p_max_step);
/***************************************************************************** 
*                              File Scope Prototypes                         * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                   Functions                                                * 
******************************************************************************/
extern void hmi_anim_1_cb(UINT32 p_cur_frame, UINT32 p_total_frames);
extern UINT32 goto_check_function(UINT32 p_cur_step);
extern void dyn_area_anim_cb(UINT32 p_cur_frame, UINT32 p_total_frames);
extern void dyn_mal_anim_cb(UINT32 p_cur_frame, UINT32 p_total_frames);
extern void ui_menu_bar_anim_cb(UINT32 p_cur_frame, UINT32 p_total_frames);

                                                                               
/*End of File*/                                                                
/***************************************************************************** 
*   for each change to this file, be sure to record:                         * 
*      1.  who made the change and when the change was made                  * 
*      2.  why the change was made and the intended result                   * 
*   Following block needs to be repeated for each change                       
****************************************************************************** 
*   Note: In the traceability column we need to trace back to the Design Doc.* 
*   For the initial version it is traced to the Design Document section.     * 
*   For further changes it shall trace to the source of the change which may * 
*   be SPSS/SCR/Defect details(Defect may be Testing/validation defect)/Any  * 
*   other reason                                                            *  
******************************************************************************/
#endif
