/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in 2014. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************//*
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_mgr02_font.c                                     
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated. Do not hand modify                          
Organization     :  Driver Information Software Section,                       
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#define HMI_GFX_MGR02_PRIV_C

/*****************************************************************************
*                                 System Includes                            *
******************************************************************************/
#include "hmi_gfx_mgr02_layout.h"
#include "hmi_gfx_mgr02_font.h"
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/

UINT8 const lc_New_fonts_3_group[]=
{
   GFX_MGR02_FONT_ID_DEFAULT_FONT,
   GFX_MGR02_FONT_ID_NEW_FONTS_1,
   GFX_MGR02_FONT_ID_NEW_FONTS_2
};
UINT8 const lc_New_fonts_4_group[]=
{
   GFX_MGR02_FONT_ID_NEW_FONTS_2,
   GFX_MGR02_FONT_ID_NEW_FONTS_1,
};
GFX_MGR02_FONT const lc_gfx_font_table[]=
{
  {2, 0, 0, 0, {56}, {&lc_Default_Font_lut[0]}},
  {2, 0, 0, 0, {24}, {&lc_New_fonts_1_lut[0]}},
  {2, 0, 0, 0, {54}, {&lc_New_fonts_2_lut[0]}},
  {3, 1, 0, 0, {0}, {lc_New_fonts_3_group}},
  {2, 1, 0, 0, {1}, {lc_New_fonts_4_group}},
  {5, 0, 1, 0, {56}, {&lc_New_fonts_7_lut}},
  {76, 0, 0, 0, {42}, {&lc_ArialForFord_AL_26_lut[0]}}
};
                                                                              
/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        3/3/2014     EMANOJ1                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
