/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_image_data.h
**                                                                            
** Description:    This file contains the image data autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 3/3/2014
**                 Total Image ROM size = [5260525 bytes]   
**                 Total RLE Savings    = [57503 bytes]
**                                                                            
**                 See the <Kepler Software Architecture document> in         
**                 ClearCase in <sw_architecture\driver_information\        
**                 platforms\kepler\05_product\design> for more details    
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_IMAGE_DATA_H
#define HMI_GFX_MGR02_IMAGE_DATA_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** externs for all the image tables generated.
*/
extern UINT8 const lc_img_odo_icon_data[800];
extern UINT8 const lc_img_trip_icon_data[960];
extern UINT8 const lc_img_dte_icon_data[768];
extern UINT8 const lc_img_header_scr1_1_data[23040];
extern UINT8 const lc_img_middle_scr1_1_data[24000];
extern UINT8 const lc_img_middle_scr1_2_data[24000];
extern UINT8 const lc_img_middle_scr1_3_data[24000];
extern UINT8 const lc_img_header_snow_flake_p2_data[616];
extern UINT8 const lc_img_test1_dcu_data[1008];
extern UINT8 const lc_img_test3_dcu_0_data[4928];
extern UINT8 const lc_img_welcome_anim_22_data[130560];
extern UINT8 const lc_img_gauge_bg_data[5577];
extern UINT8 const lc_img_poup_bg_data[81168];
extern UINT8 const lc_img_welcome_anim_3_data[130560];
extern UINT8 const lc_img_welcome_anim_4_data[130560];
extern UINT8 const lc_img_welcome_anim_5_data[130560];
extern UINT8 const lc_img_welcome_anim_6_data[130560];
extern UINT8 const lc_img_welcome_anim_7_data[130560];
extern UINT8 const lc_img_welcome_anim_8_data[130560];
extern UINT8 const lc_img_welcome_anim_9_data[130560];
extern UINT8 const lc_img_welcome_anim_10_data[130560];
extern UINT8 const lc_img_welcome_anim_11_data[130560];
extern UINT8 const lc_img_welcome_anim_12_data[130560];
extern UINT8 const lc_img_welcome_anim_13_data[130560];
extern UINT8 const lc_img_welcome_anim_14_data[130560];
extern UINT8 const lc_img_welcome_anim_15_data[130560];
extern UINT8 const lc_img_welcome_anim_16_data[130560];
extern UINT8 const lc_img_welcome_anim_17_data[130560];
extern UINT8 const lc_img_welcome_anim_18_data[130560];
extern UINT8 const lc_img_welcome_anim_19_data[130560];
extern UINT8 const lc_img_welcome_anim_20_data[130560];
extern UINT8 const lc_img_welcome_anim_21_data[130560];
extern UINT8 const lc_img_poup_bg_0_data[2016];
extern UINT8 const lc_img_ford_logo_data[126720];
extern UINT16 const lc_new_images_1_data[3024];
extern UINT16 const lc_img_popup_line_data[478];
extern UINT16 const lc_img_nissan_bg_data[32640];
extern UINT16 const lc_img_nissan_1_data[24480];
extern UINT16 const lc_img_nissan_2_data[32640];
extern UINT16 const lc_img_test1_anim_dcu_data[1008];
extern UINT16 const lc_img_test3_dcu_data[4928];
extern UINT16 const lc_img_root_clip_data[34390];
extern UINT16 const lc_img_child_clip_data[11952];
extern UINT16 const lc_img_tachometer_data[182400];
extern UINT16 const lc_img_ovg_data[108800];
extern UINT16 const lc_img_tuner_scale_data[23852];
extern UINT8 const lc_img_tune_arrow_data[620];
extern UINT16 const lc_img_test3_dcu_swr_data[4928];
extern UINT16 const lc_img_swr_swr_data[108800];
extern UINT32 const lc_img_compass_ovg_data[78400];
extern UINT32 const lc_img_compass_rotate_n_ovg_data[1800];
extern UINT32 const lc_img_compass_rotate_nw_ovg_data[1800];
extern UINT32 const lc_img_compass_rotate_w_ovg_data[1800];
extern UINT32 const lc_img_compass_rotate_sw_ovg_data[1800];
extern UINT32 const lc_img_compass_rotate_s_ovg_data[1800];
extern UINT32 const lc_img_compass_rotate_se_ovg_data[1800];
extern UINT32 const lc_img_compass_rotate_e_ovg_data[1800];
extern UINT32 const lc_img_compass_rotate_ne_ovg_data[1800];
extern UINT32 const lc_new_images_98_ovg_data[162316];
extern UINT32 const lc_img_svg_test_ovg_data[40000];
/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_IMAGE_DATA_H */
