/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2014. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 3/3/2014
**                                                                            
**                 See the <Kepler Software Architecture document> in         
**                 ClearCase in <sw_architecture\driver_information\        
**                 platforms\kepler\05_product\design> for more details    
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_IMG_ODO_ICON_BASEID                    (0)
#define GFX_IMG_TRIP_ICON_BASEID                   (1)
#define GFX_IMG_DTE_ICON_BASEID                    (2)
#define GFX_IMG_HEADER_SCR1_1_BASEID               (3)
#define GFX_IMG_MIDDLE_SCR1_1_BASEID               (4)
#define GFX_IMG_MIDDLE_SCR1_2_BASEID               (5)
#define GFX_IMG_MIDDLE_SCR1_3_BASEID               (6)
#define GFX_IMG_HEADER_SNOW_FLAKE_P2_BASEID        (7)
#define GFX_IMG_TEST1_DCU_BASEID                   (8)
#define GFX_IMG_TEST1_ANIM_DCU_BASEID              (9)
#define GFX_IMG_TEST3_DCU_BASEID                   (10)
#define GFX_IMG_TEST3_DCU_0_BASEID                 (11)
#define GFX_IMG_WELCOME_ANIM_22_BASEID             (12)
#define GFX_IMG_GAUGE_BG_BASEID                    (13)
#define GFX_IMG_POUP_BG_BASEID                     (14)
#define GFX_IMG_WELCOME_ANIM_3_BASEID              (15)
#define GFX_IMG_WELCOME_ANIM_4_BASEID              (16)
#define GFX_IMG_WELCOME_ANIM_5_BASEID              (17)
#define GFX_IMG_WELCOME_ANIM_6_BASEID              (18)
#define GFX_IMG_WELCOME_ANIM_7_BASEID              (19)
#define GFX_IMG_WELCOME_ANIM_8_BASEID              (20)
#define GFX_IMG_WELCOME_ANIM_9_BASEID              (21)
#define GFX_IMG_WELCOME_ANIM_10_BASEID             (22)
#define GFX_IMG_WELCOME_ANIM_11_BASEID             (23)
#define GFX_IMG_WELCOME_ANIM_12_BASEID             (24)
#define GFX_IMG_WELCOME_ANIM_13_BASEID             (25)
#define GFX_IMG_WELCOME_ANIM_14_BASEID             (26)
#define GFX_IMG_WELCOME_ANIM_15_BASEID             (27)
#define GFX_IMG_WELCOME_ANIM_16_BASEID             (28)
#define GFX_IMG_WELCOME_ANIM_17_BASEID             (29)
#define GFX_IMG_WELCOME_ANIM_18_BASEID             (30)
#define GFX_IMG_WELCOME_ANIM_19_BASEID             (31)
#define GFX_IMG_WELCOME_ANIM_20_BASEID             (32)
#define GFX_IMG_WELCOME_ANIM_21_BASEID             (33)
#define GFX_IMG_POUP_BG_0_BASEID                   (34)
#define GFX_IMG_FORD_LOGO_BASEID                   (35)
#define GFX_NEW_IMAGES_1_BASEID                    (36)
#define GFX_IMG_ROOT_CLIP_BASEID                   (37)
#define GFX_IMG_CHILD_CLIP_BASEID                  (38)
#define GFX_IMG_ROOT_CLIP_0_BASEID                 (39)
#define GFX_IMG_CHILD_CLIP_0_BASEID                (40)
#define GFX_IMG_POPUP_LINE_BASEID                  (41)
#define GFX_IMG_NISSAN_BG_BASEID                   (42)
#define GFX_IMG_NISSAN_1_BASEID                    (43)
#define GFX_IMG_NISSAN_2_BASEID                    (44)
#define GFX_IMG_TACHOMETER_BASEID                  (45)
#define GFX_IMG_OVG_OVG_BASEID                     (46)
#define GFX_IMG_TUNER_SCALE_OVG_BASEID             (47)
#define GFX_IMG_TUNE_ARROW_OVG_BASEID              (48)
#define GFX_IMG_TEST3_DCU_SWR_BASEID               (49)
#define GFX_IMG_SWR_SWR_BASEID                     (50)
#define GFX_IMG_TEST3_DCU_OVG_BASEID               (51)
#define GFX_IMG_COMPASS_OVG_BASEID                 (52)
#define GFX_IMG_COMPASS_ROTATE_N_OVG_BASEID        (53)
#define GFX_IMG_COMPASS_ROTATE_NW_OVG_BASEID       (54)
#define GFX_IMG_COMPASS_ROTATE_W_OVG_BASEID        (55)
#define GFX_IMG_COMPASS_ROTATE_SW_OVG_BASEID       (56)
#define GFX_IMG_COMPASS_ROTATE_S_OVG_BASEID        (57)
#define GFX_IMG_COMPASS_ROTATE_SE_OVG_BASEID       (58)
#define GFX_IMG_COMPASS_ROTATE_E_OVG_BASEID        (59)
#define GFX_IMG_COMPASS_ROTATE_NE_OVG_BASEID       (60)
#define GFX_NEW_IMAGES_98_OVG_BASEID               (61)
#define GFX_IMG_SVG_TEST_OVG_BASEID                (62)
#define GFX_IMG_SVG_TEST_0_OVG_BASEID              (63)
#define GFX_FILL_EOL_BLACK_IMG_BASEID              (64)
#define GFX_FILL_NORMAL_ALL_IMG_BASEID             (65)
#define GFX_NEW_FILL_SCREENS_9_IMG_BASEID          (66)
#define GFX_NEW_FILL_SCREENS_11_IMG_BASEID         (67)
#define GFX_NEW_FILL_SCREENS_13_IMG_BASEID         (68)
#define GFX_WDG_HEADER_TXT_IMG_BASEID              (69)
#define GFX_WDT_FOOTER_TXT_IMG_BASEID              (70)
#define GFX_WDT_FOOTERICONS_0_IMG_BASEID           (71)
#define GFX_WDG_TACHO_BG_IMG_BASEID                (72)
#define GFX_WDG_DCU_DEFAULT_IMG_BASEID             (73)
#define GFX_WDG_DCU_CHILD_IMG_BASEID               (74)
#define GFX_WDG_OK_TOUCH_IMG_BASEID                (75)
#define GFX_WDG_ROOT_CLIP_IMG_BASEID               (76)
#define GFX_WDG_CHILD_CLIP_IMG_BASEID              (77)
#define GFX_WDG_ROOT_NO_CLIP_IMG_BASEID            (78)
#define GFX_WDG_ROOT_NO_CLIP1_IMG_BASEID           (GFX_WDG_ROOT_NO_CLIP_IMG_BASEID)
#define GFX_WDG_CHILD_CLIP1_IMG_BASEID             (79)
#define GFX_WDG_ROOT_NO_CLIP1_0_IMG_BASEID         (GFX_WDG_ROOT_NO_CLIP_IMG_BASEID)
#define GFX_WDG_CHILD_CLIP2_IMG_BASEID             (80)
#define GFX_WDG_ROOR_TEXT_CLIP_IMG_BASEID          (81)
#define GFX_P42_CLIP_ISSUE_IMG_BASEID              (82)
#define GFX_WDG_POPUP_IMG_BASEID                   (83)
#define GFX_WDG_NISSAN_1_IMG_BASEID                (84)
#define GFX_WDG_NISSAN_CLIP1_IMG_BASEID            (85)
#define GFX_WDG_NISSAN_CLIP2_IMG_BASEID            (86)
#define GFX_WDG_MULTI_COLOR_IMG_BASEID             (87)
#define GFX_NEW_WIDGETS_44_IMG_BASEID              (GFX_WDG_MULTI_COLOR_IMG_BASEID)
#define GFX_WDG_DCU_OPENVG_IMG_BASEID              (88)
#define GFX_WDG_ROOT_OVG_IMG_BASEID                (89)
#define GFX_WDG_VG_FONT_IMG_BASEID                 (90)
#define GFX_WDG_ARABIC_FONT_TEST_IMG_BASEID        (91)
#define GFX_WDG_COMPASS_IMG_BASEID                 (92)
#define GFX_WDG_DYN_FB_TEST_0_IMG_BASEID           (93)
#define GFX_WDG_GUAGES_IMG_BASEID                  (0)
#define GFX_WDG_DYN_FB_TEST_IMG_BASEID             (1)
#define GFX_IMG_USER_NANIM_BASEID                  (0)
#define GFX_IMG_USER_ANIM_BASEID                   (1)
#define GFX_TXT_ROOT_CLIP_BASEID                   (0)
#define GFX_TXT_ROOT_CLIPA_BASEID                  (1)
#define GFX_TXT_ROOT_CLIP_0_BASEID                 (2)
#define GFX_TXT_FONT_TEST3_BASEID                  (3)
#define GFX_TXT_FONT_TEST4_BASEID                  (4)
#define GFX_TEXT_MCOLOR1_BASEID                    (5)
#define GFX_TXT_OVG_BASEID                         (6)
#define GFX_TXT_SVG_FONT_BASEID                    (7)
#define GFX_TXT_FONT_TEST5_BASEID                  (8)
#define GFX_TXT_FONT_TEST6_BASEID                  (9)
#define GFX_TXT_DCU_BASEID                         (10)
#define GFX_TXT_WRN_INFO_LINE1_BASEID              (11)
#define GFX_TXT_FONT_TEST2_BASEID                  (12)
#define GFX_TXT_TIME_BASEID                        (13)
#define GFX_TXT_TIME_FORMAT_BASEID                 (14)
#define GFX_TXT_TEMP_BASEID                        (15)
#define GFX_TXT_TEMP_FORMAT_BASEID                 (16)
#define GFX_TXT_DTE_VALUE_BASEID                   (17)
#define GFX_TXT_TRIP_BASEID                        (18)
#define GFX_TXT_ODO_VALUE_UNIT_BASEID              (19)
#define GFX_TRIP_FUEL_USED_ICON_BASEID             (20)
#define GFX_TEXT_MCOLOR2_BASEID                    (21)
#define GFX_TXT_WRN_INFO_LINE1_0_BASEID            (22)
#define GFX_TXT_OVG2_BASEID                        (23)
#define GFX_TXT_SWR_BASEID                         (24)
#define GFX_TXT_OVG1_BASEID                        (25)
#define GFX_TXT_VG_FONT_T1_BASEID                  (26)
#define GFX_TXT_VG_FONT_T1_0_BASEID                (27)
#define GFX_TXT_OVG1_0_BASEID                      (28)
#define GFX_IMG_G274_LB_BASEID                     (0)
#define GFX_IMG_G274_LT_BASEID                     (1)
#define GFX_IMG_G274_RB_BASEID                     (2)
#define GFX_IMG_G274_RT_BASEID                     (3)
#define GFX_IMG_G274_C12_T_BASEID                  (4)
#define GFX_IMG_G274_C12_B_BASEID                  (5)
#define GFX_IMG_G274_C12_L_BASEID                  (6)
#define GFX_IMG_G274_C12_R_BASEID                  (7)
#define GFX_IMG_TEST1_OVG_ANIM_BASEID              (8)
#define GFX_IMG_OVG_OFFSET_ISSUE_BASEID            (9)
#define GFX_IMG_OVG_OFFSET_ISSUE_0_BASEID          (10)
#define GFX_IMG_OVG_OFFSET_ISSUE_0_0_BASEID        (11)
#define GFX_NEW_IMAGES_99_BASEID                   (12)
#define GFX_IMG_TACHOMETER_POINTER_BASEID          (13)
#define GFX_FILL_EOL_BLACK_BASEID                  (0)
#define GFX_FILL_NORMAL_ALL_BASEID                 (1)
#define GFX_NEW_FILL_SCREENS_9_BASEID              (2)
#define GFX_NEW_FILL_SCREENS_11_BASEID             (3)
#define GFX_NEW_FILL_SCREENS_13_BASEID             (4)
#define GFX_INVALID_BASEID                         (0)
#define GFX_FILL_OVG_BASEID                        (5)
#define GFX_FILL_POPUP_MIDDLE_C12_BASEID           (6)
#define GFX_FILL_SWR_BASEID                        (7)
#define GFX_NEW_FILL_SCREENS_1_BASEID              (8)
#define GFX_FILL_TILE_ALL_BASEID                   (0)
#define GFX_WDG_HEADER_TXT_BASEID                  (0)
#define GFX_WDT_FOOTER_TXT_BASEID                  (1)
#define GFX_WDT_FOOTERICONS_0_BASEID               (2)
#define GFX_WDG_TACHO_BG_BASEID                    (3)
#define GFX_WDG_DCU_DEFAULT_BASEID                 (4)
#define GFX_INVALID_WDG_IMAGE_BASEID               (0)
#define GFX_WDG_DCU_KEEP_LAYER_BASEID              (5)
#define GFX_WDG_DCU_CHILD_BASEID                   (6)
#define GFX_WDG_OK_TOUCH_BASEID                    (7)
#define GFX_WDG_ROOT_CLIP_BASEID                   (8)
#define GFX_WDG_CHILD_CLIP_BASEID                  (9)
#define GFX_WDG_ROOT_NO_CLIP_BASEID                (10)
#define GFX_WDG_ROOT_NO_CLIP1_BASEID               (11)
#define GFX_WDG_CHILD_CLIP1_BASEID                 (12)
#define GFX_WDG_ROOT_NO_CLIP1_0_BASEID             (13)
#define GFX_WDG_CHILD_CLIP2_BASEID                 (14)
#define GFX_WDG_ROOR_TEXT_CLIP_BASEID              (15)
#define GFX_P42_CLIP_ISSUE_BASEID                  (16)
#define GFX_WDG_POPUP_BASEID                       (17)
#define GFX_WDG_NISSAN_1_BASEID                    (18)
#define GFX_WDG_NISSAN_CLIP1_BASEID                (19)
#define GFX_WDG_NISSAN_CLIP2_BASEID                (20)
#define GFX_WDG_MULTI_COLOR_BASEID                 (21)
#define GFX_NEW_WIDGETS_44_BASEID                  (22)
#define GFX_WDG_OVG_BASEID                         (23)
#define GFX_WDG_C12_BG_BASEID                      (24)
#define GFX_WDG_DCU_SWR_BASEID                     (25)
#define GFX_WDG_GUAGES_BASEID                      (26)
#define GFX_WDG_DCU_OPENVG_BASEID                  (27)
#define GFX_WDG_ROOT_OVG_BASEID                    (28)
#define GFX_WDG_CHILD_OVG_BASEID                   (29)
#define GFX_WDG_VG_FONT_BASEID                     (30)
#define GFX_WDG_ARABIC_FONT_TEST_BASEID            (31)
#define GFX_WDG_COMPASS_BASEID                     (32)
#define GFX_WDG_COMPASS_ROTATE_LP2_BASEID          (33)
#define GFX_WDG_COMPASS_ROTATE_LP1_BASEID          (34)
#define GFX_WDG_COMPASS_ROTATE_M_BASEID            (35)
#define GFX_WDG_COMPASS_ROTATE_RP1_BASEID          (36)
#define GFX_WDG_COMPASS_ROTATE_RP2_BASEID          (37)
#define GFX_WDG_DYN_FB_TEST_BASEID                 (38)
#define GFX_WDG_DYN_FB_TEST_0_BASEID               (39)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS              (8)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS              (94)
#define GFX_MGR02_NUM_USER_LAYERS                  (2)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS       (2)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS               (29)

#define GFX_MGR02_NUM_OF_SVGS                      (14)

#define GFX_MGR02_NUM_OF_SVG_CLIPS                 (3)
#define GFX_MGR02_NUM_OF_FILLS                     (9)
#define GFX_MGR02_NUM_OF_TILES                     (1)
#define GFX_MGR02_DYNAMIC_CLIPPED_WIDGETS
#define GFX_MGR02_STATIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS                     (40)


/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (480)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (800)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_IMG_USER_ANIM_ANIM                             = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_USER_LAYER|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_ODO_ICON_ANIM                              = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_TRIP_ICON_ANIM                             = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_HEADER_SCR1_1_ANIM                         = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_MIDDLE_SCR1_1_ANIM                         = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_MIDDLE_SCR1_2_ANIM                         = GFX_MGR02_SET_OBJ(4,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_MIDDLE_SCR1_3_ANIM                         = GFX_MGR02_SET_OBJ(5,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_HEADER_SNOW_FLAKE_P2_ANIM                  = GFX_MGR02_SET_OBJ(6,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_TEST1_ANIM_DCU_ANIM                        = GFX_MGR02_SET_OBJ(7,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_GAUGE_BG_ANIM                              = GFX_MGR02_SET_OBJ(8,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_ROOT_CLIP_0_ANIM                           = GFX_MGR02_SET_OBJ(9,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_CHILD_CLIP_0_ANIM                          = GFX_MGR02_SET_OBJ(10,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_TACHOMETER_ANIM                            = GFX_MGR02_SET_OBJ(11,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_TUNE_ARROW_ANIM                            = GFX_MGR02_SET_OBJ(12,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_COMPASS_ANIM                               = GFX_MGR02_SET_OBJ(13,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_SVG_TEST_ANIM                              = GFX_MGR02_SET_OBJ(14,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_SVG_TEST_0_ANIM                            = GFX_MGR02_SET_OBJ(15,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_FILL_EOL_BLACK_ANIM                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_FILL_NORMAL_ALL_ANIM                           = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_TACHOMETER_POINTER_ANIM                    = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SVG|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_FILL_TILE_ALL_ANIM                             = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_TILE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_WRN_INFO_LINE1_ANIM                        = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_TIME_ANIM                                  = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_TIME_FORMAT_ANIM                           = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_TEMP_ANIM                                  = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_TEMP_FORMAT_ANIM                           = GFX_MGR02_SET_OBJ(4,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_DTE_VALUE_ANIM                             = GFX_MGR02_SET_OBJ(5,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_TRIP_ANIM                                  = GFX_MGR02_SET_OBJ(6,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_ODO_VALUE_UNIT_ANIM                        = GFX_MGR02_SET_OBJ(7,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TRIP_FUEL_USED_ICON_ANIM                       = GFX_MGR02_SET_OBJ(8,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_WRN_INFO_LINE1_0_ANIM                      = GFX_MGR02_SET_OBJ(9,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_ROOT_CLIP_ANIM                             = GFX_MGR02_SET_OBJ(10,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_ROOT_CLIPA_ANIM                            = GFX_MGR02_SET_OBJ(11,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_SWR_ANIM                                   = GFX_MGR02_SET_OBJ(12,GFX_MGR02_PLATFORM_SWR|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_OVG1_ANIM                                  = GFX_MGR02_SET_OBJ(13,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_VG_FONT_T1_ANIM                            = GFX_MGR02_SET_OBJ(14,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_VG_FONT_T1_0_ANIM                          = GFX_MGR02_SET_OBJ(15,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_OVG1_0_ANIM                                = GFX_MGR02_SET_OBJ(16,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_HEADER_TXT_ANIM                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDT_FOOTER_TXT_ANIM                            = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDT_FOOTERICONS_0_ANIM                         = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_CHILD_CLIP2_ANIM                           = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_POPUP_ANIM                                 = GFX_MGR02_SET_OBJ(4,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_NISSAN_CLIP1_ANIM                          = GFX_MGR02_SET_OBJ(5,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_NISSAN_CLIP2_ANIM                          = GFX_MGR02_SET_OBJ(6,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_OVG_ANIM                                   = GFX_MGR02_SET_OBJ(7,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_GUAGES_ANIM                                = GFX_MGR02_SET_OBJ(8,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_ROOT_OVG_ANIM                              = GFX_MGR02_SET_OBJ(9,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_CHILD_OVG_ANIM                             = GFX_MGR02_SET_OBJ(10,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_COMPASS_ROTATE_LP2_ANIM                    = GFX_MGR02_SET_OBJ(11,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_COMPASS_ROTATE_LP1_ANIM                    = GFX_MGR02_SET_OBJ(12,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_COMPASS_ROTATE_M_ANIM                      = GFX_MGR02_SET_OBJ(13,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_COMPASS_ROTATE_RP1_ANIM                    = GFX_MGR02_SET_OBJ(14,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_COMPASS_ROTATE_RP2_ANIM                    = GFX_MGR02_SET_OBJ(15,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_DYN_FB_TEST_ANIM                           = GFX_MGR02_SET_OBJ(16,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_DYN_FB_TEST_0_ANIM                         = GFX_MGR02_SET_OBJ(17,GFX_MGR02_PLATFORM_OVG|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_SCR_DCU1_ANIM                                  = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SCR_MAL_ANIM_ANIM                              = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SCR_NISSAN_TEST_ANIM                           = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SCR_TACHOMETER_ANIM                            = GFX_MGR02_SET_OBJ(3,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_DIMG_TELTALES2_SCR1_ANIM                       = GFX_MGR02_SET_OBJ(4,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_DIMG_HEADER_SNOW_FLAKE_P2_ANIM                 = GFX_MGR02_SET_OBJ(5,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_DIMG_ANIM_DCU_ANIM                             = GFX_MGR02_SET_OBJ(6,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_DIMG_ANIM_TEST_1_ANIM                          = GFX_MGR02_SET_OBJ(7,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS          (16)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS           (1)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS            (1)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS           (2)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS           (1)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS           (17)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS         (18)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS          (8)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS         (4)

extern UINT32 const lc_nfill_color_FF000000_CLUT[1];
extern UINT32 const lc_nfill_color_FFFFFFFF_CLUT[1];
extern UINT32 const lc_nfill_color_FFFFE0C0_CLUT[1];
extern UINT32 const lc_nfill_color_FF0000FF_CLUT[1];
#define GFX_MGR02_STEXTS_BUFFER_SIZE (240)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_TXT_ROOT_CLIP,
   GFX_TXT_ROOT_CLIPA,
   GFX_TXT_ROOT_CLIP_0,
   GFX_TXT_FONT_TEST3,
   GFX_TXT_FONT_TEST4,
   GFX_TEXT_MCOLOR1,
   GFX_TXT_OVG,
   GFX_TXT_SVG_FONT,
   GFX_TXT_FONT_TEST5,
   GFX_TXT_FONT_TEST6,
   __GFX_MGR02_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (10)
#define GFX_MGR02_NUM_OF_STEXTS      (19)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (230)
#define GFX_MGR02_MULTI_COLOR_WDG_PRESENT
/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   GFX_DWDG_DCU                                       = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET)
  ,GFX_DWDG_CHILD_CLIP                                = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DWIDGET)
  ,GFX_NEW_WIDGETS_43                                 = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_DWIDGET)
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS              (3)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_DIMG_TELTALES2_SCR1                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_HEADER_SNOW_FLAKE_P2                      = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_1_DCU                                     = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_ANIM_DCU                                  = GFX_MGR02_SET_OBJ(3,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_ANIM_TEST_1                               = GFX_MGR02_SET_OBJ(4,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_2_DCU                                     = GFX_MGR02_SET_OBJ(5,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_WELCOME                                   = GFX_MGR02_SET_OBJ(6,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_1_DCU_0                                   = GFX_MGR02_SET_OBJ(7,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_COMPASS_ROTATE_LP2                        = GFX_MGR02_SET_OBJ(8,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_COMPASS_ROTATE_LP1                        = GFX_MGR02_SET_OBJ(9,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_COMPASS_ROTATE_M                          = GFX_MGR02_SET_OBJ(10,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_COMPASS_ROTATE_RP1                        = GFX_MGR02_SET_OBJ(11,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_COMPASS_ROTATE_RP2                        = GFX_MGR02_SET_OBJ(12,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES               (13)

#define GFX_IMG_TEST1_DCU_4                           GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_TEST1_DCU_5                           GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_DCU_1                                 GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_DCU_DEFAULT_1                         GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_TEST3_DCU_0_1                         GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_DCU_CHILD_1                           GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_TEST1_DCU_3                           GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_DCU_KEEP_LAYER_1                      GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_DCU_2                                 GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_TEST1_DCU_2                           GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_TEST1_DCU_1                           GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_USER_NANIM_1                          GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_USER_LAYER|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_3_1                      GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_4_1                      GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_5_1                      GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_6_1                      GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_7_1                      GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_8_1                      GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_9_1                      GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_10_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_11_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_12_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_13_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_14_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_15_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_16_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_17_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_18_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_19_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_20_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_21_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_WELCOME_ANIM_22_1                     GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_FORD_LOGO_1                           GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_NEW_IMAGES_1_1                            GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_DCU_OPENVG_1                          GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_TEST3_DCU_2                           GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_ROOT_CLIP_1                           GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_ROOT_CLIP_1                           GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_CHILD_CLIP_1                          GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_CHILD_CLIP_1                          GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_ROOT_NO_CLIP_1                        GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_ROOT_CLIP_2                           GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_CHILD_CLIP_2                          GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_POUP_BG_1                             GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_OK_TOUCH_1                            GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_POUP_BG_0_1                           GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_USER_NANIM_2                          GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_USER_LAYER|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_ROOT_NO_CLIP1_1                       GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_CHILD_CLIP_3                          GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_ROOT_NO_CLIP1_0_1                     GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_ROOT_CLIP_3                           GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_CHILD_CLIP1_2                         GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_ROOR_TEXT_CLIP_1                      GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_FILL_OVG_2                                GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_OVG_OFFSET_ISSUE_0_1                  GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_OVG_OFFSET_ISSUE_0_0_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_ROOT_CLIP_0_2                         GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_OVG_OFFSET_ISSUE_1                    GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_SVG_FONT_1                            GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_ROOT_CLIP_0_1                         GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_VG_FONT_1                             GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_OVG)
#define GFX_FILL_OVG_3                                GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_FORD_LOGO_2                           GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_P42_CLIP_ISSUE_1                          GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_TEST1_DCU_6                           GFX_MGR02_SET_OBJ(20 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_ROOR_TEXT_CLIP_2                      GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_CHILD_CLIP1_1                         GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_FONT_TEST3_1                          GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_FONT_TEST4_1                          GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_ARABIC_FONT_TEST_1                    GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_OVG)
#define GFX_NEW_FILL_SCREENS_1_1                      GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_FONT_TEST5_1                          GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_FONT_TEST6_1                          GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_FONT_TEST2_2                          GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_TXT_FONT_TEST2_1                          GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_POPUP_LINE_1                          GFX_MGR02_SET_OBJ(21 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_COMPASS_1                             GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_OVG)
#define GFX_NEW_IMAGES_98_1                           GFX_MGR02_SET_OBJ(22 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_NEW_IMAGES_99_1                           GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_N_1                    GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NW_1                   GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_W_1                    GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SW_1                   GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_S_1                    GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SE_1                   GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_E_1                    GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NE_1                   GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_N_2                    GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NW_2                   GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_W_2                    GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SW_2                   GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_S_2                    GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SE_2                   GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_E_2                    GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NE_2                   GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_N_3                    GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NW_3                   GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_W_3                    GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SW_3                   GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_S_3                    GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SE_3                   GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_E_3                    GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NE_3                   GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_N_4                    GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NW_4                   GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_W_4                    GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SW_4                   GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_S_4                    GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SE_4                   GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_E_4                    GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NE_4                   GFX_MGR02_SET_OBJ(26 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_N_5                    GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NW_5                   GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_W_5                    GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SW_5                   GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_S_5                    GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_SE_5                   GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_E_5                    GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_COMPASS_ROTATE_NE_5                   GFX_MGR02_SET_OBJ(27 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_NEW_FILL_SCREENS_9_1                      GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_DCU)
#define GFX_NEW_FILL_SCREENS_11_1                     GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_NISSAN_1_1                            GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_NISSAN_BG_1                           GFX_MGR02_SET_OBJ(28 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_NISSAN_1_1                            GFX_MGR02_SET_OBJ(29 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_NISSAN_2_1                            GFX_MGR02_SET_OBJ(30 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_TACHO_BG_1                            GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_DTE_ICON_1                            GFX_MGR02_SET_OBJ(31 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_NEW_FILL_SCREENS_13_1                     GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_DCU)
#define GFX_WDG_MULTI_COLOR_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_NEW_WIDGETS_44_1                          GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_DCU)
#define GFX_TEXT_MCOLOR1_1                            GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_TEXT_MCOLOR2_1                            GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_DCU)
#define GFX_FILL_OVG_1                                GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_OVG)
#define GFX_TXT_OVG_1                                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_OVG)
#define GFX_TXT_OVG2_1                                GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_TEST1_OVG_ANIM_1                      GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_WDG_C12_BG_1                              GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_LB_1                             GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_LT_1                             GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_RB_1                             GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_RT_1                             GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_C12_T_1                          GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_C12_B_1                          GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_C12_L_1                          GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_G274_C12_R_1                          GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_OVG)
#define GFX_FILL_POPUP_MIDDLE_C12_1                   GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_TUNER_SCALE_1                         GFX_MGR02_SET_OBJ(32 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_OVG)
#define GFX_IMG_OVG_1                                 GFX_MGR02_SET_OBJ(33 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_OVG)
#define GFX_FILL_SWR_1                                GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_SWR_1                                 GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_WDG_DCU_SWR_1                             GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_TEST3_DCU_1                           GFX_MGR02_SET_OBJ(34 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES             (35)
#define GFX_MGR02_NUM_SVG_INSTANCES                (13)
#define GFX_MGR02_NUM_FILL_INSTANCES               (4)
#define GFX_MGR02_NUM_TILE_INSTANCES               (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES               (18)
#define GFX_MGR02_NUM_TEXT_INSTANCES               (15)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_DCU1                                       = (0)
  ,GFX_SCR_DCU_STARTUP                                = (1)
  ,GFX_SCR_DCU_BASE                                   = (2)
  ,GFX_SCR_DCU_POPUP                                  = (3)
  ,GFX_SCR_USER_LAYER                                 = (4)
  ,GFX_SCR_CLIP_WIDGETS                               = (5)
  ,GFX_SCR_VG_FONT_TEST                               = (6)
  ,GFX_SCR_MAL_ANIM                                   = (7)
  ,GFX_SCR_FONT_TEST                                  = (8)
  ,GFX_SCR_DYN_DATA_ANIM                              = (9)
  ,GFX_SCR_POPUP                                      = (10)
  ,GFX_SCR_TEST                                       = (11)
  ,GFX_SCR_NISSAN_TEST                                = (12)
  ,GFX_SCR_TACHOMETER                                 = (13)
  ,GFX_SCR_MULTI_COLOR                                = (14)
  ,GFX_SCR_OVG                                        = (15)
  ,GFX_SCR_SWR                                        = (16)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS                      (17)
#define GFX_MGR02_LAYER0_DAR_SIZE                     (30)
#define GFX_MGR02_LAYER1_DAR_SIZE                     (16)
#define GFX_MGR02_LAYER2_DAR_SIZE                     (4)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (2)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX               (30)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_DCU1_BG_COLOR                               (0xFF000000)
#define GFX_SCR_DCU_STARTUP_BG_COLOR                        (0xFF000000)
#define GFX_SCR_DCU_BASE_BG_COLOR                           (0xFF000000)
#define GFX_SCR_DCU_POPUP_BG_COLOR                          (0xFF000000)
#define GFX_SCR_USER_LAYER_BG_COLOR                         (0xFF000000)
#define GFX_SCR_CLIP_WIDGETS_BG_COLOR                       (0xFF000000)
#define GFX_SCR_VG_FONT_TEST_BG_COLOR                       (0xFF000000)
#define GFX_SCR_MAL_ANIM_BG_COLOR                           (0xFF000000)
#define GFX_SCR_FONT_TEST_BG_COLOR                          (0xFF000000)
#define GFX_SCR_DYN_DATA_ANIM_BG_COLOR                      (0xFF000000)
#define GFX_SCR_POPUP_BG_COLOR                              (0xFFE0E0E0)
#define GFX_SCR_TEST_BG_COLOR                               (0xFF000000)
#define GFX_SCR_NISSAN_TEST_BG_COLOR                        (0xFF000000)
#define GFX_SCR_TACHOMETER_BG_COLOR                         (0xFF000000)
#define GFX_SCR_MULTI_COLOR_BG_COLOR                        (0xFF000000)
#define GFX_SCR_OVG_BG_COLOR                                (0xFF000000)
#define GFX_SCR_SWR_BG_COLOR                                (0xFF000000)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (3)
#define GFX_MGR02_NUM_PRIORITY            (2)
#define GFX_MGR02_UNICODE              (0)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (1)
#define GFX_MGR02_MAX_TEXT_LENGTH         (30)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (23)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (23)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_ARGB8888)
#define GFX_MGR02_NEWPROJECT
#define GFX_MGR02_KEPLER
#define GFX_MGR02_OPEN_VG
#define GFX_MGR02_SOFWTARE
#define GFX_MGR02_COMPRESSION_ENABLED

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        3/3/2014     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
