/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_clut_table.h
**                                                                            
** Description:    This file contains the CLUT header autogenerated by        
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 3/3/2014
**                                                                            
**                 See the <Kepler Software Architecture document> in         
**                 ClearCase in <sw_architecture\driver_information\        
**                 platforms\kepler\05_product\design> for more details    
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CLUT_TABLE_H
#define HMI_GFX_MGR02_CLUT_TABLE_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#include "hmi_gfx_mgr02_clut_table.cfg"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** CLUT table ID's.
*/
#define GFX_CLUT_FOOTER_NEW_CLUT                             (0)
#define GFX_IMG_ODO_ICON_CLUT                                (GFX_CLUT_FOOTER_NEW_CLUT)
#define GFX_IMG_TRIP_ICON_CLUT                               ( GFX_IMG_ODO_ICON_CLUT)
#define GFX_IMG_DTE_ICON_CLUT                                ( GFX_IMG_ODO_ICON_CLUT)
#define GFX_TELTALE_CLUT_CLUT                                (1)
#define GFX_IMG_HEADER_SCR1_1_CLUT                           (GFX_TELTALE_CLUT_CLUT)
#define GFX_IMG_MIDDLE_SCR1_1_CLUT                           ( GFX_IMG_HEADER_SCR1_1_CLUT)
#define GFX_IMG_MIDDLE_SCR1_2_CLUT                           ( GFX_IMG_HEADER_SCR1_1_CLUT)
#define GFX_IMG_MIDDLE_SCR1_3_CLUT                           ( GFX_IMG_HEADER_SCR1_1_CLUT)
#define GFX_CLUT_HEADER_CLUT                                 (2)
#define GFX_IMG_HEADER_SNOW_FLAKE_P2_CLUT                    (GFX_CLUT_HEADER_CLUT)
#define GFX_DCU_DEF_CLUT                                     (3)
#define GFX_IMG_TEST1_DCU_CLUT                               (GFX_DCU_DEF_CLUT)
#define GFX_IMG_TEST3_DCU_0_CLUT                             ( GFX_IMG_TEST1_DCU_CLUT)
#define GFX_WELCOME_CLUT_CLUT                                (4)
#define GFX_IMG_WELCOME_ANIM_22_CLUT                         (GFX_WELCOME_CLUT_CLUT)
#define GFX_IMG_GAUGE_BG_CLUT                                (5)
#define GFX_IMG_POUP_BG_CLUT                                 (6)
#define GFX_IMG_WELCOME_ANIM_3_CLUT                          ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_4_CLUT                          ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_5_CLUT                          ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_6_CLUT                          ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_7_CLUT                          ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_8_CLUT                          ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_9_CLUT                          ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_10_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_11_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_12_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_13_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_14_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_15_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_16_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_17_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_18_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_19_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_20_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_WELCOME_ANIM_21_CLUT                         ( GFX_IMG_WELCOME_ANIM_22_CLUT)
#define GFX_IMG_POUP_BG_0_CLUT                               (7)
#define GFX_IMG_FORD_LOGO_CLUT                               (8)
#define GFX_NEW_IMAGES_1_CLUT                                (9)
#define GFX_WDG_PP_CLUT                                      (10)
#define GFX_IMG_POPUP_LINE_CLUT                              (GFX_WDG_PP_CLUT)
#define GFX_IMG_NISSAN_BG_CLUT                               (11)
#define GFX_IMG_NISSAN_1_CLUT                                (12)
#define GFX_IMG_NISSAN_2_CLUT                                (13)
#define GFX_WDT_FOOTERICONS_0_CLUT                           ( GFX_IMG_ODO_ICON_CLUT)
#define GFX_WDG_DCU_DEFAULT_CLUT                             ( GFX_IMG_TEST1_DCU_CLUT)
#define GFX_WDG_DCU_CHILD_CLUT                               ( GFX_IMG_TEST1_DCU_CLUT)
#define GFX_WDG_OK_TOUCH_CLUT                                ( GFX_IMG_POUP_BG_0_CLUT)
#define GFX_P42_CLIP_ISSUE_CLUT                              ( GFX_IMG_TEST1_DCU_CLUT)
#define GFX_WDG_POPUP_CLUT                                   ( GFX_IMG_POPUP_LINE_CLUT)
#define GFX_WDG_NISSAN_1_CLUT                                ( GFX_IMG_NISSAN_BG_CLUT)
#define GFX_WDG_NISSAN_CLIP1_CLUT                            ( GFX_IMG_NISSAN_1_CLUT)
#define GFX_WDG_NISSAN_CLIP2_CLUT                            ( GFX_IMG_NISSAN_2_CLUT)
#define GFX_FILL_EOL_BLACK_CLUT                              (14)
#define GFX_FILL_NORMAL_ALL_CLUT                             (15)
#define GFX_NEW_FILL_SCREENS_9_CLUT                          (16)
#define GFX_NEW_FILL_SCREENS_11_CLUT                         (GFX_FILL_NORMAL_ALL_CLUT)
#define GFX_NEW_FILL_SCREENS_13_CLUT                         (17)
#define GFX_MGR02_NUM_OF_CLUTS                               (18+ GFX_MGR02_PROD_SPEC_CLUT_TABLE_NUM)

/*
** CLUT table size.
*/
#define GFX_CLUT_FOOTER_NEW_CLUT_SIZE                        (45)
#define GFX_IMG_ODO_ICON_CLUT_SIZE                           (45)
#define GFX_IMG_TRIP_ICON_CLUT_SIZE                          ( GFX_IMG_ODO_ICON_CLUT_SIZE)
#define GFX_IMG_DTE_ICON_CLUT_SIZE                           ( GFX_IMG_ODO_ICON_CLUT_SIZE)
#define GFX_TELTALE_CLUT_CLUT_SIZE                           (223)
#define GFX_IMG_HEADER_SCR1_1_CLUT_SIZE                      (223)
#define GFX_IMG_MIDDLE_SCR1_1_CLUT_SIZE                      ( GFX_IMG_HEADER_SCR1_1_CLUT_SIZE)
#define GFX_IMG_MIDDLE_SCR1_2_CLUT_SIZE                      ( GFX_IMG_HEADER_SCR1_1_CLUT_SIZE)
#define GFX_IMG_MIDDLE_SCR1_3_CLUT_SIZE                      ( GFX_IMG_HEADER_SCR1_1_CLUT_SIZE)
#define GFX_CLUT_HEADER_CLUT_SIZE                            (55)
#define GFX_IMG_HEADER_SNOW_FLAKE_P2_CLUT_SIZE               (55)
#define GFX_DCU_DEF_CLUT_SIZE                                (88)
#define GFX_IMG_TEST1_DCU_CLUT_SIZE                          (88)
#define GFX_IMG_TEST3_DCU_0_CLUT_SIZE                        ( GFX_IMG_TEST1_DCU_CLUT_SIZE)
#define GFX_WELCOME_CLUT_CLUT_SIZE                           (256)
#define GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE                    (256)
#define GFX_IMG_GAUGE_BG_CLUT_SIZE                           (19)
#define GFX_IMG_POUP_BG_CLUT_SIZE                            (190)
#define GFX_IMG_WELCOME_ANIM_3_CLUT_SIZE                     ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_4_CLUT_SIZE                     ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_5_CLUT_SIZE                     ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_6_CLUT_SIZE                     ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_7_CLUT_SIZE                     ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_8_CLUT_SIZE                     ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_9_CLUT_SIZE                     ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_10_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_11_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_12_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_13_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_14_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_15_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_16_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_17_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_18_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_19_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_20_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_WELCOME_ANIM_21_CLUT_SIZE                    ( GFX_IMG_WELCOME_ANIM_22_CLUT_SIZE)
#define GFX_IMG_POUP_BG_0_CLUT_SIZE                          (106)
#define GFX_IMG_FORD_LOGO_CLUT_SIZE                          (255)
#define GFX_NEW_IMAGES_1_CLUT_SIZE                           (223)
#define GFX_WDG_PP_CLUT_SIZE                                 (33)
#define GFX_IMG_POPUP_LINE_CLUT_SIZE                         (33)
#define GFX_IMG_NISSAN_BG_CLUT_SIZE                          (44)
#define GFX_IMG_NISSAN_1_CLUT_SIZE                           (66)
#define GFX_IMG_NISSAN_2_CLUT_SIZE                           (102)
#define GFX_WDT_FOOTERICONS_0_CLUT_SIZE                      ( GFX_IMG_ODO_ICON_CLUT_SIZE)
#define GFX_WDG_DCU_DEFAULT_CLUT_SIZE                        ( GFX_IMG_TEST1_DCU_CLUT_SIZE)
#define GFX_WDG_DCU_CHILD_CLUT_SIZE                          ( GFX_IMG_TEST1_DCU_CLUT_SIZE)
#define GFX_WDG_OK_TOUCH_CLUT_SIZE                           ( GFX_IMG_POUP_BG_0_CLUT_SIZE)
#define GFX_P42_CLIP_ISSUE_CLUT_SIZE                         ( GFX_IMG_TEST1_DCU_CLUT_SIZE)
#define GFX_WDG_POPUP_CLUT_SIZE                              ( GFX_IMG_POPUP_LINE_CLUT_SIZE)
#define GFX_WDG_NISSAN_1_CLUT_SIZE                           ( GFX_IMG_NISSAN_BG_CLUT_SIZE)
#define GFX_WDG_NISSAN_CLIP1_CLUT_SIZE                       ( GFX_IMG_NISSAN_1_CLUT_SIZE)
#define GFX_WDG_NISSAN_CLIP2_CLUT_SIZE                       ( GFX_IMG_NISSAN_2_CLUT_SIZE)
#define GFX_FILL_EOL_BLACK_CLUT_SIZE                         (1)
#define GFX_FILL_NORMAL_ALL_CLUT_SIZE                        (1)
#define GFX_NEW_FILL_SCREENS_9_CLUT_SIZE                     (1)
#define GFX_NEW_FILL_SCREENS_11_CLUT_SIZE                    (1)
#define GFX_NEW_FILL_SCREENS_13_CLUT_SIZE                    (1)

/*
** externs for all the palette's generated.
*/
extern UINT32 const CLUT_FOOTER_NEW_clut[45];
/* img_trip_icon Palette Optimized with img_odo_icon_clut */
/* img_dte_icon Palette Optimized with img_odo_icon_clut */
extern UINT32 const teltale_clut_clut[223];
/* img_middle_scr1_1 Palette Optimized with img_header_scr1_1_clut */
/* img_middle_scr1_2 Palette Optimized with img_header_scr1_1_clut */
/* img_middle_scr1_3 Palette Optimized with img_header_scr1_1_clut */
extern UINT32 const CLUT_HEADER_clut[55];
extern UINT32 const dcu_def_clut[88];
/* img_test3_dcu_0 Palette Optimized with img_test1_dcu_clut */
extern UINT32 const welcome_clut_clut[256];
extern UINT32 const img_gauge_bg_clut[19];
extern UINT32 const img_poup_bg_clut[190];
/* img_welcome_anim_3 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_4 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_5 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_6 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_7 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_8 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_9 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_10 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_11 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_12 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_13 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_14 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_15 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_16 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_17 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_18 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_19 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_20 Palette Optimized with img_welcome_anim_22_clut */
/* img_welcome_anim_21 Palette Optimized with img_welcome_anim_22_clut */
extern UINT32 const img_poup_bg_0_clut[106];
extern UINT32 const img_ford_logo_clut[255];
extern UINT32 const New_images_1_clut[223];
extern UINT32 const wdg_pp_clut[33];
extern UINT32 const img_nissan_bg_clut[44];
extern UINT32 const img_nissan_1_clut[66];
extern UINT32 const img_nissan_2_clut[102];
/* wdt_footericons_0 Palette Optimized with img_odo_icon_clut */
/* wdg_dcu_default Palette Optimized with img_test1_dcu_clut */
/* wdg_dcu_child Palette Optimized with img_test1_dcu_clut */
/* wdg_ok_touch Palette Optimized with img_poup_bg_0_clut */
/* p42_clip_issue Palette Optimized with img_test1_dcu_clut */
/* wdg_popup Palette Optimized with img_popup_line_clut */
/* wdg_nissan_1 Palette Optimized with img_nissan_bg_clut */
/* wdg_nissan_clip1 Palette Optimized with img_nissan_1_clut */
/* wdg_nissan_clip2 Palette Optimized with img_nissan_2_clut */

#if GFX_MGR02_NUM_OF_CLUTS > 0
  extern GFX_MGR02_CLUT_DATA const lc_gfx_mgr02_clut_array[GFX_MGR02_NUM_OF_CLUTS];
#endif

/*
** mapping for Palette data which is repeating
*/
#define img_odo_icon_clut                                    (CLUT_FOOTER_NEW_clut)
#define img_trip_icon_clut                                   (img_odo_icon_clut)
#define img_dte_icon_clut                                    (img_odo_icon_clut)
#define img_header_scr1_1_clut                               (teltale_clut_clut)
#define img_middle_scr1_1_clut                               (img_header_scr1_1_clut)
#define img_middle_scr1_2_clut                               (img_header_scr1_1_clut)
#define img_middle_scr1_3_clut                               (img_header_scr1_1_clut)
#define img_header_snow_flake_p2_clut                        (CLUT_HEADER_clut)
#define img_test1_dcu_clut                                   (dcu_def_clut)
#define img_test3_dcu_0_clut                                 (img_test1_dcu_clut)
#define img_welcome_anim_22_clut                             (welcome_clut_clut)
#define img_welcome_anim_3_clut                              (img_welcome_anim_22_clut)
#define img_welcome_anim_4_clut                              (img_welcome_anim_22_clut)
#define img_welcome_anim_5_clut                              (img_welcome_anim_22_clut)
#define img_welcome_anim_6_clut                              (img_welcome_anim_22_clut)
#define img_welcome_anim_7_clut                              (img_welcome_anim_22_clut)
#define img_welcome_anim_8_clut                              (img_welcome_anim_22_clut)
#define img_welcome_anim_9_clut                              (img_welcome_anim_22_clut)
#define img_welcome_anim_10_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_11_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_12_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_13_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_14_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_15_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_16_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_17_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_18_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_19_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_20_clut                             (img_welcome_anim_22_clut)
#define img_welcome_anim_21_clut                             (img_welcome_anim_22_clut)
#define img_popup_line_clut                                  (wdg_pp_clut)
#define wdt_footericons_0_clut                               (img_odo_icon_clut)
#define wdg_dcu_default_clut                                 (img_test1_dcu_clut)
#define wdg_dcu_child_clut                                   (img_test1_dcu_clut)
#define wdg_ok_touch_clut                                    (img_poup_bg_0_clut)
#define p42_clip_issue_clut                                  (img_test1_dcu_clut)
#define wdg_popup_clut                                       (img_popup_line_clut)
#define wdg_nissan_1_clut                                    (img_nissan_bg_clut)
#define wdg_nissan_clip1_clut                                (img_nissan_1_clut)
#define wdg_nissan_clip2_clut                                (img_nissan_2_clut)


/*
** CLUT Index definitions for the widget background color
*/
#define GFX_WDT_FOOTERICONS_0_BG_COLOR_INDEX                (0x10101010)
#define GFX_WDG_DCU_DEFAULT_BG_COLOR_INDEX                  (0x00000000)
#define GFX_WDG_DCU_CHILD_BG_COLOR_INDEX                    (0x00000000)
#define GFX_WDG_OK_TOUCH_BG_COLOR_INDEX                     (0x63636363)
#define GFX_P42_CLIP_ISSUE_BG_COLOR_INDEX                   (0x00000000)
#define GFX_WDG_POPUP_BG_COLOR_INDEX                        (0x00000000)
#define GFX_WDG_NISSAN_1_BG_COLOR_INDEX                     (0x00000000)
#define GFX_WDG_NISSAN_CLIP1_BG_COLOR_INDEX                 (0x00000000)
#define GFX_WDG_NISSAN_CLIP2_BG_COLOR_INDEX                 (0x00000000)
/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_CLUT_TABLE_H */
