/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2022. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 9/21/2022
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_IMG_CIRCLE_IMXRT_BASEID (0)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS          (0U)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS (1)
#define GFX_MGR02_NUM_3D_MDL_LAYERS (0)
#define GFX_MGR02_NUM_USER_LAYERS   (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS (0)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS (0)

#define GFX_MGR02_NUM_OF_SVGS       (0)

#define GFX_MGR02_NUM_OF_SVG_CLIPS  (0)
#define GFX_MGR02_NUM_OF_FILLS      (0)
#define GFX_MGR02_NUM_OF_TILES      (0)
#define GFX_MGR02_NUM_VIDEO_LAYERS  (0)
#define GFX_MGR02_NUM_OF_SWDGS      (0)

#define GFX_MGR02_NUM_VISIBLE_AREA      (1U)

/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (200)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (400)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_IMG_CIRCLE_ANIM                 = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_SCR_SAMPLE_ANIM                 = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS (1)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS (1)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS (1)

#define GFX_MGR02_STEXTS_BUFFER_SIZE (0)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (0)
#define GFX_MGR02_NUM_OF_STEXTS      (0)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (0)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (0)
#define GFX_MGR02_MAX_PATH_CMD_BUF_LENGTH   (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   __GFX_EMPTY_LIST_DWDG
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS (0)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   __GFX_EMPTY_LIST_DIMG
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES (0)

#define GFX_MGR02_NUM_SIMAGE_INSTANCES (0)
#define GFX_MGR02_NUM_SVG_INSTANCES (0)
#define GFX_MGR02_NUM_FILL_INSTANCES (0)
#define GFX_MGR02_NUM_TILE_INSTANCES (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES (0)
#define GFX_MGR02_NUM_TEXT_INSTANCES (0)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_SAMPLE                      = (0)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS       (1)
#define GFX_MGR02_LAYER0_DAR_SIZE      (1)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (1)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX   (1)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_SAMPLE_BG_COLOR                             (0x000000FF)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x00000000)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (6)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1U)
#define GFX_MGR02_NUM_PRIORITY            (1)
#define GFX_MGR02_UNICODE              (1)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (0)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (0)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (0)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_RGB888)
#define GFX_MGR02_IMXRT_TEST
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (1)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_IMXRT
#define GFX_MGR02_RENDER_NONE

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        9/21/2022     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
