/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in 2009. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_anim_engine_cfg.h                                    
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated by GDT . Do not handmodify this file. 
                    Generated on MM/DD/YYYY - 10/11/2023
Organization     :  DI/Audio Software Section,                                 
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#ifndef HMI_GFX_ANIM_ENGINE_CFG_H
#define HMI_GFX_ANIM_ENGINE_CFG_H
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/
                                                                               
#define GFX_OPEN_ANIM_FRAME1                      (0)
#define GFX_OPEN_ANIM_NUM_FRAMES                  (1)

#define GFX_NEW_ANIMATIONS_1_FRAME1               (0)
#define GFX_NEW_ANIMATIONS_1_NUM_FRAMES           (1)


enum
{
    GFX_OPEN_ANIM
   ,GFX_NEW_ANIMATIONS_1
   ,GFX_TOTAL_NUM_ANIMATIONS
};
#define GFX_NUM_ANIMATIONS                        (2)
#define GFX_NUM_LINEAR_ANIMATIONS                 (1)
#define GFX_BASE_ANIM_RATE_MSEC                   (167)
#define GFX_ANIM_GOTO_COUNT_ARRAY_SIZE            (0)

#define GFX_BASE_ANIM_RATE_SCALE                  (10)

/***************************************************************************** 
*                              File Scope Prototypes                         * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                   Functions                                                * 
******************************************************************************/

                                                                               
/*End of File*/                                                                
/***************************************************************************** 
*   for each change to this file, be sure to record:                         * 
*      1.  who made the change and when the change was made                  * 
*      2.  why the change was made and the intended result                   * 
*   Following block needs to be repeated for each change                       
****************************************************************************** 
*   Note: In the traceability column we need to trace back to the Design Doc.* 
*   For the initial version it is traced to the Design Document section.     * 
*   For further changes it shall trace to the source of the change which may * 
*   be SPSS/SCR/Defect details(Defect may be Testing/validation defect)/Any  * 
*   other reason                                                            *  
******************************************************************************/
#endif
