/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_image_data.h
**                                                                            
** Description:    This file contains the image data autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 10/11/2023
**                 Total Image ROM size = [1398601 bytes]   
**                 Total RLE Savings    = [0 bytes]
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_IMAGE_DATA_H
#define HMI_GFX_MGR02_IMAGE_DATA_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** externs for all the image tables generated.
*/
extern UINT8 const lc_img_opening_anim_0_mon_data[39200];
extern UINT8 const lc_img_opening_anim_1_mon_data[39200];
extern UINT8 const lc_img_opening_anim_2_mon_data[39200];
extern UINT8 const lc_img_opening_anim_3_mon_data[39200];
extern UINT8 const lc_img_opening_anim_4_mon_data[39200];
extern UINT8 const lc_img_opening_anim_5_mon_data[39200];
extern UINT8 const lc_img_opening_anim_6_mon_data[39200];
extern UINT8 const lc_img_opening_anim_7_mon_data[39200];
extern UINT8 const lc_img_opening_anim_8_mon_data[39200];
extern UINT8 const lc_img_opening_anim_9_mon_data[39200];
extern UINT8 const lc_img_opening_anim_10_mon_data[39200];
extern UINT8 const lc_img_opening_anim_11_mon_data[39200];
extern UINT8 const lc_img_opening_anim_12_mon_data[39200];
extern UINT8 const lc_img_opening_anim_13_mon_data[39200];
extern UINT8 const lc_img_opening_anim_14_mon_data[39200];
extern UINT8 const lc_img_opening_anim_15_mon_data[39200];
extern UINT8 const lc_img_opening_anim_16_mon_data[39200];
extern UINT8 const lc_img_opening_anim_17_mon_data[39200];
extern UINT8 const lc_img_opening_anim_18_mon_data[39200];
extern UINT8 const lc_img_opening_anim_19_mon_data[39200];
extern UINT8 const lc_img_opening_anim_20_mon_data[39200];
extern UINT8 const lc_img_opening_anim_21_mon_data[39200];
extern UINT8 const lc_img_opening_anim_22_mon_data[39200];
extern UINT8 const lc_img_opening_anim_23_mon_data[39200];
extern UINT8 const lc_img_opening_anim_24_mon_data[19520];
extern UINT8 const lc_img_info_popup_border_mon_data[40584];
extern UINT8 const lc_img_info_popup1_mon_data[1200];
extern UINT8 const lc_img_ack_popup_border_mon_data[40584];
extern UINT8 const lc_img_ack_popup1_mon_data[2100];
extern UINT8 const lc_img_hardwrng_border_mon_data[75000];
extern UINT8 const lc_img_hardwrng1_mon_data[3040];
extern UINT8 const lc_img_softwrng_border_mon_data[75000];
extern UINT8 const lc_img_infowrng1_mon_data[2728];
extern UINT8 const lc_img_infowrng_border_mon_data[75000];
extern UINT8 const lc_img_softwrng1_mon_data[2048];
extern UINT8 const lc_img_hardwng_1_mon_data[8190];
extern UINT8 const lc_img_progress1_mon_data[2400];
extern UINT8 const lc_img_progress2_mon_data[2400];
extern UINT8 const lc_img_progress3_mon_data[2400];
extern UINT8 const lc_img_progress4_mon_data[2400];
extern UINT8 const lc_img_progress5_mon_data[2400];
extern UINT8 const lc_img_progress6_mon_data[2400];
extern UINT8 const lc_img_progress7_mon_data[2400];
extern UINT8 const lc_img_progress8_mon_data[2400];
extern UINT8 const lc_img_progress9_mon_data[2400];
extern UINT8 const lc_img_progress10_mon_data[2400];
extern UINT8 const lc_img_progress11_mon_data[2400];
extern UINT8 const lc_img_progress12_mon_data[2400];
extern UINT8 const lc_img_progress13_mon_data[2400];
extern UINT8 const lc_img_progress14_mon_data[2400];
extern UINT8 const lc_img_progress15_mon_data[2400];
extern UINT8 const lc_img_progress16_mon_data[2400];
extern UINT8 const lc_img_progress17_mon_data[2400];
extern UINT8 const lc_img_progress18_mon_data[2400];
extern UINT8 const lc_img_progress19_mon_data[2400];
extern UINT8 const lc_img_progress20_mon_data[2400];
extern UINT8 const lc_img_progress21_mon_data[2400];
extern UINT8 const lc_img_progress22_mon_data[2400];
extern UINT8 const lc_img_progress23_mon_data[2400];
extern UINT8 const lc_img_menu_media_mon_data[851];
extern UINT8 const lc_img_menu_bg_mon_data[46512];
extern UINT8 const lc_img_menu_focus_mon_data[10244];

/*
** mapping for image data which is repeating
*/
#define lc_img_menu_phone_data                               (lc_img_menu_media_mon_data)
#define lc_img_menu_settings_data                            (lc_img_menu_media_mon_data)
#define lc_img_menu_arrow_data                               (lc_img_menu_media_mon_data)
#define lc_new_images_148_data                               (lc_img_opening_anim_24_mon_data)

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_IMAGE_DATA_H */
