/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2023. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 10/11/2023
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_IMG_OPENING_ANIM_0_MON_BASEID        (0)
#define GFX_IMG_OPENING_ANIM_1_MON_BASEID        (1)
#define GFX_IMG_OPENING_ANIM_2_MON_BASEID        (2)
#define GFX_IMG_OPENING_ANIM_3_MON_BASEID        (3)
#define GFX_IMG_OPENING_ANIM_4_MON_BASEID        (4)
#define GFX_IMG_OPENING_ANIM_5_MON_BASEID        (5)
#define GFX_IMG_OPENING_ANIM_6_MON_BASEID        (6)
#define GFX_IMG_OPENING_ANIM_7_MON_BASEID        (7)
#define GFX_IMG_OPENING_ANIM_8_MON_BASEID        (8)
#define GFX_IMG_OPENING_ANIM_9_MON_BASEID        (9)
#define GFX_IMG_OPENING_ANIM_10_MON_BASEID       (10)
#define GFX_IMG_OPENING_ANIM_11_MON_BASEID       (11)
#define GFX_IMG_OPENING_ANIM_12_MON_BASEID       (12)
#define GFX_IMG_OPENING_ANIM_13_MON_BASEID       (13)
#define GFX_IMG_OPENING_ANIM_14_MON_BASEID       (14)
#define GFX_IMG_OPENING_ANIM_15_MON_BASEID       (15)
#define GFX_IMG_OPENING_ANIM_16_MON_BASEID       (16)
#define GFX_IMG_OPENING_ANIM_17_MON_BASEID       (17)
#define GFX_IMG_OPENING_ANIM_18_MON_BASEID       (18)
#define GFX_IMG_OPENING_ANIM_19_MON_BASEID       (19)
#define GFX_IMG_OPENING_ANIM_20_MON_BASEID       (20)
#define GFX_IMG_OPENING_ANIM_21_MON_BASEID       (21)
#define GFX_IMG_OPENING_ANIM_22_MON_BASEID       (22)
#define GFX_IMG_OPENING_ANIM_23_MON_BASEID       (23)
#define GFX_IMG_OPENING_ANIM_24_MON_BASEID       (24)
#define GFX_IMG_INFO_POPUP_BORDER_MON_BASEID     (25)
#define GFX_IMG_INFO_POPUP1_MON_BASEID           (26)
#define GFX_IMG_ACK_POPUP_BORDER_MON_BASEID      (27)
#define GFX_IMG_ACK_POPUP1_MON_BASEID            (28)
#define GFX_IMG_HARDWRNG_BORDER_MON_BASEID       (29)
#define GFX_IMG_HARDWRNG1_MON_BASEID             (30)
#define GFX_IMG_SOFTWRNG_BORDER_MON_BASEID       (31)
#define GFX_IMG_INFOWRNG1_MON_BASEID             (32)
#define GFX_IMG_INFOWRNG_BORDER_MON_BASEID       (33)
#define GFX_IMG_SOFTWRNG1_MON_BASEID             (34)
#define GFX_IMG_HARDWNG_1_MON_BASEID             (35)
#define GFX_IMG_PROGRESS1_MON_BASEID             (36)
#define GFX_IMG_PROGRESS2_MON_BASEID             (37)
#define GFX_IMG_PROGRESS3_MON_BASEID             (38)
#define GFX_IMG_PROGRESS4_MON_BASEID             (39)
#define GFX_IMG_PROGRESS5_MON_BASEID             (40)
#define GFX_IMG_PROGRESS6_MON_BASEID             (41)
#define GFX_IMG_PROGRESS7_MON_BASEID             (42)
#define GFX_IMG_PROGRESS8_MON_BASEID             (43)
#define GFX_IMG_PROGRESS9_MON_BASEID             (44)
#define GFX_IMG_PROGRESS10_MON_BASEID            (45)
#define GFX_IMG_PROGRESS11_MON_BASEID            (46)
#define GFX_IMG_PROGRESS12_MON_BASEID            (47)
#define GFX_IMG_PROGRESS13_MON_BASEID            (48)
#define GFX_IMG_PROGRESS14_MON_BASEID            (49)
#define GFX_IMG_PROGRESS15_MON_BASEID            (50)
#define GFX_IMG_PROGRESS16_MON_BASEID            (51)
#define GFX_IMG_PROGRESS17_MON_BASEID            (52)
#define GFX_IMG_PROGRESS18_MON_BASEID            (53)
#define GFX_IMG_PROGRESS19_MON_BASEID            (54)
#define GFX_IMG_PROGRESS20_MON_BASEID            (55)
#define GFX_IMG_PROGRESS21_MON_BASEID            (56)
#define GFX_IMG_PROGRESS22_MON_BASEID            (57)
#define GFX_IMG_PROGRESS23_MON_BASEID            (58)
#define GFX_IMG_MENU_MEDIA_MON_BASEID            (59)
#define GFX_IMG_MENU_PHONE_MON_BASEID            (60)
#define GFX_IMG_MENU_SETTINGS_MON_BASEID         (61)
#define GFX_IMG_MENU_ARROW_MON_BASEID            (62)
#define GFX_IMG_MENU_BG_MON_BASEID               (63)
#define GFX_IMG_MENU_FOCUS_MON_BASEID            (64)
#define GFX_NEW_IMAGES_148_MON_BASEID            (65)
#define GFX_TXT_INFO_POPUP_BASEID                (0)
#define GFX_TXT_ACK_POPUP_BASEID                 (1)
#define GFX_TXT_HARDWRNG_BASEID                  (2)
#define GFX_TXT_SOFTWRNG_BASEID                  (3)
#define GFX_TXT_INFOWRNG_BASEID                  (4)
#define GFX_TXT_KEYPAD_TEXT_BASEID               (5)
#define GFX_TXT_PROGRESS_BASEID                  (6)
#define GFX_TXT_KEYPAD_ENTRY_BASEID              (7)
#define GFX_TXT_MENU_TIME_BASEID                 (8)
#define GFX_TXT_MENU_HEADER_BASEID               (9)
#define GFX_TXT_MENU_VC_C1_BASEID                (10)
#define GFX_TXT_MENU_VC_C2_BASEID                (11)
#define GFX_TXT_MENU_VC_C3_BASEID                (12)
#define GFX_TXT_MENU_VC_C4_BASEID                (13)
#define GFX_TXT_MENU_VC_C5_BASEID                (14)
#define GFX_TXT_MENU_VC_C6_BASEID                (15)
#define GFX_TXT_INFO_POPUP_0_1_BASEID            (16)
#define GFX_TXT_INFO_POPUP_0_1_0_0_BASEID        (17)
#define GFX_TXT_KEYPAD_POPUP_BASEID              (18)
#define GFX_TXT_PROGRESS_POPUP_BASEID            (19)
#define GFX_TXT_ACK_HEADER_BASEID                (20)
#define GFX_TXT_INFO_HEADER_BASEID               (21)
#define GFX_TXT_INFO_POPUP_0_1_0_BASEID          (22)
#define GFX_INVALID_BASEID                       (0)
#define GFX_FILL_KEYPAD_BASEID                   (0)
#define GFX_FILL_BG_BLUE_BASEID                  (1)
#define GFX_FILL_M08N_2_TITLE_CLEAR_BASEID       (2)
#define GFX_NEW_FILL_SCREENS_9_BASEID            (3)
#define GFX_INVALID_WDG_IMAGE_BASEID             (0)
#define GFX_WDG_INFO_POPUP_BASEID                (0)
#define GFX_WDG_ACK_POPUP_BASEID                 (1)
#define GFX_WDG_KEYPAD_POPUP_BASEID              (2)
#define GFX_WDG_PROGRESS_POPUP_BASEID            (3)
#define GFX_WDG_HARD1_BASEID                     (4)
#define GFX_WDG_SOFT1_BASEID                     (5)
#define GFX_WDG_INFO1_BASEID                     (6)
#define GFX_WDG_MENU_HEADER_BASEID               (7)
#define GFX_WDG_MENU_BASEID                      (8)
#define GFX_NEW_WIDGETS_13_BASEID                (9)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS            (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS          (0U)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS            (66)
#define GFX_MGR02_NUM_3D_MDL_LAYERS              (0)
#define GFX_MGR02_NUM_USER_LAYERS                (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS     (0)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS             (23)

#define GFX_MGR02_NUM_OF_SVGS                    (0)

#define GFX_MGR02_NUM_OF_SVG_CLIPS               (0)
#define GFX_MGR02_NUM_OF_FILLS                   (4)
#define GFX_MGR02_NUM_OF_TILES                   (0)
#define GFX_MGR02_NUM_VIDEO_LAYERS               (0)
#define GFX_MGR02_STATIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS                   (10)

#define GFX_MGR02_NUM_VISIBLE_AREA      (11U)

/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (800)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (480)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_IMG_OPENING_ANIM_24_ANIM                     = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_MENU_FOCUS_ANIM                          = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_FILL_BG_BLUE_ANIM                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_MENU_VC_C1_ANIM                          = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_MENU_VC_C2_ANIM                          = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_MENU_VC_C3_ANIM                          = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_MENU_VC_C4_ANIM                          = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_MENU_VC_C5_ANIM                          = GFX_MGR02_SET_OBJ(4,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_MENU_VC_C6_ANIM                          = GFX_MGR02_SET_OBJ(5,GFX_MGR02_PLATFORM_MON|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_IMG_VC_MENU_G1_ANIM                          = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_VC_MENU_G2_ANIM                          = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_VC_MENU_G3_ANIM                          = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_VC_MENU_G4_ANIM                          = GFX_MGR02_SET_OBJ(3,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_VC_MENU_G5_ANIM                          = GFX_MGR02_SET_OBJ(4,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_VC_MENU_G6_ANIM                          = GFX_MGR02_SET_OBJ(5,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS        (2)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS           (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS         (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS          (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS         (1)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS         (0)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS         (6)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS       (0)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS        (6)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS       (0)

#define GFX_MGR02_STEXTS_BUFFER_SIZE (56)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_TXT_INFO_POPUP,
   GFX_TXT_ACK_POPUP,
   GFX_TXT_HARDWRNG,
   GFX_TXT_SOFTWRNG,
   GFX_TXT_INFOWRNG,
   GFX_TXT_KEYPAD_TEXT,
   GFX_TXT_PROGRESS,
   GFX_TXT_KEYPAD_ENTRY,
   GFX_TXT_MENU_TIME,
   GFX_TXT_MENU_HEADER,
   GFX_TXT_MENU_VC_C1,
   GFX_TXT_MENU_VC_C2,
   GFX_TXT_MENU_VC_C3,
   GFX_TXT_MENU_VC_C4,
   GFX_TXT_MENU_VC_C5,
   GFX_TXT_MENU_VC_C6,
   GFX_TXT_INFO_POPUP_0_1,
   GFX_TXT_INFO_POPUP_0_1_0_0,
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (18)
#define GFX_MGR02_NUM_OF_STEXTS      (5)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (622)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (0)
#define GFX_MGR02_MAX_PATH_CMD_BUF_LENGTH   (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   GFX_DWDG_WRNG                                    = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET)
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS            (1)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_DIMG_OPEN_ANIM                               = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_PROGRESS                                = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_VC_MENU_G1                               = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_VC_MENU_G2                               = GFX_MGR02_SET_OBJ(3,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_VC_MENU_G3                               = GFX_MGR02_SET_OBJ(4,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_VC_MENU_G4                               = GFX_MGR02_SET_OBJ(5,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_VC_MENU_G5                               = GFX_MGR02_SET_OBJ(6,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_VC_MENU_G6                               = GFX_MGR02_SET_OBJ(7,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_ARROW_MENU_A1                            = GFX_MGR02_SET_OBJ(8,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_ARROW_MENU_A2                            = GFX_MGR02_SET_OBJ(9,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_ARROW_MENU_A3                            = GFX_MGR02_SET_OBJ(10,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_ARROW_MENU_A4                            = GFX_MGR02_SET_OBJ(11,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_ARROW_MENU_A5                            = GFX_MGR02_SET_OBJ(12,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_IMG_ARROW_MENU_A6                            = GFX_MGR02_SET_OBJ(13,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES             (14)

#define GFX_NEW_FILL_SCREENS_9_1                    GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_MON)
#define GFX_NEW_WIDGETS_13_1                        GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_NEW_IMAGES_148_1                        GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_INFO_POPUP_0_1_0_2                  GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_0_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_1_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_2_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_3_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_4_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_5_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_6_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_7_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_8_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_9_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_10_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_11_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_12_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_13_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_14_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_15_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_16_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_17_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_18_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_19_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_20_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_21_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_22_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_OPENING_ANIM_23_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_INFO_POPUP_0_1_1                    GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_INFO_POPUP_1                        GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_INFO_POPUP_BORDER_2                 GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_INFO_POPUP_1                        GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_INFO_POPUP1_1                       GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_INFO_HEADER_1                       GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_HARD1_1                             GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_HARDWRNG_BORDER_1                   GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_HARDWRNG_1                          GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_HARDWRNG1_1                         GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_HARDWNG_1_1                         GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_SOFT1_1                             GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_SOFTWRNG_BORDER_1                   GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_SOFTWRNG_1                          GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_SOFTWRNG1_1                         GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_INFO1_1                             GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_INFOWRNG_BORDER_1                   GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_INFOWRNG1_1                         GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_INFOWRNG_1                          GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_ACK_POPUP_1                         GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_ACK_POPUP_BORDER_1                  GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_ACK_POPUP1_1                        GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_ACK_POPUP_1                         GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_ACK_HEADER_1                        GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_KEYPAD_POPUP_1                      GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_INFO_POPUP_BORDER_3                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_KEYPAD_POPUP_1                      GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_KEYPAD_TEXT_1                       GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_FILL_KEYPAD_1                           GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_KEYPAD_ENTRY_1                      GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_INFO_POPUP_BORDER_1                 GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_PROGRESS_1                          GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_PROGRESS_POPUP_1                    GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_PROGRESS_POPUP_1                    GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS1_1                         GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS2_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS3_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS4_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS5_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS6_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS7_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS8_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS9_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS10_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS11_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS12_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS13_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS14_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS15_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS16_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS17_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS18_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS19_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS20_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS21_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS22_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_PROGRESS23_1                        GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_BG_1                           GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_MENU_1                              GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_MEDIA_1                        GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_PHONE_1                        GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_SETTINGS_1                     GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_MEDIA_2                        GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_PHONE_2                        GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_SETTINGS_2                     GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_MEDIA_3                        GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_PHONE_3                        GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_SETTINGS_3                     GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_MEDIA_4                        GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_PHONE_4                        GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_SETTINGS_4                     GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_MEDIA_5                        GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_PHONE_5                        GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_SETTINGS_5                     GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_MEDIA_6                        GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_PHONE_6                        GFX_MGR02_SET_OBJ(18 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_SETTINGS_6                     GFX_MGR02_SET_OBJ(19 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_ARROW_1                        GFX_MGR02_SET_OBJ(20 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_ARROW_2                        GFX_MGR02_SET_OBJ(21 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_ARROW_3                        GFX_MGR02_SET_OBJ(22 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_ARROW_4                        GFX_MGR02_SET_OBJ(23 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_ARROW_5                        GFX_MGR02_SET_OBJ(24 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_IMG_MENU_ARROW_6                        GFX_MGR02_SET_OBJ(25 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_MON)
#define GFX_WDG_MENU_HEADER_1                       GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_MON)
#define GFX_FILL_M08N_2_TITLE_CLEAR_1               GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_MENU_HEADER_1                       GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_MENU_TIME_1                         GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_INFO_POPUP_0_1_0_1                  GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_STEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_TXT_INFO_POPUP_0_1_0_0_1                GFX_MGR02_SET_OBJ(17 ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_MON)
#define GFX_NEW_FILL_SCREENS_9_2                    GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_MON)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES           (26)
#define GFX_MGR02_NUM_SVG_INSTANCES              (0)
#define GFX_MGR02_NUM_FILL_INSTANCES             (4)
#define GFX_MGR02_NUM_TILE_INSTANCES             (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES             (10)
#define GFX_MGR02_NUM_TEXT_INSTANCES             (18)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_STARTUP                                  = (0)
  ,GFX_SCR_OPENING_ANIM                             = (1)
  ,GFX_SCR_INFO_POPUP                               = (2)
  ,GFX_SCR_WARNING                                  = (3)
  ,GFX_SCR_ACK_POPUP                                = (4)
  ,GFX_SCR_KEYPAD_POPUP                             = (5)
  ,GFX_SCR_PROGRESS_POPUP                           = (6)
  ,GFX_SCR_MENU                                     = (7)
  ,GFX_NEW_SCREENS_1                                = (8)
  ,GFX_SCR_STARTUP_0                                = (9)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS                    (10)
#define GFX_MGR02_LAYER0_DAR_SIZE                   (55)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (1)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX             (55)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_STARTUP_BG_COLOR                            (0xFF000000UL)
#define GFX_SCR_OPENING_ANIM_BG_COLOR                       (0xFF000000UL)
#define GFX_SCR_INFO_POPUP_BG_COLOR                         (0xFF000000UL)
#define GFX_SCR_WARNING_BG_COLOR                            (0xFF000000UL)
#define GFX_SCR_ACK_POPUP_BG_COLOR                          (0xFF000000UL)
#define GFX_SCR_KEYPAD_POPUP_BG_COLOR                       (0xFF000000UL)
#define GFX_SCR_PROGRESS_POPUP_BG_COLOR                     (0xFF000000UL)
#define GFX_SCR_MENU_BG_COLOR                               (0xFF000000UL)
#define GFX_NEW_SCREENS_1_BG_COLOR                          (0xFF000000UL)
#define GFX_SCR_STARTUP_0_BG_COLOR                          (0xFF000000UL)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x00000000u)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (0)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1U)
#define GFX_MGR02_NUM_PRIORITY            (7)
#define GFX_MGR02_UNICODE              (1)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (100)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (0)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (0)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_4BPP)
#define GFX_MGR02_NEWPROJECT
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (2)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_MONOTFT
#define GFX_MGR02_HOR_PACKING     (0)
#define GFX_MGR02_BIT_ORDER_LSB_FIRST     (1)
#define GFX_MGR02_RENDER_NONE
#define GFX_MGR02_CLIP_TEXT_ENABLE
#define GFX_MGR02_APPEND_CHAR          46
#define GFX_MGR02_APPEND_CHAR_CNT      (3)

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        10/11/2023     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
