[SystemStateConfiguration]
; ///@Domain ID, which is send by System state to :ScPwMgr for extend the shutdown time
DomainId=1
; ///@Periodicity of the broadcast message
PowerStateMessagePeriodicityMs=2000
; ///@Full Run Component Transition List
; ///SoundManager
;FullRunComponentTransitionList=1
ShutdownFinalTimeoutMs=250
