#ifndef gear_5_prns_unselected_d_selected_cold_img_e8_h
#define gear_5_prns_unselected_d_selected_cold_img_e8_h
namespace UX_SHMI_PLAYER
{
extern const uint8_t gear_5_prns_unselected_d_selected_cold_img_e8[14991];
}
#endif
