/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2013. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**============================================================================
**
** Name:           ux_shmi_uimain.h
**
** Description:    
**
** Organization:   UI Frameworks & Tools, Visteon
**
**============================================================================
**
**==========================================================================*/
#ifndef ux_shmi_uimain_h
#define ux_shmi_uimain_h

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "ux_safehmi_item.h"
#include "ux_safehmi_image.h"
#include "ux_safehmi_canvas.h"
#include "ux_safehmi_rectangle.h"


/*============================================================================
** I N T E R N A L   M A C R O   A N D   T Y P E   D E F I N I T I O N S
**==========================================================================*/

#define ui_main (UX_SHMI_PLAYER::root)
#define UX_SHMI_MAX_DESIGN_DEPTH (3)


namespace UX_SHMI_PLAYER
{
/*============================================================================
** I N T E R N A L   F U N C T I O N   P R O T O T Y P E S
**==========================================================================*/

enum class SHMI_ELEMENTS
{
	SHMI_WALLPAPER_REFERENCE,
	SHMI_GEAR_PRNDS_REGION_1,
	SHMI_GEAR_1_PRNDS_UNSELECTED_COLD,
	SHMI_GEAR_1_PRNDS_UNSELECTED_WARM,
	SHMI_GEAR_2_RNDS_UNSELECTED_P_SELECTED_COLD,
	SHMI_GEAR_2_RNDS_UNSELECTED_P_SELECTED_WARM,
	SHMI_GEAR_3_PNDS_UNSELECTED_R_SELECTED_COLD,
	SHMI_GEAR_3_PNDS_UNSELECTED_R_SELECTED_WARM,
	SHMI_GEAR_4_PRDS_UNSELECTED_N_SELECTED_COLD,
	SHMI_GEAR_4_PRDS_UNSELECTED_N_SELECTED_WARM,
	SHMI_GEAR_5_PRNS_UNSELECTED_D_SELECTED_COLD,
	SHMI_GEAR_5_PRNS_UNSELECTED_D_SELECTED_WARM,
	SHMI_GEAR_6_PRND_UNSELECTED_S_SELECTED_COLD,
	SHMI_GEAR_6_PRND_UNSELECTED_S_SELECTED_WARM,
	SHMI_GEAR_7_PRNDS_SELECTED_COLD,
	SHMI_GEAR_7_PRNDS_SELECTED_WARM,
	SHMI_GEAR_PRNDS_REGION_2,
	SHMI_GEAR_8_PRNDM_UNSELECTED_COLD,
	SHMI_GEAR_8_PRNDM_UNSELECTED_WARM,
	SHMI_GEAR_9_RNDM_UNSELECTED_P_SELECTED_COLD,
	SHMI_GEAR_9_RNDM_UNSELECTED_P_SELECTED_WARM,
	SHMI_GEAR_10_PNDM_UNSELECTED_R_SELECTED_COLD,
	SHMI_GEAR_10_PNDM_UNSELECTED_R_SELECTED_WARM,
	SHMI_GEAR_11_PRDM_UNSELECTED_N_SELECTED_COLD,
	SHMI_GEAR_11_PRDM_UNSELECTED_N_SELECTED_WARM,
	SHMI_GEAR_12_PRNM_UNSELECTED_D_SELECTED_COLD,
	SHMI_GEAR_12_PRNM_UNSELECTED_D_SELECTED_WARM,
	SHMI_GEAR_13_PRND_UNSELECTED_M_SELECTED_COLD,
	SHMI_GEAR_13_PRND_UNSELECTED_M_SELECTED_WARM,
	SHMI_GEAR_14_PRNDM_SELECTED_COLD,
	SHMI_GEAR_14_PRNDM_SELECTED_WARM,
	SHMI_GEAR_PRNDS_REGION_3,
	SHMI_GEAR_15_PRNDL_UNSELECTED_COLD,
	SHMI_GEAR_15_PRNDL_UNSELECTED_WARM,
	SHMI_GEAR_15_RNDL_UNSELECTED_P_SELECTED_COLD,
	SHMI_GEAR_16_RNDL_UNSELECTED_P_SELECTED_WARM,
	SHMI_GEAR_17_PNDL_UNSELECTED_R_SELECTED_COLD,
	SHMI_GEAR_17_PNDL_UNSELECTED_R_SELECTED_WARM,
	SHMI_GEAR_18_PRDL_UNSELECTED_N_SELECTED_COLD,
	SHMI_GEAR_18_PRDL_UNSELECTED_N_SELECTED_WARM,
	SHMI_GEAR_19_PRNL_UNSELECTED_D_SELECTED_COLD,
	SHMI_GEAR_19_PRNL_UNSELECTED_D_SELECTED_WARM,
	SHMI_GEAR_20_PRND_UNSELECTED_L_SELECTED_COLD,
	SHMI_GEAR_20_PRND_UNSELECTED_L_SELECTED_WARM,
	SHMI_GEAR_21_PRNDL_SELECTED_COLD,
	SHMI_GEAR_21_PRNDL_SELECTED_WARM,
	SHMI_EPB_REGION,
	SHMI_TELLTALE_EPB_ROW,
	SHMI_TELLTALE_EPB_USA,
	SHMI_TELLTALE_BRAKE_ROW,
	SHMI_TELLTALE_BRAKE_USA,
	SHMI_IMG_HAZARD_TT,
	SHMI_IMG_HIGHBEAM_TT,
	SHMI_IMG_LAMP_ICON,
	SHMI_IMG_LANEDEP_TT,
	SHMI_IMG_LOWBEAM_TT,
	SHMI_IMG_LTURN_TT,
	SHMI_TOTAL_ITEMS
};
extern int32_t GetItemX(const SHMI_ELEMENTS assetID);
extern int32_t GetItemY(const SHMI_ELEMENTS assetID);
extern bool GetItemVisibility(const SHMI_ELEMENTS assetID);
extern int32_t GetItemFlipbookIndex(const SHMI_ELEMENTS assetID);//Added for FTP. Not autogenerated
extern void SetItemVisibility(const SHMI_ELEMENTS assetID, const bool p_val);
extern void SetItemX(const SHMI_ELEMENTS assetID, const int32_t p_val);
extern void SetItemY(const SHMI_ELEMENTS assetID, const int32_t p_val);
extern void SetItemFlipbookIndex(const SHMI_ELEMENTS assetID, const int32_t p_val);



class Canvasroot : public ux_safehmi_canvas
{
public:
    Canvasroot(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren) :ux_safehmi_canvas(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren)
    {
       
       
    }
    
};

extern class Canvasroot root;
class Imagewallpaper_reference : public ux_safehmi_image
{
public:
    Imagewallpaper_reference(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Itemgear_PRNDS_region_1 : public ux_safehmi_item
{
public:
    Itemgear_PRNDS_region_1(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible, 
	          const uint32_t pcolor, const int32_t pchildcount, const ux_safehmi_item ** const pchildren, const sHMI_ObjType ptype) :ux_safehmi_item(px, py, pwidth, pheight, 
                                                             pvisible, pcolor, pchildcount, pchildren, ptype)
    {
       SetFlipbookIndex(0);
    }
    
};


class Imagegear_1_PRNDS_unselected_cold : public ux_safehmi_image
{
public:
    Imagegear_1_PRNDS_unselected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_1_PRNDS_unselected_warm : public ux_safehmi_image
{
public:
    Imagegear_1_PRNDS_unselected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_2_RNDS_unselected_P_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_2_RNDS_unselected_P_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_2_RNDS_unselected_P_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_2_RNDS_unselected_P_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_3_PNDS_unselected_R_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_3_PNDS_unselected_R_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_3_PNDS_unselected_R_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_3_PNDS_unselected_R_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_4_PRDS_unselected_N_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_4_PRDS_unselected_N_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_4_PRDS_unselected_N_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_4_PRDS_unselected_N_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_5_PRNS_unselected_D_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_5_PRNS_unselected_D_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_5_PRNS_unselected_D_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_5_PRNS_unselected_D_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_6_PRND_unselected_S_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_6_PRND_unselected_S_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_6_PRND_unselected_S_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_6_PRND_unselected_S_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_7_PRNDS_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_7_PRNDS_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_7_PRNDS_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_7_PRNDS_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Itemgear_PRNDS_region_2 : public ux_safehmi_item
{
public:
    Itemgear_PRNDS_region_2(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible, 
	          const uint32_t pcolor, const int32_t pchildcount, const ux_safehmi_item ** const pchildren, const sHMI_ObjType ptype) :ux_safehmi_item(px, py, pwidth, pheight, 
                                                             pvisible, pcolor, pchildcount, pchildren, ptype)
    {
       SetFlipbookIndex(0);
    }
    
};


class Imagegear_8_PRNDM_unselected_cold : public ux_safehmi_image
{
public:
    Imagegear_8_PRNDM_unselected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_8_PRNDM_unselected_warm : public ux_safehmi_image
{
public:
    Imagegear_8_PRNDM_unselected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_9_RNDM_unselected_P_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_9_RNDM_unselected_P_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_9_RNDM_unselected_P_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_9_RNDM_unselected_P_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_10_PNDM_unselected_R_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_10_PNDM_unselected_R_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_10_PNDM_unselected_R_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_10_PNDM_unselected_R_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_11_PRDM_unselected_N_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_11_PRDM_unselected_N_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_11_PRDM_unselected_N_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_11_PRDM_unselected_N_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_12_PRNM_unselected_D_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_12_PRNM_unselected_D_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_12_PRNM_unselected_D_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_12_PRNM_unselected_D_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_13_PRND_unselected_M_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_13_PRND_unselected_M_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_13_PRND_unselected_M_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_13_PRND_unselected_M_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_14_PRNDM_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_14_PRNDM_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_14_PRNDM_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_14_PRNDM_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Itemgear_PRNDS_region_3 : public ux_safehmi_item
{
public:
    Itemgear_PRNDS_region_3(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible, 
	          const uint32_t pcolor, const int32_t pchildcount, const ux_safehmi_item ** const pchildren, const sHMI_ObjType ptype) :ux_safehmi_item(px, py, pwidth, pheight, 
                                                             pvisible, pcolor, pchildcount, pchildren, ptype)
    {
       SetFlipbookIndex(0);
    }
    
};


class Imagegear_15_PRNDL_unselected_cold : public ux_safehmi_image
{
public:
    Imagegear_15_PRNDL_unselected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_15_PRNDL_unselected_warm : public ux_safehmi_image
{
public:
    Imagegear_15_PRNDL_unselected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_15_RNDL_unselected_P_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_15_RNDL_unselected_P_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_16_RNDL_unselected_P_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_16_RNDL_unselected_P_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_17_PNDL_unselected_R_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_17_PNDL_unselected_R_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_17_PNDL_unselected_R_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_17_PNDL_unselected_R_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_18_PRDL_unselected_N_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_18_PRDL_unselected_N_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_18_PRDL_unselected_N_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_18_PRDL_unselected_N_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_19_PRNL_unselected_D_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_19_PRNL_unselected_D_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_19_PRNL_unselected_D_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_19_PRNL_unselected_D_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_20_PRND_unselected_L_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_20_PRND_unselected_L_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_20_PRND_unselected_L_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_20_PRND_unselected_L_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_21_PRNDL_selected_cold : public ux_safehmi_image
{
public:
    Imagegear_21_PRNDL_selected_cold(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagegear_21_PRNDL_selected_warm : public ux_safehmi_image
{
public:
    Imagegear_21_PRNDL_selected_warm(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Itemepb_region : public ux_safehmi_item
{
public:
    Itemepb_region(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible, 
	          const uint32_t pcolor, const int32_t pchildcount, const ux_safehmi_item ** const pchildren, const sHMI_ObjType ptype) :ux_safehmi_item(px, py, pwidth, pheight, 
                                                             pvisible, pcolor, pchildcount, pchildren, ptype)
    {
       SetFlipbookIndex(0);
    }
    
};


class Imagetelltale_epb_row : public ux_safehmi_image
{
public:
    Imagetelltale_epb_row(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagetelltale_epb_usa : public ux_safehmi_image
{
public:
    Imagetelltale_epb_usa(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagetelltale_brake_row : public ux_safehmi_image
{
public:
    Imagetelltale_brake_row(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imagetelltale_brake_usa : public ux_safehmi_image
{
public:
    Imagetelltale_brake_usa(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageimg_hazard_tt : public ux_safehmi_image
{
public:
    Imageimg_hazard_tt(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageimg_highbeam_tt : public ux_safehmi_image
{
public:
    Imageimg_highbeam_tt(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageimg_lamp_icon : public ux_safehmi_image
{
public:
    Imageimg_lamp_icon(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageimg_lanedep_tt : public ux_safehmi_image
{
public:
    Imageimg_lanedep_tt(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageimg_lowbeam_tt : public ux_safehmi_image
{
public:
    Imageimg_lowbeam_tt(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};

class Imageimg_lturn_tt : public ux_safehmi_image
{
public:
    Imageimg_lturn_tt(const int32_t px, const int32_t py, const int32_t pwidth, const int32_t pheight, const bool pvisible,
			  const uint32_t pcolor, const uint32_t pchildcount, const ux_safehmi_item ** const pchildren, const uint8_t * const pImagePtr) :ux_safehmi_image(px, py, pwidth, pheight, 
                                                                      pvisible, pcolor, pchildcount, pchildren, pImagePtr)
    {
       
    }
    
};



}
/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** CMS Rev 1.0      16-Jan-2016  emanoj1
** Creation.
**
**==========================================================================*/
#endif

/* end of file =============================================================*/
