/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in2024. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_mgr02_font.h                                       
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated. Do not hand modify                          
Organization     :  Driver Information Software Section,                       
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#ifndef HMI_GFX_MGR02_FONT_H
#define HMI_GFX_MGR02_FONT_H
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/

extern GFX_MGR02_FONT_LUT const lc_Default_Font_lut[];
extern GFX_MGR02_FONT_LUT const lc_New_fonts_1_lut[];



extern GFX_MGR02_FONT const lc_gfx_font_table[2];
enum 
{
   GFX_MGR02_FONT_ID_DEFAULT_FONT,
   GFX_MGR02_FONT_ID_NEW_FONTS_1,

   GFX_MGR02_TOTAL_NUM_OF_FONTS
};
#define GFX_MGR02_NUM_OF_FONTS       (2)
#define GFX_MGR02_NUM_OF_FONT_GROUPS (0)
#define GFX_MGR02_OVG_FONT_PRESENT   (0)

#define GFX_MGR02_LUP_LINEAR (0)
#define GFX_MGR02_LUP_HYBRID (1)
#define GFX_MGR02_LUP_BINARY (2)

#define GFX_MGR02_CHAR_SEARCH_MODE (GFX_MGR02_LUP_LINEAR)
#define GFX_MGRO02_FONT_CHARBUF_MAX_SIZE   (2908)


/***************************************************************************** 
*                                 Type Declarations                          * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                Globally  accessed Variable Declarations    * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the variable.                                                        * 
* purpose, critical section, unit, and resolution                            * 
******************************************************************************/
                                                                               
                                                                               
/***************************************************************************** 
*                                 Locally used Variable Declarations         * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the variable.                                                        * 
* purpose, critical section, unit, and resolution                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                       Locally used Constant Declarations                   * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the constant.                                                        * 
* purpose, unit, and resolution                                              * 
******************************************************************************/
                                                                               

#endif
