/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2024. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 10/23/2024
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_IMG_SPEED_BASEID                (0)
#define GFX_IMG_CIRCLE_BASEID               (1)
#define GFX_NEW_IMAGES_3_BASEID             (2)
#define GFX_NEW_IMAGES_1_BASEID             (3)
#define GFX_NEW_IMAGES_2_BASEID             (4)
#define GFX_IMG_VGL_COMP_SWLRE_VGLITE_BASEID (5)
#define GFX_WDG_VGL_COMP_IMG_BASEID         (6)
#define GFX_NEW_WIDGETS_3_IMG_BASEID        (0)
#define GFX_NEW_TEXTS_2_BASEID              (0)
#define GFX_IMG_TEST_SVG_BASEID             (0)
#define GFX_INVALID_BASEID                  (0)
#define GFX_NEW_FILL_SCREENS_1_BASEID       (0)
#define GFX_NEW_FILL_SCREENS_2_BASEID       (1)
#define GFX_NEW_FILL_SCREENS_5_BASEID       (2)
#define GFX_FILL_VGL_COMP_BASEID            (3)
#define GFX_NEW_WIDGETS_3_BASEID            (0)
#define GFX_WDG_VGL_COMP_BASEID             (1)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS       (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS          (2U)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS       (7)
#define GFX_MGR02_NUM_3D_MDL_LAYERS         (0)
#define GFX_MGR02_NUM_USER_LAYERS           (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS (1)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS        (1)

#define GFX_MGR02_NUM_OF_SVGS               (1)

#define GFX_MGR02_NUM_OF_SVG_CLIPS          (0)
#define GFX_MGR02_NUM_OF_FILLS              (4)
#define GFX_MGR02_NUM_OF_TILES              (0)
#define GFX_MGR02_NUM_VIDEO_LAYERS          (0)
#define GFX_MGR02_DYNAMIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS              (2)

#define GFX_MGR02_NUM_VISIBLE_AREA      (3U)

/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (720)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (1280)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_IMG_SPEED_ANIM                          = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_CIRCLE_ANIM                         = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_NEW_IMAGES_3_ANIM                       = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_NEW_FILL_SCREENS_1_ANIM                 = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_NEW_FILL_SCREENS_2_ANIM                 = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_NEW_FILL_SCREENS_5_ANIM                 = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_NEW_TEXTS_2_ANIM                        = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_NEW_WIDGETS_3_ANIM                      = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_IMXRT|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDG_VGL_COMP_ANIM                       = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_VGLITE|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_SCR_TV2_SAMLE1_ANIM                     = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS   (3)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS      (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS    (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS     (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS    (3)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS    (0)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS    (1)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS  (2)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS   (1)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS  (1)

#define GFX_MGR02_STEXTS_BUFFER_SIZE (0)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_NEW_TEXTS_2,
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (1)
#define GFX_MGR02_NUM_OF_STEXTS      (0)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (1)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (31)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (0)
#define GFX_MGR02_MAX_PATH_CMD_BUF_LENGTH   (113)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   __GFX_EMPTY_LIST_DWDG
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS       (0)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   __GFX_EMPTY_LIST_DIMG
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES        (0)

#define GFX_NEW_IMAGES_1_1                     GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_IMXRT)
#define GFX_IMG_TEST_SVG_1                     GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SVG|GFX_MGR02_PLATFORM_IMXRT)
#define GFX_NEW_IMAGES_2_1                     GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_IMXRT)
#define GFX_FILL_VGL_COMP_1                    GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_IMXRT)
#define GFX_IMG_VGL_COMP_SWLRE_1               GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_IMXRT)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES      (2)
#define GFX_MGR02_NUM_SVG_INSTANCES         (1)
#define GFX_MGR02_NUM_FILL_INSTANCES        (1)
#define GFX_MGR02_NUM_TILE_INSTANCES        (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES        (0)
#define GFX_MGR02_NUM_TEXT_INSTANCES        (0)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_TV2_SAMLE1                          = (0)
  ,GFX_SCR_IMXRT_WO_WIDGET                     = (1)
  ,GFX_SCR_IMXRT_FPS_FILL_IMG                  = (2)
  ,GFX_SCR_VGL_COMP_UT                         = (3)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS               (4)
#define GFX_MGR02_LAYER0_DAR_SIZE              (1)
#define GFX_MGR02_WIDGET0_DAR_SIZE             (5)
#define GFX_MGR02_WIDGET1_DAR_SIZE             (2)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (3)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX        (7)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_TV2_SAMLE1_BG_COLOR                         (0x000000FFUL)
#define GFX_SCR_IMXRT_WO_WIDGET_BG_COLOR                    (0x000000FFUL)
#define GFX_SCR_IMXRT_FPS_FILL_IMG_BG_COLOR                 (0x000000FFUL)
#define GFX_SCR_VGL_COMP_UT_BG_COLOR                        (0x000000FFUL)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x00000000u)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (6)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1U)
#define GFX_MGR02_NUM_PRIORITY            (1)
#define GFX_MGR02_UNICODE              (1)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (30)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (0)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (0)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_ARGB8888)
#define GFX_MGR02_TV2_GDT_PORTING
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (1)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_IMXRT
#define GFX_MGR02_IMXRT_PXP
#define GFX_MGR02_VGLITE
#define GFX_MGR02_COMPRESSION_ENABLED
#define GFX_MGR02_DECOMPR_BUF_SIZE        (522240)
#define GFX_MGR02_RENDER_NONE
#define GFX_MGR02_CLIP_TEXT_ENABLE
#define GFX_MGR02_APPEND_CHAR          46
#define GFX_MGR02_APPEND_CHAR_CNT      (3)

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        10/23/2024     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
