/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2017 -2018. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**==========================================================================*/

/*============================================================================
**
** Name:           Ctrl_Telltale_Cfg.h
**
** Description:    This is an autogenerated file. Do not hand modify...
**                  
** Organization:   Driver Information Software Section,
**                 Visteon
**
**============================================================================
**
**==========================================================================*/

#ifndef CTRL_TELLTALE_CFG_H
#define CTRL_TELLTALE_CFG_H

//=====================================================================================================================
//  FORWARD DECLARATIONS                                                                                               
//=====================================================================================================================
/*                                                                                                                     
** This is a excel generated file. pls refer  ; xxx;  excel utility for configurations                                    
** DO NOT TOUCH THESE.                                                                                                 
**                                                                                                                     
*/                                                                                                                     
                                                                                                                       
//=====================================================================================================================
// !!!!!!!!!!!!!!!!!!!DO NOT DELETE THE BELOW MENTIONED MACROS !!!!!!!                                                 
// USE THIS MACRO FOR CONFIGURING ON/OFF FROM APP LAYER/CTRL LAYER/CTRL                                                
//=====================================================================================================================
//=====================================================================================================================
/*                                                                                                                     
** TELLTALE ATTRIBUTE MACROS...                                                                                        
** DO NOT TOUCH THESE.                                                                                                 
** ATTRIBUTE BYTE 1                                                                                                    
*/                                                                                                                     
//=====================================================================================================================
#define cTT_RUN          ((uint8)0x08u) /* RUN Bit, if set in attributes, the tt will be enabled in RUN.*/             
#define cTT_OFF_RUN      ((uint8)0x0Cu) /* RUN OFF Bit, if set in attributes, the tt will be enabled in RUN and OFF.*/ 
#define cTT_OFF          ((uint8)0x04u) /* OFF Bit, if set in attributes, the tt will be enabled in OFF.*/             
#define cTT_ACC          ((uint8)0x02u) /* ACC Bit, if set in attributes, the tt will be enabled in ACC.*/             
#define cTT_CRANK        ((uint8)0x01u) /* CRANK Bit, if set in attributes, the tt will be enabled in CRANK.*/         
#define cTT_ZERO         ((uint8)0x00u) /* Null value*/                                                                
                                                                                                                       
//=====================================================================================================================
/*                                                                                                                     
** The FOLLOWING MACROS should return a BOOLEAN indicating                                                             
** whether the state is active or inactive (0 = inactive)                                                              
**                                                                                                                     
** VALID VALUES:  Must resolve to a BOOLEAN EXPRESSION.                                                                
**                For example:   (ign_status == IGN_OFF)                                                               
**                A TESTBIT can also be used.                                                                          
**                In this sample file, the FIGSW_IS_SW_XYZ macros                                                      
**                are written to be BOOLEAN EXPRESSIONS.                                                               
*/                                                                                                                     
//=====================================================================================================================
                                                                                                                       
#define cIGN_RUN    1U                                                                                          
                                                                                                                       
#define cIGN_OFF    3U                                                                                          
                                                                                                                       
//The Below 2 States are not used in the Hyundai                                                                       
#define cIGN_ACC    2U                                                                                                  
                                                                                                                       
#define cIGN_CRANK  4U                                                                                                  
/*=====================================================================================================================*/
/*                                                                                                                       
**The cPRODUCT_SPECIFIC_TELLTALE_CONFIG macro is a means for the                                                       
**application to populate the telltale attributes.                                                                     
                                                                                                                       
**Note: cTT_NUM_ENTRIES_TELLTALE_CONFIG number of structure instances will be created for this macro.                  
                                                                                                                       
**The following information needs frames the structure:                                                                
                                                                                                                       
typedef struct TellTaleMdl_TTConfig                                                                                    
{                                                                                                                      
 boolean Is_TTProveOut_Enabled;                                                                                        
 uint16 ProveOut_ONtime;                                                                                               
 uint16 ProveOut_OFFtime;                                                                                              
 uint16 ProveOut_StartPhase;                                                                                           
 uint8  Operational_states;                                                                                            
 uint8  LVSD_state;                                                                                                    
 uint8  HVSD_state;                                                                                                    
                                                                                                                       
}TellTaleMdl_TTConfig;                                                                                                 
                                                                                                                       
 Valid values:                                                                                                         
                                                                                                                       
 Is_TTProveOut_Enabled    - TRUE or FALSE                                                                              
 ProveOut_ONtime     - in counts.  - i.e counts = (time in ms / scheduler tick rate of the task)                       
 ProveOut_OFFtime    - in counts.  - i.e counts = (time in ms / scheduler tick rate of the task)                       
 ProveOut_StartPhase - eTtStatus_On  or eTtStatus_Off                                                                    
 Operational_states  - cTT_RUN | cTT_OFF | cTT_ACC | cTT_CRANK                                                         
 LVSD_state          - eTtStatus_On or eTtStatus_Off or cTT_TURN_INPUT                                                   
 HVSD state          - eTtStatus_On or eTtStatus_Off or cTT_TURN_INPUT                                                   
** Note: The order of attributes shall match with the telltale ids given in the above macro.                           
                                                                                                                       
=====================================================================================================================  
######### EXAMPLE: #########                                                                                           
=====================================================================================================================  
case 1: - cTTMDL_SPECIFIC_PROVEOUT                                                                                     
#define cPRODUCT_SPECIFIC_TELLTALE_CONFIG \                                                                            
{                                                                                                                      
  {0x01,\        Is_TTProveOut_Enabled;                                                                                
   100,\         ProveOut_ONtime - in counts;                                                                          
   50,\         ProveOut_OFFtime - in counts;                                                                          
   eTtStatus_On,\         ProveOut_StartPhase;                                                                          
   cTT_RUN|cTT_CRANK,\       Operational_states;                                                                       
   eTtStatus_On,\         LVSD_state;                                                                                   
   cTT_INPUT,\       HVSD_state;                                                                                       
  };                                                                                                                   
}                                                                                                                      
                                                                                                                       
case 2 :cTTMDL_COMMON_PROVEOUT                                                                                         
#define cPRODUCT_SPECIFIC_TELLTALE_CONFIG \                                                                            
{                                                                                                                      
  {\                                                                                                                   
   0x01,\                                                                                                              
   cTT_RUN,\                                                                                                           
   cTT_TURN_ON,\                                                                                                       
   eTtStatus_On,\                                                                                                       
   },\                                                                                                                 
}                                                                                                                      
=====================================================================================================================*/

#define cPRODUCT_SPECIFIC_TELLTALE_CONFIG \
       {/*#define TT_ABS_INDEX       (0) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_AIRBAG_INDEX       (1) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_BRAKE_RED_INDEX       (2) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_BRAKE_HOLD_INDEX       (3) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_BRAKE_YELLOW_INDEX       (4) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_PARKING_BRAKE_INDEX       (5) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_TRACTION_CTRL_INDEX       (6) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_VCS_OFF_INDEX       (7) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ABS_INDEX_US       (8) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_BRAKE_RED_INDEX_US       (9) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_PARKING_BRAKE_INDEX_US       (10) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SAF_RES4_INDEX       (11) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SAF_RES5_INDEX       (12) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SAF_RES6_INDEX       (13) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SAF_RES7_INDEX       (14) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SAF_RES8_INDEX       (15) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ADAS_INDEX       (16) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_AUTO_HIGH_BEAM_INDEX       (17) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_BRAKE_HOLD_STANDBY_INDEX       (18) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_FUEL_INDEX       (19) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_FFOG_INDEX       (20) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_HEAD_INDEX       (21) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_HIGH_BEAM_INDEX       (22) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_PCS_OFF_INDEX       (23) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_READY_INDEX       (24) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_RFOG_INDEX       (25) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SEAT_BELT_INDEX       (26) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_TAIL_LIGHT_INDEX       (27) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_TURN_HAZARD_RIGHT_INDEX       (28) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_TURN_HAZARD_LEFT_INDEX       (29) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_OFF_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_EWT_INDEX       (30) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LO_GREEN       (31) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SHADED_GREEN       (32) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_HI_GREEN       (33) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_HI_WHITE       (34) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_INFRA       (35) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_VEHICLE       (36) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_COMBINATION       (37) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SSS_GREEN       (38) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SSS_AMBER       (39) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LCA_LEFT_WHITE       (40) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LCA_LEFT_GRAY       (41) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LCA_LEFT_GREEN       (42) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LCA_RIGHT_WHITE       (43) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LCA_RIGHT_GRAY       (44) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LCA_RIGHT_GREEN       (45) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LTA_GREEN       (46) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LTA_WHITE       (47) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LTA_AMBER       (48) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_CCT_GREEN       (49) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_CCT_WHITE       (50) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_CCT_AMBER       (51) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_RCCT_GREEN       (52) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_RCCT_WHITE       (53) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_RCCT_AMBER       (54) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_WHITE_LV4       (55) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_WHITE_LV3       (56) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_WHITE_LV2       (57) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_WHITE_LV1       (58) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_GREEN_LV4       (59) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_GREEN_LV3       (60) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_GREEN_LV2       (61) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ACCDT_GREEN_LV1       (62) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SL_GREEN       (63) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SL_WHITE       (64) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_SL_AMBER       (65) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_AUTO_LSD_AMBER       (66) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_DRIVEMODE_SPORT       (67) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_DRIVEMODE_ECO       (68) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_DRIVEMODE_CUSTOM       (69) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_DRIVEMODE_RANGE       (70) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_DRIVEMODE_REARCOMFORT       (71) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_DRIVEMODE_SNOW       (72) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_DRIVEMODE_TRACK       (73) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LDA_RED       (74) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LDA_AMBER       (75) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LDA_WHITE       (76) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LDA_OFF_AMBER       (77) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_LDA_OFF_WHITE       (78) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_ECOLAMP       (79) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_PS_GREEN       (80) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_PKBOPER_TXT       (81) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_PKBOPER_IMG       (82) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_TPMS_INDEX       (83) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_EBPWIND_RED_US       (84) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_EBPWIND_RED       (85) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_FMSR_AMBER       (86) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_FMFR_AMBER       (87) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_MULWL_GREEN       (88) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_HCS_ACCESS_GREEN       (89) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_HCS_LIFT_GREEN       (90) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       },\
       {/*#define TT_HCS_LIFT_AMBER       (91) */\
         0,\
         0,\
         0,\
         TT_TURN_OFF,\
         cTT_RUN,\
         TT_TURN_OFF,\
         TT_TURN_OFF,\
       }

                                                                                                                           
//=====================================================================================================================    
#endif
