/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_clut_table.c
**                                                                            
** Description:    This file contains the CLUT table autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 2/24/2023
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#define HMI_GFX_MGR02_CLUT_TABLE_C
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_layout.h"
#include "hmi_gfx_mgr02_clut_table.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/
                                                                              
/*============================================================================
** M E M O R Y   A L L O C A T I O N                                          
**==========================================================================*/

#if defined(__IAR_SYSTEMS_ICC)
#pragma section="GFX02_IMGDEF_RO_DATA"
#pragma section="GFX02_IMGDEF_RW_DATA"
#elif defined(__CWCC__)
#pragma push
#pragma section "GFX02_IMGDEF_RO_DATA" "GFX02_IMGDEF_RO_DATA"
#pragma section "GFX02_IMGDEF_RW_DATA" "GFX02_IMGDEF_RW_DATA"
#define GFX02_IMGDEF_RO_DATA_PREFIX __declspec(section "GFX02_IMGDEF_RO_DATA")
#define GFX02_IMGDEF_RW_DATA_PREFIX __declspec(section "GFX02_IMGDEF_RW_DATA")
#elif defined(__RENESAS__)
#pragma section GFX02_IMGDEF_RO_DATA
#pragma section GFX02_IMGDEF_RW_DATA
#elif defined(__ghs__)
#pragma ghs section rodata="GFX02_IMGDEF_RO_DATA"
#pragma ghs section bss="GFX02_IMGDEF_RW_DATA"
#endif
#ifndef GFX02_IMGDEF_RO_DATA_PREFIX
#define GFX02_IMGDEF_RO_DATA_PREFIX
#endif
#ifndef GFX02_IMGDEF_RW_DATA_PREFIX
#define GFX02_IMGDEF_RW_DATA_PREFIX
#endif

#if GFX_MGR02_NUM_OF_CLUTS > 0
GFX_MGR02_CLUT_DATA const lc_gfx_mgr02_clut_array[GFX_MGR02_NUM_OF_CLUTS] =
{
#if GFX_MGR02_PROD_SPEC_CLUT_TABLE_NUM > 0
  ,GFX_MGR02_PROD_SPEC_CLUT_TABLE
#endif
};
#endif /* #if GFX_MGR02_NUM_OF_CLUTS > 0 */


#if defined(__IAR_SYSTEMS_ICC)
#pragma memory=default
#elif defined(__CWCC__)
#pragma pop
#elif (defined(__RENESAS__))
#pragma section
#elif defined(__ghs__)
#pragma ghs section rodata=default
#pragma ghs section bss=default
#endif

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
