/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in 2009. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_anim_engine_cfg.h                                    
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated by GDT . Do not handmodify this file. 
                    Generated on MM/DD/YYYY - 2/24/2023
Organization     :  DI/Audio Software Section,                                 
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#ifndef HMI_GFX_ANIM_ENGINE_CFG_H
#define HMI_GFX_ANIM_ENGINE_CFG_H
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/
                                                                               
#define GFX_WELCOME_ANIMATION_FRAME2              (0)
#define GFX_WELCOME_ANIMATION_FRAME3              (1)
#define GFX_WELCOME_ANIMATION_FRAME5              (2)
#define GFX_WELCOME_ANIMATION_NUM_FRAMES          (3)

#define GFX_CLUTCHANIMATION_FRAME_1               (0)
#define GFX_CLUTCHANIMATION_FRAME_2               (1)
#define GFX_CLUTCHANIMATION_NUM_FRAMES            (2)

#define GFX_WARNINGBLINKANIMATION_FRAME_1         (0)
#define GFX_WARNINGBLINKANIMATION_FRAME_2         (1)
#define GFX_WARNINGBLINKANIMATION_NUM_FRAMES      (2)

#define GFX_MINIPOPUPSLIDEUPSLIDEDOWN_FRAME_1     (0)
#define GFX_MINIPOPUPSLIDEUPSLIDEDOWN_FRAME_2     (1)
#define GFX_MINIPOPUPSLIDEUPSLIDEDOWN_NUM_FRAMES  (2)

#define GFX_SPANNER_ROTATE_ANIMATION_FRAME_1      (0)
#define GFX_SPANNER_ROTATE_ANIMATION_FRAME_2      (1)
#define GFX_SPANNER_ROTATE_ANIMATION_NUM_FRAMES   (2)

#define GFX_ICE_ANIM_FRAME_1                      (0)
#define GFX_ICE_ANIM_FRAME_2                      (1)
#define GFX_ICE_ANIM_NUM_FRAMES                   (2)


enum
{
    GFX_WELCOME_ANIMATION
   ,GFX_CLUTCHANIMATION
   ,GFX_WARNINGBLINKANIMATION
   ,GFX_MINIPOPUPSLIDEUPSLIDEDOWN
   ,GFX_SPANNER_ROTATE_ANIMATION
   ,GFX_ICE_ANIM
   ,GFX_TOTAL_NUM_ANIMATIONS
};
#define GFX_NUM_ANIMATIONS                        (6)
#define GFX_NUM_LINEAR_ANIMATIONS                 (1)
#define GFX_BASE_ANIM_RATE_MSEC                   (167)
#define GFX_ANIM_GOTO_COUNT_ARRAY_SIZE            (5)

#define GFX_BASE_ANIM_RATE_SCALE                  (10)

/***************************************************************************** 
*                              File Scope Prototypes                         * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                   Functions                                                * 
******************************************************************************/
extern void hmi_welcome_animation_cb(UINT32 p_cur_frame, UINT32 p_total_frames);
extern UINT32 hmi_clutchanimaton_goto_cb(UINT32 p_cur_step);
extern UINT32 hmi_warnblinkanimaton_goto_cb(UINT32 p_cur_step);
extern void HMI_MiniPopupSlideUpSlideDown_cb(UINT32 p_cur_frame, UINT32 p_total_frames);
extern UINT32 minipopupslideupslidedown_goto_cb(UINT32 p_cur_step);
extern void hmi_spanner_anim_cb(UINT32 p_cur_frame, UINT32 p_total_frames);
extern UINT32 hmi_spanner_goto_cb(UINT32 p_cur_step);
extern UINT32 ICE_TT_blinkanimaton_goto_cb(UINT32 p_cur_step);

                                                                               
/*End of File*/                                                                
/***************************************************************************** 
*   for each change to this file, be sure to record:                         * 
*      1.  who made the change and when the change was made                  * 
*      2.  why the change was made and the intended result                   * 
*   Following block needs to be repeated for each change                       
****************************************************************************** 
*   Note: In the traceability column we need to trace back to the Design Doc.* 
*   For the initial version it is traced to the Design Document section.     * 
*   For further changes it shall trace to the source of the change which may * 
*   be SPSS/SCR/Defect details(Defect may be Testing/validation defect)/Any  * 
*   other reason                                                            *  
******************************************************************************/
#endif
