#! python3
"""1. Parse warnings from build_log.txt file, which is generated by CI_makeall.bat.
2. Warnings are logged in a excel workbook and saved in a backup path.
3. Warning count is written in a csv file for Jenkins to plot graph.

External dependencies:
1. 'openpyxl' package
	> pip install openpyxl
2. 'l_utils.py' file
	> lib/l_utils.py
"""

__author1__ = 'ssulaim1'
__date__ = '16-Jan-2019'

__author2__ = 'rboya1,sswathi1'
__date__ = '15-May-2023'


from bs4 import BeautifulSoup
import sys
import csv
import re
import os
import openpyxl
import openpyxl.utils
import openpyxl.styles
from collections import Counter
from lib.l_utils import path_safe
from lib.l_utils import read_config
from lib.l_utils import add_date_to_filename
Repo_Swc=""
SWC_Repo=""
List_SwcRepo = []
ArrayRepo=[]
file_warning = []
swc_names = []
pattern_Swc_Repo=r'((\w\.?\_?)+)\/(([s|S]rc)|cfg|stub|template)'
pattern_Swc= re.compile('.*name\=.*\/(\S+)\"\s+path.*')
workspace_path = str(sys.argv[2])


with open(workspace_path + "/.repo/project.list","r") as file:
	for lines in file:
		swc_name = os.path.basename(lines.strip())
		swc_names.append(swc_name)
#print('software component names:', swc_names)

def read_warnings(warning_log_file, warning_deviation_file, warning_html_file):
	global SWC_Repo
	with open(warning_log_file) as wf:
		# print('output.txt', warning_log_file)
		contents = wf.readlines()
		# print(contents)
		# contents = list(set(contents))
	#print(contents)
	warnings = []

	after_deviation = []
	count = 1
	Read_Variant=sys.argv[1].strip()

	for line in contents:
		try:
			if (Read_Variant.find("VIP") != -1) or (Read_Variant.find("BL") != -1) or (Read_Variant.find("HSM") != -1):
				pattern = r'^("[^\,]*), line ([0-9]+): warning (#[0-9]+-[a-zA-Z]+): ([^\n]*)$'
			else:
				pattern = r'^(/home[^\,]*):([0-9]+):([0-9]+): warning: ([^\n]*)$'
			end_pattern = r'\^\n$'
			match = re.search(pattern, line)
			line_number = match.group(2)
			warning_id = match.group(3)
			wrn_description = match.group(4)

			if (match != None):
				i = count
				while i < (count+5): #Support Maximum 5 line warning description
					match_end = re.search(end_pattern, contents[i])
						# print(contents[i])
					if (match_end == None):
						wrn_description += contents[i]
						i += 1
					else:
						break

			FileName= match.group(1)
			#print('file names:',FileName)

			strings_of_each_filename = FileName.split('/')
			#print("strings of each file names:", strings_of_each_filename)
			for i in range(len(swc_names)):
				for j in range(len(strings_of_each_filename)):
					if swc_names[i] == strings_of_each_filename[j]:
						SWC_Repo = swc_names[i]
			for y in range(len(strings_of_each_filename)):
				if "mcal" == strings_of_each_filename[y]:
					# print('mcal swc name:', strings_of_each_filename[y])
					if "drivers" == strings_of_each_filename[y+2]:
						# print("drivers found", strings_of_each_filename[y+2])
						SWC_Repo = strings_of_each_filename[y+3]
					else:
						# print("startup found", strings_of_each_filename[y-2])
						SWC_Repo = strings_of_each_filename[y-2]
			#warning_description_spliting = " ".join(wrn_description.split())
			#print('spliting warning description with tab space:',warning_description_spliting)
			ArrayRepo.append(SWC_Repo)
			warning = [match.group(1), int(match.group(2)), match.group(3), " ".join(wrn_description.split()), SWC_Repo]
			SWC_Repo=""
			# print(ArrayRepo)	

		except (AttributeError, ValueError):
			pass
		else:
			#if warning not in warnings:
				
				warnings.append(warning)
			# print(len(warnings))
		count += 1
	counts = dict(Counter(ArrayRepo))
	# print(counts)
	duplicates = {key:value for key, value in counts.items() if value > 0}
	# print(duplicates)

	# with open('../vp-build/misc_scripts/kpi_scripts/Plot_Batch/Componentwise_compiler_warnings.csv', 'w', newline='') as fp:
	# 	fieldnames = ['SW Component', 'Warning Count']
	# 	writer = csv.DictWriter(fp, fieldnames=fieldnames)
	# 	writer.writeheader()
	# 	for key, value in duplicates.items():
	# 		writer.writerow({'SW Component': key, 'Warning Count': value})

	if os.path.exists(warning_deviation_file):
		wb_obj = openpyxl.load_workbook(warning_deviation_file)
		sheet_obj = wb_obj['Compiler warnings']
		warnings = sorted(warnings, key=lambda x: x[0])

		for row, warning in enumerate(warnings, start=2):
			deviation_status = 0
			for row_dev in range(1, sheet_obj.max_row + 1):
				if ((warning[0] == sheet_obj.cell(row = row_dev, column = 1).value) and \
					(warning[2] == sheet_obj.cell(row = row_dev, column = 3).value) and \
					(warning[3] == sheet_obj.cell(row = row_dev, column = 4).value)):
					deviation_status = 1
					break
			if deviation_status == 0:
				after_deviation.append(warnings[row-2])
		create_html_file(after_deviation, warning_html_file)
		return after_deviation
	else:
		create_html_file(warnings, warning_html_file)
		return	warnings

def create_html_file(warning_list, warning_html_file):
	fileout = open(warning_html_file, "w")
	table = "<html>"
	table += "<head>"
	table += "<title>Compiler Warning Detailed Report</title>"
	table += "<style>"
	table += "TD { "
	table += "font-family: calibri;"
	table += "   font-size: 10pt; "
	table += "    color: ; background: none;"
	table += " }"
	table += "TABLE{ "
	table += "       background: white ;"
	table += "}"
	table += "</style>"
	table += "</head>"
	table += "<body style =\"background:#e6f2ff\">"
	table += "<h1 style =\"font-family:calibri\" >Compiler Warning Detailed Report<h1>"

	table += "<table border='1' cellpadding='10' cellspacing='0' width='100%'>"

	# Create the table's column headers
	table += "  <tr>\n"
	table += "    <th>{0}</th>\n".format("Sr.no")
	table += "    <th>{0}</th>\n".format("File Name")
	table += "    <th>{0}</th>\n".format("Warning ID")	
	table += "    <th>{0}</th>\n".format("Line Number")
	table += "    <th>{0}</th>\n".format("Warning Description")
	table += "    <th>{0}</th>\n".format("SwcName")	
	table += "  </tr>\n"
	# Create the table's row data
	count = 1
	for line in warning_list:
		table += "  <tr>\n"
		table += "    <td>{0}</td>\n".format(count)
		table += "    <td>{0}</td>\n".format(line[0])
		table += "    <td>{0}</td>\n".format(line[2])
		table += "    <td>{0}</td>\n".format(line[1])
		table += "    <td>{0}</td>\n".format(line[3])
		table += "    <td>{0}</td>\n".format(line[4])
		table += "  </tr>\n"
		count += 1
	table += "</table>"

	table += "</body>"
	table += "</html>"

	fileout.writelines(table)
	fileout.close()

def create_componentwise(warning_html_file,component_wise_file):
	#path of the html file
	path=warning_html_file

	# Read the HTML file
	with open(path, 'r') as file:
		html_content = file.read()

	# Parse the HTML using BeautifulSoup
	soup = BeautifulSoup(html_content, 'html.parser')

	# Find the table element
	table = soup.find('table')

	# Initialize a dictionary to store software component counts
	component_counts = {}

	# Iterate over each row in the table
	for row in table.find_all('tr'):
		# Find the last column in the row
		cells = row.find_all('td')
		if cells:
			component_name = cells[-1].text.strip()
			# Increment the count for the component name in the dictionary
			component_counts[component_name] = component_counts.get(component_name, 0) + 1

# Write the component counts to the CSV file
	with open(component_wise_file, 'w', newline='') as file:
		writer = csv.writer(file)
		writer.writerow(['SW Component', 'Warning Count'])
		for component_name, count in component_counts.items():
			writer.writerow([component_name, count])

	print(f'CSV file has been generated.')

def create_header_row(worksheet):
	header_text = ['File Name', 'Line Number', 'Warning ID', 'Warning Description', 'SWC']
	column_widths = [102, 11.5, 11, 228, 25]

	max_col_letter = openpyxl.utils.get_column_letter(len(header_text))
	header_font = openpyxl.styles.Font(bold=True)
	header_cells = worksheet[f'A1:{max_col_letter}1']
	for cell, text in zip(header_cells[0], header_text):
		cell.value = text
		cell.font = header_font
	for col, width in enumerate(column_widths, 1):
		col_letter = openpyxl.utils.get_column_letter(col)
		worksheet.column_dimensions[col_letter].width = width

	worksheet.freeze_panes = 'A2'


def write_warnings_xl(warnings, worksheet):
	create_header_row(worksheet)
	warnings = sorted(warnings, key=lambda x: x[0])
	for row, warning in enumerate(warnings, start=2):
		worksheet[f'A{row}'] = warning[0]
		worksheet[f'B{row}'] = warning[1]
		worksheet[f'C{row}'] = warning[2]
		worksheet[f'D{row}'] = warning[3]
		worksheet[f'E{row}'] = warning[4]


def write_warnings_count(warnings, out_file):
	with open(out_file, 'w+') as f:
		print('noOfWarnings', file=f)
		print(len(warnings), file=f)


@path_safe()
def main():
	try:
		Read_Variant=sys.argv[1].strip()
		local_paths = read_config(workspace_path + "/programs/vw/my2022/fpkb8/vp-build/Misc_Scripts/KPI_Scripts/configs/local_paths.json")
		log_files = read_config(workspace_path + "/programs/vw/my2022/fpkb8/vp-build/Misc_Scripts/KPI_Scripts/configs/logfile_paths.json")
		if (Read_Variant.find("VIP") != -1):			
			build_log = local_paths['build_log']
			warning_count_file = log_files['csv_plot_files']['comp_warnings']
			warning_details_file = log_files['backup_files']['comp_warnings']
			warning_html_file = local_paths['Compiler_warning_html']
			warning_deviation_file = local_paths['Compiler_deviation_file']
			warning_threshold = local_paths['warning_threshold']
			component_wise_file=local_paths['Component_wise_vip']
		elif (Read_Variant.find("BL") != -1):
			build_log = local_paths['build_log_bl']
			warning_count_file = log_files['csv_plot_files']['comp_warnings_bl']
			warning_details_file = log_files['backup_files']['comp_warnings_bl']
			warning_html_file = local_paths['Compiler_warning_bl_html']
			warning_deviation_file = local_paths['Compiler_deviation_file_bl']
			warning_threshold = local_paths['warning_threshold']
			component_wise_file=local_paths['Component_wise_bl']
		elif (Read_Variant.find("HSM") != -1):
			build_log = local_paths['build_log_hsm']
			warning_count_file = log_files['csv_plot_files']['comp_warnings_hsm']
			warning_details_file = log_files['backup_files']['comp_warnings_hsm']
			warning_html_file = local_paths['Compiler_warning_hsm_html']
			warning_deviation_file = local_paths['Compiler_deviation_file_hsm']
			warning_threshold = local_paths['warning_threshold']
			component_wise_file=local_paths['Component_wise_hsm']            
		else:			
			build_log = local_paths['build_log_gip']
			warning_count_file = log_files['csv_plot_files']['comp_warnings_gip']
			warning_details_file = log_files['backup_files']['comp_warnings_gip']
			warning_html_file = local_paths['Compiler_warning_gip_html']
			warning_deviation_file = local_paths['Compiler_deviation_file_gip']
			warning_threshold = local_paths['warning_threshold']
			component_wise_file=local_paths['Component_wise_gip']

	except FileNotFoundError as fof:
		print(fof)
		print('Configuration file not found!')
		exit(1)
	except KeyError as key:
		print(f'[ERROR] {str(key)} not found in config files')
		exit(1)

	wb = openpyxl.Workbook()
	ws = wb.active
	ws.title = 'Compiler warnings'

	try:
		warnings = read_warnings(build_log, warning_deviation_file, warning_html_file)
		create_componentwise(warning_html_file,component_wise_file)
	except FileNotFoundError:
		print(f'Fatal. Unable to read warnings from {build_log} file.')
		exit(1)
	write_warnings_xl(warnings, ws)
	write_warnings_count(warnings, warning_count_file)
	
	try:

		wb.save(add_date_to_filename(warning_details_file))
	except ValueError:
		print(f'Invalid filename format {warning_details_file} Should be <name>.<extension>')
	except FileNotFoundError:
		print(f'Path {os.path.dirname(warning_details_file)} does not exist')
	except PermissionError:
		print(f'Unable to update {warning_details_file}. Opened in other application')
	else:
		print(f'Generated warning details in {warning_details_file}')
		print(f'Generated warning count in {warning_count_file}')
		print(f'Generated warning details as HTML in {warning_html_file}')

	if (len(warnings) > int(warning_threshold)):
		print("\n***************************************************************")
		print(f'Actual No of Compiler warnings {len(warnings)}')
		print(f'Threshold value {(warning_threshold)}')
		print(f'Build failure due to actual no of warnings are exceeded threshold value ')
		print("***************************************************************\n")
		exit(1)
	else:
		print(f'Build compiled successfully without any compiler warnings')
		print(f'Actual No of Compiler warnings {len(warnings)}')
		print(f'Threshold value {(warning_threshold)}')

if __name__ == '__main__':
	main()
