/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_image_data.h
**                                                                            
** Description:    This file contains the image data autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 6/24/2024
**                 Total Image ROM size = [10295894 bytes]   
**                 Total RLE Savings    = [0 bytes]
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_IMAGE_DATA_H
#define HMI_GFX_MGR02_IMAGE_DATA_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** externs for all the image tables generated.
*/
extern UINT8 const lc_rgbtest_data[132];
extern UINT8 const lc_img_ah_tt_data[2064];
extern UINT8 const lc_img_compass_data[364];
extern UINT8 const lc_img_ah_tt_0_0_data[800];
extern UINT8 const lc_img_tt_side_stand_data[352];
extern UINT8 const lc_img_tt_master_warning_data[360];
extern UINT8 const lc_img_tt_high_beam_data[284];
extern UINT8 const lc_img_tt_grip_heater_data[928];
extern UINT8 const lc_img_test_data[6390];
extern UINT8 const lc_rgbtest_4_colors_data[3000];
extern UINT8 const lc_rgbtest_2_colors_data[750];
extern UINT32 const lc_speedodial_ovg_data[384000];
extern UINT32 const lc_rsbr_1_ovg_data[1394];
extern UINT8 const lc_rsbr_2_data[2772];
extern UINT8 const lc_rsbr_3_data[2072];
extern UINT32 const lc_tbt_1_ovg_data[925];
extern UINT16 const lc_tbt_2_data[925];
extern UINT16 const lc_tbt_4_data[925];
extern UINT32 const lc_tbt_5_ovg_data[925];
extern UINT8 const lc_tbt_1_0_data[2396];
extern UINT8 const lc_tbt_2_0_data[1112];
extern UINT8 const lc_tbt_5_0_data[2500];
extern UINT8 const lc_car_data[27444];
extern UINT32 const lc_ring_ovg_data[114244];
extern UINT8 const lc_door_fl_data[6816];
extern UINT8 const lc_door_fr_data[6636];
extern UINT8 const lc_door_rl_data[6948];
extern UINT8 const lc_door_rr_data[7036];
extern UINT8 const lc_hood_data[4440];
extern UINT8 const lc_trunk_data[8152];
extern UINT8 const lc_sunroof_data[2612];
extern UINT32 const lc_img_pressclutch_0_ovg_data[12430];
extern UINT32 const lc_img_pressclutch_1_ovg_data[12430];
extern UINT32 const lc_img_pressclutch_2_ovg_data[12430];
extern UINT32 const lc_img_pressclutch_3_ovg_data[12430];
extern UINT32 const lc_img_pressclutch_4_ovg_data[12430];
extern UINT32 const lc_img_pressclutch_5_ovg_data[12430];
extern UINT32 const lc_img_pressclutch_6_ovg_data[12430];
extern UINT32 const lc_img_pressclutch_7_ovg_data[12430];
extern UINT32 const lc_minibg_ovg_data[55200];
extern UINT32 const lc_nom_0_ovg_data[2898];
extern UINT32 const lc_nom_40_ovg_data[2898];
extern UINT32 const lc_nom_80_ovg_data[2898];
extern UINT32 const lc_nom_120_ovg_data[2898];
extern UINT32 const lc_nom_160_ovg_data[2898];
extern UINT32 const lc_nom_200_ovg_data[2898];
extern UINT32 const lc_nom_240_ovg_data[2898];
extern UINT8 const lc_rgbtest_0_data[990];
extern UINT8 const lc_rgbtest_1_data[264];
extern UINT8 const lc_rgbtest_2_data[200];
extern UINT8 const lc_rgbtest_3_data[256];
extern UINT8 const lc_rgbtest_4_data[344];
extern UINT32 const lc_tripmenu_ovg_data[34475];
extern UINT32 const lc_img_bg_speedo_ovg_data[384000];
extern UINT32 const lc_regengauge_ovg_data[338880];
extern UINT32 const lc_img_bg_regen_ovg_data[384000];
extern UINT8 const lc_img_ah_tt_0_data[544];
extern UINT8 const lc_img_ah_tt_0_1_data[1924];
extern UINT8 const lc_img_ah_tt_0_2_data[1508];
extern UINT8 const lc_img_compression_test_data[35008];
extern UINT16 const lc_new_images_1_data[384000];
extern UINT32 const lc_img1_ovg_data[6390];
extern UINT8 const lc_rgbtest_8_colors_data[1200];
extern UINT32 const lc_img_test_checkerboard_ovg_data[130560];
extern UINT32 const lc_img_horizontal_lines_ovg_data[130560];
extern UINT32 const lc_img_vertical_lines_ovg_data[130560];
extern UINT32 const lc_img_bg_gauge_ovg_data[130560];

/*
** mapping for image data which is repeating
*/
#define lc_tbt_4_0_data                                      (lc_tbt_4_data)

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_IMAGE_DATA_H */
