/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_clut_table.h
**                                                                            
** Description:    This file contains the CLUT header autogenerated by        
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 6/24/2024
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CLUT_TABLE_H
#define HMI_GFX_MGR02_CLUT_TABLE_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#include "hmi_gfx_mgr02_clut_table.cfg"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** CLUT table ID's.
*/
#define GFX_RGBTEST_CLUT                                     (0)
#define GFX_IMG_AH_TT_CLUT                                   (1)
#define GFX_IMG_COMPASS_CLUT                                 (2)
#define GFX_IMG_AH_TT_0_0_CLUT                               (3)
#define GFX_IMG_TT_SIDE_STAND_CLUT                           (4)
#define GFX_IMG_TT_MASTER_WARNING_CLUT                       (5)
#define GFX_IMG_TT_HIGH_BEAM_CLUT                            (6)
#define GFX_IMG_TT_GRIP_HEATER_CLUT                          (7)
#define GFX_IMG_TEST_CLUT                                    (8)
#define GFX_RGBTEST_4_COLORS_CLUT                            (9)
#define GFX_RGBTEST_2_COLORS_CLUT                            (10)
#define GFX_MGR02_NUM_OF_CLUTS                               (11U+ GFX_MGR02_PROD_SPEC_CLUT_TABLE_NUM)

/*
** CLUT table size.
*/
#define GFX_RGBTEST_CLUT_SIZE                                (6)
#define GFX_IMG_AH_TT_CLUT_SIZE                              (2)
#define GFX_IMG_COMPASS_CLUT_SIZE                            (2)
#define GFX_IMG_AH_TT_0_0_CLUT_SIZE                          (2)
#define GFX_IMG_TT_SIDE_STAND_CLUT_SIZE                      (18)
#define GFX_IMG_TT_MASTER_WARNING_CLUT_SIZE                  (126)
#define GFX_IMG_TT_HIGH_BEAM_CLUT_SIZE                       (103)
#define GFX_IMG_TT_GRIP_HEATER_CLUT_SIZE                     (85)
#define GFX_IMG_TEST_CLUT_SIZE                               (256)
#define GFX_RGBTEST_4_COLORS_CLUT_SIZE                       (4)
#define GFX_RGBTEST_2_COLORS_CLUT_SIZE                       (2)

/*
** externs for all the palette's generated.
*/
extern UINT8 const RGBTest_clut[18];
extern UINT8 const img_ah_tt_clut[6];
extern UINT8 const img_compass_clut[6];
extern UINT8 const img_ah_tt_0_0_clut[6];
extern UINT8 const img_tt_side_stand_clut[54];
extern UINT8 const img_tt_master_warning_clut[378];
extern UINT8 const img_tt_high_beam_clut[309];
extern UINT8 const img_tt_grip_heater_clut[255];
extern UINT8 const img_test_clut[768];
extern UINT8 const RGBTest_4_colors_clut[12];
extern UINT8 const RGBTest_2_colors_clut[6];

#if GFX_MGR02_NUM_OF_CLUTS > 0
  extern GFX_MGR02_CLUT_DATA const lc_gfx_mgr02_clut_array[GFX_MGR02_NUM_OF_CLUTS];
#endif

/*
** mapping for Palette data which is repeating
*/


/*
** CLUT Index definitions for the widget background color
*/
/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_CLUT_TABLE_H */
