/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2018. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 3/19/2018
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/



typedef enum
{
   GFX_SCR_MAIN_ANIM                                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_DIMG_SPEED_SHAFT1_ANIM                                   = GFX_MGR02_SET_OBJ(51,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;


/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_TXT_ODO_VALUE,
   GFX_TXT_OAT_VALUE,
   GFX_TXT_ODO_UNIT,
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;


/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   GFX_DWDG_IFE_SEL                                             = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET)
}GFX_MGR02_DWDG_ELEM_ID;

/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_DIMG_MENU_ICON4                                          = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_SPEED_SHAFT1                                        = GFX_MGR02_SET_OBJ(694,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;

typedef enum
{
   GFX_SCR_MAIN
}GFX_MGR02_SCR_ELEM_ID;




/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        3/19/2018     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
