-- VectorCAST 6.4s (05/01/17)
-- Test Case Script
-- 
-- Environment    : HMI_VIEW_VCAST_HT
-- Unit(s) Under Test: hmi_gfx_mgr02_amber_iris
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS
--
