; ═══════════════════════════════════════════════════════════════════
;  dlt_gateway.ini  –  DLT Gateway configuration
; ═══════════════════════════════════════════════════════════════════

[DltGatewayConfiguration]
DaemonHost            = 127.0.0.1
DaemonPort            = 3490
ReconnectIntervalMS   = 2000
; -1 = retry indefinitely
ReconnectMaxRetries   = -1
TransportType         = SharedMemory
NumberOfCores         = 3
Core_0                = Core0
Core_1                = Core1
Core_2                = Core2

[Core0]
;Core Name
Name             = VIP
;TransportType - Shared Memory
;Shared memory start address
ShmStartAddress  = 0x82385000
;Shared memory total size
ShmSize          = 8192
NumberOfBuffers  = 3
Buffer_0 = Core0Buffer0
Buffer_1 = Core0Buffer1
Buffer_2 = Core0Buffer2

;Transport type - UART/SPI
;Device ID
;DeviceId = "/dev/ser2"
;Speed of the device
;Speed    = 1000000
;Flow control: 0 - disabled, 1 - enabled
;FlowCtlr = 0

[Core1]
;Core Name
Name             = DM
;TransportType - Shared Memory
;Shared memory start address
ShmStartAddress  = 0x82388000
;Shared memory total size
ShmSize          = 4096
NumberOfBuffers  = 2
Buffer_0 = Core1Buffer0
Buffer_1 = Core1Buffer1

;Transport type - UART/SPI
;Device ID
;DeviceId = "/dev/ser2"
;Speed of the device
;Speed    = 1000000
;Flow control: 0 - disabled, 1 - enabled
;FlowCtlr = 0

[Core2]
;Core Name
Name             = HSM
;TransportType - Shared Memory
;Shared memory start address
ShmStartAddress  = 0x82387000
;Shared memory total size
ShmSize          = 4096
NumberOfBuffers  = 2
Buffer_0 = Core2Buffer0
Buffer_1 = Core2Buffer1

;Transport type - UART/SPI
;Device ID
;DeviceId = "/dev/ser2"
;Speed of the device
;Speed    = 1000000
;Flow control: 0 - disabled, 1 - enabled
;FlowCtlr = 0

;Shared memory based buffers start address, size and position (UCL message)
;


[Core0Buffer0]
BufferStartAddress=0x82385000
BufferSize=2048
; DLTEXT_VIP_SHAREMEMBUF1 = 0x01 -> bit 0
Position            = 0

[Core0Buffer1]
BufferStartAddress=0x82385800
BufferSize=2048
; DLTEXT_VIP_SHAREMEMBUF2 = 0x02 -> bit 1
Position            = 1

[Core0Buffer2]
BufferStartAddress=0x82386000
BufferSize=4096
; DLTEXT_SHAREMEMRESETBUF = 0x04 -> bit 2
Position            = 2


[Core1Buffer0]
BufferStartAddress=0x82388000
BufferSize=2048
; DLTEXT_DM_BUFFER1 = 0x20 -> bit 5
Position            = 5

[Core1Buffer1]
BufferStartAddress=0x82388800
BufferSize=2048
; DLTEXT_DM_BUFFER2 = 0x40 -> bit 6
Position            = 6


[Core2Buffer0]
BufferStartAddress=0x82387000
BufferSize=2048
; DLTEXT_HSM_BUFFER1 = 0x08 -> bit 3
Position            = 3

[Core2Buffer1]
BufferStartAddress=0x82387800
BufferSize=2048
; DLTEXT_HSM_BUFFER2 = 0x10 -> bit 4
Position            = 4
