; UDS Services configuration parameters.
; INI configuration file for UDS Services .
; fileName : uds_services.ini
; filePath : The configuration file should be in "/tmp/" or "/etc/uds/" . If the file path needs to be changed , update mUdsCoreIniFilePath1 in CUdsCoreComponent class.

; /*! udsCore is the container for the generic configuration values for the uds core. */ 
[udsServices]
; /*! UDS Service Manager periodic task time */
; /*! Range -  10..65535 */
; /*! Units - milliseconds */
udsServiceManagerMainFunctionPeriodInMs=10

; /*! udsDownloadServices is the container for the generic configuration values for the uds Download Services. */ 
[udsDownloadServices]
; /*! Temporary file path for downloading the requested file using diagnostic services */
; /*! type : string */
; /*! format : The string should start with "/" and end with "/" . eg: /tmp/ , /etc/uds/ */
;downloadTemporaryFilePath   = /tmp/
downloadTemporaryFilePath   = /fota_cache/

; /*! udsDiagModeAddress is the container for the configuration values for the list of supported Diagnostic mode address */
; /*! numberOfDiagModeAddress  - It defines the total number of logical address of the client supported for Diagnostic mode */
; /*! Range - 1..255 */ 
[udsDiagModeAddress]
numberOfDiagModeAddress = 2
; /*! diagModeAddress_n - It defines the logical address of the client to be accepted by the ECU for Diagnostic mode. "n" - represents the index of the number of address . range ( 0 .. numberOfDiagModeAddress -1) */
; /*! Value : 0x0000 - 0xFFFE . The value 0xFFFF is considered as an Invalid value and if configured the request will not be accepted */
diagModeAddress_0 = 0xF000
diagModeAddress_1 = 0xE401

; /*! Temporary file path for downloading the requested file using diagnostic services */
; /*! numberOfDiagModeAddress  - It defines the total number of logical address of the client supported for FOTA mode */
; /*! Range - 1..255 */ 
[udsFotaModeAddress]
numberOfFotaModeAddress = 2
; /*! diagModeAddress_n - It defines the logical address of the client to be accepted by the ECU for FOTA mode. "n" - represents the index of the number of address . range ( 0 .. numberOfFotaModeAddress -1) */
; /*! Value : 0x0000 - 0xFFFE . The value 0xFFFF is considered as an Invalid value and if configured the request will not be accepted */
fotaModeAddress_0 = 0x0F02
fotaModeAddress_1 = 0x0E80



