/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  Os_Alarm_Lcfg.h
Module Short Name:  Os_Alarm_Lcfg.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OS_ALARM_LCFG_H
#define OS_ALARM_LCFG_H
/* automatically generated by mOS Configurator xls v3.1 */
/* Generation time: 10-02-2025 11:13:58 */



/*****************************************************************************
*                            Include files                                   *
*****************************************************************************/



/*****************************************************************************
*                                 Macro Definitions                          *
*----------------------------------------------------------------------------*
* Definition of macro shall be followed by a comment that explains the       *
* purpose of the macro.                                                      *
*****************************************************************************/


/* Alarms */

extern const AlarmConfigType AlarmConfig_Rte_Al_TE2_OsTask_Diagnostics_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE2_OsTask_Mcal_10msLP_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE2_OsTask_MemSer_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE2_OsTask_ModeMgt_5msLP_0_5ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_Ea_Ea_MainFunction;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_GdtCdd_CGdtCdd_Impl_MainFunction;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_NvMExt_NvMExt_SpeedupRunnable;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_AppFun_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_CANFun_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_Diagnostics_0_100ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_Diagnostics_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_DispFun_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_DispFun_0_5ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_EthFun_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_Mcal_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_MemSer_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_SafeApp_0_30ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_SafeBsw_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_TripFun_0_50ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_OsTask_WdgMngt_0_10ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_SafeBsw_OsTask_SafeBsw_WdgM_CheckPoint_20ms;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_Test_Comp_AudioTaskStubRunnable;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_Test_Comp_FotaTaskStubRunnable;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_Test_Comp_GaugeTaskStubRunnable;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_Test_Comp_IndTaskStubRunnable;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_Test_Comp_LinTaskStubRunnable;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_Test_Comp_WarnTaskStubRunnable;
extern const AlarmConfigType AlarmConfig_Rte_Al_TE_UclProxyCdd_CUclProxyCdd_Impl_MainFunction;



extern const AlarmConfigRefType AlarmRefConfig[OsNumberOfAlarms];



#endif    /* */
/* end of file */
/****************************************************************
Created Time: 10-02-2025 11:13:58
****************************************************************/
