/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  Os_Alarm_Cfg.h
Module Short Name:  Os_Alarm_Cfg.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OS_ALARM_CFG_H
#define OS_ALARM_CFG_H
/* automatically generated by mOS Configurator xls v3.1 */
/* Generation time: 10-02-2025 11:13:58 */



/*****************************************************************************
*                            Include files                                   *
*****************************************************************************/



/*****************************************************************************
*                                 Macro Definitions                          *
*----------------------------------------------------------------------------*
* Definition of macro shall be followed by a comment that explains the       *
* purpose of the macro.                                                      *
*****************************************************************************/

#define OsNumberOfAlarms             28U

/* Alarms */

#define Rte_Al_TE2_OsTask_Diagnostics_0_10ms (0U)
#define Rte_Al_TE2_OsTask_Mcal_10msLP_0_10ms (1U)
#define Rte_Al_TE2_OsTask_MemSer_0_10ms (2U)
#define Rte_Al_TE2_OsTask_ModeMgt_5msLP_0_5ms (3U)
#define Rte_Al_TE_Ea_Ea_MainFunction (4U)
#define Rte_Al_TE_GdtCdd_CGdtCdd_Impl_MainFunction (5U)
#define Rte_Al_TE_NvMExt_NvMExt_SpeedupRunnable (6U)
#define Rte_Al_TE_OsTask_AppFun_0_10ms (7U)
#define Rte_Al_TE_OsTask_CANFun_0_10ms (8U)
#define Rte_Al_TE_OsTask_Diagnostics_0_100ms (9U)
#define Rte_Al_TE_OsTask_Diagnostics_0_10ms (10U)
#define Rte_Al_TE_OsTask_DispFun_0_10ms (11U)
#define Rte_Al_TE_OsTask_DispFun_0_5ms (12U)
#define Rte_Al_TE_OsTask_EthFun_0_10ms (13U)
#define Rte_Al_TE_OsTask_Mcal_0_10ms (14U)
#define Rte_Al_TE_OsTask_MemSer_0_10ms (15U)
#define Rte_Al_TE_OsTask_SafeApp_0_30ms (16U)
#define Rte_Al_TE_OsTask_SafeBsw_0_10ms (17U)
#define Rte_Al_TE_OsTask_TripFun_0_50ms (18U)
#define Rte_Al_TE_OsTask_WdgMngt_0_10ms (19U)
#define Rte_Al_TE_SafeBsw_OsTask_SafeBsw_WdgM_CheckPoint_20ms (20U)
#define Rte_Al_TE_Test_Comp_AudioTaskStubRunnable (21U)
#define Rte_Al_TE_Test_Comp_FotaTaskStubRunnable (22U)
#define Rte_Al_TE_Test_Comp_GaugeTaskStubRunnable (23U)
#define Rte_Al_TE_Test_Comp_IndTaskStubRunnable (24U)
#define Rte_Al_TE_Test_Comp_LinTaskStubRunnable (25U)
#define Rte_Al_TE_Test_Comp_WarnTaskStubRunnable (26U)
#define Rte_Al_TE_UclProxyCdd_CUclProxyCdd_Impl_MainFunction (27U)


/* Num of applications in alarm */
#define OsNumberOfApplicationsAlarm0                 0
#define OsNumberOfApplicationsAlarm1                 0
#define OsNumberOfApplicationsAlarm2                 0
#define OsNumberOfApplicationsAlarm3                 0
#define OsNumberOfApplicationsAlarm4                 0
#define OsNumberOfApplicationsAlarm5                 0
#define OsNumberOfApplicationsAlarm6                 0
#define OsNumberOfApplicationsAlarm7                 0
#define OsNumberOfApplicationsAlarm8                 0
#define OsNumberOfApplicationsAlarm9                 0
#define OsNumberOfApplicationsAlarm10                 0
#define OsNumberOfApplicationsAlarm11                 0
#define OsNumberOfApplicationsAlarm12                 0
#define OsNumberOfApplicationsAlarm13                 0
#define OsNumberOfApplicationsAlarm14                 0
#define OsNumberOfApplicationsAlarm15                 0
#define OsNumberOfApplicationsAlarm16                 0
#define OsNumberOfApplicationsAlarm17                 0
#define OsNumberOfApplicationsAlarm18                 0
#define OsNumberOfApplicationsAlarm19                 0
#define OsNumberOfApplicationsAlarm20                 0
#define OsNumberOfApplicationsAlarm21                 0
#define OsNumberOfApplicationsAlarm22                 0
#define OsNumberOfApplicationsAlarm23                 0
#define OsNumberOfApplicationsAlarm24                 0
#define OsNumberOfApplicationsAlarm25                 0
#define OsNumberOfApplicationsAlarm26                 0
#define OsNumberOfApplicationsAlarm27                 0


/*****************************************************************************
*                                 Alarm Table                                *
******************************************************************************/


/********************** Alarm 0 ***********************/
#define osCounterIdOfAlarm_0              NULL
#define osActivateTaskIdOfAlarm_0         NULL
#define osCbkOfAlarm_0                    NULL
#define osTaskIdOfAlarm_0                 OsTask_Diagnostics
#define osActionOfAlarm_0                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_0                Rte_Ev_Cyclic2_OsTask_Diagnostics_0_10ms
/********************** Alarm 1 ***********************/
#define osCounterIdOfAlarm_1              NULL
#define osActivateTaskIdOfAlarm_1         OsTask_Mcal
#define osCbkOfAlarm_1                    NULL
#define osTaskIdOfAlarm_1                 NULL
#define osActionOfAlarm_1                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_1                0
/********************** Alarm 2 ***********************/
#define osCounterIdOfAlarm_2              NULL
#define osActivateTaskIdOfAlarm_2         NULL
#define osCbkOfAlarm_2                    NULL
#define osTaskIdOfAlarm_2                 OsTask_MemSer
#define osActionOfAlarm_2                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_2                Rte_Ev_Cyclic2_OsTask_MemSer_0_10ms
/********************** Alarm 3 ***********************/
#define osCounterIdOfAlarm_3              NULL
#define osActivateTaskIdOfAlarm_3         OsTask_ModeMgt
#define osCbkOfAlarm_3                    NULL
#define osTaskIdOfAlarm_3                 NULL
#define osActionOfAlarm_3                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_3                0
/********************** Alarm 4 ***********************/
#define osCounterIdOfAlarm_4              NULL
#define osActivateTaskIdOfAlarm_4         NULL
#define osCbkOfAlarm_4                    NULL
#define osTaskIdOfAlarm_4                 OsTask_MemSer
#define osActionOfAlarm_4                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_4                Rte_Ev_Run_Ea_Ea_MainFunction
/********************** Alarm 5 ***********************/
#define osCounterIdOfAlarm_5              NULL
#define osActivateTaskIdOfAlarm_5         NULL
#define osCbkOfAlarm_5                    NULL
#define osTaskIdOfAlarm_5                 OsTask_LSH_16ms
#define osActionOfAlarm_5                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_5                Rte_Ev_Run_GdtCdd_CGdtCdd_Impl_MainFunction
/********************** Alarm 6 ***********************/
#define osCounterIdOfAlarm_6              NULL
#define osActivateTaskIdOfAlarm_6         NULL
#define osCbkOfAlarm_6                    NULL
#define osTaskIdOfAlarm_6                 OsTask_NvmSpeedup
#define osActionOfAlarm_6                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_6                Rte_Ev_Run_NvMExt_NvMExt_SpeedupRunnable
/********************** Alarm 7 ***********************/
#define osCounterIdOfAlarm_7              NULL
#define osActivateTaskIdOfAlarm_7         OsTask_AppFun
#define osCbkOfAlarm_7                    NULL
#define osTaskIdOfAlarm_7                 NULL
#define osActionOfAlarm_7                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_7                0
/********************** Alarm 8 ***********************/
#define osCounterIdOfAlarm_8              NULL
#define osActivateTaskIdOfAlarm_8         OsTask_CANFun
#define osCbkOfAlarm_8                    NULL
#define osTaskIdOfAlarm_8                 NULL
#define osActionOfAlarm_8                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_8                0
/********************** Alarm 9 ***********************/
#define osCounterIdOfAlarm_9              NULL
#define osActivateTaskIdOfAlarm_9         NULL
#define osCbkOfAlarm_9                    NULL
#define osTaskIdOfAlarm_9                 OsTask_Diagnostics
#define osActionOfAlarm_9                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_9                Rte_Ev_Cyclic_OsTask_Diagnostics_0_100ms
/********************** Alarm 10 ***********************/
#define osCounterIdOfAlarm_10              NULL
#define osActivateTaskIdOfAlarm_10         NULL
#define osCbkOfAlarm_10                    NULL
#define osTaskIdOfAlarm_10                 OsTask_Diagnostics
#define osActionOfAlarm_10                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_10                Rte_Ev_Cyclic_OsTask_Diagnostics_0_10ms
/********************** Alarm 11 ***********************/
#define osCounterIdOfAlarm_11              NULL
#define osActivateTaskIdOfAlarm_11         NULL
#define osCbkOfAlarm_11                    NULL
#define osTaskIdOfAlarm_11                 OsTask_DispFun
#define osActionOfAlarm_11                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_11                Rte_Ev_Cyclic_OsTask_DispFun_0_10ms
/********************** Alarm 12 ***********************/
#define osCounterIdOfAlarm_12              NULL
#define osActivateTaskIdOfAlarm_12         NULL
#define osCbkOfAlarm_12                    NULL
#define osTaskIdOfAlarm_12                 OsTask_DispFun
#define osActionOfAlarm_12                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_12                Rte_Ev_Cyclic_OsTask_DispFun_0_5ms
/********************** Alarm 13 ***********************/
#define osCounterIdOfAlarm_13              NULL
#define osActivateTaskIdOfAlarm_13         OsTask_EthFun
#define osCbkOfAlarm_13                    NULL
#define osTaskIdOfAlarm_13                 NULL
#define osActionOfAlarm_13                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_13                0
/********************** Alarm 14 ***********************/
#define osCounterIdOfAlarm_14              NULL
#define osActivateTaskIdOfAlarm_14         OsTask_Mcal
#define osCbkOfAlarm_14                    NULL
#define osTaskIdOfAlarm_14                 NULL
#define osActionOfAlarm_14                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_14                0
/********************** Alarm 15 ***********************/
#define osCounterIdOfAlarm_15              NULL
#define osActivateTaskIdOfAlarm_15         NULL
#define osCbkOfAlarm_15                    NULL
#define osTaskIdOfAlarm_15                 OsTask_MemSer
#define osActionOfAlarm_15                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_15                Rte_Ev_Cyclic_OsTask_MemSer_0_10ms
/********************** Alarm 16 ***********************/
#define osCounterIdOfAlarm_16              NULL
#define osActivateTaskIdOfAlarm_16         OsTask_SafeApp
#define osCbkOfAlarm_16                    NULL
#define osTaskIdOfAlarm_16                 NULL
#define osActionOfAlarm_16                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_16                0
/********************** Alarm 17 ***********************/
#define osCounterIdOfAlarm_17              NULL
#define osActivateTaskIdOfAlarm_17         NULL
#define osCbkOfAlarm_17                    NULL
#define osTaskIdOfAlarm_17                 OsTask_SafeBsw
#define osActionOfAlarm_17                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_17                Rte_Ev_Cyclic_OsTask_SafeBsw_0_10ms
/********************** Alarm 18 ***********************/
#define osCounterIdOfAlarm_18              NULL
#define osActivateTaskIdOfAlarm_18         OsTask_TripFun
#define osCbkOfAlarm_18                    NULL
#define osTaskIdOfAlarm_18                 NULL
#define osActionOfAlarm_18                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_18                0
/********************** Alarm 19 ***********************/
#define osCounterIdOfAlarm_19              NULL
#define osActivateTaskIdOfAlarm_19         OsTask_WdgMngt
#define osCbkOfAlarm_19                    NULL
#define osTaskIdOfAlarm_19                 NULL
#define osActionOfAlarm_19                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_19                0
/********************** Alarm 20 ***********************/
#define osCounterIdOfAlarm_20              NULL
#define osActivateTaskIdOfAlarm_20         NULL
#define osCbkOfAlarm_20                    NULL
#define osTaskIdOfAlarm_20                 OsTask_SafeBsw
#define osActionOfAlarm_20                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_20                Rte_Ev_Run_SafeBsw_OsTask_SafeBsw_WdgM_CheckPoint_20ms
/********************** Alarm 21 ***********************/
#define osCounterIdOfAlarm_21              NULL
#define osActivateTaskIdOfAlarm_21         OsTask_AudioFun
#define osCbkOfAlarm_21                    NULL
#define osTaskIdOfAlarm_21                 NULL
#define osActionOfAlarm_21                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_21                0
/********************** Alarm 22 ***********************/
#define osCounterIdOfAlarm_22              NULL
#define osActivateTaskIdOfAlarm_22         OsTask_FotaFun
#define osCbkOfAlarm_22                    NULL
#define osTaskIdOfAlarm_22                 NULL
#define osActionOfAlarm_22                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_22                0
/********************** Alarm 23 ***********************/
#define osCounterIdOfAlarm_23              NULL
#define osActivateTaskIdOfAlarm_23         OsTask_GaugeFun
#define osCbkOfAlarm_23                    NULL
#define osTaskIdOfAlarm_23                 NULL
#define osActionOfAlarm_23                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_23                0
/********************** Alarm 24 ***********************/
#define osCounterIdOfAlarm_24              NULL
#define osActivateTaskIdOfAlarm_24         OsTask_IndFun
#define osCbkOfAlarm_24                    NULL
#define osTaskIdOfAlarm_24                 NULL
#define osActionOfAlarm_24                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_24                0
/********************** Alarm 25 ***********************/
#define osCounterIdOfAlarm_25              NULL
#define osActivateTaskIdOfAlarm_25         OsTask_LinFun
#define osCbkOfAlarm_25                    NULL
#define osTaskIdOfAlarm_25                 NULL
#define osActionOfAlarm_25                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_25                0
/********************** Alarm 26 ***********************/
#define osCounterIdOfAlarm_26              NULL
#define osActivateTaskIdOfAlarm_26         OsTask_WarnFun
#define osCbkOfAlarm_26                    NULL
#define osTaskIdOfAlarm_26                 NULL
#define osActionOfAlarm_26                 ALARM_ACTIVATE_TASK_ACTION
#define osEventIdOfAlarm_26                0
/********************** Alarm 27 ***********************/
#define osCounterIdOfAlarm_27              NULL
#define osActivateTaskIdOfAlarm_27         NULL
#define osCbkOfAlarm_27                    NULL
#define osTaskIdOfAlarm_27                 OsTask_MemSer
#define osActionOfAlarm_27                 ALARM_SET_EVENT_ACTION
#define osEventIdOfAlarm_27                Rte_Ev_Run_UclProxyCdd_CUclProxyCdd_Impl_MainFunction



#endif    /* */
/* end of file */
/****************************************************************
Created Time: 10-02-2025 11:13:58
****************************************************************/
