/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  Os_Core_Cfg.h
Module Short Name:  Os_Core_Cfg.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OS_CORE_CFG_H
#define OS_CORE_CFG_H
/* automatically generated by mOS Configurator xls v3.1 */
/* Generation time: 10-02-2025 11:13:58 */



/*****************************************************************************
*                            Include files                                   *
*****************************************************************************/


/*****************************************************************************
*                                 Macro Definitions                          *
*----------------------------------------------------------------------------*
* Definition of macro shall be followed by a comment that explains the       *
* purpose of the macro.                                                      *
*****************************************************************************/

#define OsNumberOfCores             1U

/* CoreId Type */
#define OS_CFG_CORE_CORE_0        OsCoreAsr0
#define OsCoreAsr0             0UL
#define OS_CFG_CORE_COREINVALID               1UL



#endif    /* */
/* end of file */
/****************************************************************
Created Time: 10-02-2025 11:13:58
****************************************************************/
