/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  Os_IsrLcfg.h
Module Short Name:  Os_IsrLcfg.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OS_ISRLCFG_H
#define OS_ISRLCFG_H
/* automatically generated by mOS Configurator xls v3.1 */
/* Generation time: 10-02-2025 11:13:58 */



/*****************************************************************************
*                            Include files                                   *
*****************************************************************************/



/*****************************************************************************
*                                 Macro Definitions                          *
*----------------------------------------------------------------------------*
* Definition of macro shall be followed by a comment that explains the       *
* purpose of the macro.                                                      *
*****************************************************************************/




extern const OsIsrConfigType OsIsrConfig_McuOsGptIsr;
extern const OsIsrConfigType OsIsrConfig_McuCan0RxTxIsr;
extern const OsIsrConfigType OsIsrConfig_McuCan1RxTxIsr;
extern const OsIsrConfigType OsIsrConfig_McuCddIpcMbxFromA53SS_0_0Isr;
extern const OsIsrConfigType OsIsrConfig_McuSpi0NvmRxTxIsr;
extern const OsIsrConfigType OsIsrConfig_McuDss0Isr;
extern const OsIsrConfigType OsIsrConfig_McuI2c3IoIsr;
extern const OsIsrConfigType OsIsrConfig_Eth_TxIrqHdlr_0;
extern const OsIsrConfigType OsIsrConfig_Eth_RxIrqHdlr_0;
extern const OsIsrConfigType OsIsrConfig_Eth_MdioIrqHdlr;
extern const OsIsrConfigType OsIsrConfig_McuEsmIsr;
extern const OsIsrConfigType OsIsrConfig_MCU_IntrISR_UART0;
extern const OsIsrConfigType OsIsrConfig_McuI2c0PmicIsr;
extern const OsIsrConfigType OsIsrConfig_Gpt_Ch3Isr;
extern const OsIsrConfigType OsIsrConfig_Gpt_Ch4Isr;
extern const OsIsrConfigType OsIsrConfig_Spi_IrqUnitMcspi2TxRx;
extern const OsIsrConfigType OsIsrConfig_MCU_ISR_6;
extern const OsIsrConfigType OsIsrConfig_MAIN_ISR_34;
extern const OsIsrConfigType OsIsrConfig_MAIN_ISR_35;
extern const OsIsrConfigType OsIsrConfig_MCU_ISR_7;
extern const OsIsrConfigRefType OsIsrRefConfig[OsNumberOfIsr];
extern const osStackPtrType IsrStackConfig[osdNumberOfCat2ISRs];
extern const osStackDataType IsrStackSize[osdNumberOfCat2ISRs];


/* ISR function prototypes */

extern void osTimerInterruptfunc(void);
extern void Can_0_Int0ISRfunc(void);
extern void Can_1_Int0ISRfunc(void);
extern void Cdd_IpcIrqMbxFromA53SS_0_0func(void);
extern void Spi_IrqUnitMcuMcspi0TxRxfunc(void);
extern void Dss_0_Isrfunc(void);
extern void McuI2c3IoIsrfunc(void);
extern void Eth_TxIrqHdlr_0func(void);
extern void Eth_RxIrqHdlr_0func(void);
extern void Eth_MdioIrqHdlrfunc(void);
extern void WkupEsmIntrfunc(void);
extern void MCU_IntrISR_UART0func(void);
extern void McuI2c0PmicIsrfunc(void);
extern void Gpt_Ch3Isrfunc(void);
extern void Gpt_Ch4Isrfunc(void);
extern void Spi_IrqUnitMcspi2TxRxfunc(void);
extern void MCU_ISR_6func(void);
extern void MAIN_ISR_34func(void);
extern void MAIN_ISR_35func(void);
extern void MCU_ISR_7func(void);



#endif    /* */
/* end of file */
/****************************************************************
Created Time: 10-02-2025 11:13:58
****************************************************************/
