/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  Os_ResourceCfg.h
Module Short Name:  Os_ResourceCfg.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OS_RESOURCECFG_H
#define OS_RESOURCECFG_H
/* automatically generated by mOS Configurator xls v3.1 */
/* Generation time: 10-02-2025 11:13:58 */



/*****************************************************************************
*                            Include files                                   *
*****************************************************************************/
                                                                              
                                                                              
/*****************************************************************************
*                                 Macro Definitions                          *
*----------------------------------------------------------------------------*
* Definition of macro shall be followed by a comment that explains the       *
* purpose of the macro.                                                      *
*****************************************************************************/

#define NumberOfResources                    1U

#define OS_RES_TYPE_STANDARD                  0x00U
#define OS_RES_TYPE_INTERNAL                  0x01U
#define OS_RES_TYPE_LINKED                    0x02U


/* OsApp count accessing given resource */
#define OsNumberOfApplicationsSchedRes0    3



#define OsMaxPriorityLevel           26U

/* Resource IDs */

#define osdMaxTaskOfPrio0 12
#define osdMaxTaskOfPrio1 12
#define osdMaxTaskOfPrio2 12
#define osdMaxTaskOfPrio3 12
#define osdMaxTaskOfPrio4 12
#define osdMaxTaskOfPrio5 12
#define osdMaxTaskOfPrio6 12
#define osdMaxTaskOfPrio7 12
#define osdMaxTaskOfPrio8 12
#define osdMaxTaskOfPrio9 12
#define osdMaxTaskOfPrio10 12
#define osdMaxTaskOfPrio11 12
#define osdMaxTaskOfPrio12 12
#define osdMaxTaskOfPrio13 12
#define osdMaxTaskOfPrio14 12
#define osdMaxTaskOfPrio15 12
#define osdMaxTaskOfPrio16 12
#define osdMaxTaskOfPrio17 12
#define osdMaxTaskOfPrio18 12
#define osdMaxTaskOfPrio19 12
#define osdMaxTaskOfPrio20 12
#define osdMaxTaskOfPrio21 12
#define osdMaxTaskOfPrio22 12
#define osdMaxTaskOfPrio23 12
#define osdMaxTaskOfPrio24 12
#define osdMaxTaskOfPrio25 12


#endif    /* */
/* end of file */
/****************************************************************
Created Time: 10-02-2025 11:13:58
****************************************************************/
