/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  OsStacks_Lcfg.h
Module Short Name:  OsStacks_Lcfg.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OSSTACKS_LCFG_H
#define OSSTACKS_LCFG_H
/* file: C:\00_Karthikeyan\Work\MCAL\stackMonitoring\Os_Basic/OsStacks_Lcfg.h */
/* automatically generated by mOS Configurator xls v1.0 */
/* Generation time: 10-02-2025 11:13:58 */
/* vAutosar SIP Stack Generation */




osqStack1 extern osqStack2 osStackDataType osqStack3 osFIQStack [64]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osIRQCat1Stack [128]; /* PRQA S 777 */ /* PRQA S 4152 */


osqStack1 extern osqStack2 osStackDataType osqStack3 osSystemStack [256]; /* PRQA S 777 */ /* PRQA S 4152 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level0 [128]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level1 [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level2 [512]; /* PRQA S 777 */ /* PRQA S 4152 */



osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_IpcUclEvDyn [1024]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_DiagnosticsDyn [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_LSH_16msDyn [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_InitTaskDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_AppFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_AudioFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_Can0DataRxEvDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_Can1DataRxEvDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_CANFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_DispFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_EthFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_FotaEvDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_FotaFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_GaugeFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_IdleTaskDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_IndFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_LinFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_McalDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_MemSerDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_ModeMgtDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_NvmSpeedupDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_SafeAppDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_SafeBswDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_TripFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_WarnFunDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 OsStack_OsTask_WdgMngtDyn [256]; /* PRQA S 777 */ /* PRQA S 4152 */




#endif    /* */
/* end of file */
/****************************************************************
Created Time: 10-02-2025 11:13:58
****************************************************************/
