/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  OsStacks_cfg.h
Module Short Name:  OsStacks_cfg.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OSSTACKS_CFG_H
#define OSSTACKS_CFG_H
/* file: C:\00_Karthikeyan\Work\MCAL\stackMonitoring\Os_Basic/OsStacks_cfg.h */
/* automatically generated by mOS Configurator xls v1.0 */
/* Generation time: 10-02-2025 11:13:58 */
/* vAutosar SIP Stack Generation */


#define osdOsTask_IpcUclEv_BOT osBottomOfStack(OsStack_OsTask_IpcUclEvDyn)
#define osdOsTask_IpcUclEv_TOP osAssignStack(OsStack_OsTask_IpcUclEvDyn)

#define osdOsTask_Diagnostics_BOT osBottomOfStack(OsStack_OsTask_DiagnosticsDyn)
#define osdOsTask_Diagnostics_TOP osAssignStack(OsStack_OsTask_DiagnosticsDyn)

#define osdOsTask_LSH_16ms_BOT osBottomOfStack(OsStack_OsTask_LSH_16msDyn)
#define osdOsTask_LSH_16ms_TOP osAssignStack(OsStack_OsTask_LSH_16msDyn)

#define osdInitTask_BOT osBottomOfStack(OsStack_InitTaskDyn)
#define osdInitTask_TOP osAssignStack(OsStack_InitTaskDyn)

#define osdOsTask_AppFun_BOT osBottomOfStack(OsStack_OsTask_AppFunDyn)
#define osdOsTask_AppFun_TOP osAssignStack(OsStack_OsTask_AppFunDyn)

#define osdOsTask_AudioFun_BOT osBottomOfStack(OsStack_OsTask_AudioFunDyn)
#define osdOsTask_AudioFun_TOP osAssignStack(OsStack_OsTask_AudioFunDyn)

#define osdOsTask_Can0DataRxEv_BOT osBottomOfStack(OsStack_OsTask_Can0DataRxEvDyn)
#define osdOsTask_Can0DataRxEv_TOP osAssignStack(OsStack_OsTask_Can0DataRxEvDyn)

#define osdOsTask_Can1DataRxEv_BOT osBottomOfStack(OsStack_OsTask_Can1DataRxEvDyn)
#define osdOsTask_Can1DataRxEv_TOP osAssignStack(OsStack_OsTask_Can1DataRxEvDyn)

#define osdOsTask_CANFun_BOT osBottomOfStack(OsStack_OsTask_CANFunDyn)
#define osdOsTask_CANFun_TOP osAssignStack(OsStack_OsTask_CANFunDyn)

#define osdOsTask_DispFun_BOT osBottomOfStack(OsStack_OsTask_DispFunDyn)
#define osdOsTask_DispFun_TOP osAssignStack(OsStack_OsTask_DispFunDyn)

#define osdOsTask_EthFun_BOT osBottomOfStack(OsStack_OsTask_EthFunDyn)
#define osdOsTask_EthFun_TOP osAssignStack(OsStack_OsTask_EthFunDyn)

#define osdOsTask_FotaEv_BOT osBottomOfStack(OsStack_OsTask_FotaEvDyn)
#define osdOsTask_FotaEv_TOP osAssignStack(OsStack_OsTask_FotaEvDyn)

#define osdOsTask_FotaFun_BOT osBottomOfStack(OsStack_OsTask_FotaFunDyn)
#define osdOsTask_FotaFun_TOP osAssignStack(OsStack_OsTask_FotaFunDyn)

#define osdOsTask_GaugeFun_BOT osBottomOfStack(OsStack_OsTask_GaugeFunDyn)
#define osdOsTask_GaugeFun_TOP osAssignStack(OsStack_OsTask_GaugeFunDyn)

#define osdOsTask_IdleTask_BOT osBottomOfStack(OsStack_OsTask_IdleTaskDyn)
#define osdOsTask_IdleTask_TOP osAssignStack(OsStack_OsTask_IdleTaskDyn)

#define osdOsTask_IndFun_BOT osBottomOfStack(OsStack_OsTask_IndFunDyn)
#define osdOsTask_IndFun_TOP osAssignStack(OsStack_OsTask_IndFunDyn)

#define osdOsTask_LinFun_BOT osBottomOfStack(OsStack_OsTask_LinFunDyn)
#define osdOsTask_LinFun_TOP osAssignStack(OsStack_OsTask_LinFunDyn)

#define osdOsTask_Mcal_BOT osBottomOfStack(OsStack_OsTask_McalDyn)
#define osdOsTask_Mcal_TOP osAssignStack(OsStack_OsTask_McalDyn)

#define osdOsTask_MemSer_BOT osBottomOfStack(OsStack_OsTask_MemSerDyn)
#define osdOsTask_MemSer_TOP osAssignStack(OsStack_OsTask_MemSerDyn)

#define osdOsTask_ModeMgt_BOT osBottomOfStack(OsStack_OsTask_ModeMgtDyn)
#define osdOsTask_ModeMgt_TOP osAssignStack(OsStack_OsTask_ModeMgtDyn)

#define osdOsTask_NvmSpeedup_BOT osBottomOfStack(OsStack_OsTask_NvmSpeedupDyn)
#define osdOsTask_NvmSpeedup_TOP osAssignStack(OsStack_OsTask_NvmSpeedupDyn)

#define osdOsTask_SafeApp_BOT osBottomOfStack(OsStack_OsTask_SafeAppDyn)
#define osdOsTask_SafeApp_TOP osAssignStack(OsStack_OsTask_SafeAppDyn)

#define osdOsTask_SafeBsw_BOT osBottomOfStack(OsStack_OsTask_SafeBswDyn)
#define osdOsTask_SafeBsw_TOP osAssignStack(OsStack_OsTask_SafeBswDyn)

#define osdOsTask_TripFun_BOT osBottomOfStack(OsStack_OsTask_TripFunDyn)
#define osdOsTask_TripFun_TOP osAssignStack(OsStack_OsTask_TripFunDyn)

#define osdOsTask_WarnFun_BOT osBottomOfStack(OsStack_OsTask_WarnFunDyn)
#define osdOsTask_WarnFun_TOP osAssignStack(OsStack_OsTask_WarnFunDyn)

#define osdOsTask_WdgMngt_BOT osBottomOfStack(OsStack_OsTask_WdgMngtDyn)
#define osdOsTask_WdgMngt_TOP osAssignStack(OsStack_OsTask_WdgMngtDyn)

#define osdFIQStack_BOT osBottomOfStack(osFIQStack)
#define osdFIQStack_TOP osAssignStack(osFIQStack)


#define osdIRQCat1Stack_BOT osBottomOfStack(osIRQCat1Stack)
#define osdIRQCat1Stack_TOP osAssignStack(osIRQCat1Stack)


#define osdSystemStack_BOT osBottomOfStack(osSystemStack)
#define osdSystemStack_TOP osAssignStack(osSystemStack)


#define osdMcuOsGptIsr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuOsGptIsr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuCan0RxTxIsr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuCan0RxTxIsr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuCan1RxTxIsr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuCan1RxTxIsr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuCddIpcMbxFromA53SS_0_0Isr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuCddIpcMbxFromA53SS_0_0Isr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuSpi0NvmRxTxIsr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuSpi0NvmRxTxIsr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuDss0Isr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuDss0Isr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuI2c3IoIsr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuI2c3IoIsr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdEth_TxIrqHdlr_0_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdEth_TxIrqHdlr_0_TOP osAssignStack(osLevelStackCore0Level1)

#define osdEth_RxIrqHdlr_0_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdEth_RxIrqHdlr_0_TOP osAssignStack(osLevelStackCore0Level1)

#define osdEth_MdioIrqHdlr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdEth_MdioIrqHdlr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuEsmIsr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuEsmIsr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMCU_IntrISR_UART0_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMCU_IntrISR_UART0_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMcuI2c0PmicIsr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMcuI2c0PmicIsr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdGpt_Ch3Isr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdGpt_Ch3Isr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdGpt_Ch4Isr_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdGpt_Ch4Isr_TOP osAssignStack(osLevelStackCore0Level1)

#define osdSpi_IrqUnitMcspi2TxRx_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdSpi_IrqUnitMcspi2TxRx_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMCU_ISR_6_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMCU_ISR_6_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMAIN_ISR_34_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMAIN_ISR_34_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMAIN_ISR_35_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMAIN_ISR_35_TOP osAssignStack(osLevelStackCore0Level1)

#define osdMCU_ISR_7_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdMCU_ISR_7_TOP osAssignStack(osLevelStackCore0Level1)




#endif    /* */
/* end of file */
/****************************************************************
Created Time: 10-02-2025 11:13:58
****************************************************************/
