# *********************************************************************************************************************
# Company:             Johnson Controls Inc.
# ---------------------------------------------------------------------------------------------------------------------
# Copyright:           This software is JCI property.
#                      Duplication or disclosure without JCI written authorization is prohibited.
# ---------------------------------------------------------------------------------------------------------------------
# Project:             E40_Platform
# Language:            Apache ANT Properties
# ---------------------------------------------------------------------------------------------------------------------
#      DO NOT CHANGE THIS FILE! IT HAS BEEN GENERATED. ANY CHANGES WILL BE OVERWRITTEN AT THE NEXT GENERATION!
# ---------------------------------------------------------------------------------------------------------------------
# Generated on Fri Mar 22 16:34:47 IST 2024 by the JCI UML Generation chain from the "E40_Platform" model.
# ---------------------------------------------------------------------------------------------------------------------
# Entity:              MemAbstract (DesignUnit)
# Description:         None
# Owner:               SWC_PACKAGES (Package)
# ---------------------------------------------------------------------------------------------------------------------
# Rhapsody version:    9.0.1
# Generator version:   V3.0.27
# Generator date:      11/12/2014 12:04:26,40
# ---------------------------------------------------------------------------------------------------------------------
name=E40_Platform.C_GlobalDesign.SW_Classes.SWC_PACKAGES.MemAbstract
stereotype=DesignUnit,HLR
tags.list=PORT_ACCESS
tags.element.PORT_ACCESS=None # from MemAbstract (DesignUnit)
unit.file.path=E40_Platform_out/C_GlobalDesign/SW_Classes/SWC_PACKAGES/MemAbstract/MemAbstract.sbs
location=E40_Platform_out/C_GlobalDesign/SW_Classes/SWC_PACKAGES/MemAbstract
