/*
 * shutdown.h
 *
 *  Created on: 17-Aug-2020
 *      Author: DRAJ5
 */

#ifndef CLUSTER_PLATFORM_DIJKSTRA_ABSTRACTION_BSPAL_SYS_SHUTDOWN_TEST_UT_STUBS_SYS_SHUTDOWN_H_
#define CLUSTER_PLATFORM_DIJKSTRA_ABSTRACTION_BSPAL_SYS_SHUTDOWN_TEST_UT_STUBS_SYS_SHUTDOWN_H_
#define FLAG_REVERSE_ORDER		0x200
extern void shutdown_system_with_reason(int type,int flags,char* reason);
#define SHUTDOWN_REBOOT 2
#define SHUTDOWN_SYSTEM 3
#endif /* CLUSTER_PLATFORM_DInJKSTRA_ABSTRACTION_BSPAL_SYS_SHUTDOWN_TEST_UT_STUBS_SYS_SHUTDOWN_H_ */
