/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_identifiers.h                                 
**                                                                            
** Description:    This file contains the language identifier interfaces      
**                 Autogenerated by LanguageEncoder.exe Version : 1.1.0.20.          
**                 Do not handmodify this file								  
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_LANGUAGE_IDENTIFIERS_H
#define HMI_LANGUAGE_IDENTIFIERS_H
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#ifndef WIN32
#include "wchar.h"
#endif

/*============================================================================
** T Y P E   D E F I N I T I O N S                                                  
**==========================================================================*/
#ifndef LNG_UNICODE
   #define LNG_UNICODE
#endif /* LNG_UNICODE */

/* Release label major version 4 */
/* Release label minor version 12 */
#define HMI_LANG_CORE_TOOL_LABEL                  "LANG_TOOL_LABEL::rel-UI-CORE-ICEAPPLE-4.12"
#define HMI_LANG_CORE_TOOL_MAJOR_VERSION          4
#define HMI_LANG_CORE_TOOL_MINOR_VERSION          12
#define HMI_LANG_CORE_TOOL_VERSION                ((HMI_LANG_CORE_TOOL_MAJOR_VERSION * 100) + HMI_LANG_CORE_TOOL_MINOR_VERSION)

#define   HMI_LANGUAGE_UK_ENGLISH_FEAT
#define   HMI_LANGUAGE_FRENCH_FEAT
#define   HMI_LANGUAGE_US_ENGLISH_FEAT

typedef enum
{
   HMI_LANGUAGE_UK_ENGLISH,
   HMI_LANGUAGE_FRENCH,
   HMI_LANGUAGE_US_ENGLISH,
   LNG_MAX_LANGUAGE_COUNT
} HMI_LANGUAGE_T;

#define HM_LANG_MAX_STRING_SIZE         62
#define SID_WORLD                       0x0000
#define SID_HARD_WRNG                   0x0006
#define SID_SOFT_WRNG                   0x0014
#define SID_INFO_WRNG                   0x001D
#define SID_INFO_POPUP                  0x002A
#define SID_ACK_POPUP                   0x0033
#define SID_KEYPAD_POPUP                0x003D
#define SID_TxtID_1_13                  0x004A
#define SID_TxtID_1_Blank               0x004F
#define SID_HELLO                       0x0051
#define SID_PROGRESS_POPUP              0x0068
#define SID_TxtID_1_14                  0x00E9
#define SID_TxtID_1_303                 0x00FC
#define SID_TxtID_1_309                 0x0129
#define SID_TxtID_1_324                 0x015D
#define SID_TxtID_1_920                 0x0187
#define SID_TxtID_1_1024                0x01BA
#define SID_TxtID_1_1038                0x01CD
#define SID_TxtID_1_1052                0x01FD
#define SID_TxtID_1_1053                0x0216
#define SID_TxtID_1_1121                0x0233
#define SID_TxtID_1_1461                0x0254
/* Total Language Table Size = 0.61kBytes */
#define HM_LANG_MAX_PAGE                1
#define HM_LANG_MAX_SID                 0x0271u
#define HM_LANG_COMMON_MAX_SID          0x004Fu
#define HM_END_OF_SID                   (0xFFFFu)
#define HM_LANG_BUFFER_MAX_SIZE         (0x274u)        /* This is the language database size */
typedef UINT16 LANG_SID_T;

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        08/12/09     JKANOZA                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                               
/* end of file =============================================================*/ 
#endif /* HMI_LANGUAGE_IDENTIFIERS_H */
