/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2024. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 1/23/2024
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_IMG_OPENING_ANIM_0_SWR_BASEID    (0)
#define GFX_IMG_OPENING_ANIM_1_SWR_BASEID    (1)
#define GFX_IMG_OPENING_ANIM_2_SWR_BASEID    (2)
#define GFX_IMG_OPENING_ANIM_3_SWR_BASEID    (3)
#define GFX_IMG_OPENING_ANIM_4_SWR_BASEID    (4)
#define GFX_IMG_OPENING_ANIM_5_SWR_BASEID    (5)
#define GFX_IMG_OPENING_ANIM_6_SWR_BASEID    (6)
#define GFX_IMG_OPENING_ANIM_7_SWR_BASEID    (7)
#define GFX_IMG_OPENING_ANIM_8_SWR_BASEID    (8)
#define GFX_IMG_OPENING_ANIM_9_SWR_BASEID    (9)
#define GFX_IMG_OPENING_ANIM_10_SWR_BASEID   (10)
#define GFX_IMG_OPENING_ANIM_11_SWR_BASEID   (11)
#define GFX_IMG_OPENING_ANIM_12_SWR_BASEID   (12)
#define GFX_IMG_OPENING_ANIM_13_SWR_BASEID   (13)
#define GFX_IMG_OPENING_ANIM_14_SWR_BASEID   (14)
#define GFX_IMG_OPENING_ANIM_15_SWR_BASEID   (15)
#define GFX_IMG_OPENING_ANIM_16_SWR_BASEID   (16)
#define GFX_IMG_OPENING_ANIM_17_SWR_BASEID   (17)
#define GFX_IMG_OPENING_ANIM_18_SWR_BASEID   (18)
#define GFX_IMG_OPENING_ANIM_19_SWR_BASEID   (19)
#define GFX_IMG_OPENING_ANIM_20_SWR_BASEID   (20)
#define GFX_IMG_OPENING_ANIM_21_SWR_BASEID   (21)
#define GFX_IMG_OPENING_ANIM_22_SWR_BASEID   (22)
#define GFX_IMG_OPENING_ANIM_23_SWR_BASEID   (23)
#define GFX_IMG_OPENING_ANIM_24_SWR_BASEID   (24)
#define GFX_IMG_OPENING_SWR_BASEID           (25)
#define GFX_IMG_ARGB8888_SWR_BASEID          (26)
#define GFX_IMG_ARGB1555_SWR_BASEID          (27)
#define GFX_NEW_TEXTS_3_BASEID               (0)
#define GFX_INVALID_BASEID                   (0)
#define GFX_FS_BG_BASEID                     (0)
#define GFX_FILL_TEST_BASEID                 (1)
#define GFX_NEW_FILL_SCREENS_1_BASEID        (2)
#define GFX_INVALID_WDG_IMAGE_BASEID         (0)
#define GFX_WDGT_IMG_BASEID                  (0)
#define GFX_WDGT_TEXT_BASEID                 (1)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS        (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS          (0U)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS        (28)
#define GFX_MGR02_NUM_3D_MDL_LAYERS          (0)
#define GFX_MGR02_NUM_USER_LAYERS            (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS (0)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS         (1)

#define GFX_MGR02_NUM_OF_SVGS                (0)

#define GFX_MGR02_NUM_OF_SVG_CLIPS           (0)
#define GFX_MGR02_NUM_OF_FILLS               (3)
#define GFX_MGR02_NUM_OF_TILES               (0)
#define GFX_MGR02_NUM_VIDEO_LAYERS           (0)
#define GFX_MGR02_STATIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS               (2)

#define GFX_MGR02_NUM_VISIBLE_AREA      (2U)

/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (800)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (480)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_IMG_ARGB8888_ANIM                        = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_SWR|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_ARGB1555_ANIM                        = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_SWR|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_SCR_STARTUP_ANIM                         = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SCR_IMG_ANIM                             = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SCR_TEXT_ANIM                            = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS    (2)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS       (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS     (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS      (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS     (0)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS     (0)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS     (0)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS   (0)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS    (3)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS   (3)

#define GFX_MGR02_STEXTS_BUFFER_SIZE (0)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_NEW_TEXTS_3,
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (1)
#define GFX_MGR02_NUM_OF_STEXTS      (0)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (101)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (0)
#define GFX_MGR02_MAX_PATH_CMD_BUF_LENGTH   (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   __GFX_EMPTY_LIST_DWDG
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS        (0)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_DIMG_OPEN_ANIM                           = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES         (1)

#define GFX_IMG_OPENING_1                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_FS_BG_1                             GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_0_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_1_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_2_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_3_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_4_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_5_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_6_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_7_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_8_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_9_1                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_10_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_11_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_12_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_13_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_14_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_15_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_16_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_17_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_18_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_19_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_20_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_21_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_22_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_23_1               GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_IMG_OPENING_ANIM_24_1               GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_SWR)
#define GFX_WDGT_IMG_1                          GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_SWR)
#define GFX_FILL_TEST_1                         GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_WDGT_TEXT_1                         GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_PLATFORM_SWR)
#define GFX_NEW_FILL_SCREENS_1_1                GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_FILL|GFX_MGR02_PLATFORM_SWR)
#define GFX_NEW_TEXTS_3_1                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_SWR)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES       (3)
#define GFX_MGR02_NUM_SVG_INSTANCES          (0)
#define GFX_MGR02_NUM_FILL_INSTANCES         (1)
#define GFX_MGR02_NUM_TILE_INSTANCES         (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES         (2)
#define GFX_MGR02_NUM_TEXT_INSTANCES         (1)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_STARTUP                              = (0)
  ,GFX_SCR_OPENING_ANIM                         = (1)
  ,GFX_SCR_IMG                                  = (2)
  ,GFX_SCR_TEXT                                 = (3)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS                (4)
#define GFX_MGR02_LAYER0_DAR_SIZE               (5)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (1)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX         (5)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_STARTUP_BG_COLOR                            (0xFF000000UL)
#define GFX_SCR_OPENING_ANIM_BG_COLOR                       (0xFF000000UL)
#define GFX_SCR_IMG_BG_COLOR                                (0xFF000000UL)
#define GFX_SCR_TEXT_BG_COLOR                               (0xFF000000UL)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x00000000u)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (0)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1U)
#define GFX_MGR02_NUM_PRIORITY            (2)
#define GFX_MGR02_UNICODE              (1)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (100)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (0)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (0)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_ARGB8888)
#define GFX_MGR02_NEWPROJECT
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (2)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_SOFTWARE
#define GFX_MGR02_RENDER_NONE

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        1/23/2024     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
