#ifndef PORT_CFG_H
#define PORT_CFG_H

/** \brief AUTOSAR Port Port Driver
 **
 ** This file contains API definitions of the configuration of the
 ** AUTOSAR module Port that is target independent.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */
/*==================[inclusions]=============================================*/
#include <Port_Cfg_Der.h>     /* include architecture specific configuration part */

/*==================[macros]=================================================*/
#define PORT_GEN_MODULE_ID                   124U  /* Module ID */
#define PORT_GEN_VENDOR_ID                   66U   /* Vendor ID */
#define PORT_GEN_AR_RELEASE_MAJOR_VERSION    4U    /* Autosar Release Major Version */
#define PORT_GEN_AR_RELEASE_MINOR_VERSION    2U    /* Autosar Release Minor Version */
#define PORT_GEN_AR_RELEASE_REVISION_VERSION 2U    /* Autosar Release Revision Version */
#define PORT_GEN_SW_MAJOR_VERSION            1U    /* Software Major Version */
#define PORT_GEN_SW_MINOR_VERSION            18U    /* Software Minor Version */
#define PORT_GEN_SW_PATCH_VERSION            0U    /* Software Patch Version */

/* Symbolic names for user configured Port Pins */
  /* For WCO_IN */
#define PortConf_PortPin_WCO_IN    PORT_PIN_P000_0
  /* For WCO_OUT */
#define PortConf_PortPin_WCO_OUT    PORT_PIN_P000_1
  /* For ECO_IN */
#define PortConf_PortPin_ECO_IN    PORT_PIN_P000_2
  /* For ECO_OUT */
#define PortConf_PortPin_ECO_OUT    PORT_PIN_P000_3
  /* For DO_5VSW2_3V3_EN */
#define PortConf_PortPin_DO_5VSW2_3V3_EN    PORT_PIN_P001_4
  /* For CXPI_CLK */
#define PortConf_PortPin_CXPI_CLK    PORT_PIN_P001_5
  /* For CAN_TX */
#define PortConf_PortPin_CAN_TX    PORT_PIN_P001_6
  /* For CAN_RX */
#define PortConf_PortPin_CAN_RX    PORT_PIN_P001_7
  /* For DI_AL_HAZARD */
#define PortConf_PortPin_DI_AL_HAZARD    PORT_PIN_P002_1
  /* For DI_AH_IGNITION */
#define PortConf_PortPin_DI_AH_IGNITION    PORT_PIN_P002_2
  /* For MCU_SWCLK */
#define PortConf_PortPin_MCU_SWCLK    PORT_PIN_P002_4
  /* For MCU_SWDIO */
#define PortConf_PortPin_MCU_SWDIO    PORT_PIN_P002_5
  /* For CAN_STB */
#define PortConf_PortPin_CAN_STB    PORT_PIN_P003_0
  /* For DI_SMPS_3V3_PG */
#define PortConf_PortPin_DI_SMPS_3V3_PG    PORT_PIN_P003_1
  /* For STOP_LAMP_MCU */
#define PortConf_PortPin_STOP_LAMP_MCU    PORT_PIN_P004_4
  /* For PWM_GREEN_TT_DIMMING */
#define PortConf_PortPin_PWM_GREEN_TT_DIMMING    PORT_PIN_P004_5
  /* For HCAN_TX */
#define PortConf_PortPin_HCAN_TX    PORT_PIN_P004_6
  /* For HCAN_RX */
#define PortConf_PortPin_HCAN_RX    PORT_PIN_P004_7
  /* For DI_AL_FUEL_LID_EFI_ECU */
#define PortConf_PortPin_DI_AL_FUEL_LID_EFI_ECU    PORT_PIN_P005_0
  /* For CXPI_EN */
#define PortConf_PortPin_CXPI_EN    PORT_PIN_P005_1
  /* For CXPI_RX */
#define PortConf_PortPin_CXPI_RX    PORT_PIN_P005_2
  /* For CXPI_TX */
#define PortConf_PortPin_CXPI_TX    PORT_PIN_P005_3
  /* For PARK_BRAKE_TT_OUT */
#define PortConf_PortPin_PARK_BRAKE_TT_OUT    PORT_PIN_P005_4
  /* For HCAN_STB */
#define PortConf_PortPin_HCAN_STB    PORT_PIN_P005_5
  /* For DI_AL_BRAKE_LEVEL */
#define PortConf_PortPin_DI_AL_BRAKE_LEVEL    PORT_PIN_P006_0
  /* For DI_AL_OIL_W */
#define PortConf_PortPin_DI_AL_OIL_W    PORT_PIN_P006_1
  /* For DI_AL_DRV_SEAT_BUCKLE */
#define PortConf_PortPin_DI_AL_DRV_SEAT_BUCKLE    PORT_PIN_P006_2
  /* For DI_AL_WASHER_LEVEL_SW */
#define PortConf_PortPin_DI_AL_WASHER_LEVEL_SW    PORT_PIN_P006_3
  /* For ADC_FUEL_5V_MON */
#define PortConf_PortPin_ADC_FUEL_5V_MON    PORT_PIN_P007_0
  /* For ADC_FUEL_MAIN */
#define PortConf_PortPin_ADC_FUEL_MAIN    PORT_PIN_P007_1
  /* For IGN_AD */
#define PortConf_PortPin_IGN_AD    PORT_PIN_P007_2
  /* For FUEL_SEND_SUB_MICRO_AD */
#define PortConf_PortPin_FUEL_SEND_SUB_MICRO_AD    PORT_PIN_P007_3
  /* For DO_SYC1 */
#define PortConf_PortPin_DO_SYC1    PORT_PIN_P007_4
  /* For AI_BATTERY */
#define PortConf_PortPin_AI_BATTERY    PORT_PIN_P007_5
  /* For AI_LCD_NTC */
#define PortConf_PortPin_AI_LCD_NTC    PORT_PIN_P007_6
  /* For AI_TEMP_RTC */
#define PortConf_PortPin_AI_TEMP_RTC    PORT_PIN_P007_7
  /* For Flasher_Diag_sense_1 */
#define PortConf_PortPin_Flasher_Diag_sense_1    PORT_PIN_P008_0
  /* For STR_SW2_ADIN */
#define PortConf_PortPin_STR_SW2_ADIN    PORT_PIN_P008_1
  /* For STR_SW1_ADIN */
#define PortConf_PortPin_STR_SW1_ADIN    PORT_PIN_P008_2
  /* For RHEO_SW_IN_ADIN */
#define PortConf_PortPin_RHEO_SW_IN_ADIN    PORT_PIN_P008_3
  /* For ADC_RHEO_5V_MON_ADIN */
#define PortConf_PortPin_ADC_RHEO_5V_MON_ADIN    PORT_PIN_P008_4
  /* For BG_Dimming_PWM */
#define PortConf_PortPin_BG_Dimming_PWM    PORT_PIN_P008_5
  /* For SEAT_BELT_TT_MCUOUT */
#define PortConf_PortPin_SEAT_BELT_TT_MCUOUT    PORT_PIN_P008_6
  /* For ODO_TripKnobInput */
#define PortConf_PortPin_ODO_TripKnobInput    PORT_PIN_P008_7
  /* For Flasher_Diag_sense_2 */
#define PortConf_PortPin_Flasher_Diag_sense_2    PORT_PIN_P009_0
  /* For PWM_LCD_BL_DIMMING */
#define PortConf_PortPin_PWM_LCD_BL_DIMMING    PORT_PIN_P009_1
  /* For TURN_LEFT_TT_MCUOUT */
#define PortConf_PortPin_TURN_LEFT_TT_MCUOUT    PORT_PIN_P009_2
  /* For DI_AL_VACUUM */
#define PortConf_PortPin_DI_AL_VACUUM    PORT_PIN_P009_3
  /* For DI_LCD_BL_PWR_FAULT */
#define PortConf_PortPin_DI_LCD_BL_PWR_FAULT    PORT_PIN_P009_4
  /* For PWM_IN_SPEED_4P_IN */
#define PortConf_PortPin_PWM_IN_SPEED_4P_IN    PORT_PIN_P009_5
  /* For DO_LCD_BL_PWR_EN */
#define PortConf_PortPin_DO_LCD_BL_PWR_EN    PORT_PIN_P009_6
  /* For NC */
#define PortConf_PortPin_NC    PORT_PIN_P009_7
  /* For DO_3V3_DISP_SW_EN */
#define PortConf_PortPin_DO_3V3_DISP_SW_EN    PORT_PIN_P011_0
  /* For AMP_SHTD */
#define PortConf_PortPin_AMP_SHTD    PORT_PIN_P011_1
  /* For FUEL_RHEO_SUP_EN */
#define PortConf_PortPin_FUEL_RHEO_SUP_EN    PORT_PIN_P011_2
  /* For DO_LCD_STBYB */
#define PortConf_PortPin_DO_LCD_STBYB    PORT_PIN_P011_3
  /* For SBATT2_EN */
#define PortConf_PortPin_SBATT2_EN    PORT_PIN_P011_4
  /* For TT_SREG_SRCK */
#define PortConf_PortPin_TT_SREG_SRCK    PORT_PIN_P011_5
  /* For TT_SREG_SERIN */
#define PortConf_PortPin_TT_SREG_SERIN    PORT_PIN_P011_6
  /* For TT_SREG_SEROUT */
#define PortConf_PortPin_TT_SREG_SEROUT    PORT_PIN_P011_7
  /* For TT_SREG_EN */
#define PortConf_PortPin_TT_SREG_EN    PORT_PIN_P012_0
  /* For TT_SREG_CLR */
#define PortConf_PortPin_TT_SREG_CLR    PORT_PIN_P012_1
  /* For BRAKE_TT_MCUOUT */
#define PortConf_PortPin_BRAKE_TT_MCUOUT    PORT_PIN_P014_2
  /* For AIRBAG_TT_MCUOUT */
#define PortConf_PortPin_AIRBAG_TT_MCUOUT    PORT_PIN_P014_3
  /* For TT_SHIFT_ERR */
#define PortConf_PortPin_TT_SHIFT_ERR    PORT_PIN_P014_4
  /* For TURN_RIGHT_TT_MCUOUT */
#define PortConf_PortPin_TURN_RIGHT_TT_MCUOUT    PORT_PIN_P014_5
  /* For TT_SHIFT_G1_G2 */
#define PortConf_PortPin_TT_SHIFT_G1_G2    PORT_PIN_P014_6
  /* For TT_SHIFT_RCK */
#define PortConf_PortPin_TT_SHIFT_RCK    PORT_PIN_P014_7
  /* For DO_SMPS_5V_SW_EN */
#define PortConf_PortPin_DO_SMPS_5V_SW_EN    PORT_PIN_P015_0
  /* For PCS_OFF_TT_MCUOUT */
#define PortConf_PortPin_PCS_OFF_TT_MCUOUT    PORT_PIN_P015_1
  /* For ABS_TT_MCUOUT */
#define PortConf_PortPin_ABS_TT_MCUOUT    PORT_PIN_P015_2
  /* For SLIP_TT_MCUOUT */
#define PortConf_PortPin_SLIP_TT_MCUOUT    PORT_PIN_P015_3
  /* For VCS_OFF_TT_MCUOUT */
#define PortConf_PortPin_VCS_OFF_TT_MCUOUT    PORT_PIN_P015_4
  /* For HOLD_TT_MCUOUT */
#define PortConf_PortPin_HOLD_TT_MCUOUT    PORT_PIN_P015_5
  /* For ECB_EPB_TT_MCUOUT */
#define PortConf_PortPin_ECB_EPB_TT_MCUOUT    PORT_PIN_P015_6
  /* For HIGH_BEAM_TT_MCUOUT */
#define PortConf_PortPin_HIGH_BEAM_TT_MCUOUT    PORT_PIN_P015_7
  /* For FUEL_TEMP_GAUG_TEXT_PWM_OUT */
#define PortConf_PortPin_FUEL_TEMP_GAUG_TEXT_PWM_OUT    PORT_PIN_P016_0
  /* For PWM_OUT_ILL2 */
#define PortConf_PortPin_PWM_OUT_ILL2    PORT_PIN_P016_1
  /* For Flasher_FL_RL_OUT */
#define PortConf_PortPin_Flasher_FL_RL_OUT    PORT_PIN_P016_2
  /* For Flasher_DEN1 */
#define PortConf_PortPin_Flasher_DEN1    PORT_PIN_P016_3
  /* For PWM_OUT_ILL1 */
#define PortConf_PortPin_PWM_OUT_ILL1    PORT_PIN_P016_4
  /* For Flasher_DSEL1 */
#define PortConf_PortPin_Flasher_DSEL1    PORT_PIN_P016_5
  /* For Flasher_FR_RR_OUT */
#define PortConf_PortPin_Flasher_FR_RR_OUT    PORT_PIN_P016_6
  /* For MCU_HFLASH_DQ4 */
#define PortConf_PortPin_MCU_HFLASH_DQ4    PORT_PIN_P018_0
  /* For MCU_HFLASH_DQ2 */
#define PortConf_PortPin_MCU_HFLASH_DQ2    PORT_PIN_P018_1
  /* For MCU_HFLASH_DQ3 */
#define PortConf_PortPin_MCU_HFLASH_DQ3    PORT_PIN_P018_2
  /* For MCU_HFLASH_DQ5 */
#define PortConf_PortPin_MCU_HFLASH_DQ5    PORT_PIN_P018_3
  /* For MCU_HFLASH_DQ0 */
#define PortConf_PortPin_MCU_HFLASH_DQ0    PORT_PIN_P018_4
  /* For MCU_HFLASH_DQ6 */
#define PortConf_PortPin_MCU_HFLASH_DQ6    PORT_PIN_P018_5
  /* For MCU_HFLASH_DQ1 */
#define PortConf_PortPin_MCU_HFLASH_DQ1    PORT_PIN_P018_6
  /* For MCU_HFLASH_DQ7 */
#define PortConf_PortPin_MCU_HFLASH_DQ7    PORT_PIN_P018_7
  /* For MCU_HFLASH_CLK */
#define PortConf_PortPin_MCU_HFLASH_CLK    PORT_PIN_P019_0
  /* For MCU_HFLASH_RWDS */
#define PortConf_PortPin_MCU_HFLASH_RWDS    PORT_PIN_P019_1
  /* For MCU_HFLASH_CS0 */
#define PortConf_PortPin_MCU_HFLASH_CS0    PORT_PIN_P019_2
  /* For DO_FLASH_RESET */
#define PortConf_PortPin_DO_FLASH_RESET    PORT_PIN_P019_3
  /* For MCU_HRAM_DQ4 */
#define PortConf_PortPin_MCU_HRAM_DQ4    PORT_PIN_P020_0
  /* For MCU_HRAM_DQ2 */
#define PortConf_PortPin_MCU_HRAM_DQ2    PORT_PIN_P020_1
  /* For MCU_HRAM_DQ3 */
#define PortConf_PortPin_MCU_HRAM_DQ3    PORT_PIN_P020_2
  /* For MCU_HRAM_DQ5 */
#define PortConf_PortPin_MCU_HRAM_DQ5    PORT_PIN_P020_3
  /* For MCU_HRAM_DQ0 */
#define PortConf_PortPin_MCU_HRAM_DQ0    PORT_PIN_P020_4
  /* For MCU_HRAM_DQ6 */
#define PortConf_PortPin_MCU_HRAM_DQ6    PORT_PIN_P020_5
  /* For MCU_HRAM_DQ1 */
#define PortConf_PortPin_MCU_HRAM_DQ1    PORT_PIN_P020_6
  /* For MCU_HRAM_DQ7 */
#define PortConf_PortPin_MCU_HRAM_DQ7    PORT_PIN_P020_7
  /* For MCU_HRAM_CLK */
#define PortConf_PortPin_MCU_HRAM_CLK    PORT_PIN_P021_0
  /* For MCU_HRAM_RWDS */
#define PortConf_PortPin_MCU_HRAM_RWDS    PORT_PIN_P021_1
  /* For MCU_HRAM_CS0 */
#define PortConf_PortPin_MCU_HRAM_CS0    PORT_PIN_P021_2
  /* For DO_LCD_RST */
#define PortConf_PortPin_DO_LCD_RST    PORT_PIN_P021_3

/* Symbolic names for user configured AMUX splitter cells */
  /* For PortAmuxSplitCell_0 */
#define PortConf_PortAmuxSplitCell_PortAmuxSplitCell_0    PORT_AMUX_CELL_0

/* Symbolic names for user configured Trigger groups */
#define PortConf_PortTrGroupContainer_PortTrGroupContainer_0        PORT_TR_GROUP_PDMA0_0_15
#define PortConf_PortTr1To1GroupContainer_PortTr1To1GroupContainer_0    PORT_TR_1TO1_GROUP_TO_PDMA0

/* Symbolic names for user configured Output triggers */
#define PortConf_PortOutputTrigger_PortOutputTrigger_0        PORT_TR_GROUP_PDMA0_0_15_OUT_CPUSS_DW0_TR_IN_0
#define PortConf_Port1To1OutputTrigger_Port1To1OutputTrigger_0    PORT_TR_1TO1_GROUP_TO_PDMA0_OUT_CPUSS_DW0_TR_IN_32

/* PortConfigSet container short name  */
#define PortConf_PortConfigSet_PortConfigSet_Active    (Port_Config[0])
#define PortConf_PortConfigSet_PortConfigSet_Sleep    (Port_Config[1])

/* User configured API defines */
#define PORT_SET_PIN_DIRECTION_API        STD_ON
#define PORT_SET_PIN_MODE_API             STD_ON
#define PORT_VERSION_INFO_API             STD_ON
#define PORT_SAFETY_FUNCTION_API          STD_ON
#define PORT_SET_DIO_ALTERNATE_MODE_API   STD_ON
#define PORT_SET_TRIGGER_API              STD_ON
#define PORT_TRIGGER_COMMAND_API          STD_ON

/* User configured DET defines */
#define PORT_DEV_ERROR_DETECT             STD_ON

/** This parameter defines the existence and the name of a callout function
 that is called each time an error was detected.
 The function has to have the following parameters: (ModuleId: uint16,
 InstanceId: uint8, ApiId: uint8, ErrorId: uint8) */
#define PORT_ERROR_CALLOUT_FUNCTION ErrorCalloutHandler

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* PORT_CFG_H  */
/*==================[end of file]============================================*/
