/*
 * doip_routine.h
 *
 *  Created on: May 19, 2020
 *      Author: MMK
 */

#ifndef DOIP_ROUTINE_H
#define DOIP_ROUTINE_H

/* Subfunction Identifiers */
#define UDS_MGR_ROUTINE_SUBFUNC_ID_START (0x01u)
#define UDS_MGR_ROUTINE_SUBFUNC_ID_STOP (0x02u)
#define UDS_MGR_ROUTINE_SUBFUNC_ID_RESULTS (0x03u)

#define UDS_MGR_ROUTINE_ID_RUNDTCTEST (0xFF06u)
#define UDS_MGR_ROUTINE_ID_CHECKPROGRAMDEPENDENCIES (0xFF01u)

/* global DTC */
#define UDS_MGR_ROUTINE_RUNDTC_STATUSRECORD_BYTE1 (0x10u)

/* Routine Offset Macros */
#define UDS_MGR_ROUTINE_ID_SUBFUNC_OFFSET (0u)
#define UDS_MGR_ROUTINE_ID_SUBFUNC_SIZE (1u)
#define UDS_MGR_ROUTINE_ID_OFFSET (UDS_MGR_ROUTINE_ID_SUBFUNC_OFFSET + UDS_MGR_ROUTINE_ID_SUBFUNC_SIZE)
#define UDS_MGR_ROUTINE_ID_SIZE (2u)
#define UDS_MGR_ROUTINE_RECORD_OFFSET (UDS_MGR_ROUTINE_ID_OFFSET + UDS_MGR_ROUTINE_ID_SIZE)
#define UDS_MGR_ROUTINE_RECORD_SIZE (2u)
#define UDS_MGR_ROUTINE_DTCNUMBER_OFFSET (UDS_MGR_ROUTINE_RECORD_OFFSET + UDS_MGR_ROUTINE_RECORD_SIZE)

#define UDS_MGR_LOGICALZONESCOUNT                    2U
#define UDS_MGR_GLOBALDTCCOUNT                           1
#define UDS_MGR_BASEDTCMIN                               ( 0xFD00U)
#define UDS_MGR_BASEDTCMAX       ((UDS_MGR_BASEDTCMIN + (UDS_MGR_LOGICALZONESCOUNT - 1)))
#define UDS_MGR_ALLDTCMAX        ((UDS_MGR_BASEDTCMIN + ((UDS_MGR_LOGICALZONESCOUNT + UDS_MGR_GLOBALDTCCOUNT) - 1)))
#define UDS_MGR_GLOBALDTC        ((UDS_MGR_BASEDTCMIN + ((UDS_MGR_LOGICALZONESCOUNT + UDS_MGR_GLOBALDTCCOUNT) - 1)))

#define UDS_MGR_RCREQUEST_DTCLOGZONEIDMIN                  UDS_MGR_BASEDTCMIN
#define UDS_MGR_RCREQUEST_DTCLOGZONEIDMAX                  UDS_MGR_BASEDTCMAX
#define UDS_MGR_RCREQUEST_DTCGLOBALID                      UDS_MGR_GLOBALDTC
#define UDS_MGR_VALIDDTC                         ((uint8_t) 0x51U)

#define ASCII_TO_HEX(x) ((((x) > '9') ? ((x) + 9) : (x)) & 0x0Fu)
#define ASCII_TO_UINT8(x) ((ASCII_TO_HEX((x)[0]) << 4u) | ASCII_TO_HEX((x)[1]))
#define UINT8_TO_UINT16(h, l) ((uint16_t)((uint16_t)(h) << 8u) | ((uint16_t)(l)))

#endif /* DOIP_ROUTINE_H */
