 /*****************************************************************************   
 *                                                                            *   
 *              CONFIDENTIAL VISTEON CORPORATION                              *   
 *                                                                            *   
 * This is an unpublished work of authorship, which contains trade            *   
 * secrets, created in 2013. Visteon Corporation owns all rights to           *   
 * this work and intends to maintain it in confidence to preserve             *   
 * its trade secret status. Visteon Corporation reserves the right,           *   
 * under the copyright laws of the United States or those of any              *   
 * other country that may have jurisdiction, to protect this work             *   
 * as an unpublished work, in the event of an inadvertent or                  *   
 * deliberate unauthorized publication. Visteon Corporation also              *   
 * reserves its rights under all copyright laws to protect this               *   
 * work as a published work, when appropriate. Those having access            *   
 * to this work may not copy it, use it, modify it or disclose the            *   
 * information contained in it without the written authorization              *   
 * of Visteon Corporation.                                                    *   
 *                                                                            *   
 ******************************************************************************/  
 /*****************************************************************************   
                                                                                  
 File Name        :  di_warnings_constants.inc 
 Module Short Name:  warnings                                                          
 VOBName          :   
 Author           :  Auto generated 
 Description      :  Interface file.                           
 Organization     :  Driver Information Software Section,                         
                     Visteon Corporation                                          
 ----------------------------------------------------------------------------     
 Compiler Name    :                                                               
 Target Processor :                                                               
                                                                                  
 *******************************************************************************/  
                                                                                  
 
                                                                                  
 /*****************************************************************************   
 *                                 System Includes                            *   
 ******************************************************************************/  
 
 
 /*****************************************************************************   
 *                                 Project Includes                           *   
 ******************************************************************************/  
 
 
 
 
 /*****************************************************************************   
 *                                 Manifest Constants                         *   
 *----------------------------------------------------------------------------*   
 * Definition of constant shall be followed by a comment that explains the    *   
 * purpose of the constant.                                                   *   
 ******************************************************************************/  
 
 
 /*****************************************************************************   
 *                                 Macro Definitions                          *   
 *----------------------------------------------------------------------------*   
 * Definition of macro shall be followed by a comment that explains the       *   
 * purpose of the macro.                                                      *   
 ******************************************************************************/  
 
 
 
UI_WARNING_DETAIL_DATA_T const c_warning_detail_U16A[] =
{
    {NULL ,NULL ,CLR_DUR_TRANS_TO_OFF ,NO ,NO ,NO},
};
