/*
 * \file hsm_data.h
 *
 * \brief Interface glue between TIFS interface and internal operation
 *
 * Copyright (C) 2020-2021 Texas Instruments Incorporated - http://www.ti.com/
 * ALL RIGHTS RESERVED
 */


#ifndef HSM_DATA_H
#define HSM_DATA_H

#include <config.h>
#include <types/ftbool.h>
#include <msg/msg_private.h>
#include <hsm_core/hsm.h>
#include <dmsc_core.h>

/** TIFS-managed events generated from secure proxy message threshold */
#define TIFS_EVT_TYPE_SEC_PROXY_MSG  (u8) 0x5AU

/** TIFS-managed events generated from secure peripherals (firewall, jtag) */
#define TIFS_EVT_TYPE_SEC_PERIPHERAL (u8) 0xA5U

/* Forward declaration of structure */
struct hsm_evt_data;

typedef s32 (*hsm_irq_handler)(struct hsm_evt_data *evt_data);
typedef s32 (*hsm_proc_handler)(struct hsm_evt_data *evt_data);

/**
 * \brief ISR handler for secure proxy events
 *
 * This is the handler invoked when an interrupt is received due to an event
 * generated by receiving a secure proxy message.
 *
 * \param evt_data hsm_evt_data structure corresponding to the irq responsible
 *                 for triggering the interrupt.
 * \return Success if message parsed successfully, otherwise returns error.
 */
s32 sec_proxy_isr_handler(struct hsm_evt_data *evt_data);

/**
 * \brief Process handler for secure proxy events
 *
 * This is the handler invoked when processing an interrupt from an event
 * generated by receiving a secure proxy message.
 *
 * \param evt_data hsm_evt_data structure corresponding to the irq responsible
 *                 for triggering the interrupt.
 *
 * \return Success if message processed successfully, otherwise returns error.
 */
s32 sec_proxy_process_handler(struct hsm_evt_data *evt_data);

/**
 * \brief Process handler for secure peripheral events
 *
 * This is the handler invoked when processing an interrupt from an event
 * generated by firewall exception or JTAG connection
 *
 * \param evt_data hsm_evt_data structure corresponding to the irq responsible
 *                 for triggering the interrupt.
 *
 * \return Success if event processed successfully, otherwise returns error.
 */
s32 sec_int_process_handler(struct hsm_evt_data *evt_data);

/**
 * \struct hsm_queue_evt_data
 * \brief Contains data needed for secure HWI operation.
 *
 * \param hw_msg_queue_id The ID of the hardware message queue this HWI
 *			  services.
 * \param hw_msg_buffer A static buffer the size of the hardware message queue
 *			to store the message for sharing with a worker task.
 * \param hw_msg_buffer_sz The size of hw_msg_buffer in bytes.
 * \param forwarded_hw_msg_buffer A static buffer the size of the hardware
 *				  message queue to store the message for
 *				  sharing with a worker task at a different
 *				  execution level, currently only for
 *				  forwarding secure buffers to user task.
 * \param forwarded_hw_msg_buffer_sz The size of forwarded_hw_msg_buffer in
 *				     bytes.
 * \param secure_msg_data Pointer to store message origin data for the
 *			  currently received secure message that is shared with
 *			  secure worker tasks.
 * \param user_msg_data Pointer to store message origin data for the
 *			currently received user message that is shared with
 *			user worker tasks.
 * \param is_secure Flag to indicate if this queue receives secure messages.
 */
struct hsm_queue_evt_data {
	const u16		hw_msg_queue_id;
	u32 *const		hw_msg_buffer;
	const u32		hw_msg_buffer_sz;
	struct msg_data *const	secure_msg_data;

	struct msg_data *const	user_msg_data;
	u32 *const		forwarded_hw_msg_buffer;
	const u32		forwarded_hw_msg_buffer_sz;

	const sbool		is_secure;
};

/**
 * \struct hsm_queue_evt_data
 *
 * \param irq_num The irq number for this HWI.
 * \param priority Priority level passed to the OSAL of this interrupt. This
 *		   is the priority level within the hardware and should match all
 *		   other HWIs defined at the same logical queue priority and
 *		    execution level.
 * \param active Whether the current event is actively being serviced
 * \param evt_type identifier for type of event associated with this irq
 * \param int_data Specific data for this irq
 * \param irq_handler Handler to be invoked by the TIFS ISR handler
 * \param proc_handler Handler to be invoked by the TIFS process handler
*/
struct hsm_evt_data {
	const u32		irq_num;
	const s32		priority;
	ftbool			active;
	u8			evt_type;
	union {
		struct hsm_queue_evt_data msg_data;
	} int_data;
	hsm_irq_handler	irq_handler;
	hsm_proc_handler	proc_handler;
};

/**
 * \brief List of TIFS events, sorted in prioritized order
 *
 * The event list is sorted according to the following priority order
 * * Secure peripheral interrupts (firewall, JTAG)
 * * Message forward sec_proxy queues
 * * High priority sec_proxy queues
 * * Low priority sec_proxy queues
 *
 * It is expected that the priorities registered in the interrupt controller are
 * consistent across a given priority group in order to prevent race conditions
 * due to nested prioritized interrupts.
 */
extern struct hsm_evt_data hsm_evt_data_list[];

/** \brief size of the hsm_evt_data_list */
extern u32 hsm_evt_data_list_size;
extern u32 HSMintrupt_host;

#endif /* TIFS_DATA_H */
