///////////////////////////////////////////////////////////////////////////////
//
//                     CONFIDENTIAL VISTEON CORPORATION
//
// This is an unpublished work of authorship, which contains trade secrets,
// created in 2018. Visteon Corporation owns all rights to this work and
// intends to maintain it in confidence to preserve its trade secret status.
// Visteon Corporation reserves the right, under the copyright laws of the
// United States or those of any other country that may have jurisdiction,
// to protect this work as an unpublished work, in the event of an
// inadvertent or deliberate unauthorized publication. Visteon Corporation
// also reserves its rights under all copyright laws to protect this work as
// a published work, when appropriate. Those having access to this work may
// not copy it, use it, modify it or disclose the information contained in
// it without the written authorization of Visteon Corporation.
//
/// @file gfx3d_scg_gloabl_data.h
/// @author ssharm20@visteon.com
/// @brief holds the project scope global data. 
/// @date 11-Sep-2018
/// @copyright © 2019, Visteon Corporation, All Rights Reserved
///////////////////////////////////////////////////////////////////////////////
#ifndef gfx3d_scg_gloabl_data_h
#define gfx3d_scg_gloabl_data_h

#include <mutex>
#include <map>

namespace rendercore_engine
{
    const uint32_t RC_MAT_INVALID_SHADER_ID = 0xFFFFFFFFU;	///< invalid shader ID
    const uint32_t RC_MAT_DEFAULT_SHADER_ID = 0xFFFFFFFDU;	///< default shader ID
    const uint32_t RC_MAT_AUTO_SHADER_ID_ST = 0x80000000U;	///< auto shader ID start value
    class gfx3d_scg_project;
    /// <summary>
    /// Keeps track of shader program objects for a project instance
    /// </summary>
    class gfx3d_glslshader_properties
    {
    private:
        std::map<uint32_t, rc_glslShaderObj> shaderObjects[static_cast<size_t>(rc_glslShaderType::Total)];
        std::map<uint32_t, rc_glslProgramObj> programObjects{};
    protected:
#if ((RC_MTHREADS & RC_MTHREAD_RENDERING) != 0)
        std::recursive_mutex sdata_mutex; ///< mutex to protect all static data access by threads
#endif
    public:
        rc_glslShaderObj& get_shader_obj(const uint32_t p_id, std::map<uint32_t, rc_glslShaderObj>& p_map);
        rc_glslShaderObj& GetVertShaderObj(const uint32_t p_id);
        rc_glslShaderObj& GetFragShaderObj(const uint32_t p_id);
        void ShClearAll();
        bool ShClear(const uint32_t p_sid, std::map<uint32_t, rc_glslShaderObj>& p_map);
        bool ShClear(const uint32_t p_sid, const rc_glslShaderType p_type);
        /// <summary>
        /// searches the p_map for passed shader key (ID) and if found, then returns
        /// the shader program object corresponding to it.
        /// if not found an empty rc_glslObj is returned, so that a new shader program
        /// can be created.
        /// </summary>
        /// <param name="p_id">shader key to be searched in map file</param>
        /// <returns>returns shader object </returns>
        rc_glslProgramObj& GetProgShaderObj(const uint32_t p_id);
        GLuint GetGLProgObj(const uint32_t p_id);
        void PgmClearAll();
        bool PgmClear(const uint32_t p_sid);

    };
    /// <summary>
    /// Project's global data class for material. 
    /// Keeps track of active material instances, default textures and shader ID generation
    /// </summary>
    class gfx3d_material_properties : public gfx3d_glslshader_properties
    {
    private:
        GLuint defTexObj = 0U;   ///< GL id for a default black texture to be used when there is no user supplied texture for a uniform
        GLuint defCTexObj = 0U;  ///< GL id for a default black cubemap texture to be used when there is no user supplied texture for a uniform
        GLuint ppVbo = 0U;       ///< GL vertex buffer object for the post process stage material   
        /// <summary>
        /// Total number of instances of material used by the application
        /// its used to determine when to release all static data (on event matInstances '> 0' to '0')
        /// and when to initialize them (on event matInstances '0' to '> 0')
        /// </summary>
        size_t matInstances = 0U;
        /// Used to generate vs_uid/fs_uid/po_uid when they are invalid
        /// RC_MAT_AUTO_SHADER_ID_ST - 0x0xFFFFFFFC are used for auto numbering
        /// Note:- 0 to 0x7FFFFFFF (RC_MAT_AUTO_SHADER_ID_ST-1) are reserved for
        /// rdf_cpp autogeneration
        /// These ranges itself are huge as we dont normally expect even > 100 shaders
        uint32_t shaderID = 0U;
        /// <summary>
        /// When a material gets deleted, the autogenerated shader ID becomes
        /// unused. Those IDs are feed to this vector, so that they can be reused
        /// when a new material gets created by the user at run time.
        /// </summary>
        std::vector<uint32_t> unusedShaderIDs;
#if (GLES3_RENDERER < 30)
#if defined(RC_GL_PGMBIN_EXTN_STATICLOAD)
#elif defined(RC_GL_PGMBIN_EXTN_DYNAMICLOAD)
        PFNGLPROGRAMBINARYOESPROC rcgl_ProgramBinary = nullptr;
#endif
#endif
    public:
        /// <summary>
        /// Register removal of a material instance
        /// Note : Every call to addMaterialInstance must have a rmoveMaterialInstance
        /// </summary>
        /// <returns>true if success.</returns>
        bool rmoveMaterialInstance();
        /// <summary>
        /// Register a material instance. Called when a new instance is created
        /// </summary>
        void addMaterialInstance();
        /// <summary>
        /// Removes a shader ID that was generated earlier. So that it can be reused later
        /// </summary>
        /// <param name="p_shid">shader ID</param>
        void removeShaderID(const uint32_t p_shid);
        /// <summary>
        /// Generates a shader ID
        /// </summary>
        uint32_t generateShaderID();
        /// <summary>
        /// Get the default texture ID to be used
        /// </summary>
        GLuint getDefaultTextureID();
        /// <summary>
        /// Gets the default cubemap texture ID to be used
        /// </summary>
        GLuint getDefaultCubemapTextureID();
        /// <summary>
        /// Gets the currently active material instances
        /// </summary>
        size_t getMatInstaces() const;
        /// <summary>
        /// Sets up the vertex buffer data for the post process stage material
        /// (Vertex data is set to draw a quad)
        /// </summary>
        /// <param name="p_mat">post process stage material</param>
        void setupPPVertexBuffer(gfx3d_scg_material* p_mat);
    };
    class rc_hbfe_global_state;
    class rc_mtfe_global_state;
    /// <summary>
    /// Font global data instance for a project
    /// </summary>
    class gfx3d_font_properties
    {
    private:
        char32_t default_character = static_cast<char32_t>(0xFFFD); ///< is a default character in the font whenever any Unicode is missing
#if ((RC_MTHREADS & RC_MTHREAD_RENDERING) != 0)
        mutable std::recursive_mutex font_mutex;
#endif
        rc_hbfe_global_state* hbfeState = nullptr;
        rc_mtfe_global_state* mtfeState = nullptr;
    public:
        ~gfx3d_font_properties();
        /// <summary>
        /// Returns the fonts default character code
        /// </summary>
        /// <returns>returns font's default character </returns>
        char32_t GetDefaultChar() const;
        /// <summary>
        /// Set default character all fonts
        /// If the given text string has character codes not present in font
        /// file, it will be replaced with this default character
        /// Its default value is Unicode 0xFFFD
        /// </summary>
        /// <param name="p_default_char"> font's default character </param>
        void SetDefaultChar(const char32_t p_default_char);
#if ((RC_MTHREADS & RC_MTHREAD_RENDERING) != 0)
        /// <summary>
        /// Return the global mutex
        /// </summary>
        /// <returns></returns>
        std::recursive_mutex& GetMutex() const;
#endif
        rc_hbfe_global_state* GetHbFeGlobalState() const;
        rc_hbfe_global_state* CreateHbFeGlobalState(gfx3d_scg_project* const p_project);
        rc_mtfe_global_state* GetMtFeGlobalState() const;
        rc_mtfe_global_state* CreateMtFeGlobalState(gfx3d_scg_project* const p_project);
    };
    struct gfx3d_global_data
    {
        gfx3d_material_properties matGProp;
        gfx3d_font_properties fntGProp;
    };
}
#endif