/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2010. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**============================================================================
**
** Name:           gdg02_image_data.c
**
** Description:    This file is used by the application code to determine
**                 where graphic pixel data generated by the GDT tool
**                 should reside in memory.  The two choices are internal
**                 flash or external flash (accessed via the QSPI
**                 peripheral).  Details on how to make the selection are
**                 available below.
**
** Organization:   Driver Information Software Section,
**                 DI Core Engineering Department
**
**============================================================================
**
**==========================================================================*/
#define GDG02_IMAGE_DATA_C

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "system.h"

/*
** For files in external flash memory, #include them as in the example below.
** Note the use of #pragmas.
*/
#ifndef WIN32
   typedef UINT8  GFX_IMG_DATA_T    __attribute__ ((aligned (8)));
   typedef UINT16 GFX_IMG_DATA16_T  __attribute__ ((aligned (8)));
   typedef UINT32 GFX_IMG_DATA32_T  __attribute__ ((aligned (8)));
#else
   typedef UINT8  GFX_IMG_DATA_T;
   typedef UINT16 GFX_IMG_DATA16_T;
   typedef UINT32 GFX_IMG_DATA32_T;
#endif

#define GFX_IMG_DATA_PREFIX
/*
** For files in internal flash memory, #include them as in the example below.
** Note that nothing special needs to be done.
*/

#include "img_track_apps_race_lights_tree.dat"
#include "img_track_apps_race_lights_big.dat"
#include "img_0_grey.dat"
#include "img_0_white.dat"
#include "img_1_white.dat"
#include "img_2_white.dat"
#include "img_3_white.dat"
#include "img_4_white.dat"
#include "img_5_white.dat"
#include "img_6_white.dat"
#include "img_7_white.dat"
#include "img_8_white.dat"
#include "img_9_white.dat"
#include "img_white_mi.dat"
#include "img_white_km.dat"
#include "img_white_dot.dat"
#undef GFX_IMG_DATA_PREFIX

#if defined(MATLAB_MEX_FILE)||defined(WIN32)
	#define GFX_IMG_DATA_PREFIX
#else
	#pragma push
	#pragma section "QSPI0_FLASH"
	#define GFX_IMG_DATA_PREFIX   __declspec(section "QSPI0_FLASH")
#endif
#include "SplashScreenLayer1.dat"
#include "SplashScreenLayer2.dat"
#include "SplashScreenLayer3.dat"
#include "SplashScreenLayer4.dat"
#include "SplashScreenLayer5.dat"
#include "SplashScreenLayer6.dat"
#include "SplashScreenLayer7.dat"
#include "SplashScreenLayer8.dat"
#include "SplashScreenLayer9.dat"
#include "SplashScreenLayer10.dat"
#include "SplashScreenLayer11.dat"
#include "SplashScreenLayer12.dat"
#include "SplashScreenLayer13.dat"
#include "SplashScreenLayer14.dat"
#include "SplashScreenLayer15.dat"
#include "SplashScreenLayer16.dat"
#include "SplashScreenLayer17.dat"
#include "SplashScreenLayer18.dat"
#include "SplashScreenLayer19.dat"
#include "SplashScreenLayer20.dat"
#include "img_4bpp_bmp.dat"
#include "img_2bpp_bmp.dat"
#include "img_1bpp_bmp.dat"
#include "img_8bpp_smiley_bmp.dat"
#include "img_4bpp_widget_1.dat"
#include "img_4bpp_widget_2.dat"
#include "trip_bkgnd_grid_b.dat"
#include "img_trip_icon_a.dat"
#include "img_trip_icon_b.dat"
#include "img_ife_scale_bkgnd.dat"
#include "img_statusbluebar.dat"
#include "acc_seperator.dat"
#include "acc_title_icon.dat"
#include "acc_car_icon_dist_1.dat"
#include "acc_car_icon_dist_2.dat"
#include "acc_car_icon_dist_3.dat"
#include "acc_car_icon_dist_4.dat"
#include "wrn_brake_ico.dat"
#include "info_area_block.dat"
#include "img_4bpp_widget_0_0_0.dat"
#include "img_32bpp_bmp.dat"
#include "img_24bpp_bmp.dat"
#include "img_rgb565_bmp.dat"
#include "img_8bpp_bmp.dat"
#include "img_argb1555_bmp.dat"
#include "img_argb4444_bmp.dat"
#include "img_8bpp_alpha.dat"
#include "img_4bpp_alpha.dat"
#include "img_8bpp_tt1.dat"
#include "img_8bpp_tt2.dat"
#include "img_8bpp_tt3.dat"
#include "img_8bpp_tt4.dat"
#include "img_8bpp_tt5.dat"
#include "img_8bpp_tt6.dat"
#include "img_32bpp_png.dat"
#include "img_race_green_big.dat"
#include "img_race_green_small.dat"
#include "img_race_yellow_double1.dat"
#include "img_etm_rgb_gradient_dithered.dat"
#include "img_layer_visible3.dat"
#include "img_layer_visible4.dat"
#include "img_eco_panel_bg.dat"
#include "img_eco_panel_leaf_4.dat"
#include "img_eco_panel_leaf_3.dat"
#include "img_eco_panel_leaf_2.dat"
#include "img_eco_panel_leaf_1.dat"
#include "img_gear_D.dat"
#include "img_gear_L.dat"
#include "img_gear_N.dat"
#include "img_gear_P.dat"
#include "img_gear_R.dat"
#include "wrn_seatbelt_ico.dat"
#include "wrn_fuel_ico.dat"
#include "warning_bar_acc.dat"
#include "wrn_block_long_right.dat"
#include "img_multi_wdgt_a.dat"
#include "img_multi_wdgt_b.dat"
#include "new_images_4.dat"
#include "new_images_2.dat"
#define lc_trip_bkgnd_grid_a_data lc_trip_bkgnd_grid_b_data
/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** CMS Rev 1        01/13/10     JKANOZA
** Initial revision.
**
**==========================================================================*/

/* end of file =============================================================*/
