#ifndef OS_ASSEMBLY

#define ACTIVETASKINDEX					0
#define REQUESTEDTASKINDEX	1
#define ACTIVETASKPRIORITY	2
#define REQUESTEDTASKPRIORITY	3
#define TASKPRIORITYBITS	4
#define REQUESTSCHEDULER 5
#define LOCKDISPATCHER 6
#define INTSAVEDISABLEREQUESTCOUNTER 7
#define INTSAVESTATUS 8
#define INTSAVEGLOBAL 9 
#define CURRENTCONTEXT 10


#define TASKSTARTADDRESS 0
#define TASKSTACKSTARTADDRESS 1
#define TASKSTACKSIZE 2
#define TASKPRIORITY 3
#define	TASKMAXACTIVATIONCOUNT 4
#define TASKCATEGORY 5

#define FROM_NO_TASK 0
#define FROM_ACTIVE_TASK 1
#define RESUME_TASK 2
#define FROM_INVALID_TASK 3

#else
.equ ACTIVETASKINDEX	,				0
.equ REQUESTEDTASKINDEX	, 1
.equ ACTIVETASKPRIORITY	, 2
.equ REQUESTEDTASKPRIORITY ,	3
.equ TASKPRIORITYBITS	, 4
.equ REQUESTSCHEDULER , 5
.equ LOCKDISPATCHER , 6
.equ INTSAVEDISABLEREQUESTCOUNTER , 7
.equ INTSAVESTATUS , 8
.equ INTSAVEGLOBAL , 9 
.equ CURRENTCONTEXT , 10

.equ TASKSTARTADDRESS, 0
.equ TASKSTACKSTARTADDRESS ,1
.equ TASKSTACKSIZE, 2
.equ TASKPRIORITY, 3
.equ TASKMAXACTIVATIONCOUNT, 4
.equ TASKCATEGORY ,5

.equ FROM_NO_TASK ,0
.equ FROM_ACTIVE_TASK , 1
.equ RESUME_TASK , 2
.equ FROM_INVALID_TASK , 3
#endif