/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_1.c
**                                                                            
** Description:    This file contains the language database                   
**                 Autogenerated by LanguageEncoder.exe 3.0.0.0.          
**                 Do not handmodify this file						   	     
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#define HMI_LANGUAGE_1_C

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "hmi_language_interface.h"

/*============================================================================
** T Y P E   D E F I N I T I O N S
**==========================================================================*/

/*============================================================================
** I N T E R N A L   F U N C T I O N   P R O T O T Y P E S
**==========================================================================*/

/*============================================================================
** M E M O R Y   A L L O C A T I O N
**==========================================================================*/

#if defined(__COSMIC_SYSTEMS_ICC)
  #pragma section const {HMI_STN_1}
#endif

#if defined(__IAR_SYSTEMS_ICC)
  #pragma memory=constseg(HMI_LNG_1_CONST)
#endif

#if defined(__CWCC__)
   #pragma push
   #pragma section "HMI_LNG_1_CONST" "HMI_LNG_1_CONST"
   #define LNG_DATA_DATA_PREFIX __declspec(section "HMI_LNG_1_CONST")
#else
   #define LNG_DATA_DATA_PREFIX
#endif

#define HM_LANG_INDEX_WITHIN_BOUND(mp_index, mp_offset)   ((mp_index+mp_offset) < HM_LANG_BUFFER_MAX_SIZE)

LNG_DATA_DATA_PREFIX static UINT8 const HmStrLngTable1[HM_LANG_BUFFER_MAX_SIZE] = { 
/*0x0000      */ 0x05, 'W', 'O', 'R', 'L', 'D'
/*0x0006      */, 0x0D, 'B', 'r', 'a', 'k', 'e', ' ', 'F', 'a', 'i', 'l', 'u', 'r', 'e'
/*0x0014      */, 0x08, 'L', 'o', 'w', ' ', 'F', 'u', 'e', 'l'
/*0x001D      */, 0x0C, 'H', 'e', 'a', 'd', 'l', 'i', 'g', 'h', 't', ' ', 'O', 'N'
/*0x002A      */, 0x08, 'A', 'u', 'd', 'i', 'o', ' ', 'O', 'N'
/*0x0033      */, 0x09, 'W', 'i', 'p', 'e', 'r', ' ', 'O', 'F', 'F'
/*0x003D      */, 0x0C, 'E', 'n', 't', 'e', 'r', ' ', 'N', 'u', 'm', 'b', 'e', 'r'
/*0x004A      */, 0x04, 'M', 'e', 'n', 'u'
/*0x004F      */, 0x01, ' '
/*0x0051      */, 0x0D, 'H', 'E', 'L', 'L', 'O', ' ', 'W', 'a', 'r', 'n', 'i', 'n', 'g'
/*0x005F      */, 0x05, 'H', 'E', 'L', 'L', 'O'
/*0x0065      */, 0x1F, 0x00, 0x5F
/*0x0068      */, 0xE2, 0x20, 0x2B, 0xE8, 0x06, 0x4A, 0x4E, 0x2C, 0x52, 0x31, 0x50, 0x4A, 0x81, ' ', 0xE5, 0x06, 0x27, 0x44, 0x22, 0x46, 0x81, ' ', 0xEA, 0x06, 0x23, 0x44, 0x25, 0x2A, 0x51, 0x35, 0x27, 0x44, 0x4F, 0x81, ' ', 0xE3, 0x06, 0x28, 0x40, 0x9E, ' ', 'M', 'y', ' ', 'T', 'h', 'u', 'm', 'b', ' ', 'D', 'r', 'i', 'v', 'e', ' ', 't', 'h', 'e', ' ', 'f', 'i', 'r', 's', 't', ' ', 'a', 'n', 'd', ' ', 0x84, 'l', 'a', 's', 't', 0x62, 0x20, 0x0E
/*0x00B6      */, 0x00
/*0x00B7      */, 0x9E, 'N', 'o', ' ', 'p', 'h', 'o', 'n', 'e', ' ', 'f', 'o', 'u', 'n', 'd', '.', 0x0A, 'U', 'n', 'a', 'b', 'l', 'e', ' ', 't', 'o', ' ', 'p', 'l', 'a', 'c', 0x12, 'e', ' ', 'e', 'm', 'e', 'r', 'g', 'e', 'n', 'c', 'y', ' ', 'c', 'a', 'l', 'l', '.', 0x0A
/*0x00E9      */, 0x04, 'R', 'o', 'o', 't'
/*0x00EE      */, 0x1F, 0x00, 0xE9
/*0x00F1      */, 0x0A, 'F', 'o', 'r', 'd', ' ', 'R', 'a', 'd', 'i', 'o'
/*0x00FC      */, 0x0E, 'A', 'u', 'd', 'i', 'o', ' ', 's', 'e', 't', 't', 'i', 'n', 'g', 's'
/*0x010B      */, 0x0E, 'R', 'é', 'g', 'l', 'a', 'g', 'e', 's', ' ', 'a', 'u', 'd', 'i', 'o'
/*0x011A      */, 0x0E, 'A', 'u', 'd', 'i', 'o', ' ', 'S', 'e', 't', 't', 'i', 'n', 'g', 's'
/*0x0129      */, 0x10, 'V', 'e', 'h', 'i', 'c', 'l', 'e', ' ', 's', 'e', 't', 't', 'i', 'n', 'g', 's'
/*0x013A      */, 0x11, 'R', 'é', 'g', 'l', 'a', 'g', 'e', 's', ' ', 'v', 'é', 'h', 'i', 'c', 'u', 'l', 'e'
/*0x014C      */, 0x10, 'V', 'e', 'h', 'i', 'c', 'l', 'e', ' ', 'S', 'e', 't', 't', 'i', 'n', 'g', 's'
/*0x015D      */, 0x0D, 'A', 'm', 'b', 'i', 'e', 'n', 't', ' ', 'l', 'i', 'g', 'h', 't'
/*0x016B      */, 0x0D, 'L', 'u', 'm', '.', ' ', 'a', 'm', 'b', 'i', 'a', 'n', 't', 'e'
/*0x0179      */, 0x0D, 'A', 'm', 'b', 'i', 'e', 'n', 't', ' ', 'L', 'i', 'g', 'h', 't'
/*0x0187      */, 0x10, 'D', 'e', 'f', 'l', 'a', 't', 'i', 'o', 'n', ' ', 'd', 'e', 't', 'e', 'c', 't'
/*0x0198      */, 0x10, 'C', 'o', 'n', 't', 'r', '.', ' ', 'p', 'r', '.', ' ', 'p', 'n', 'e', 'u', 's'
/*0x01A9      */, 0x10, 'D', 'e', 'f', 'l', 'a', 't', 'i', 'o', 'n', ' ', 'D', 'e', 't', 'e', 'c', 't'
/*0x01BA      */, 0x03, 'E', 'S', 'C'
/*0x01BE      */, 0x1F, 0x01, 0xBA
/*0x01C1      */, 0x0B, 'A', 'd', 'v', 'a', 'n', 'c', 'e', 'T', 'r', 'a', 'c'
/*0x01CD      */, 0x11, 'P', 'a', 'r', 'k', ' ', 'l', 'o', 'c', 'k', ' ', 'c', 'o', 'n', 't', 'r', 'o', 'l'
/*0x01DF      */, 0x0E, 'C', 't', 'r', 'l', ' ', 'p', 'a', 'r', 'k', ' ', 'l', 'o', 'c', 'k'
/*0x01EE      */, 0x0E, 'P', 'a', 'r', 'k', ' ', 'L', 'o', 'c', 'k', ' ', 'C', 't', 'r', 'l'
/*0x01FD      */, 0x0A, 'S', 'Y', 'N', 'C', '-', 'M', 'e', 'd', 'i', 'a'
/*0x0208      */, 0x0A, 'S', 'Y', 'N', 'C', '-', 'M', 'é', 'd', 'i', 'a'
/*0x0213      */, 0x1F, 0x01, 0xFD
/*0x0216      */, 0x0A, 'S', 'Y', 'N', 'C', '-', 'P', 'h', 'o', 'n', 'e'
/*0x0221      */, 0x0E, 'S', 'Y', 'N', 'C', '-', 'T', 'é', 'l', 'é', 'p', 'h', 'o', 'n', 'e'
/*0x0230      */, 0x1F, 0x02, 0x16
/*0x0233      */, 0x0C, 'A', 'l', 'a', 'r', 'm', ' ', 's', 'y', 's', 't', 'e', 'm'
/*0x0240      */, 0x06, 'A', 'l', 'a', 'r', 'm', 'e'
/*0x0247      */, 0x0C, 'A', 'l', 'a', 'r', 'm', ' ', 'S', 'y', 's', 't', 'e', 'm'
/*0x0254      */, 0x0C, 'T', 'y', 'r', 'e', ' ', 'm', 'o', 'n', 'i', 't', 'o', 'r'
/*0x0261      */, 0x0F, 'S', 'u', 'r', 'v', '.', ' ', 'p', 'r', '.', ' ', 'p', 'n', 'e', 'u', 's'
/*0x0271      */, 0x1F, 0x02, 0x54
};
#if defined(__COSMIC_SYSTEMS_ICC)  
#pragma section const {}           
#endif                             

#if defined(__IAR_SYSTEMS_ICC)     
#pragma memory=default             
#endif                             

#if defined(__CWCC__)
   #pragma pop
#endif
/*============================================================================
** E N T R Y   P O I N T S
**==========================================================================*/
#if defined(__IAR_SYSTEMS_ICC)     
#pragma codeseg(HMI_LNG_1_CODE)     
#endif                             

#if defined(__COSMIC_SYSTEMS_ICC)  
#pragma section(HMI_LNG_1C)         
#endif                             

#if defined(__IAR_SYSTEMS_ICC)
  #pragma memory=default
#endif
/*============================================================================
** Function Name:    HmLanguage1GetStringLen
** Visibility:		 local
** Description:		 Returns the string length for the passed SID
** Invocation:		 By HmLanguage1GetString
** Inputs/Outputs:	 SID
** Critical Section: String Length
** Created:          16-Aug-2010 by EMANOJ1
** Updated:          16-Aug-2010 by EMANOJ1
**==========================================================================*/
static UINT16 HmLanguage1GetStringLen(LANG_SID_T p_sid)
{
   UINT8 const *p_lang_db_U8P      = (UINT8 const *)&HmStrLngTable1[p_sid];
   UINT16 fl_string_length_U16 = 0U;
   UINT8 fl_temp_U8;
   UINT8 fl_command_byte_U8;

   do
   {
      fl_command_byte_U8 = *p_lang_db_U8P;
      fl_temp_U8         = (UINT8)(fl_command_byte_U8  & HMI_LNG_CMD_LENGTH_MASK);
      fl_string_length_U16++;
      if(fl_temp_U8 == HMI_LNG_CMD_LENGTH_MASK)
      {
         /* We got another SID */
         if((fl_command_byte_U8 & HMI_LNG_CMD_EXT_ESID_BIT) != 0U)
         {
            fl_temp_U8 = 3U;
         }
         else
         {
            fl_temp_U8 = 2U;
         }
      }
      p_lang_db_U8P++;
      fl_string_length_U16 += (UINT16)fl_temp_U8;
      p_lang_db_U8P        = &p_lang_db_U8P[fl_temp_U8];
   }
   while((fl_command_byte_U8 & HMI_LNG_CMD_LINK_BIT) != 0U);

   return(fl_string_length_U16);
}

/*============================================================================
** Function Name:    HmLanguage1GetString
** Visibility:		 Global
** Description:		 Returns the SID if the requested SID is mapped to another
**                   one (SID linking)
**                   If the requested SID is not linked to another SID, then
**					 writes the string in p_str_dest_P and returns HM_END_OF_SID
** Invocation:		 Invoked by hmi_language_interface.c
** Inputs/Outputs:	 sid, pointer to buffer where the string needs to be returned
**                   and current language as inputs. Returns linked SID if any
** Critical Section: None
** Created:          16-Aug-2010 by EMANOJ1
** Updated:          16-Aug-2010 by EMANOJ1
**==========================================================================*/
#ifdef HM_LANG_USE_INERNAL_STRING_BUFFER
LANG_SID_T HmLanguage1GetString(LANG_SID_T p_sid, HMI_CHAR * p_str_dest_P, UINT8 p_cur_language_U8)
#else
LANG_SID_T HmLanguage1GetString(LANG_SID_T p_sid, HMI_CHAR * p_str_dest_P, UINT8 p_req_length, UINT8 p_cur_language_U8)
#endif
{
   UINT8 const * fl_lang_db_U8P;
   LANG_SID_T fl_tbl_index = 0U;
#ifdef LNG_UNICODE
   UINT8   fl_codepage_U8;
#endif
   UINT8   fl_str_length_U8;
   UINT8   fl_index;
   UINT8   fl_command_byte_U8;
   LANG_SID_T fl_sid = p_sid;
   HMI_CHAR * fl_str_dest_P = p_str_dest_P;
#ifndef HM_LANG_USE_INERNAL_STRING_BUFFER
   UINT8   fl_req_length = p_req_length;
#endif

 #ifdef HM_LANG_MAX_SID
   if( fl_sid <= HM_LANG_MAX_SID)
   {
 #endif
    #ifdef HM_LANG_COMMON_MAX_SID
	  if( fl_sid > HM_LANG_COMMON_MAX_SID)
    #endif
	  {
    #if HM_LANG_MAX_PAGE > 1
		fl_sid = (fl_sid & HMI_LNG_SID_INDEX_MASK);
    #endif
		for (fl_index = 0; fl_index < p_cur_language_U8; fl_index++)
		{
		  fl_sid += HmLanguage1GetStringLen(fl_sid);
		}
	  }
	#ifdef HM_LANG_COMMON_MAX_SID
	#if HM_LANG_MAX_PAGE > 1
	  else
	  {
	  	fl_sid = fl_sid & HMI_LNG_SID_INDEX_MASK;
	  }
	#endif
	#endif

    #ifndef HM_LANG_USE_INERNAL_STRING_BUFFER
      /*
      ** Last location is reserved for null termination so reduce one from
      ** the input buffer length
      */
      if(fl_req_length > 0U)
      {
        fl_req_length--;
      }
    #endif

      fl_lang_db_U8P = (UINT8 const *)&HmStrLngTable1[0];
      fl_tbl_index   = fl_sid;
      fl_sid         = HM_END_OF_SID;
      if(fl_tbl_index < HM_LANG_BUFFER_MAX_SIZE)
      {
        do
        {
          fl_command_byte_U8 = fl_lang_db_U8P[fl_tbl_index++];
          fl_str_length_U8    = (UINT8)(fl_command_byte_U8  & HMI_LNG_CMD_LENGTH_MASK);

          if((fl_str_length_U8 == HMI_LNG_CMD_LENGTH_MASK) && (HM_LANG_INDEX_WITHIN_BOUND(fl_tbl_index,1u)))
          {
            /* We got another SID */
            fl_sid   = fl_lang_db_U8P[fl_tbl_index++];
            fl_sid <<= 8;
            fl_sid  |= fl_lang_db_U8P[fl_tbl_index];
            if(((fl_command_byte_U8 & HMI_LNG_CMD_EXT_ESID_BIT) != 0U) && (HM_LANG_INDEX_WITHIN_BOUND(fl_tbl_index,1u)))
            {
              /*extended fl_sid - 3byte coding */
              fl_tbl_index++;
              fl_sid <<= 8;
              fl_sid  |= fl_lang_db_U8P[fl_tbl_index];
            }
            /* exit the loop */
            fl_command_byte_U8 = 0;
          }
          else
          {
           #ifdef LNG_UNICODE
            fl_codepage_U8 = (UINT8)((fl_command_byte_U8 & HMI_LNG_CMD_CPAGE_MASK) >> 5U);
            if (fl_codepage_U8 == 0x2U)
            {
              /* Page 4 */
              fl_codepage_U8 = 4;
            }
            else if((fl_codepage_U8 == 3U) && (HM_LANG_INDEX_WITHIN_BOUND(fl_tbl_index,0u)))
            {
              fl_codepage_U8 = fl_lang_db_U8P[fl_tbl_index++];
              fl_str_length_U8--;
            }
            else
            {
            }
           #endif
           #ifndef HM_LANG_USE_INERNAL_STRING_BUFFER
            if(fl_str_length_U8 > fl_req_length)
            {
              fl_str_length_U8 = fl_req_length;
              fl_req_length     = 0;
            }
            else
            {
              fl_req_length -= fl_str_length_U8;
            }
            if(fl_req_length == 0U)
            {
              /*
              ** We can exit the loop after copying the required length
              */
              fl_command_byte_U8 = 0;
            }
           #endif
            for(fl_index = 0; ((fl_index < fl_str_length_U8) && (HM_LANG_INDEX_WITHIN_BOUND(fl_tbl_index,0u))); fl_index++)
            {
             #ifdef LNG_UNICODE
              HMI_CHAR fl_codepage_hmi_char = (HMI_CHAR)(fl_codepage_U8);
              *fl_str_dest_P = (HMI_CHAR)(fl_codepage_hmi_char << 8U);
              *fl_str_dest_P|= (HMI_CHAR)(fl_lang_db_U8P[fl_tbl_index++]);
             #else
              *fl_str_dest_P = fl_lang_db_U8P[fl_tbl_index++];
             #endif
              fl_str_dest_P++;
            }
          }
        }
        while(((fl_command_byte_U8 & HMI_LNG_CMD_LINK_BIT) != 0U) && (HM_LANG_INDEX_WITHIN_BOUND(fl_tbl_index,0u)));
        *fl_str_dest_P = 0;
      }					/* if(fl_tbl_index < HM_LANG_BUFFER_MAX_SIZE) */
 #ifdef HM_LANG_MAX_SID
   }
   else
   {
	 *fl_str_dest_P = 0;
   }
 #endif
   return(fl_sid);
}

#if defined(__COSMIC_SYSTEMS_ICC)
#pragma section {}
#endif

#if defined(__IAR_SYSTEMS_ICC)
#pragma memory=default
#endif

/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** Rev 1.3          06-Jul-2017 by ARAJASE2
** Changes done to fix the following Coverity Warning.
** 1.Overrunning array of 6675 bytes at byte offset 6675 by dereferencing pointer <fl_lang_db_U8P>.
**		Change: fl_lang_db_U8P pointer usage changed to access as array.
**
**============================================================================
**
** Rev 1.2          23-Jul-2015 by ARAJASE2
** Changes done to fix the following QAC Warnings.
** 1.++ WARNING ++: <=4=(5209) Use of basic type 'unsigned char'.
**		Changes: 'unsigned char' is changed as UINT8
** 2.++ WARNING ++: <=7=(2212) Body of control statement is not enclosed within braces.
**		Changes: Added open and close braces for else loop
** 3.++ WARNING ++: <=7=(5133) Comment delimiter found within comment. 
**
**============================================================================
**
** Rev 1.1          29-Jan-2015 by ARAJASE2
** Changes done to fix the following QAC Warnings.
** 1.++ WARNING ++: <=7=(0311) Dangerous pointer cast results in loss of const qualification.
**		Changes: UINT8       *p_lang_db_U8P	 = (UINT8       *)&HmStrLngTable1[p_sid]; is changed as 
**            UINT8 const *p_lang_db_U8P  = (UINT8 const *)&HmStrLngTable1[p_sid];
** 2.++ WARNING ++: <=5=(3440) Using the value resulting from a ++ or -- operation.
**		Changes: x = *ptr++ changed as x = *p; p++;
** http:/stackoverflow.com/questions/859770/on-a-dereferenced-pointer-in-c
**
**============================================================================
** Rev 1.0          16-Aug-2010 by EMANOJ1
** Initial revision.
**
**==========================================================================*/

/* end of file =============================================================*/
