#ifndef ICU_COMMON_TYPES_H
#define ICU_COMMON_TYPES_H

/** \file  
 ** \brief AUTOSAR Icu ICU Driver
 **
 ** This file contains data types and constantsof the ICU module
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]============================================*/
#include <TSAutosar.h>        /* global configuration */
#include <Std_Types.h>        /* AUTOSAR standard types */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/** \brief numeric identifier of a ICU channel
 **
 ** This type is implementation specific. It is chosen in order to have the
 ** most efficient implementation on a specific microcontroller platform */
typedef uint8 Icu_LowCountType;

/** \brief numeric identifier of a ICU channel
 **
 ** 
 ** */
typedef uint8 Icu_ChannelType;

/** \brief Numeric identifier of a ICU channel.
 **
 ** This type is implementation specific. It is chosen in order to have the
 ** most efficient implementation on a specific microcontroller platform. */
typedef uint8 Icu_ResourceType;

/** \brief S6J3 ICU Resource type of a ICU channel.
 **
 ** This type is implementation specific. It is chosen in order to have the
 ** most efficient implementation on a specific microcontroller platform. */
typedef uint8 Icu_ChannelResourceType;

/** \brief Definition of the channel status of an ICU channel.
 **
 ** This type is implementation specific. It is chosen in order to have the
 ** most efficient implementation on a specific microcontroller platform. */
typedef uint8 Icu_ChannelStatusType;

/** \brief Type, to abstract the return value of the service Icu_GetTimestampIndex().
 **
 ** Implementation specific. This type shall be chosen in order to have the most
 ** efficient implementation on a specific microcontroller platform.
 **/
typedef uint16 Icu_IndexType;

/** \brief Type, to abstract the return value of the service Icu_GetEdgeNumbers().
 **
 ** Implementation specific. This type shall be chosen in order to have the most
 ** efficient implementation on a specific microcontroller platform.
 **/
typedef uint16 Icu_EdgeNumberType;

/** \brief width of the buffer for timestamp ticks and measured elapsed timeticks.
 **
 ** Implementation specific. This type shall be chosen in order to have the most
 ** efficient implementation on a specific microcontroller platform.
 **/
typedef uint32 Icu_ValueType;


/** \brief Definition of the type of activation edge of an ICU channel */
typedef enum
{
  ICU_INIT_EDGE   = 0,  /* Init edge is used only by de-initialization. */
  ICU_RISING_EDGE,      /* A rising edge causes the chosen action to happen */
  ICU_FALLING_EDGE,     /* A falling edge causes the chosen action to happen */
  ICU_BOTH_EDGES,       /* A rising or falling edge causes the chosen action to happen */
  ICU_LOW_LEVEL,        /* Low level causes an external interrupt. */
  ICU_HIGH_LEVEL        /* High level causes an external interrupt. */
} Icu_ActivationType;

/** \brief Definition of the input state of an ICU channel */
typedef enum
{
  ICU_IDLE = 0,         /* No activation edge has been detected */
  ICU_ACTIVE            /* An activation edge has been detected */
} Icu_InputStateType;

/** \brief Definition of the mode of the Icu */
typedef enum
{
  ICU_MODE_NORMAL = 1,  /* Normal operation */
  ICU_MODE_SLEEP        /* Reduced power operation mode */
} Icu_ModeType;

/** \brief definition of the measurement mode type */
typedef enum
{
  ICU_MODE_SIGNAL_EDGE_DETECT = 1, /* mode for detecting signal edges */
  ICU_MODE_SIGNAL_MEASUREMENT,     /* mode for measuring time between edges */
  ICU_MODE_TIMESTAMP,              /* mode for capturing timer values on edges */
  ICU_MODE_EDGE_COUNTER            /* mode for counting edges */
} Icu_MeasurementModeType;

/** \brief definition of the signal measurement property type */
typedef enum
{
  ICU_LOW_TIME = 1, /* reading the elapsed signal low time */
  ICU_HIGH_TIME,    /* reading the elapsed signal high time */
  ICU_PERIOD_TIME,  /* reading the elapsed signal period time */
  ICU_ACTIVE_TIME,  /* reading the elapsed signal active time */
  ICU_DUTY_CYCLE    /* reading values needed to calculate the signal duty cycle */
} Icu_SignalMeasurementPropertyType;

/** \brief definition of the timestamp buffer type */
typedef enum
{
  ICU_LINEAR_BUFFER = 1,  /* filling the buffer will just be done once */
  ICU_CIRCULAR_BUFFER     /* after reaching the end, filling the buffer continues from the beginning */
} Icu_TimestampBufferType;

/** \brief Holds the ICU driver status */
typedef enum
{
  ICU_S_ILLEGAL = 0,   /** illegal initialization value */
  ICU_S_UNINITIALIZED, /** driver was not initialized  */
  ICU_S_INITIALIZED,   /** driver successfully initialized */
  ICU_S_LOCKED         /** driver locked except for the service established the lock */
} Icu_DriverStatusType;

/** \brief Type which contains the values, needed for calculating duty cycles. */
typedef struct
{
  Icu_ValueType ActiveTime; /* coherent active-time measured on a channel */
  Icu_ValueType PeriodTime; /* coherent period-time measured on a channel */
} Icu_DutyCycleType;

/** \brief Definition of the common state of a single channel */
typedef struct
{
  /* wakeup */
  boolean                               WakeupEnable;     /* enable/disable wakeup */
  boolean                               WakeupDetected;   /* wakeup was detected */

  Icu_ChannelStatusType                 Status;           /* enable/disable notification or
                                                             enable/disable counting or
                                                             start/stop timestamp or
                                                             start/stop signal measurement */

  Icu_ActivationType                    ActivationEdge;   /* edge to count */

  /* pointer to a structure holding extension state data of a single channel */
  P2VAR(void, AUTOMATIC, ICU_APPL_DATA) ExtStatePtr;
  
} Icu_ChannelCommonStateType;

/** \brief Definition of the state of edge detect channel */
typedef struct
{
  /* input state for edge detect */
  Icu_InputStateType          InputState[2];    /* current input state  */
  Icu_LowCountType            InputStateIndex;  /* index for accessing InputState[] */

  boolean                     NotifyEnabled;    /* enabled/disable notification at runtime */
  
} Icu_EdgeDetectChannelStateType;

/** \brief Definition of the state of edge count channel */
typedef struct
{
  /* edge count mode */
  Icu_EdgeNumberType          EdgeNumber;       /* number of detected edges */
  
} Icu_EdgeCountChannelStateType;

/** \brief Definition of the state of signal measurement channel */
typedef struct
{
  /* results and input state are double buffered, hence the array size must be 2 */
  /* result time for signal measurement */
  Icu_ValueType               Time[2];          /* result time high, low, period time */
  Icu_ValueType               ActiveTime[2];    /* result time active time for duty cycle */

  /* signal measurement: high, low, period */
  Icu_ActivationType          NextEdge;         /* next edge to detect */
  Icu_ValueType               PrevTime;         /* time of the previous edge */

  /* signal measurement: duty cycle */
  Icu_ValueType               SplitTime;        /* time of the phase change within a period */

  /* input state for signal measurement */
  Icu_InputStateType          InputState[2];    /* current input state  */

  Icu_LowCountType            InputStateIndex;  /* index for accessing InputState[] */
  Icu_LowCountType            Index;            /* index for accessing Time[], ActiveTime[] */

  boolean                     First;            /* 1st/n-th start edge */
  
} Icu_SignalMeasChannelStateType;

/** \brief Definition of the state of time stamp channel */
typedef struct
{
  /* timestamp mode */
  Icu_EdgeNumberType                             EdgeNumber;       /* number of measured timestamps */
  Icu_EdgeNumberType                             NotifyInterval;   /* number of detected events till notification */
  uint16                                         BufferSize;       /* number of buffer elements */
  uint16                                         BufferPos;        /* buffer position for next write */
  P2VAR(Icu_ValueType, AUTOMATIC, ICU_APPL_DATA) BufferPtr;

  boolean                                        NotifyEnabled;    /* enabled/disable notification at runtime */
  
} Icu_TimeStampChannelStateType;

typedef struct Icu_drvFctTable_s Icu_drvFctTable_t;

/** \brief  typedef definiton for function callback pointer */
typedef P2FUNC(void, ICU_CODE, Icu_FuncPtrType)(void);

/** \brief  typedef definiton for function get table pointer. */
typedef P2FUNC(P2CONST(Icu_drvFctTable_t, AUTOMATIC, ICU_CONST), ICU_CODE, Icu_GetTblType)(void);

/** \brief Definition of the configuration of a single channel */
typedef struct
{
  Icu_ChannelType                                             ChannelID;            /* Icu channel number */
  Icu_ResourceType                                            ResourceID;           /* architecture specific configuration data of a single channel */
  Icu_ChannelResourceType                                     ChannelResourceKind;  /* 32bitICU or ExtInt */

  /* common configuration data of a single channel */
  boolean                                                     WakeupCapability;     /* Channel is capable to do a wake-up */
  boolean                                                     RegExist_IcssIcsc;    /* Icss/Icsc registers exist or not. */
  Icu_ActivationType                                          DefaultEdge;          /* default value for first edge to detect */
  Icu_MeasurementModeType                                     MeasurementMode;      /* defines measure mode */

  /* pointer to a structure holding common state data of a single channel */
  P2VAR(Icu_ChannelCommonStateType, AUTOMATIC, ICU_APPL_DATA) StatePtr;

  /* pointer to a structure holding extension config of a single channel */
  P2CONST(void, AUTOMATIC, ICU_APPL_DATA)                     ExtConfigPtr;

  volatile CONSTP2VAR(uint32, ICU_CONST, REGSPACE)            BaseAddress;          /* IcuResource's base address. */

  Icu_GetTblType                                              GetFuncTable;         /* Peripheral function table pointer */

} Icu_ChannelConfigType;

/** \brief Definition of the extension configuration of Edge Detect channel */
typedef struct
{
  Icu_FuncPtrType                     Notification;         /* Channel notification function */

} Icu_EdgeDetectExtensionConfigType;

/** \brief Definition of the extension configuration of Signal Measurement channel */
typedef struct
{
  Icu_SignalMeasurementPropertyType   MeasurementProperty;  /* defines what to measure */

} Icu_SignalMeasExtConfigType;

/** \brief Definition of the extension configuration of TimeStamp channel */
typedef struct
{
  Icu_FuncPtrType                                  Notification;  /* Channel notification function */
 
  Icu_TimestampBufferType                          BufferMode;    /* defines buffering strategy */
  CONSTP2VAR(Icu_ValueType, AUTOMATIC, ICU_CONST)  BufName;       /* Timestamp buffer Name */
  uint16                                           BufSize;       /* Timestamp buffer size */

} Icu_TimeStampExtensionConfigType;

/** \brief Definition of the functional pointer to register layer function. */
typedef P2FUNC(void, ICU_CODE, Icu_drvVoidFct_t)  (P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr);
typedef P2FUNC(void, ICU_CODE, Icu_drvVoidFct2_t) (P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,Icu_ActivationType Activation);
typedef P2FUNC(boolean,            ICU_CODE, Icu_drvResultFct_t)     (P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_CONST) ChannelPtr);
typedef P2FUNC(Icu_ActivationType, ICU_CODE, Icu_drvActivationFct_t) (P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_CONST) ChannelPtr);

struct Icu_drvFctTable_s
{
  Icu_drvVoidFct2_t        drvSetActivationCondition;
  Icu_drvVoidFct_t         drvIsrDisable;
  Icu_drvVoidFct_t         drvIsrEnable;
  Icu_drvVoidFct_t         drvClearInterruptRequestFlag;
  Icu_drvResultFct_t       drvGetInterruptRequestFlag;
  
  Icu_drvResultFct_t       drvCheckIsrEnabled;
  Icu_drvActivationFct_t   drvGetActivationCondition;
};

/** \brief Definition of the state of the driver */
typedef struct
{
  /* Module wakeup mode */
  Icu_ModeType             WakeupMode;

} Icu_StateType;

/** \brief driver Initialization data
 **
 ** This structure contains the initialization data of the ICU driver. */
typedef struct
{
  /* pointer to a structure holding state data of the driver */
  P2VAR(Icu_StateType, AUTOMATIC, ICU_APPL_DATA) StatePtr;

  /* Number of configured ICU channels */
  Icu_ChannelType   ConfiguredChannels;

  volatile CONSTP2VAR(uint32, ICU_CONST, REGSPACE) ExtInt_BaseAddress;   /* External Interrupt's base address. */
  uint32                                           NFESR_Data;           /* Noise filter enabled channels . */
  uint32                                           NFECR_Data;           /* Noise filter disabled channels . */
  
  /* pointer to an array holding configuration entries for all configured channels */
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr;
  

} Icu_ConfigType;

/* Icu_CheckChannelStatusType is structure of channel's state */
typedef struct
{
  Icu_DriverStatusType    driverStatus;              /* driver status */
  Icu_ModeType            driverWakeupMode;          /* Module wakeup mode */

  Icu_ChannelStatusType   channelStatus;             /* channel running/stopped */
  boolean                 channelWakeupEnable;       /* enable/disable wakeup */
  boolean                 channelNotifyEnabled;      /* enable/disable Notification */
  Icu_ActivationType      channelActivationEdge;     /* edge Type */

} Icu_CheckChannelStatusType;

/** \brief Register Type of External Interrupt controller. */
typedef struct
{
  volatile uint32  Enir;
  volatile uint32  Enisr;
  volatile uint32  Enicr;
  volatile uint32  Eirr;
  volatile uint32  Eircr;
  volatile uint32  Nfer;
  volatile uint32  Nfesr;
  volatile uint32  Nfecr;
  volatile uint32  Elvr0;
  volatile uint32  Elvr1;
  volatile uint32  Elvr2;
  volatile uint32  Elvr3;

} Icu_EICType;

/** \brief Register Type of Input Capture Unit. */
typedef struct
{
  volatile uint32  Ipcp0;
  volatile uint32  Ipcp1;
  volatile uint32  Ics;
  volatile uint32  Icsc;
  volatile uint32  Icss;

} Icu_ICUType;

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

#endif /* ifndef ICU_COMMON_TYPES_H */
/*==================[end of file]============================================*/
