//---------------------------------------------------------------------------------------------------------------------
//
// VISTEON CORPORATION CONFIDENTIAL
// ________________________________
//
// [2017] Visteon Corporation
// All Rights Reserved.
//
// NOTICE: This is an unpublished work of authorship, which contains trade secrets.
// Visteon Corporation owns all rights to this work and intends to maintain it in confidence to preserve
// its trade secret status. Visteon Corporation reserves the right, under the copyright laws of the United States
// or those of any other country that may have jurisdiction, to protect this work as an unpublished work,
// in the event of an inadvertent or deliberate unauthorized publication. Visteon Corporation also reserves its rights
// under all copyright laws to protect this work as a published work, when appropriate.
// Those having access to this work may not copy it, use it, modify it, or disclose the information contained in it
// without the written authorization of Visteon Corporation.
//-----------------------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------------
// File is Auto generated from python based tool.
// Generation Date: January 30,2024, 21:48:05
// Last generated by: RDARSHAN
// Tool contact: skiranku@visteon.com
//------------------------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------------
#ifndef __CDD_FITMANAGER_CFG_H__
#define __CDD_FITMANAGER_CFG_H__


#include "Std_Types.h"
#include "CDD_FitManager_Types.h"
#include "CDD_FitManager_Defines.h"
#include "CDD_FitManager_Version.h"


/* User includes defnitions */
#include "CDD_McuFit_UserHandler.h"
#include "CDD_BswFit_UserHandler.h"

/* Preprocessor defnitions */
#define CDD_FITMANAGER_DEV_ERROR_DETECT                     STD_ON
#define CDD_FITMANAGER_MAX_NUMBER_OF_MODULES                2
/* FIT Module ID defnitions */
#define CDD_FITMANAGER_CDD_MCUFIT_MODULE_ID                 0
#define CDD_FITMANAGER_CDD_BSWFIT_MODULE_ID                 1
/* FIT Module test count defnitions */
#define CDD_FITMANAGER_CDD_MCUFIT_TEST_COUNT                5
#define CDD_FITMANAGER_CDD_BSWFIT_TEST_COUNT                5
/* FIT CDD_McuFit Module test ID defnitions */
#define CDD_FITMANAGER_CDD_MCUFIT_WDT_SELFTST_TEST_ID       1
#define CDD_FITMANAGER_CDD_MCUFIT_WRITE_PRO_REG_TEST_ID     2
#define CDD_FITMANAGER_CDD_MCUFIT_MAIN_CLOCK_TEST_ID        3
#define CDD_FITMANAGER_CDD_MCUFIT_EXTWDG_TEST_ID            4
#define CDD_FITMANAGER_CDD_MCUFIT_ECC_TEST_ID               5

/* FIT CDD_BswFit Module test ID defnitions */
#define CDD_FITMANAGER_CDD_BSWFIT_WDGM_ALIVE_TEST_ID        1
#define CDD_FITMANAGER_CDD_BSWFIT_MPU_TEST_ID               2
#define CDD_FITMANAGER_CDD_BSWFIT_STACK_OVERFLOW_TEST_ID    3
#define CDD_FITMANAGER_CDD_BSWFIT_STACK_UNDERFLOW_TEST_ID   4
#define CDD_FITMANAGER_CDD_BSWFIT_NVM_INTEGRITY_ID          5

/* FIT Module test config array declarations */

#define	CDD_FITMANAGER_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
extern CONST(CDD_FitManager_TestConfigType_t, CDD_FITMANAGER_APPL_CONST)	CDD_McuFit_TestConfigArray[CDD_FITMANAGER_CDD_MCUFIT_TEST_COUNT];
#define	CDD_FITMANAGER_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

#define	CDD_FITMANAGER_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
extern CONST(CDD_FitManager_TestConfigType_t, CDD_FITMANAGER_APPL_CONST)	CDD_BswFit_TestConfigArray[CDD_FITMANAGER_CDD_BSWFIT_TEST_COUNT];
#define	CDD_FITMANAGER_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"


/* FIT Module configuration data */
#define	CDD_FITMANAGER_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"
extern CONST(FitModuleConfigType, CDD_FITMANAGER_APPL_CONST)CDD_FitManager_ModuleConfigData[2];
#define	CDD_FITMANAGER_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"


#endif/*End of File */
