/*
 *  Copyright (C) 2021 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 * 
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Auto generated file
 */

#ifndef TI_DRIVERS_CONFIG_H_
#define TI_DRIVERS_CONFIG_H_

#include <stdint.h>
#include <drivers/hw_include/cslr_soc.h>
#include "ti_dpl_config.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Common Functions
 */
void System_init(void);
void System_deinit(void);
/*
 * DSS
 */
#include <drivers/dss.h>
#include <drivers/fvid2.h>
#define CONFIG_DSS_NUM_FRAMES_PER_PIPELINE     2U

#define CONFIG_DSS_NUM_SAFETY_REGIONS          4U

/* DSS Instance Macros */
#define CONFIG_DSS0 (0U)
#define CONFIG_DSS_NUM_INSTANCES (1U)
/* I2C Instance Macros */
#define CONFIG_I2C0 (0U)

/*
 * GPIO
 */
// #include <drivers/gpio.h>

/* GPIO PIN Macros */
#define DO_MCU_CMIC_PHOLD_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define DO_MCU_CMIC_PHOLD_PIN (15)
#define DO_MCU_CMIC_PHOLD_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MCU_CMIC_PHOLD_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MCU_AMUX_S1_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define DO_MCU_AMUX_S1_PIN (14)
#define DO_MCU_AMUX_S1_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MCU_AMUX_S1_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MCU_AMUX_S0_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define DO_MCU_AMUX_S0_PIN (13)
#define DO_MCU_AMUX_S0_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MCU_AMUX_S0_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MCU_CMIC_PBSTATE_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define DI_MCU_CMIC_PBSTATE_PIN (10)
#define DI_MCU_CMIC_PBSTATE_DIR (GPIO_DIRECTION_INPUT)
#define DI_MCU_CMIC_PBSTATE_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MCU_FALD_CONN_CHK_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define DI_MCU_FALD_CONN_CHK_PIN (7)
#define DI_MCU_FALD_CONN_CHK_DIR (GPIO_DIRECTION_INPUT)
#define DI_MCU_FALD_CONN_CHK_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MCU_PMIC_INTN_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define DI_MCU_PMIC_INTN_PIN (0)
#define DI_MCU_PMIC_INTN_DIR (GPIO_DIRECTION_INPUT)
#define DI_MCU_PMIC_INTN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MCU_CMIC_RES_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define DO_MCU_CMIC_RES_PIN (16)
#define DO_MCU_CMIC_RES_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MCU_CMIC_RES_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_SOC_TCON_GRBN_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_SOC_TCON_GRBN_PIN (56)
#define DO_SOC_TCON_GRBN_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_SOC_TCON_GRBN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MCU_SMPS_FALD_6V_EN_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_MCU_SMPS_FALD_6V_EN_PIN (32)
#define DO_MCU_SMPS_FALD_6V_EN_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MCU_SMPS_FALD_6V_EN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MD_DISP_3V3_EN_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_MD_DISP_3V3_EN_PIN (54)
#define DO_MD_DISP_3V3_EN_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MD_DISP_3V3_EN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_SOC_TCON_BPS_CMD_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_SOC_TCON_BPS_CMD_PIN (61)
#define DO_SOC_TCON_BPS_CMD_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_SOC_TCON_BPS_CMD_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_SOC_TCON_BPS_SEL0_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_SOC_TCON_BPS_SEL0_PIN (62)
#define DO_SOC_TCON_BPS_SEL0_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_SOC_TCON_BPS_SEL0_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_SOC_TCON_BPS_SEL1_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_SOC_TCON_BPS_SEL1_PIN (63)
#define DO_SOC_TCON_BPS_SEL1_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_SOC_TCON_BPS_SEL1_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DIO_SOC_TCON_SPARE_BASE_ADDR (CSL_GPIO0_BASE)
#define DIO_SOC_TCON_SPARE_PIN (64)
#define DIO_SOC_TCON_SPARE_DIR (GPIO_DIRECTION_OUTPUT)
#define DIO_SOC_TCON_SPARE_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MD_TCON_STBN_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_MD_TCON_STBN_PIN (67)
#define DO_MD_TCON_STBN_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MD_TCON_STBN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MD_TFT_STBYB_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_MD_TFT_STBYB_PIN (68)
#define DO_MD_TFT_STBYB_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MD_TFT_STBYB_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MCU_FALD_SMPS_6V_PG_BASE_ADDR (CSL_GPIO0_BASE)
#define DI_MCU_FALD_SMPS_6V_PG_PIN (33)
#define DI_MCU_FALD_SMPS_6V_PG_DIR (GPIO_DIRECTION_INPUT)
#define DI_MCU_FALD_SMPS_6V_PG_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MD_TFT_FAILT_BASE_ADDR (CSL_GPIO0_BASE)
#define DI_MD_TFT_FAILT_PIN (69)
#define DI_MD_TFT_FAILT_DIR (GPIO_DIRECTION_INPUT)
#define DI_MD_TFT_FAILT_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MD_TCON_IND_OUT_BASE_ADDR (CSL_GPIO1_BASE)
#define DI_MD_TCON_IND_OUT_PIN (11)
#define DI_MD_TCON_IND_OUT_DIR (GPIO_DIRECTION_INPUT)
#define DI_MD_TCON_IND_OUT_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MD_TFT_RST_BASE_ADDR (CSL_GPIO0_BASE)
#define DO_MD_TFT_RST_PIN (52)
#define DO_MD_TFT_RST_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MD_TFT_RST_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_TP12033_BASE_ADDR (CSL_GPIO1_BASE)
#define DO_TP12033_PIN (12)
#define DO_TP12033_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_TP12033_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DO_MD_GNSS_3V3_EN_BASE_ADDR (CSL_GPIO1_BASE)
#define DO_MD_GNSS_3V3_EN_PIN (8)
#define DO_MD_GNSS_3V3_EN_DIR (GPIO_DIRECTION_OUTPUT)
#define DO_MD_GNSS_3V3_EN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MCU_TFT_CON_CHK_1_BASE_ADDR (CSL_GPIO0_BASE)
#define DI_MCU_TFT_CON_CHK_1_PIN (41)
#define DI_MCU_TFT_CON_CHK_1_DIR (GPIO_DIRECTION_INPUT)
#define DI_MCU_TFT_CON_CHK_1_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define DI_MCU_TFT_CON_CHK_2_BASE_ADDR (CSL_GPIO0_BASE)
#define DI_MCU_TFT_CON_CHK_2_PIN (42)
#define DI_MCU_TFT_CON_CHK_2_DIR (GPIO_DIRECTION_INPUT)
#define DI_MCU_TFT_CON_CHK_2_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define WDG_TRIG_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define WDG_TRIG_PIN (19)
#define WDG_TRIG_DIR (GPIO_DIRECTION_INPUT)
#define WDG_TRIG_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define PMIC_LPM_EN_BASE_ADDR (CSL_MCU_GPIO0_BASE)
#define PMIC_LPM_EN_PIN (22)
#define PMIC_LPM_EN_DIR (GPIO_DIRECTION_INPUT)
#define PMIC_LPM_EN_TRIG_TYPE (GPIO_TRIG_TYPE_NONE)
#define CONFIG_GPIO_NUM_INSTANCES (26U)


#ifdef __cplusplus
}
#endif

#endif /* TI_DRIVERS_CONFIG_H_ */
