# *********************************************************************************************************************
# Company:             Johnson Controls Inc.
# ---------------------------------------------------------------------------------------------------------------------
# Copyright:           This software is JCI property.
#                      Duplication or disclosure without JCI written authorization is prohibited.
# ---------------------------------------------------------------------------------------------------------------------
# Project:             E40_Platform
# Language:            Apache ANT Properties
# ---------------------------------------------------------------------------------------------------------------------
#      DO NOT CHANGE THIS FILE! IT HAS BEEN GENERATED. ANY CHANGES WILL BE OVERWRITTEN AT THE NEXT GENERATION!
# ---------------------------------------------------------------------------------------------------------------------
# Generated on Tue Aug 06 13:07:41 IST 2024 by the JCI UML Generation chain from the "E40_Platform" model.
# ---------------------------------------------------------------------------------------------------------------------
# Entity:              DefaultConfig (Configuration)
# Description:         None
# Owner:               LIB_A2T_SYS_OSAL (Component)
# ---------------------------------------------------------------------------------------------------------------------
# Rhapsody version:    9.0.1
# Generator version:   V3.0.27
# Generator date:      11/12/2014 12:04:26,40
# ---------------------------------------------------------------------------------------------------------------------
name=DefaultConfig
stereotype=
description=""
