/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_identifiers.h                                 
**                                                                            
** Description:    This file contains the language identifier interfaces      
**                 Autogenerated by LanguageEncoder.exe Version : 1.1.0.23.          
**                 Do not handmodify this file								  
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_LANGUAGE_IDENTIFIERS_H
#define HMI_LANGUAGE_IDENTIFIERS_H
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#ifndef WIN32
#include "wchar.h"
#endif

/*============================================================================
** T Y P E   D E F I N I T I O N S                                                  
**==========================================================================*/
#ifndef LNG_UNICODE
   #define LNG_UNICODE
#endif /* LNG_UNICODE */

#define HM_LANG_USE_INERNAL_STRING_BUFFER
/* Release label major version 4 */
/* Release label minor version 12 */
#define HMI_LANG_CORE_TOOL_LABEL                  "LANG_TOOL_LABEL::rel-UI-CORE-ICEAPPLE-4.12"
#define HMI_LANG_CORE_TOOL_MAJOR_VERSION          4
#define HMI_LANG_CORE_TOOL_MINOR_VERSION          12
#define HMI_LANG_CORE_TOOL_VERSION                ((HMI_LANG_CORE_TOOL_MAJOR_VERSION * 100) + HMI_LANG_CORE_TOOL_MINOR_VERSION)

#define   HMI_LANGUAGE_UK_ENGLISH_FEAT
#define   HMI_LANGUAGE_US_ENGLISH_FEAT

typedef enum
{
   HMI_LANGUAGE_UK_ENGLISH,
   HMI_LANGUAGE_US_ENGLISH,
   LNG_MAX_LANGUAGE_COUNT
} HMI_LANGUAGE_T;

#define HM_LANG_MAX_STRING_SIZE         40
#define T_No                            0x0000
#define TXTID_BLANK                     0x0001
#define TXT_ID_ESP_ON                   0x0002
#define TXT_ID_ESP_TURNED               0x001E
#define TXT_ID_AVH                      0x002D
#define TXT_ID_AVH_FAIL                 0x0039
#define TXT_ID_TCS_ALERT                0x0045
#define TXT_ID_TRACT_CNTRL              0x0056
#define TXT_ID_TURN_OFF                 0x0067
#define TXT_ID_ESP_SYS_ALRT             0x0072
#define TXT_ID_ESP_PROGRAM              0x0083
#define TXT_ID_PARK_ALERT               0x00A0
#define TXT_ID_PB_ENGAGE                0x00B1
#define TXT_ID_AFTER_IMPACT             0x00C4
#define TXT_ID_MAL_DETECT               0x00D0
#define TXT_ID_PRESS_BP                 0x00E5
#define TXT_ID_REL_PB                   0x00F7
#define TXT_ID_PB_APPL                  0x010D
#define TXT_ID_DYN                      0x0120
#define TXT_ID_APMI_ALERT               0x0135
#define TXT_ID_APB_HOLD                 0x0141
#define TXT_ID_APB_SLOPE                0x0159
#define TXT_ID_APB_BUCKLE               0x0168
#define TXT_ID_APBMI                    0x0179
#define TXT_ID_SHIFT_TO_P               0x017F
#define TXT_ID_DRIVE_MODE_WARN          0x01A1
#define TXT_ID_DRV_CNTRL                0x01B4
#define TXT_ID_SHFT_DEN                 0x01C8
#define TXT_ID_STEER_FAIL               0x01CF
#define TXT_ID_STOP_DRV                 0x01E0
#define TXT_ID_MAL_FNCTN                0x01ED
#define TXT_ID_TRAN_SYS                 0x01F9
#define TXT_ID_TRAN_ALRT                0x020D
#define TXT_ID_LIMP_ACT                 0x0220
#define TXT_ID_SEAT_REM                 0x0234
#define TXT_ID_FAST_DRV_BLT             0x0247
#define TXT_ID_FAST_PASS_BLT            0x025F
#define TXT_ID_SPEED_LIMT               0x027A
#define TXT_ID_OVER_SPEED               0x028E
#define TXT_ID_SLOW                     0x02A5
#define TXT_ID_WET_MODE                 0x02AF
#define TXT_ID_ROUGH_MODE               0x02B3
#define TXT_ID_STP_VEHICLE_SAFE         0x02BE
#define TXT_ID_DOOR_OPEN                0x02D6
#define TXT_ID_CRUISE                   0x02E0
#define TXT_ID_CRUISE_OVR               0x02EF
#define TXT_ID_CHANGE_GEAR              0x02FF
#define TXT_ID_RES_CRUISE               0x030B
#define TXT_ID_CRU_ACT                  0x0322
#define TXT_ID_HDC_ON                   0x0330
#define TXT_ID_DEF_LOW                  0x033E
#define TXT_ID_REFILL                   0x034C
#define TXT_ID_REF_DEF                  0x0358
#define TXT_ID_ENG_RESTART              0x0363
#define TXT_ID_NXT_KEY                  0x037B
#define TXT_ID_ENG_STOP                 0x038A
#define TXT_ID_EMPTY                    0x0396
#define TXT_ID_DEF_FAULT                0x03A1
#define TXT_ID_QUAL_LOW                 0x03B2
#define TXT_ID_SAND_MODE                0x03C2
#define TXT_ID_MUD_MODE                 0x03C7
#define TXT_ID_SNOW_MODE                0x03D0
#define TXT_ID_PRESS_BRAKE              0x03DB
#define TXT_ID_PRESS_CLUTCH             0x03DE
#define TXT_ID_START_ENGINE             0x03F1
#define TXT_ID_LAMP_ALERT               0x0401
#define TXT_ID_LAMP_ACTIVE              0x040C
#define TXT_ID_SHIFTTOPARK              0x0424
#define TXT_ID_EXIT                     0x0432
#define TXT_ID_DRV_MAL                  0x043A
#define TXT_ID_DRV_SYSFLT               0x0452
#define TXT_ID_HDC_CTRL                 0x0460
#define TXT_ID_HDC_ACTV                 0x0475
#define TXT_ID_HHC_CTRL                 0x0483
#define TXT_ID_SYS_DEACTV               0x0496
#define TXT_ID_SPD_CROSS                0x04A9
#define TXT_ID_DRV_1GEAR                0x04C1
#define TXT_ID_10KMPH                   0x04D3
#define TXT_ID_PRESS_START              0x04E1
#define TXT_ID_TURN_WHEEL               0x04F4
#define TXT_ID_TEA                      0x050C
#define TXT_ID_BREAK                    0x0519
#define TXT_ID_ATTN_LVL                 0x0527
#define TXT_ID_ASSIST                   0x0537
#define TXT_ID_CHK                      0x054F
#define TXT_ID_WRNG_SYS                 0x0566
#define TXTID_KEYNOT                    0x0575
#define TXT_ID_MAIN_MENU                0x058C
#define TXT_ID_TRIP_INFO                0x0596
#define TXT_ID_TRIP_A                   0x05A0
#define TXT_ID_TRIP_B                   0x05A7
#define TXT_ID_TRIP_IFE                 0x05AE
#define TXT_ID_TRIP_BACK                0x05B9
#define TXT_ID_DRIVE_ASSIST             0x05BE
#define TXT_ID_DRIVER_ASSIST            0x05CB
#define TXT_ID_ATT_ASSIST               0x05D9
#define TXT_ID_DRIVE_ASSIST_BACK        0x05EA
#define TXT_ID_VEHICLE_INFO             0x05F0
#define TXT_ID_DEF                      0x05FD
#define TXT_ID_VEHICLE_INFO_BACK        0x0612
#define TXT_ID_NOTIFICATIONS            0x0619
#define TXT_ID_NOTIFICATIONS_BACK       0x0627
#define TXT_ID_NAVIGATION               0x0636
#define TXT_ID_COMPASS                  0x0641
#define TXT_ID_NAVI_BACK                0x0649
#define TXT_ID_AC_INFO                  0x0652
#define TXT_ID_AC_INFO_MENU             0x065A
#define TXT_ID_AC_BACK                  0x0663
#define TXT_ID_LAYOUT                   0x0666
#define TXT_DIAL_VIEW                   0x066D
#define TXT_ID_SETTINGS                 0x0677
#define TXT_ID_ILLUMINATION             0x0680
#define TXT_ID_SETT_ILLUMIN             0x068D
#define TXT_ID_SETTINGS_BACK            0x069B
#define TXT_ID_SETT_UNIT_GROUP          0x06AC
#define TXT_ID_UNIT_MENU                0x06B1
#define TXT_ID_TPMS                     0x06B7
#define TXT_ID_POW_TORQ                 0x06C8
#define TXT_ID_G_FORCE                  0x06D9
#define TXT_ID_DATE_TIME                0x06E7
#define TXT_ID_SER_REM                  0x06F5
#define TXT_ID_TBT_NAVI                 0x0707
#define TXT_ID_DIGITAL_VIEW             0x070A
#define TXT_ID_MINIMAL_VIEW             0x0717
#define TXT_ID_NOTIFI_LINE1             0x0724
#define TXT_ID_SETT_FACTORY_RESET       0x0727
#define TXT_ID_FACTORY_RESET            0x0735
#define TXT_ID_SETT_SERREM_RST          0x0743
#define TXT_ID_SER_REM_RST              0x075A
#define TXT_ID_SETT_ABOUT               0x0771
#define TXT_ID_ABOUT                    0x0777
#define TXT_ID_TEMP_MENU                0x0786
#define TXT_ID_TEMPERATURE              0x0792
#define TXT_ID_UNIT_BACK                0x07A7
#define TXT_ID_PRESSURE_MENU            0x07B3
#define TXT_ID_PRESSURE                 0x07BC
#define TXT_ID_SMALL_BACK               0x07CE
#define TXT_ID_SETT_FAV_MENU            0x07D3
#define TXT_ID_FAV_MENU                 0x07EC
#define TXT_ID_DEGREE_C                 0x07FB
#define TXT_ID_DEGREE_F                 0x07FD
#define TXT_ID_PRESSURE_PSI             0x07FF
#define TXT_ID_PRESSURE_KPA             0x0803
#define TXT_ID_FR_YES                   0x0807
#define TXT_ID_FR_CANCEL                0x080B
#define TXT_ID_SRR_YES                  0x0812
#define TXT_ID_SRR_CANCEL               0x0816
#define TXT_ID_ABT_SETT_L1              0x0819
#define TXT_ID_ABT_SETT_L2              0x0840
#define TXT_ID_ABT_SETT_L3              0x0862
#define TXT_ID_ABT_SETT_L4              0x0887
#define TXT_ID_ABT_SETT_L5              0x089F
#define TXT_ID_ABT_SETT_L6              0x08C2
#define TXT_ID_ABT_SETT_L7              0x08CD
#define TXT_ID_ABT_SETT_L8              0x08E2
#define TXT_ID_ABT_SETT_L9              0x0904
#define TXT_ID_ABT_SETT_L10             0x0927
#define TXT_ID_ABT_SETT_L11             0x094A
#define TXT_ID_ABT_SETT_L12             0x096B
#define TXT_ID_ABT_SETT_L13             0x0990
#define TXT_ID_F_RESET_FAV              0x09AA
#define TXT_ID_F_RST_YES                0x09BB
#define TXT_ID_F_RST_CANCEL             0x09BE
#define TXT_ID_SEAT_STORE               0x09C6
#define TXT_ID_SEAT_SEL                 0x09E2
#define TXT_ID_SEAT_FAIL                0x0A00
#define TXT_ID_FUEL_WARN                0x0A22
#define TXT_ID_FUEL_LOW                 0x0A35
#define TXT_ID_TRIP_A_RESET             0x0A44
#define TXT_ID_TRIPA_RST_YES            0x0A51
#define TXT_ID_TRIPA_RST_CANCEL         0x0A56
#define TXT_ID_TRIP_B_RESET             0x0A59
#define TXT_ID_TRIPB_RST_YES            0x0A66
#define TXT_ID_TRIPB_RST_CANCEL         0x0A6C
#define TXT_ID_SER_REM_GROUP            0x0A6F
#define TXT_ID_NOTIF                    0x0A80
#define TXT_ID_DR_OPEN_ALERT            0x0A90
#define TXT_ID_DR_OPEN_SYS_FAIL         0x0AA0
#define TXT_ID_CONTACT_SER_CEN          0x0AB3
#define TXT_ID_RCW                      0x0ACA
#define TXT_ID_SYS_FAIL                 0x0AE1
#define TXT_ID_SYS_TEMP_UNAVAIL         0x0AF0
#define TXT_ID_BSD                      0x0B0C
#define TXT_ID_BSD_SYS_FAIL             0x0B21
#define TXT_ID_BSD_SYS_TMP_UNAVAIL      0x0B34
#define TXT_ID_BSD_ORVM_FAIL            0x0B50
#define TXT_ID_ORVM_IND_FAIL            0x0B67
#define TXT_ID_TSR                      0x0B83
#define TXT_ID_TSR_SYS_UNAVAIL          0x0B98
#define TXT_ID_SYS_TMP_UNAVAIL          0x0BAF
#define TXT_ID_HIGH_BEAM_ASS            0x0BCE
#define TXT_ID_HB_ASS_SYS_FAIL          0x0BDF
#define TXT_ID_LANE_DEP_WARN            0x0BF2
#define TXT_ID_LDW_SYS_FAIL             0x0C09
#define TXT_ID_SYS_NOT_CAL              0x0C1C
#define TXT_ID_LAN_DEP_WARN_LKA         0x0C32
#define TXT_ID_LDW_LKS_SYS_FAIL         0x0C42
#define TXT_ID_LDW_LKS_SYS_NOT_CAL      0x0C59
#define TXT_ID_FCW_AEB_SYS_WARN         0x0C77
#define TXT_ID_SYS_LMT_PERF             0x0C8E
#define TXT_ID_CAM_BLOCK                0x0CA9
#define TXT_ID_RADAR_BLOCK              0x0CC0
#define TXT_ID_FCW_AEB_SYS_FAIL         0x0CD6
#define TXT_ID_COL_WARN                 0x0CED
#define TXT_ID_EMG_BRAKING              0x0CFF
#define TXT_ID_INC_TRAFFIC_DET          0x0D11
#define TXT_ID_DNT_OPEN_DOOR            0x0D2B
#define TXT_ID_LOW_KEY_BAT              0x0D40
#define TXT_ID_TPMS_ALERT               0x0D56
#define TXT_ID_CHECK_ALL_TYRE_PRE       0x0D61
#define TXT_ID_RESET_TPMS_SYS           0x0D7A
#define TXT_ID_TPMS_SYS_FAULT           0x0D90
#define TXT_ID_ITPMS_RESET_MENU         0x0DA3
#define TXT_ID_ITPMS_RESET              0x0DAF
#define TXT_ID_TPMS_RESET               0x0DBA
#define TXT_ID_TR_YES                   0x0DC6
#define TXT_ID_TR_CANCEL                0x0DC9
#define TXT_ID_AUTO_START_STOP          0x0DCC
#define TXT_ID_AUTO_START_ENABLED       0x0DDC
#define TXT_ID_VEHICLE_ROLL             0x0DEF
#define TXT_ID_LOW_BRAKE_AST_VAC        0x0DFF
#define TXT_ID_HIGH_CABIN_TEMP          0x0E17
#define TXT_ID_LOW_COOLANT_TEMP         0x0E2E
#define TXT_ID_ENABLED                  0x0E47
#define TXT_ID_DISABLED                 0x0E4F
#define TXT_ID_START_THE_ENGINE         0x0E58
#define TXT_ID_TRANSMISSION_MALF        0x0E69
#define TXT_ID_DONT_PRESS_BRAKE         0x0E82
#define TXT_ID_ACC_TOGETHER             0x0E9B
#define TXT_ID_TRANS_WARN               0x0EA4
#define TXT_ID_STAY_IN_D_MOD            0x0EB9
#define TXT_ID_FOR_TWENTY_SEC           0x0EC8
#define TXT_ID_AUTO_PARK_MALF           0x0ED7
#define TXT_ID_ENSUR_HANDBRAKE          0x0EED
#define TXT_ID_AUTO_PARK_ACTIV          0x0EFE
#define TXT_ID_TRANS_OIL                0x0F12
#define TXT_ID_TEMP_HIGH                0x0F23
#define TXT_ID_HIGH_STEERING_ANGLE      0x0F34
#define TXT_ID_LOW_BATTERY_CHARGE       0x0F48
#define TXT_ID_CLOCK_FORMAT             0x0F5B
#define TXT_ID_CLOCK_SET_TIME           0x0F6A
#define TXT_ID_CLK_BACK                 0x0F73
#define TXT_ID_CLOCK_MENU               0x0F76
#define TXT_ID_CALENDAR_MENU            0x0F7C
#define TXT_ID_CLOCK_HR                 0x0F85
#define TXT_ID_CLOCK_MIN                0x0F8C
#define TXT_ID_CLOCK_MODE               0x0F94
#define TXT_ID_CLOCK_YES                0x0F9D
#define TXT_ID_CLOCK_CANCEL             0x0FA5
#define TXT_ID_CALENDAR_DAY             0x0FB0
#define TXT_ID_CALENDAR_MONTH           0x0FB8
#define TXT_ID_CALENDAR_YEAR            0x0FC2
#define TXT_ID_CALENDAR_YES             0x0FCB
#define TXT_ID_CALENDAR_CANCEL          0x0FD3
#define TXT_ID_SW_VER                   0x0FDE
#define TXT_ID_CRUISE_ON                0x0FF0
#define TXT_ID_CRUISE_ACITAVTED         0x0FFA
#define TXT_ID_CRUISE_CANCELLED         0x100B
#define TXT_ID_CRUISE_RESUMING          0x101C
#define TXT_ID_CRUISE_UNABLE            0x102F
#define TXT_ID_CRUISE_OFF               0x1039
#define TXT_ID_CRUISE_TXT               0x1044
#define TXT_ID_CRUISE_SPEED             0x104B
#define TXT_ID_ACTIVATED_CRUISE         0x1058
#define TXT_ID_CRUISE_UNAVAILABLE       0x1068
#define TXT_ID_GSM_PRESS_BRAKE          0x1074
#define TXT_ID_BEFORE_SHIFTING          0x1080
#define TXT_ID_GSM_PRESS_UNLOCK         0x1090
#define TXT_ID_GSM_PRESS_TOSHIFT        0x109D
#define TXT_ID_PRESS_BRAKE_AND_UNLOCK   0x10A6
#define TXT_ID_PRESS_UNLOCK_TOSHIFT     0x10BB
#define TXT_ID_PRESS_PARK_BUTTON        0x10BE
#define TXT_ID_GEAR_SELECTOR_PARK       0x10D0
#define TXT_ID_NOT_AVAILABLE            0x10E3
#define TXT_ID_SPEED_TOO_HIGH           0x10F1
#define TXT_ID_FOR_PARK                 0x1100
#define TXT_ID_AUTO_MODE                0x1109
#define TXT_ID_AVAILABLE                0x1118
#define TXT_ID_STEEP_SLOPE              0x1122
#define TXT_ID_ACC_TO_MOVE              0x112E
#define TXT_ID_DCT_PRESS_BRAKE          0x1141
#define TXT_ID_AVOID_ROLLBACK           0x1150
#define TXT_ID_DISTANCE_MENU            0x115F
#define TXT_ID_DISTANCE_KM              0x1168
#define TXT_ID_DISTANCE_MI              0x1170
#define TXT_ID_DISTANCE                 0x117A
#define TXT_ID_FASTEN_SB_DRIVER         0x118C
#define TXT_ID_FASTEN_SB_CODRIVER       0x119A
#define TXT_ID_FASTEN_DRIVER_AND        0x11AB
#define TXT_ID_PASSEN_SB                0x11BC
#define TXT_ID_FASTEN_SB_PASSEN         0x11D2
#define TXT_ID_ESP_TURN_OFF             0x11ED
#define TXT_ID_AMT_GSM_SHIFT            0x11FC
#define TXT_ID_AMT_GSM_PRESS_BBRAKE     0x120C
#define TXT_ID_AMT_GSM_UNLOCK_TOSHIFT   0x121B
#define TXT_ID_MEM_SEAT                 0x122B
#define TXT_ID_SB                       0x1237
#define TXT_ID_PEPS_DCT                 0x1240
#define TXT_ID_IGN_ON_OFF               0x1261
#define TXT_ID_TO_START_VEH             0x1278
#define TXT_ID_PLS_CHECK_DEVICE         0x1289
#define TXT_ID_CHARGING_PAD             0x12A1
#define TXT_ID_SHIFT_TO_P_N             0x12BA
#define TXT_ID_SHIFTTOPARK_1            0x12CA
#define TXT_ID_POSLAMP_LINE1            0x12DC
#define TXT_ID_AUTO_WIPER_TITLE         0x12E6
#define TXT_ID_AUTO_WIPER_LINE1         0x12F7
#define TXT_ID_AEB_TITLE                0x130C
#define TXT_ID_AEB_LINE1                0x1316
#define TXT_ID_AEB_LINE2                0x1330
#define TXT_ID_ABPMI_MAL_TITLE          0x1359
#define TXT_ID_KEY_BAT_LOW_LINE1        0x136A
#define TXT_ID_MEM_SEAT_CANCLE_TITLE    0x137A
#define TXT_ID_RESUME_CRUISE            0x138F
#define TXT_ID_F_TRIP                   0x139D
#define TXT_ID_F_DRIVE_ASSIST           0x13B2
#define TXT_ID_F_VEH_INFO               0x13CD
#define TXT_ID_F_NOTIFICATIONS          0x13E8
#define TXT_ID_F_NAVIGATION             0x1405
#define TXT_ID_F_LAYOUT                 0x141C
#define TXT_ID_F_SETTINGS               0x142B
#define TXT_ID_F_BACK                   0x143E
#define TXT_ID_START_REQ_BY_AT          0x1454
/* Total Language Table Size = 5.12kBytes */
#define HM_LANG_MAX_PAGE                1
#define HM_LANG_MAX_SID                 0x146Au
#define HM_LANG_COMMON_MAX_SID          0x138Fu
#define HM_END_OF_SID                   (0xFFFFu)
#define HM_LANG_BUFFER_MAX_SIZE         (0x1480u)        /* This is the language database size */
typedef UINT16 LANG_SID_T;

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        08/12/09     JKANOZA                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                               
/* end of file =============================================================*/ 
#endif /* HMI_LANGUAGE_IDENTIFIERS_H */
