charon-systemd {
        fragment_size = 1280
        make_before_break = yes
        retransmit_base = 1.3
        retransmit_timeout = 1.5
        retransmit_tries = 10

    # Section to configure native systemd journal logger, very similar to the
    # syslog logger as described in LOGGER CONFIGURATION in strongswan.conf(5).
    journal {

        # Loglevel for a specific subsystem.
        # <subsystem> = <default>

        # Default loglevel.
        # default = 1

    }

}