# *********************************************************************************************************************
# Company:             Johnson Controls Inc.
# ---------------------------------------------------------------------------------------------------------------------
# Copyright:           This software is JCI property.
#                      Duplication or disclosure without JCI written authorization is prohibited.
# ---------------------------------------------------------------------------------------------------------------------
# Project:             E40_Platform
# Language:            Apache ANT Properties
# ---------------------------------------------------------------------------------------------------------------------
#      DO NOT CHANGE THIS FILE! IT HAS BEEN GENERATED. ANY CHANGES WILL BE OVERWRITTEN AT THE NEXT GENERATION!
# ---------------------------------------------------------------------------------------------------------------------
# Generated on Tue Aug 06 13:07:38 IST 2024 by the JCI UML Generation chain from the "E40_Platform" model.
# ---------------------------------------------------------------------------------------------------------------------
# Entity:              A2T_TST (DesignUnit)
# Description:         A2TOM Unit Test Framework
# Owner:               A2T_TC_FWK (Package)
# ---------------------------------------------------------------------------------------------------------------------
# Rhapsody version:    9.0.1
# Generator version:   V3.0.27
# Generator date:      11/12/2014 12:04:26,40
# ---------------------------------------------------------------------------------------------------------------------
name=A2T_TC.A2T_TC_FWK.A2T_TST
stereotype=DesignUnit
unit.file.path=A2T_TC_out/A2T_TC_FWK/A2T_TST/A2T_TST.sbs
location=A2T_TC_out/A2T_TC_FWK/A2T_TST
