
[VMF_VMQ]
; connection via character device
device_type=VMQ                  ; VMQ character device
local_device=VMF_receive_port    ; mi transfer messages are read from that device and send to vmf 
local_groups=1-119,127-250     	 ; vmf-groups comma separated
remote_device=VMF_send_port      ; remote device name  - received vmf messages are send to this device 

