/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2024. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 10/22/2024
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_IMG_LOW_BEAM_TV2_BASEID       (0)
#define GFX_IMG_BRAKE_TT_TV2_BASEID       (1)
#define GFX_IMG_RTURN_TT_TV2_BASEID       (2)
#define GFX_IMG_HAZARD_TT_TV2_BASEID      (3)
#define GFX_IMG_AIRBAG_TT_TV2_BASEID      (4)
#define GFX_IMG_ESC_TT_TV2_BASEID         (5)
#define GFX_IMG_ABS_TT_TV2_BASEID         (6)
#define GFX_IMG_SWHEEL_ICON_TV2_BASEID    (7)
#define GFX_IMG_FILL_SIGCDD_TV2_BASEID    (8)
#define GFX_IMG_HIGH_BEAM_TV2_BASEID      (9)
#define GFX_WDGT_SIG_CDD_IMG_BASEID       (10)
#define GFX_TXT_SAMPLE_BASEID             (0)
#define GFX_TXT_SAMPLE_1_BASEID           (1)
#define GFX_TXT_SAMPLE_0_0_BASEID         (2)
#define GFX_NEW_TEXTS_1_BASEID            (3)
#define GFX_TXT_SAMPLE_0_BASEID           (4)
#define GFX_INVALID_BASEID                (0)
#define GFX_FILL_SC_BASEID                (0)
#define GFX_WDGT_SIG_CDD_BASEID           (0)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS     (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS          (1U)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS     (11)
#define GFX_MGR02_NUM_3D_MDL_LAYERS       (0)
#define GFX_MGR02_NUM_USER_LAYERS         (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS (0)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS      (5)

#define GFX_MGR02_NUM_OF_SVGS             (0)

#define GFX_MGR02_NUM_OF_SVG_CLIPS        (0)
#define GFX_MGR02_NUM_OF_FILLS            (1)
#define GFX_MGR02_NUM_OF_TILES            (0)
#define GFX_MGR02_NUM_VIDEO_LAYERS        (0)
#define GFX_MGR02_DYNAMIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS            (1)

#define GFX_MGR02_NUM_VISIBLE_AREA      (2U)

/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (0)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (0)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (800)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (480)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_FILL_SC_ANIM                          = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_SAMPLE_0_ANIM                     = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_SAMPLE_ANIM                       = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_SAMPLE_1_ANIM                     = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_TXT_SAMPLE_0_0_ANIM                   = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_DTEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_WDGT_SIG_CDD_ANIM                     = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_TRAVEO2|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_SCR_SIG_CDD_ANIM                      = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_SCREEN | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS (0)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS    (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS  (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS   (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS  (1)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS  (0)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS  (4)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS (1)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS (1)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS (1)

#define GFX_MGR02_STEXTS_BUFFER_SIZE (10)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_TXT_SAMPLE,
   GFX_TXT_SAMPLE_1,
   GFX_TXT_SAMPLE_0_0,
   GFX_NEW_TEXTS_1,
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (4)
#define GFX_MGR02_NUM_OF_STEXTS      (1)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (2)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (3)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (112)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (60)
#define GFX_MGR02_MAX_PATH_CMD_BUF_LENGTH   (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   GFX_DWDG_TEST1                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET)
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS     (1)

 /*  Dynamic widget indices */
 /*  GFX_DWDG_TEST1 indices */
#define GFX_DWDG_TEST1_IDX_WDGT_SIG_CDD                        (0)

/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_DIMG_LOW_BEAM                         = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_BRAKE_TT                         = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_RTURN                            = GFX_MGR02_SET_OBJ(2,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_HAZARD                           = GFX_MGR02_SET_OBJ(3,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_AIRBAG                           = GFX_MGR02_SET_OBJ(4,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_ESC_TT                           = GFX_MGR02_SET_OBJ(5,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_ABS_TT                           = GFX_MGR02_SET_OBJ(6,GFX_MGR02_TYPE_DIMAGE)
  ,GFX_DIMG_SWHEEL_ICON                      = GFX_MGR02_SET_OBJ(7,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES      (8)

 /*  Dynamic Images indices */
 /*  GFX_DIMG_LOW_BEAM indices */
#define GFX_DIMG_LOW_BEAM_IDX_IMG_LOW_BEAM                        (0)
#define GFX_DIMG_LOW_BEAM_IDX_IMG_FILL_SIGCDD                        (1)
 /*  GFX_DIMG_BRAKE_TT indices */
#define GFX_DIMG_BRAKE_TT_IDX_IMG_BRAKE_TT                        (0)
#define GFX_DIMG_BRAKE_TT_IDX_IMG_HIGH_BEAM                        (1)
#define GFX_DIMG_BRAKE_TT_IDX_IMG_FILL_SIGCDD                        (2)
 /*  GFX_DIMG_RTURN indices */
#define GFX_DIMG_RTURN_IDX_IMG_RTURN_TT                        (0)
#define GFX_DIMG_RTURN_IDX_IMG_FILL_SIGCDD                        (1)
 /*  GFX_DIMG_HAZARD indices */
#define GFX_DIMG_HAZARD_IDX_IMG_HAZARD_TT                        (0)
#define GFX_DIMG_HAZARD_IDX_IMG_FILL_SIGCDD                        (1)
 /*  GFX_DIMG_AIRBAG indices */
#define GFX_DIMG_AIRBAG_IDX_IMG_AIRBAG_TT                        (0)
#define GFX_DIMG_AIRBAG_IDX_IMG_FILL_SIGCDD                        (1)
 /*  GFX_DIMG_ESC_TT indices */
#define GFX_DIMG_ESC_TT_IDX_IMG_ESC_TT                        (0)
#define GFX_DIMG_ESC_TT_IDX_IMG_FILL_SIGCDD                        (1)
 /*  GFX_DIMG_ABS_TT indices */
#define GFX_DIMG_ABS_TT_IDX_IMG_ABS_TT                        (0)
#define GFX_DIMG_ABS_TT_IDX_IMG_FILL_SIGCDD                        (1)
 /*  GFX_DIMG_SWHEEL_ICON indices */
#define GFX_DIMG_SWHEEL_ICON_IDX_IMG_SWHEEL_ICON                        (0)
#define GFX_DIMG_SWHEEL_ICON_IDX_IMG_FILL_SIGCDD                        (1)


#define GFX_IMG_LOW_BEAM_1                   GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_1                GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_BRAKE_TT_1                   GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_HIGH_BEAM_1                  GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_2                GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_RTURN_TT_1                   GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_3                GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_HAZARD_TT_1                  GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_4                GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_AIRBAG_TT_1                  GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_5                GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_ESC_TT_1                     GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_6                GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_ABS_TT_1                     GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_7                GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_SWHEEL_ICON_1                GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_IMG_FILL_SIGCDD_8                GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_NEW_TEXTS_1_1                    GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_DTEXT|GFX_MGR02_PLATFORM_TRAVEO2)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES    (9)
#define GFX_MGR02_NUM_SVG_INSTANCES       (0)
#define GFX_MGR02_NUM_FILL_INSTANCES      (0)
#define GFX_MGR02_NUM_TILE_INSTANCES      (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES      (0)
#define GFX_MGR02_NUM_TEXT_INSTANCES      (1)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_SIG_CDD                           = (0)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS             (1)
#define GFX_MGR02_LAYER0_DAR_SIZE            (1)
#define GFX_MGR02_WIDGET0_DAR_SIZE           (12)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (2)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX      (27)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_SIG_CDD_BG_COLOR                            (0x000000FFUL)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x000000FFu)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (5)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1U)
#define GFX_MGR02_NUM_PRIORITY            (1)
#define GFX_MGR02_UNICODE              (1)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (20)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (0)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (0)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_ARGB8888)
#define GFX_MGR02_GEN2_PROJECT
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (1)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_TRAVEO2
#define GFX_MGR02_USE_EXT_FONT_ENGINE
#define GFX_MGR02_RENDER_NONE
/*
** Traveo2 - Instructin buffer size in bytes
*/
#define GFX_MGR02_IRIS_MEMTASK0_IBUFF_SIZE             0
#define GFX_MGR02_IRIS_MEMTASK1_IBUFF_SIZE             65536
#define GFX_MGR02_IRIS_MEMTASK2_IBUFF_SIZE             0
#define GFX_MGR02_IRIS_WINTASK0_IBUFF_SIZE             0
#define GFX_MGR02_IRIS_WINTASK1_IBUFF_SIZE             0
#define GFX_MGR02_IRIS_WINTASK2_IBUFF_SIZE             0
#define GFX_MGR02_IRIS_WINTASK3_IBUFF_SIZE             0

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        10/22/2024     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
