/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in 2024. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_mgr02_font.c                                     
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated. Do not hand modify                          
Organization     :  Driver Information Software Section,                       
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#define HMI_GFX_MGR02_PRIV_C

/*****************************************************************************
*                                 System Includes                            *
******************************************************************************/
#include "hmi_gfx_mgr02_layout.h"
#include "hmi_gfx_mgr02_font.h"
#include "hmi_gfx_mgr02_font.cfg"
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/

UINT8 const lc_New_fonts_1_group[]=
{
   GFX_MGR02_FONT_ID_ARABIC_FONT,
   GFX_MGR02_FONT_ID_THAI_FONT
};
#ifndef GFX_MGR02_FONT_TABLE_PREFIX
  #define GFX_MGR02_FONT_TABLE_PREFIX
#endif

GFX_MGR02_FONT_TABLE_PREFIX GFX_MGR02_FONT const lc_gfx_font_table[]=
{
  {50.000F, 2048, 0, 0, 0, 1, 0, GFX_MGR02_FONT_ENCODING_8BPP,20,{96}, 255, 1, {&FrutigerLTArabic_65Bold[0]}},
  {50.000F, 1000, 0, 0, 0, 1, 0, GFX_MGR02_FONT_ENCODING_8BPP,20,{76}, 255, 2, {&NeueFrutigerThaiTrad_Md[0]}},
  {0.000F, 0, 2, 1, 0, 0, 0, 0, 0,{0}, 255, 255, {lc_New_fonts_1_group}}
};
                                                                              
                                                                              
/* Multi line used special characters */
#ifdef GFX_MGR02_SHAPE_ENGINE_ENABLED
GFX_MGR02_SHAPE_CMAP const lc_unique_font_id_sp_1[] = 
{ 
  { 32, 3},    /* space */
  { 12, 0},    /* form feed */
  { 10, 0},    /* new line */
  { 13, 2},    /* carriage return */
  { 9, 0},    /* horizontal tab */
  { 11, 0},    /* vertical tab */
  { 127, 0}  /* del */
};

GFX_MGR02_SHAPE_CMAP const lc_unique_font_id_sp_2[] = 
{ 
  { 32, 3},    /* space */
  { 12, 0},    /* form feed */
  { 10, 0},    /* new line */
  { 13, 2},    /* carriage return */
  { 9, 0},    /* horizontal tab */
  { 11, 0},    /* vertical tab */
  { 127, 0}  /* del */
};

GFX_MGR02_SHAPE_CMAP_TABLE const lc_gfx_font_ml_sp_cmap[] = 
{ 
  {
	&lc_unique_font_id_sp_1[0], 
	7
  },
  {
	&lc_unique_font_id_sp_2[0], 
	7
  },
};

/* Multi line used line breaking characters */
GFX_MGR02_SHAPE_CMAP const lc_unique_font_id_lb_1[] = 
{ 
  { 32, 3}
};

GFX_MGR02_SHAPE_CMAP const lc_unique_font_id_lb_2[] = 
{ 
  { 32, 3}
};

GFX_MGR02_SHAPE_CMAP_TABLE const lc_gfx_font_ml_lb_cmap[] = 
{ 
  {
	&lc_unique_font_id_lb_1[0], 
	GFX_MGR02_TOTAL_LINE_BREAK_CHAR
  },
  {
	&lc_unique_font_id_lb_2[0], 
	GFX_MGR02_TOTAL_LINE_BREAK_CHAR
  },
};

#endif
/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        10/22/2024     EMANOJ1                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
