/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2010. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**============================================================================
**
** Name:           gdg02_image_data.c
**
** Description:    This file is used by the application code to determine
**                 where graphic pixel data generated by the GDT tool
**                 should reside in memory.  The two choices are internal
**                 flash or external flash (accessed via the QSPI
**                 peripheral).  Details on how to make the selection are
**                 available below.
**
** Organization:   Driver Information Software Section,
**                 DI Core Engineering Department
**
**============================================================================
**
**==========================================================================*/
#define GDG02_IMAGE_DATA_C

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "system.h"
#include "hmi_gfx_mgr02_layout.h"

/*
** For files in external flash memory, #include them as in the example below.
** Note the use of #pragmas.
*/
#ifndef WIN32
   typedef UINT8  GFX_IMG_DATA_T    __attribute__ ((aligned (8)));
   typedef UINT16 GFX_IMG_DATA16_T  __attribute__ ((aligned (8)));
   typedef UINT32 GFX_IMG_DATA32_T  __attribute__ ((aligned (8)));
#else
   typedef UINT8  GFX_IMG_DATA_T;
   typedef UINT16 GFX_IMG_DATA16_T;
   typedef UINT32 GFX_IMG_DATA32_T;
#endif

#define GFX_IMG_DATA_PREFIX
#define GFX_IMG_DATA_SUFFIX 
#if 0
#include "img_opening_anim_0_ovg.dat"
#include "img_opening_anim_1_ovg.dat"
#include "img_opening_anim_2_ovg.dat"
#include "img_opening_anim_3_ovg.dat"
#include "img_opening_anim_4_ovg.dat"
#include "img_opening_anim_5_ovg.dat"
#include "img_opening_anim_6_ovg.dat"
#include "img_opening_anim_7_ovg.dat"
#include "img_opening_anim_8_ovg.dat"
#include "img_opening_anim_9_ovg.dat"
#include "img_opening_anim_10_ovg.dat"
#include "img_opening_anim_11_ovg.dat"
#include "img_opening_anim_12_ovg.dat"
#include "img_opening_anim_13_ovg.dat"
#include "img_opening_anim_14_ovg.dat"
#include "img_opening_anim_15_ovg.dat"
#include "img_opening_anim_16_ovg.dat"
#include "img_opening_anim_17_ovg.dat"
#include "img_opening_anim_18_ovg.dat"
#include "img_opening_anim_19_ovg.dat"
#include "img_opening_anim_20_ovg.dat"
#include "img_opening_anim_21_ovg.dat"
#include "img_opening_anim_22_ovg.dat"
#include "img_opening_anim_23_ovg.dat"
#include "img_opening_anim_24_ovg.dat"
#include "img_info_popup_border.dat"
#include "img_info_popup1.dat"
#include "img_ack_popup_border.dat"
#include "img_ack_popup1.dat"
#include "img_hardwrng_border_ovg.dat"
#include "img_hardwrng1_ovg.dat"
#include "img_softwrng_border_ovg.dat"
#include "img_infowrng1_ovg.dat"
#include "img_infowrng_border_ovg.dat"
#include "img_softwrng1_ovg.dat"
#include "img_hardwng_1_ovg.dat"
#include "img_progress1.dat"
#include "img_progress2_ovg.dat"
#include "img_progress3_ovg.dat"
#include "img_progress4_ovg.dat"
#include "img_progress5_ovg.dat"
#include "img_progress6_ovg.dat"
#include "img_progress7_ovg.dat"
#include "img_progress8_ovg.dat"
#include "img_progress9_ovg.dat"
#include "img_progress10_ovg.dat"
#include "img_progress11_ovg.dat"
#include "img_progress12_ovg.dat"
#include "img_progress13_ovg.dat"
#include "img_progress14_ovg.dat"
#include "img_progress15_ovg.dat"
#include "img_progress16_ovg.dat"
#include "img_progress17_ovg.dat"
#include "img_progress18_ovg.dat"
#include "img_progress19_ovg.dat"
#include "img_progress20_ovg.dat"
#include "img_progress21_ovg.dat"
#include "img_progress22_ovg.dat"
#include "img_progress23_ovg.dat"
#include "img_menu_media.dat"
#include "img_menu_phone.dat"
#include "img_menu_settings.dat"
#include "img_menu_arrow.dat"
#endif
//#include "img_opening_ovg.dat"
#if 0
//   #include "img_1_ovg.dat"
//#include "new_images_6_ovg.dat"
   #include "new_images_5.dat"
   #include "new_images_6.dat"
//   #include "img_1.dat"
#endif
#include "img_opening_anim_0_mon.dat"
#include "img_opening_anim_1_mon.dat"
#include "img_opening_anim_2_mon.dat"
#include "img_opening_anim_3_mon.dat"
#include "img_opening_anim_4_mon.dat"
#include "img_opening_anim_5_mon.dat"
#include "img_opening_anim_6_mon.dat"
#include "img_opening_anim_7_mon.dat"
#include "img_opening_anim_8_mon.dat"
#include "img_opening_anim_9_mon.dat"
#include "img_opening_anim_10_mon.dat"
#include "img_opening_anim_11_mon.dat"
#include "img_opening_anim_12_mon.dat"
#include "img_opening_anim_13_mon.dat"
#include "img_opening_anim_14_mon.dat"
#include "img_opening_anim_15_mon.dat"
#include "img_opening_anim_16_mon.dat"
#include "img_opening_anim_17_mon.dat"
#include "img_opening_anim_18_mon.dat"
#include "img_opening_anim_19_mon.dat"
#include "img_opening_anim_20_mon.dat"
#include "img_opening_anim_21_mon.dat"
#include "img_opening_anim_22_mon.dat"
#include "img_opening_anim_23_mon.dat"
#include "img_opening_anim_24_mon.dat"
#include "img_info_popup_border_mon.dat"
#include "img_info_popup1_mon.dat"
#include "img_ack_popup_border_mon.dat"
#include "img_ack_popup1_mon.dat"
#include "img_hardwrng_border_mon.dat"
#include "img_hardwrng1_mon.dat"
#include "img_softwrng_border_mon.dat"
#include "img_infowrng1_mon.dat"
#include "img_infowrng_border_mon.dat"
#include "img_softwrng1_mon.dat"
#include "img_hardwng_1_mon.dat"
#include "img_progress1_mon.dat"
#include "img_progress2_mon.dat"
#include "img_progress3_mon.dat"
#include "img_progress4_mon.dat"
#include "img_progress5_mon.dat"
#include "img_progress6_mon.dat"
#include "img_progress7_mon.dat"
#include "img_progress8_mon.dat"
#include "img_progress9_mon.dat"
#include "img_progress10_mon.dat"
#include "img_progress11_mon.dat"
#include "img_progress12_mon.dat"
#include "img_progress13_mon.dat"
#include "img_progress14_mon.dat"
#include "img_progress15_mon.dat"
#include "img_progress16_mon.dat"
#include "img_progress17_mon.dat"
#include "img_progress18_mon.dat"
#include "img_progress19_mon.dat"
#include "img_progress20_mon.dat"
#include "img_progress21_mon.dat"
#include "img_progress22_mon.dat"
#include "img_progress23_mon.dat"
#include "img_menu_media_mon.dat"
#include "img_menu_bg_mon.dat"
#include "img_menu_focus_mon.dat"
#undef GFX_IMG_DATA_PREFIX

#if defined(MATLAB_MEX_FILE)||defined(WIN32)
	#define GFX_IMG_DATA_PREFIX
#else
	#pragma push
	#pragma section "QSPI0_FLASH"
	#define GFX_IMG_DATA_PREFIX   __declspec(section "QSPI0_FLASH")
#endif

/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** CMS Rev 1        01/13/10     JKANOZA
** Initial revision.
**
**==========================================================================*/

/* end of file =============================================================*/

