/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2012. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT v1.0.41. Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 10/9/2012
**                                                                            
**                 See the <Kepler Software Architecture document> in         
**                 ClearCase in <sw_architecture\driver_information\        
**                 platforms\kepler\05_product\design> for more details    
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_types.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


#ifdef HMI_GFX_MGR02_C
/*
** Graphics Manager internal ID definitions. Donot use these in app
*/
#define GFX_MGR02_NUM_OF_IMAGE_LAYERS (0)

#define GFX_MGR02_NUM_OF_TEXT_LAYERS (0)
#endif /* #ifdef HMI_GFX_MGR02_C */

/*
** Project Specific ID definitions, this can be used by app
*/
typedef enum
{

   /* - GFX_MGR02_NUM_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_vclip
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */

   /* - GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS
   ** Widget animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_vclip
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   TEMP
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_ANIM_ELEMENTS (1)

#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS (1)

#define GFX_MGR02_NUM_USER_LAYERS (1)


/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   __GFX_MGR02_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS (0)
#define GFX_MGR02_NUM_OF_STEXTS (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
__GFX_MGR02_NUM_OF_DYNAMIC_WIDGETS
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS (1)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
  NUM_GFX_MGR02_NUM_DYNAMIC_IMAGES
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES (0)

#define GFX_MGR02_NUM_NON_ANIM_ELEMENTS (0)


/* GFX_MGR02_NUM_WIDGET_NON_ANIM_ELEMENTS */
#define GFX_MGR02_NUM_WIDGET_NON_ANIM_ELEMENTS (0)


/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_00          = (0)
  ,GFX_SCR_01          = (1)
  ,GFX_SCR_02          = (2)
  ,GFX_SCR_10          = (3)
  ,GFX_SCR_11          = (4)
  ,GFX_SCR_12          = (5)
  ,GFX_SCR_20          = (6)
  ,GFX_SCR_21          = (7)
  ,GFX_SCR_22          = (8)
  ,GFX_SCR_WARN_ONE    = (9)
  ,GFX_SCR_WARN_TWO		 = (10)
	,GFX_SCR_WARN_THREE


}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS   (9)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_MAX_TEXT_LENGTH (0)
#define GFX_MGR02_NUM_PRIORITY    (3)
#define GFX_MGR02_NUM_SOFT_LAYERS (0)
#define GFX_MGR02_DISP_WIDTH      (1)
#define GFX_MGR02_DISP_HEIGHT     (1)
#define GFX_MGR02_NEWPROJECT

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_00_BG_COLOR                                 (0x00000000)
#define GFX_SCR_01_BG_COLOR                                 (0x00000000)
#define GFX_SCR_02_BG_COLOR                                 (0x00000000)
#define GFX_SCR_10_BG_COLOR                                 (0x00000000)
#define GFX_SCR_11_BG_COLOR                                 (0x00000000)
#define GFX_SCR_12_BG_COLOR                                 (0x00000000)
#define GFX_SCR_20_BG_COLOR                                 (0x00000000)
#define GFX_SCR_21_BG_COLOR                                 (0x00000000)
#define GFX_SCR_22_BG_COLOR                                 (0x00000000)

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        10/9/2012     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
