
#ifndef ICU_H
#define ICU_H

/** \file
 ** \brief AUTOSAR Icu ICU Driver
 **
 ** This file contains or includes all external identifiers of
 ** the AUTOSAR module Icu.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/

/*==================[inclusions]============================================*/
#include <Icu_Common_Defines.h>
#include <Icu_Common_Types.h>

#include <Icu_Cfg.h>             /* Generated configuration */
#include <Icu_Version.h>

#include <EcuM.h>
/*==================[macros]================================================*/

/*------------------[Check AUTOSAR version]----------------------------------*/
#if (!defined ICU_AR_RELEASE_MAJOR_VERSION)           /* Autosar release major version check */
#error ICU_AR_RELEASE_MAJOR_VERSION must be defined
#endif

#if (!defined ICU_AR_RELEASE_MINOR_VERSION)           /* Autosar release minor version check */
#error ICU_AR_RELEASE_MINOR_VERSION must be defined
#endif

#if (!defined ICU_AR_RELEASE_REVISION_VERSION)        /* Autosar release revision version check */
#error ICU_AR_RELEASE_REVISION_VERSION must be defined
#endif


/*------------------[AUTOSAR AR version number check]----------*/
// #if !ICU_AR_VERSION_CHECK(4, 2, 1)
// #error AUTOSAR AR version number mismatch
// #endif

/*------------------[Check ICU driver version]------------------------------*/
#if (!defined ICU_SW_MAJOR_VERSION)                   /* Software major version check */
#error ICU_SW_MAJOR_VERSION must be defined
#endif /* if (!defined ICU_SW_MAJOR_VERSION) */

#if (!defined ICU_SW_MINOR_VERSION)                   /* Software minor version check */
#error ICU_SW_MINOR_VERSION must be defined
#endif /* if (!defined ICU_SW_MINOR_VERSION) */

#if (!defined ICU_SW_PATCH_VERSION)                   /* Software patch version check */
#error ICU_SW_PATCH_VERSION must be defined
#endif /* if (!defined ICU_SW_PATCH_VERSION) */


/*------------------[AUTOSAR SW version number check]----------*/
// #if !ICU_SW_VERSION_CHECK(1, 0, 28)
// #error AUTOSAR SW version number mismatch
// #endif


/*------------------[AUTOSAR configuration AR version number check]----------*/
// #if !ICU_AR_VERSION_CHECK(ICU_GEN_AR_RELEASE_MAJOR_VERSION, ICU_GEN_AR_RELEASE_MINOR_VERSION, ICU_GEN_AR_RELEASE_REVISION_VERSION)
// #error AUTOSAR configuration AR version number mismatch
// #endif

/*------------------[AUTOSAR configuration SW version number check]----------*/
// #if !ICU_SW_VERSION_CHECK(ICU_GEN_SW_MAJOR_VERSION, ICU_GEN_SW_MINOR_VERSION, ICU_GEN_SW_PATCH_VERSION)
// #error AUTOSAR configuration SW version number mismatch
// #endif

/*------------------[AUTOSAR configuration additional check]-----------------*/
// #if !ICU_EXTRA_CHECK(ICU_GEN_MODULE_ID, ICU_GEN_VENDOR_ID)
// #error AUTOSAR configuation additional check mismatch
// #endif

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/
#define ICU_START_SEC_CODE
#include <MemMap.h>
  /** \brief Icu_Init
   **
   ** This function Initialization of all configured channels of the Icu module.
   ** It checks if error detection is enabled;
   ** for ConfigPtr is valid, ConfigPtr length is valid and
   ** init was already done.
   ** It reports a detected error to DET, if enabled.
   ** It calls the Icu_Init_Arch() and sets the internal variable
   ** Icu_DriverStatus = ICU_S_INITIALIZED.
   ** 
   ** 
   ** Preconditions:
   ** - No Init call should be done before.
   **
   ** \param[in] ConfigPtr   Configuration pointer to config data.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_Init(P2CONST(Icu_ConfigType, AUTOMATIC, ICU_APPL_CONST) ConfigPtr);

#if(ICU_DE_INIT_API == STD_ON)
  /** \brief Icu_DeInit
   ** 
   ** This function does the deinit of the Icu module.
   ** It checks if error detect is enabled
   ** for init was already done.
   ** It will report an error to DET, if enabled.
   ** It calls the function Icu_DeInit_Arch() and
   ** disable all interrupts.
   ** It sets the module variables to default and sets the internal
   ** variable Icu_DriverStatus = ICU_S_UNINITIALIZED.

   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] none.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_DeInit(void);
#endif

#if(ICU_ENABLE_WAKEUP_API == STD_ON)
  /** \brief Icu_EnableWakeup
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Enables the wake-up capability of a channel.
   **
   ** Preconditions:
   ** - Init must be done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_EnableWakeup(Icu_ChannelType Channel);
#endif

#if(ICU_DISABLE_WAKEUP_API == STD_ON)
  /** \brief Icu_DisableWakeup
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Disables the wake-up capability of a channel.
   ** 
   ** Preconditions:
   ** - Init must be done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_DisableWakeup(Icu_ChannelType Channel);
#endif
  /** \brief Icu_ReportWakeupSource
   **
   ** This function does check if source is wakeup and 
   ** report wakeup sources to the ECU state manager.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval    none
   ** */
  extern FUNC(void, ICU_CODE)  Icu_ReportWakeupSource(Icu_ChannelType Channel);

#if(ICU_EDGE_COUNT_API == STD_ON)
  /** \brief Icu_DisableEdgeCount
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** The edge count is disabled.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_DisableEdgeCount(Icu_ChannelType Channel);
  /** \brief Icu_EnableEdgeCount
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** The edge count is enabled.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_EnableEdgeCount (Icu_ChannelType Channel);
   /** \brief Icu_ResetEdgeCount
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Reset the value of the counted edges to zero.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_ResetEdgeCount  (Icu_ChannelType Channel);
  /** \brief Icu_GetEdgeNumbers
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Get number of edges occured.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval    Number of edges occured.
   ** */
  extern FUNC(Icu_EdgeNumberType, ICU_CODE) Icu_GetEdgeNumbers  (Icu_ChannelType Channel);
#endif

#if(ICU_EDGE_DETECT_API == STD_ON)
  /** \brief Icu_DisableEdgeDetection
   **
   ** This function disables the edge detection of a specific channel.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval  none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_DisableEdgeDetection(Icu_ChannelType Channel);
  /** \brief Icu_EnableEdgeDetection
   **
   ** This function enables the edge detection of a specific channel.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval  none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_EnableEdgeDetection(Icu_ChannelType Channel);
#endif

#if(ICU_SET_MODE_API == STD_ON)
  /** \brief Icu_SetMode
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Set the mode of Icu module.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Mode   The mode of which is to be set.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_SetMode(Icu_ModeType Mode);
#endif
  /** \brief Icu_SetActivationCondition
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Set activation-edge of the channel.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel     Id of the channel.
   ** \param[in] Activation  Type of activation.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_SetActivationCondition(Icu_ChannelType Channel, Icu_ActivationType Activation );
  /** \brief Icu_DisableNotification
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   **
   ** Preconditions:
   ** - Notification should have been enabled.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_DisableNotification(Icu_ChannelType Channel);
  /** \brief Icu_EnableNotification
   **
   ** This function does check if init is done and channel is valid.
   ** It als checks for allowed notification type.
   ** It will report an error to DET, if enabled.
   ** If no notification function is configured, it skips the function.
   ** It calls the function IcuLld_EnableNotification().
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_EnableNotification(Icu_ChannelType Channel);

#if(ICU_GET_DUTY_CYCLE_VALUES_API == STD_ON)
  /** \brief Icu_GetDutyCycleValues
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Get duty cycle value.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   ** \param[out] DutyCycleValues  Pointer to duty cycles buffer where the results shall be placed.
   ** 
   ** \retval    none
   ** */
  extern FUNC(void, ICU_CODE)  Icu_GetDutyCycleValues( Icu_ChannelType Channel, P2VAR(Icu_DutyCycleType, AUTOMATIC, ICU_APPL_DATA) DutyCycleValues );
#endif

#if(ICU_GET_INPUT_STATE_API == STD_ON)
  /** \brief Icu_GetInputState.
   **
   ** This function checks if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** If an error has been detected ICU_IDLE will be returned.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel
   ** 
   ** \retval    Icu input state type.
   ** */
  extern FUNC(Icu_InputStateType, ICU_CODE) Icu_GetInputState(Icu_ChannelType Channel);
#endif

#if(ICU_TIMESTAMP_API == STD_ON)
  /** \brief Icu_StartTimestamp.
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Start timestamp measurement.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   ** - Icu_StartTimestamp may only be called multiple times if Icu_StopTimestamp
   **   has been called (at least once) between two calls of Icu_StartTimestamp.
   **
   ** \param[in] Channel          Id of the channel.
   ** \param[in/out] BufferPtr    pointer to buffer.
   ** \param[in] BufferSize       buffer size.
   ** \param[in] NotifyInterval   Notification interval.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_StartTimestamp(
             Icu_ChannelType                                Channel        ,
             P2VAR(Icu_ValueType, AUTOMATIC, ICU_APPL_DATA) BufferPtr      ,
             uint16                                         BufferSize     ,
             uint16                                         NotifyInterval );
   /** \brief Icu_StopTimestamp.
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Stop timestamp measurement.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE) Icu_StopTimestamp(Icu_ChannelType Channel);
   /** \brief Icu_GetTimestampIndex
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Get timestamp index.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval    Time stamp index.
   ** */
  extern FUNC(Icu_IndexType, ICU_CODE) Icu_GetTimestampIndex(Icu_ChannelType Channel);
#endif
#if(ICU_GET_TIME_ELAPSED_API == STD_ON)
  /** \brief Icu_GetTimeElapsed
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Get time elapsed.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   **
   ** \param[in] Channel   Id of the channel.
   **
   ** \retval    Elapsed time.
   ** */
  extern FUNC(Icu_ValueType, ICU_CODE) Icu_GetTimeElapsed(Icu_ChannelType Channel);
#endif

#if(ICU_GET_VERSION_INFO_API == STD_ON)
  /** \brief Icu_GetVersionInfo
   **
   ** This function gets the version infomation of the module.
   **
   ** \param[out] VersionInfo   Icu driver module's version.
   **
   ** \retval    none
   ** */
  extern FUNC(void, ICU_CODE)  Icu_GetVersionInfo(P2VAR(Std_VersionInfoType, AUTOMATIC, ICU_APPL_DATA) versioninfo);
#endif

#if(ICU_SIGNAL_MEASUREMENT_API == STD_ON)
  /** \brief Icu_StartSignalMeasurement
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Start Singal Measurement.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   ** - channel is configured in Signal Measurement mode
   **
   ** \param[in] Channel  Id of the channel.
   **
   ** \retval  none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_StartSignalMeasurement(Icu_ChannelType Channel);
  /** \brief Icu_StopSignalMeasurement
   **
   ** This function does check if init is done and channel is valid.
   ** It will report an error to DET, if enabled.
   ** Stop Signal Measurement.
   **
   ** Preconditions:
   ** - Icu_Init should have been done.
   ** - channel is configured in Signal Measurement mode
   **
   ** \param[in] Channel  Id of the channel.
   **
   ** \retval    none
   ** */
  extern FUNC(void, ICU_CODE)  Icu_StopSignalMeasurement(Icu_ChannelType Channel);
#endif

#if(ICU_WAKEUP_FUNCTIONALITY_API == STD_ON)
  /** \brief Icu_CheckWakeup
   **
   ** Checks if a wakeup capable ICU channel is the source for a wakeup 
   ** event and calls the ECU state manager service EcuM_SetWakeupEvent
   ** in case of a valid ICU channel wakeup event. 
   **
   ** Preconditions:
   ** - Init must be done.
   **
   **
   ** \param[in] WakeupSource   informatin on wakeup source to be checked. 
   **
   ** \retval   none.
   ** */
  extern FUNC(void, ICU_CODE)  Icu_CheckWakeup(EcuM_WakeupSourceType WakeupSource);
#endif

#if ( ICU_SAFETY_FUNCTION_API == STD_ON )
 /** \brief Icu_CheckChannelStatus
 **
 ** This function checks the register of the ICU driver.
 **
 ** \param[in]  Channel                  A valid configuration for the Icu driver.
 **
 ** \param[out] CheckChannelStatusPtr    Pointer to where to store the channel status information.
 **
 ** \retval     none.
 ** */
FUNC(void, ICU_CODE) Icu_CheckChannelStatus
(
  Icu_ChannelType Channel,
  P2VAR(Icu_CheckChannelStatusType, AUTOMATIC, ICU_APPL_DATA) CheckChannelStatusPtr
);
#endif

#define ICU_STOP_SEC_CODE
#include <MemMap.h>
/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

#endif /* ifndef ICU_H */
/*==================[end of file]===========================================*/
