
#ifndef TS_ARCH_NAMES_H
#define TS_ARCH_NAMES_H

/** \brief Mapping of Architecture Names/IDs
 **
 ** This files contains mapping of architecture names to IDs
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/


/*==================[inclusions]============================================*/

#include <TSDer_Names.h> /* defines for architecture names */

/*==================[macros]================================================*/
/* definition of architecture names */
#define TS_C16X             1U
#define TS_MPC              2U
#define TS_EXCALIBUR        3U
#define TS_F2MC16L          4U
#define TS_MB91             5U
#define TS_H8               6U
#define TS_HC08             7U
#define TS_HC12             8U
#define TS_M32C             9U
#define TS_NEC78K          10U
#define TS_S12X            11U
#define TS_SAF7780         12U
#define TS_SH2             13U
#define TS_ST30            14U
#define TS_TMS470          15U
#define TS_TRICORE         16U
#define TS_V850            17U
#define TS_XC16X           18U
#define TS_WINDOWS         19U
#define TS_XC2000          20U
#define TS_R32C            21U
#define TS_XPC56XX         24U
#define TS_M32R            25U

#define TS_MB96            28U
#define TS_MB9E            32U
#define TS_S6J311          32U
#define TS_S6J312          33U
#define TS_S6J323          34U
#define TS_S6J324          35U
#define TS_S6J325          36U
#define TS_S6J326          37U
#define TS_S6J320          38U
#define TS_S6J32D          39U
#define TS_S6J32C          40U
#define TS_S6J32B          41U
#define TS_S6J32A          42U
#define TS_S6J328          43U
#define TS_S6J32G          44U
#define TS_S6J329          45U
#define TS_S6J32M          46U

#define TS_S6J331         100U
#define TS_S6J335         101U
#define TS_S6J342         102U
#define TS_S6J332         103U
#define TS_S6J333         104U
#define TS_S6J334         105U
#define TS_S6J336         106U
#define TS_S6J351         107U

/* definition of value for TS_ARCH_DERIVATE macro */
#define TS_S6J3100          1U
#define TS_S6J320A          2U
#define TS_S6J320C          3U
#define TS_S6J3300          4U
#define TS_S6J3400          5U
#define TS_S6J320E          6U
#define TS_S6J3500          7U

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

#endif /* ifndef TS_ARCH_NAMES_H */
/*==================[end of file]===========================================*/
