
[VMF]
verbose=true            # display the current VMF setup on the console  
version_string=true     # print vmf-version string
vmf_mi=false            # VMF multi-instance enabled
default_severity=19     # default severity. !The old vmf-trace persistant file will be cleared and a new one with this severity is created! 
startup_q=true          # vmf-tracer startup queue enabled
tardis_name=VMF         # tardis name
tardis_cat=5            # tardis category
tardis_broadcast=192.168.1.255  # tardis broadcast address
enable_timeserver=true  # this VMF acts as time-server
timeserver_intervall=1  # time is send every second

[TRACE_SEVERITIES]
VMF-Ping=73
vmf_listen=100
Trace-Ping=100

[DLT]
enable_dlt=false		# enable DLT (-d option not needed if set here)
vmf_msg_groups=1,5-10	# VMF basic messages with this groups are send to DLT

[EXTENSIONS]
;ext1=test.bat           # VMF will auto start all extensions
;ext2=test2.exe

[LOGGING]
enabled=true            # true if VMF logging enabled
path=l:                 # path of ini file - vmf_log.ini is read from this path and log files are stored here
max_file_len=500000     # maximum length of a log file in Kbytes - if this size is reached a new log file is created
max_file_time=10        # time in seconds - after this time a new log file is created even if the max_file_size was not reached - 0 means value is ignored
 
 