/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_clut_table.c
**                                                                            
** Description:    This file contains the CLUT table autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 10/23/2024
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#define HMI_GFX_MGR02_CLUT_TABLE_C
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_layout.h"
#include "hmi_gfx_mgr02_clut_table.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/
                                                                              
/*============================================================================
** M E M O R Y   A L L O C A T I O N                                          
**==========================================================================*/

#if defined(__IAR_SYSTEMS_ICC)
#pragma section="GFX02_IMGDEF_RO_DATA"
#pragma section="GFX02_IMGDEF_RW_DATA"
#elif defined(__CWCC__)
#pragma push
#pragma section "GFX02_IMGDEF_RO_DATA" "GFX02_IMGDEF_RO_DATA"
#pragma section "GFX02_IMGDEF_RW_DATA" "GFX02_IMGDEF_RW_DATA"
#define GFX02_IMGDEF_RO_DATA_PREFIX __declspec(section "GFX02_IMGDEF_RO_DATA")
#define GFX02_IMGDEF_RW_DATA_PREFIX __declspec(section "GFX02_IMGDEF_RW_DATA")
#elif defined(__RENESAS__)
#pragma section GFX02_IMGDEF_RO_DATA
#pragma section GFX02_IMGDEF_RW_DATA
#elif defined(__ghs__)
#pragma ghs section rodata="GFX02_IMGDEF_RO_DATA"
#pragma ghs section bss="GFX02_IMGDEF_RW_DATA"
#elif defined(__GNUC__)
#define GFX02_IMGDEF_RO_DATA_PREFIX __attribute__((section("GFX02_IMGDEF_RO_DATA")))
#define GFX02_IMGDEF_RW_DATA_PREFIX __attribute__((section("GFX02_IMGDEF_RW_DATA")))
#endif
#ifndef GFX02_IMGDEF_RO_DATA_PREFIX
#define GFX02_IMGDEF_RO_DATA_PREFIX
#endif
#ifndef GFX02_IMGDEF_RW_DATA_PREFIX
#define GFX02_IMGDEF_RW_DATA_PREFIX
#endif

GFX02_IMGDEF_RO_DATA_PREFIX UINT32 const New_images_2_clut[100] = 
{
/* 000-003 */   0xFF204F83uL,0xFF004D8BuL,0xFF005795uL,0xFF094881uL
/* 004-007 */  ,0xFF004A88uL,0xFF004482uL,0xFF054685uL,0xFF003C79uL
/* 008-011 */  ,0xFF003F7DuL,0xFF004180uL,0xFF427CA9uL,0xFF799BBBuL
/* 012-015 */  ,0xFFA5B9CDuL,0xFF97AEC6uL,0xFF0E417BuL,0xFF053B7AuL
/* 016-019 */  ,0xFF5F87AAuL,0xFFB1C4D7uL,0xFFF2F8FBuL,0xFFF5F7F4uL
/* 020-023 */  ,0xFFF9FCF8uL,0xFFF7FCFFuL,0xFF013A79uL,0xFF23568BuL
/* 024-027 */  ,0xFF87A7C3uL,0xFFEAF0F2uL,0xFFF7F9F6uL,0xFF6A91B4uL
/* 028-031 */  ,0xFFDFF1F9uL,0xFFC0CFDEuL,0xFF4D88B4uL,0xFFF1F3F0uL
/* 032-035 */  ,0xFFDCE4EDuL,0xFF839AB8uL,0xFF171F53uL,0xFFD1D6D9uL
/* 036-039 */  ,0xFF383F6DuL,0xFF091751uL,0xFF001A53uL,0xFF0D1348uL
/* 040-043 */  ,0xFF02144EuL,0xFF00134CuL,0xFF0F3F7EuL,0xFF7082A0uL
/* 044-047 */  ,0xFF060E4AuL,0xFF0B1A4EuL,0xFF00174EuL,0xFF4D76A2uL
/* 048-051 */  ,0xFF657794uL,0xFF000F47uL,0xFF093D7CuL,0xFF144D87uL
/* 052-055 */  ,0xFFE2E7E9uL,0xFF566388uL,0xFFB6C3D0uL,0xFFE4ECF5uL
/* 056-059 */  ,0xFF597498uL,0xFFEDEFECuL,0xFF070C42uL,0xFF021D56uL
/* 060-063 */  ,0xFFC5CDD5uL,0xFF02093FuL,0xFF002C6AuL,0xFF6884A7uL
/* 064-067 */  ,0xFF1E2858uL,0xFF072962uL,0xFF778EAEuL,0xFF0C3E78uL
/* 068-071 */  ,0xFFDCE1E4uL,0xFF00114AuL,0xFF000A44uL,0xFF00245DuL
/* 072-075 */  ,0xFF003877uL,0xFFE7E9E6uL,0xFF003674uL,0xFF0E3474uL
/* 076-079 */  ,0xFF00225AuL,0xFF003472uL,0xFF3C4871uL,0xFF0C366FuL
/* 080-083 */  ,0xFF526C90uL,0xFF010A45uL,0xFF9EAEC1uL,0xFF4C587BuL
/* 084-087 */  ,0xFF02265FuL,0xFF023069uL,0xFF274776uL,0xFFA2AEBBuL
/* 088-091 */  ,0xFF01063DuL,0xFFD7DCDFuL,0xFF13285CuL,0xFF91A3B8uL
/* 092-095 */  ,0xFF8799B1uL,0xFF00326FuL,0xFFE5E7E4uL,0xFF13386CuL
/* 096-099 */  ,0xFF3C6693uL,0xFF002564uL,0xFFAEB6BFuL,0xFFE2E4E1uL
};

#if GFX_MGR02_NUM_OF_CLUTS > 0
GFX02_IMGDEF_RO_DATA_PREFIX GFX_MGR02_CLUT_DATA const lc_gfx_mgr02_clut_array[GFX_MGR02_NUM_OF_CLUTS] =
{
   { &New_images_2_clut[0]                                        , 100 , 0 }
#if GFX_MGR02_PROD_SPEC_CLUT_TABLE_NUM > 0
  ,GFX_MGR02_PROD_SPEC_CLUT_TABLE
#endif
};
#endif /* #if GFX_MGR02_NUM_OF_CLUTS > 0 */


#if defined(__IAR_SYSTEMS_ICC)
#pragma memory=default
#elif defined(__CWCC__)
#pragma pop
#elif (defined(__RENESAS__))
#pragma section
#elif defined(__ghs__)
#pragma ghs section rodata=default
#pragma ghs section bss=default
#endif

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
