/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in2018. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_cfg.h                                        
**                                                                            
** Description:    This file contains the application interfaces for          
**                 hmi graphics manager.                                      
**                 Autogenerated by GDT . Do not handmodify this file. 
**                 Generated on MM/DD/YYYY - 7/11/2018
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CFG_H                                                   
#define HMI_GFX_MGR02_CFG_H                                                   
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_defs.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/

/*
** Graphics Manager Image Base ID definitions.
*/
#define GFX_IMG_3_BASEID                        (0)
#define GFX_IMG_4_BASEID                        (1)
#define GFX_IMG_2BPP_NANIM_BASEID               (2)
#define GFX_IMG_8BPP_NANNIM_BASEID              (3)
#define GFX_IMG_4BPP_NANIM_BASEID               (4)
#define GFX_SIMG_1_ANIM_BASEID                  (5)
#define GFX_SIMG_3_CLIP_OPEQ_ANIM_BASEID        (6)
#define GFX_SIMG_2_ALPHA_ANIM_BASEID            (7)
#define GFX_IMG_APAL_NANIM_BASEID               (8)
#define GFX_IMG_1BPP_NANIM_BASEID               (9)
#define GFX_IMG_RGB5_NANIM_BASEID               (10)
#define GFX_IMG_RGB8_NANIM_BASEID               (11)
#define GFX_IMG_ARG15_NANIM_BASEID              (12)
#define GFX_IMG_ARG8_NANIM_BASEID               (13)
#define GFX_IMG_ARG8PRE_NANIM_BASEID            (14)
#define GFX_IMG_8BPP_ALPHA_NANIM_BASEID         (15)
#define GFX_IMG_4BPP_ALPHA_NANIM_BASEID         (16)
#define GFX_IMG_1BPP_ALPHANANIM_BASEID          (17)
#define GFX_IMG_8BPP_LUM_NANIM_BASEID           (18)
#define GFX_IMG_4BPP_LUM_NANIM_BASEID           (19)
#define GFX_IMG_1BPP_NANIM_0_BASEID             (20)
#define GFX_IMG_2BPP_NANIM_0_BASEID             (21)
#define GFX_IMG_4BPP_NANIM_0_BASEID             (22)
#define GFX_IMG_8BPP_NANNIM_0_BASEID            (23)
#define GFX_IMG_APAL_NANIM_0_BASEID             (24)
#define GFX_IMG_RGB5_NANIM_0_BASEID             (25)
#define GFX_IMG_RGB8_NANIM_0_BASEID             (26)
#define GFX_IMG_ARG15_NANIM_0_BASEID            (27)
#define GFX_IMG_ARG8_NANIM_0_BASEID             (28)
#define GFX_IMG_ARG8PRE_NANIM_0_BASEID          (29)
#define GFX_IMG_8BPP_ALPHA_NANIM_0_BASEID       (30)
#define GFX_IMG_4BPP_ALPHA_NANIM_0_BASEID       (31)
#define GFX_IMG_1BPP_ALPHANANIM_0_BASEID        (32)
#define GFX_IMG_8BPP_LUM_NANIM_0_BASEID         (33)
#define GFX_IMG_4BPP_LUM_NANIM_0_BASEID         (34)
#define GFX_IMG_DYN_1_BASEID                    (35)
#define GFX_IMG_DYN_2_BASEID                    (36)
#define GFX_FILL_NORMAL_IMG_BASEID              (37)
#define GFX_SWDG_SIMAGE_IMG_BASEID              (38)
#define GFX_SWDG_DIMAGENEW_IMG_BASEID           (39)
#define GFX_STEXT_NORMAL_BASEID                 (0)
#define GFX_FILL_NORMAL_BASEID                  (0)
#define GFX_FILL_NORMAL_1_BASEID                (0)
#define GFX_SWDG_SIMAGE_BASEID                  (0)
#define GFX_SWDG_DIMAGENEW_BASEID               (1)
#define GFX_MGR02_NUM_DCU_OVG_WIDGETS           (0)
#define GFX_MGR02_NUM_AMBER_MERGE_WIDGETS (0)

#define GFX_MGR02_NUM_OF_IMAGE_LAYERS           (40)
#define GFX_MGR02_NUM_3D_MDL_LAYERS             (0)
#define GFX_MGR02_NUM_USER_LAYERS               (0)
#define GFX_MGR02_NUM_RUNTIME_WDG_IMG_LAYERS    (0)
#define GFX_MGR02_NUM_OF_TEXT_LAYERS            (1)

#define GFX_MGR02_NUM_OF_SVGS                   (0)

#define GFX_MGR02_NUM_OF_SVG_CLIPS              (0)
#define GFX_MGR02_NUM_OF_FILLS                  (1)
#define GFX_MGR02_NUM_OF_TILES                  (1)
#define GFX_MGR02_DYNAMIC_CLIPPED_WIDGETS
#define GFX_MGR02_CLIPPED_WIDGETS
#define GFX_MGR02_NUM_OF_SWDGS                  (2)


/*
** Project Specific ID definitions, this can be used by app
*/
#define GFX_MGR02_ROTATION_90_DEG_CLOCKWISE_ENABLED           (1)
#define GFX_MGR02_ROTATION_90_DEG_ANTICLOCKWISE_ENABLED       (0)
#define GFX_MGR02_TEXT_ROTATION_SUPPORT_ENABLED               (1)
#define GFX_MGR02_LAYERS_MAX_WIDTH							  (240)
#define GFX_MGR02_LAYERS_MAX_HEIGHT							  (320)

typedef enum
{

   /*
   ** Layer animation ID's to be used with following APIs
   ** hmi_gfx_mgr02_set_obj_tile
   ** hmi_gfx_mgr02_set_obj_blend
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_fg_color
   ** hmi_gfx_mgr02_set_obj_bg_color
   ** hmi_gfx_mgr02_set_obj_fill_color
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
   GFX_SIMG_1_ANIM_ANIM                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SIMG_3_CLIP_OPEQ_ANIM_ANIM                  = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SIMG_2_ALPHA_ANIM_ANIM                      = GFX_MGR02_SET_OBJ(2,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_1BPP_NANIM_0_ANIM                       = GFX_MGR02_SET_OBJ(3,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_2BPP_NANIM_0_ANIM                       = GFX_MGR02_SET_OBJ(4,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_4BPP_NANIM_0_ANIM                       = GFX_MGR02_SET_OBJ(5,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_8BPP_NANNIM_0_ANIM                      = GFX_MGR02_SET_OBJ(6,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_APAL_NANIM_0_ANIM                       = GFX_MGR02_SET_OBJ(7,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_RGB5_NANIM_0_ANIM                       = GFX_MGR02_SET_OBJ(8,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_RGB8_NANIM_0_ANIM                       = GFX_MGR02_SET_OBJ(9,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_ARG15_NANIM_0_ANIM                      = GFX_MGR02_SET_OBJ(10,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_ARG8_NANIM_0_ANIM                       = GFX_MGR02_SET_OBJ(11,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_ARG8PRE_NANIM_0_ANIM                    = GFX_MGR02_SET_OBJ(12,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_8BPP_ALPHA_NANIM_0_ANIM                 = GFX_MGR02_SET_OBJ(13,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_4BPP_ALPHA_NANIM_0_ANIM                 = GFX_MGR02_SET_OBJ(14,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_1BPP_ALPHANANIM_0_ANIM                  = GFX_MGR02_SET_OBJ(15,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_8BPP_LUM_NANIM_0_ANIM                   = GFX_MGR02_SET_OBJ(16,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_4BPP_LUM_NANIM_0_ANIM                   = GFX_MGR02_SET_OBJ(17,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_DYN_1_ANIM                              = GFX_MGR02_SET_OBJ(18,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_DYN_2_ANIM                              = GFX_MGR02_SET_OBJ(19,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_FILL_NORMAL_ANIM                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_FILL|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_FILL_NORMAL_1_ANIM                          = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_TILE|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_STEXT_NORMAL_ANIM                           = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_STEXT|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SWDG_SIMAGE_ANIM                            = GFX_MGR02_SET_OBJ(0,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_SWDG_DIMAGENEW_ANIM                         = GFX_MGR02_SET_OBJ(1,GFX_MGR02_PLATFORM_DCU|GFX_MGR02_TYPE_SWIDGET|GFX_MGR02_ATTRIB_DYN_PROPERTY)

   /* - GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS
   ** Layer animation ID's to be used with following APIs
   ** (Valid for Screens, dynamic images and dynamic widgets)
   ** hmi_gfx_mgr02_set_obj_alpha
   ** hmi_gfx_mgr02_set_obj_pos_x
   ** hmi_gfx_mgr02_set_obj_pos_y
   ** hmi_gfx_mgr02_get_obj_pos
   */
  ,GFX_DWDG_SWDG_ANIM                              = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET | GFX_MGR02_ATTRIB_DYN_PROPERTY)
  ,GFX_IMG_DYN1_ANIM                               = GFX_MGR02_SET_OBJ(1,GFX_MGR02_TYPE_DIMAGE | GFX_MGR02_ATTRIB_DYN_PROPERTY)
}GFX_MGR02_ANIM_ELEM_ID;
#define GFX_MGR02_NUM_IMAGE_ANIM_ELEMENTS       (20)
#define GFX_MGR02_NUM_3D_ANIM_ELEMENTS          (0)
#define GFX_MGR02_NUM_USER_ANIM_ELEMENTS        (0)
#define GFX_MGR02_NUM_SVG_ANIM_ELEMENTS         (0)
#define GFX_MGR02_NUM_FILL_ANIM_ELEMENTS        (1)
#define GFX_MGR02_NUM_TILE_ANIM_ELEMENTS        (1)
#define GFX_MGR02_NUM_TEXT_ANIM_ELEMENTS        (1)
#define GFX_MGR02_NUM_WIDGET_ANIM_ELEMENTS      (2)
#define GFX_MGR02_NUM_GROUP_ANIM_ELEMENTS       (2)

#define GFX_MGR02_NUM_SCREEN_ANIM_ELEMENTS      (0)

extern UINT32 const lc_nfill_color_FF008080_CLUT[1];
#define GFX_MGR02_STEXTS_BUFFER_SIZE (26)

/*
** Dynamic Text ID definitions to be used with hmi_gfx_mgr_set_text
*/
typedef enum
{
   GFX_MGR02_TOTAL_NUM_OF_DTEXTS
}GFX_MGR02_DTEXT_ID;
#define GFX_MGR02_NUM_OF_DTEXTS      (0)
#define GFX_MGR02_NUM_OF_STEXTS      (1)
#define GFX_MGR02_NUM_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_MAX_LINES_OF_MULTI_LINE_TEXTS      (0)
#define GFX_MGR02_DTEXTS_BUFFER_SIZE (0)
#define GFX_MGR02_MAX_MULTI_LINE_TEXT_LENGTH   (0)

/* GFX_MGR02_NUM_NON_ANIM_ELEMENTS */

/*
** Dynamic Widget ID definitions to be used with hmi_gfx_mgr02_select_dwidget
*/
typedef enum
{
   GFX_DWDG_SWDG                                   = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DWIDGET)
}GFX_MGR02_DWDG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_WIDGETS           (1)


/*
** Dynamic Image ID definitions to be used with hmi_gfx_mgr02_select_dimage
*/
typedef enum
{
   GFX_IMG_DYN1                                    = GFX_MGR02_SET_OBJ(0,GFX_MGR02_TYPE_DIMAGE)
}GFX_MGR02_DIMG_ELEM_ID;
#define GFX_MGR02_NUM_DYNAMIC_IMAGES            (1)

#define GFX_IMG_1BPP_NANIM_1                       GFX_MGR02_SET_OBJ(0  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_2BPP_NANIM_1                       GFX_MGR02_SET_OBJ(1  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_4BPP_NANIM_1                       GFX_MGR02_SET_OBJ(2  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_8BPP_NANNIM_1                      GFX_MGR02_SET_OBJ(3  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_APAL_NANIM_1                       GFX_MGR02_SET_OBJ(4  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_RGB5_NANIM_1                       GFX_MGR02_SET_OBJ(5  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_RGB8_NANIM_1                       GFX_MGR02_SET_OBJ(6  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_3_1                                GFX_MGR02_SET_OBJ(7  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_4_1                                GFX_MGR02_SET_OBJ(8  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_ARG15_NANIM_1                      GFX_MGR02_SET_OBJ(9  ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_ARG8_NANIM_1                       GFX_MGR02_SET_OBJ(10 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_ARG8PRE_NANIM_1                    GFX_MGR02_SET_OBJ(11 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_4BPP_LUM_NANIM_1                   GFX_MGR02_SET_OBJ(12 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_8BPP_LUM_NANIM_1                   GFX_MGR02_SET_OBJ(13 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_4BPP_ALPHA_NANIM_1                 GFX_MGR02_SET_OBJ(14 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_8BPP_ALPHA_NANIM_1                 GFX_MGR02_SET_OBJ(15 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_IMG_1BPP_ALPHANANIM_1                  GFX_MGR02_SET_OBJ(16 ,GFX_MGR02_TYPE_SIMAGE|GFX_MGR02_PLATFORM_DCU)
#define GFX_MGR02_NUM_SIMAGE_INSTANCES          (17)
#define GFX_MGR02_NUM_SVG_INSTANCES             (0)
#define GFX_MGR02_NUM_FILL_INSTANCES            (0)
#define GFX_MGR02_NUM_TILE_INSTANCES            (0)
#define GFX_MGR02_NUM_SWDG_INSTANCES            (0)
#define GFX_MGR02_NUM_TEXT_INSTANCES            (0)

/*
** Screen Element definitions for use in hmi_gfx_mgr02_set_screen() api
*/
typedef enum
{
   GFX_SCR_TESTSIMAGENONANIM1                      = (0)
  ,GFX_SCR_TESTSIMAGEANIMRGB                       = (1)
  ,GFX_SCR_TESTSWIDGET                             = (2)
  ,GFX_SCR_TESTSIMAGEANIM1                         = (3)
  ,GFX_SCR_TESTSIMAGENONANIM2                      = (4)
  ,GFX_SCR_TESTSIMAGEANIM2                         = (5)
  ,GFX_SCR_TESTSTATICTEXT                          = (6)
}GFX_MGR02_SCR_ELEM_ID;
#define GFX_MGR02_NUM_OF_SCREENS                   (7)
#define GFX_MGR02_LAYER0_DAR_SIZE                  (9)
#define GFX_MGR02_DIRTY_REGION_NUM_VALID_OBJ_CONFIG   (1)
#define GFX_MGR02_DAR_OBJ_LIST_SIZE_MAX            (9)

/*
** Macro definitions for screen background colors
*/
#define GFX_SCR_TESTSIMAGENONANIM1_BG_COLOR                 (0xFF000000)
#define GFX_SCR_TESTSIMAGEANIMRGB_BG_COLOR                  (0xFF000000)
#define GFX_SCR_TESTSWIDGET_BG_COLOR                        (0xFF000000)
#define GFX_SCR_TESTSIMAGEANIM1_BG_COLOR                    (0xFF000000)
#define GFX_SCR_TESTSIMAGENONANIM2_BG_COLOR                 (0xFF000000)
#define GFX_SCR_TESTSIMAGEANIM2_BG_COLOR                    (0xFF000000)
#define GFX_SCR_TESTSTATICTEXT_BG_COLOR                     (0xFF000000)

/*
** Macro definitions for Display background colors.
*/
#define GFX_MGR02_DISP0_BG_COLOR							(0x00000000)

/*
** Macro definitions for planes allocated for Display.
*/
#define GFX_MGR02_NUM_DISP0_PLANES              (0)

/*
** Other useful macro definitions.
*/
#define GFX_MGR02_NUM_LAYERS              (1)
#define GFX_MGR02_NUM_PRIORITY            (1)
#define GFX_MGR02_UNICODE              (0)
#define GFX_MGR02_TOUCH_SCREEN_ENABLED    (0)
#define GFX_MGR02_MAX_TEXT_LENGTH         (25)
#define GFX_MGR02_NUM_DCU_SOFT_LAYERS     (9)
#define GFX_MGR02_NUM_DCULITE_SOFT_LAYERS (0)
#define GFX_MGR02_NUM_SOFT_LAYERS         (9)
#define GFX_MGR02_PIX_FORMAT              (GFX_MGR02_PIX_FORMAT_RGB565)
#define GFX_MGR02_NEWPROJECT
#define GFX_MGR02_TOTAL_LINE_BREAK_CHAR    (1)
#define GFX_MGR02_NUM_MASK_WIDGETS        (0)
#define GFX_MGR02_KEPLER
#define GFX_MGR02_RENDER_NONE

/*============================================================================ 
** E N T R Y   P O I N T S                                                     
**==========================================================================*/ 
                                                                               

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        7/11/2018     ASHEKHAR                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                                
/* end of file =============================================================*/ 
#endif                                                                         
