/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in 2018. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_mgr02_vgfont.c                                     
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated. Do not hand modify                          
Organization     :  Driver Information Software Section,                       
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#define HMI_GFX_MGR02_VGFONT_C

/*****************************************************************************
*                                 System Includes                            *
******************************************************************************/
#include "hmi_gfx_mgr02_layout.h"
#include "hmi_gfx_mgr02_font.h"
#include "hmi_gfx_mgr02_font.cfg"
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Type Declarations                          * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                Globally  accessed Variable Declarations    * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the variable.                                                        * 
* purpose, critical section, unit, and resolution                            * 
******************************************************************************/
                                                                               
                                                                               
/***************************************************************************** 
*                                 Locally used Variable Declarations         * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the variable.                                                        * 
* purpose, critical section, unit, and resolution                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                       Locally used Constant Declarations                   * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the constant.                                                        * 
* purpose, unit, and resolution                                              * 
******************************************************************************/
                                                                               
#if(defined(GFX_MGR02_EXT_FONT_ENGINE)&&((GFX_MGR02_EXT_FONT_ENGINE==GFX_MGR02_SPANSION_FT2) || GFX_MGR02_EXT_FONT_ENGINE==GFX_MGR02_MONOTYPE))





#endif /*if(GFX_MGR02_EXT_FONT_ENGINE==GFX_MGR02_SPANSION_FT2 || GFX_MGR02_MONOTYPE)*/

                                                                              
/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        7/11/2018     EMANOJ1                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
