/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_image_data.h
**                                                                            
** Description:    This file contains the image data autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 7/11/2018
**                 Total Image ROM size = [413956 bytes]   
**                 Total RLE Savings    = [0 bytes]
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_IMAGE_DATA_H
#define HMI_GFX_MGR02_IMAGE_DATA_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** externs for all the image tables generated.
*/
extern UINT16 const lc_img_apal_nanim_data[4320];
extern UINT8 const lc_img_2bpp_nanim_0_data[64];
extern UINT8 const lc_img_4bpp_nanim_0_data[128];
extern UINT8 const lc_img_8bpp_nannim_0_data[3456];
extern UINT16 const lc_img_apal_nanim_0_data[5704];
extern UINT16 const lc_img_3_data[5760];
extern UINT16 const lc_img_4_data[19200];
extern UINT32 const lc_simg_1_anim_data[437];
extern UINT16 const lc_simg_3_clip_opeq_anim_data[5040];
extern UINT16 const lc_simg_2_alpha_anim_data[320];
extern UINT16 const lc_img_rgb5_nanim_data[9216];
extern UINT8 const lc_img_rgb8_nanim_data[1728];
extern UINT16 const lc_img_arg15_nanim_data[5760];
extern UINT32 const lc_img_arg8_nanim_data[10000];
extern UINT32 const lc_img_arg8pre_nanim_data[512];
extern UINT8 const lc_img_8bpp_alpha_nanim_data[384];
extern UINT8 const lc_img_4bpp_alpha_nanim_data[768];
extern UINT8 const lc_img_4bpp_lum_nanim_data[192];
extern UINT16 const lc_img_rgb5_nanim_0_data[9600];
extern UINT16 const lc_img_dyn_1_data[76800];
extern UINT16 const lc_img_dyn_2_data[40000];

/*
** mapping for image data which is repeating
*/
#define lc_img_1bpp_alphananim_data                          (lc_simg_1_anim_data)
#define lc_img_8bpp_lum_nanim_data                           (lc_img_3_data)
#define lc_img_rgb8_nanim_0_data                             (lc_img_rgb8_nanim_data)
#define lc_img_arg15_nanim_0_data                            (lc_img_arg15_nanim_data)
#define lc_img_arg8_nanim_0_data                             (lc_img_arg8_nanim_data)
#define lc_img_arg8pre_nanim_0_data                          (lc_img_arg8pre_nanim_data)
#define lc_img_8bpp_alpha_nanim_0_data                       (lc_img_8bpp_alpha_nanim_data)
#define lc_img_4bpp_alpha_nanim_0_data                       (lc_img_4bpp_alpha_nanim_data)
#define lc_img_1bpp_alphananim_0_data                        (lc_simg_1_anim_data)
#define lc_img_8bpp_lum_nanim_0_data                         (lc_img_3_data)
#define lc_img_4bpp_lum_nanim_0_data                         (lc_img_4bpp_lum_nanim_data)
#define lc_img_2bpp_nanim_data                               (lc_img_2bpp_nanim_0_data)
#define lc_img_8bpp_nannim_data                              (lc_img_8bpp_nannim_0_data)
#define lc_img_4bpp_nanim_data                               (lc_img_4bpp_nanim_0_data)
#define lc_img_1bpp_nanim_data                               (lc_img_1bpp_nanim_0_data)
#define lc_img_1bpp_nanim_0_data                             (lc_img_8bpp_nannim_0_data)

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_IMAGE_DATA_H */
