/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_identifiers.h                                 
**                                                                            
** Description:    This file contains the language identifier interfaces      
**                 Autogenerated by LanguageEncoder.exe Version 1.8.          
**                 Do not handmodify this file								  
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_LANGUAGE_IDENTIFIERS_H
#define HMI_LANGUAGE_IDENTIFIERS_H
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
/* Release label major version 4 */
/* Release label minor version 12 */
#define HMI_LANG_CORE_TOOL_LABEL                  "LANG_TOOL_LABEL::rel-UI-CORE-ICEAPPLE-4.12"
#define HMI_LANG_CORE_TOOL_MAJOR_VERSION          4
#define HMI_LANG_CORE_TOOL_MINOR_VERSION          12
#define HMI_LANG_CORE_TOOL_VERSION                ((HMI_LANG_CORE_TOOL_MAJOR_VERSION * 100) + HMI_LANG_CORE_TOOL_MINOR_VERSION)

#define   HMI_LANGUAGE_UK_ENGLISH_FEAT
#define   HMI_LANGUAGE_FRENCH_FEAT
#define   HMI_LANGUAGE_US_ENGLISH_FEAT

typedef enum
{
   HMI_LANGUAGE_UK_ENGLISH,
   HMI_LANGUAGE_FRENCH,
   HMI_LANGUAGE_US_ENGLISH,
   LNG_MAX_LANGUAGE_COUNT
} HMI_LANGUAGE_T;

#define HM_LANG_MAX_STRING_SIZE         6
#define SID_HELLO                       0x0000
#define SID_WORLD                       0x0006
/* Total Language Table Size = 0.01kBytes */
#define HM_LANG_MAX_PAGE                1
#define HM_LANG_MAX_SID                 0x0006u
#define HM_LANG_COMMON_MAX_SID          0x0006u
#define HM_END_OF_SID                   (0xFFFFu)
#define HM_LANG_BUFFER_MAX_SIZE         (0xCu)        /* This is the language database size */
typedef UINT16 LANG_SID_T;

/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        08/12/09     JKANOZA                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                               
/* end of file =============================================================*/ 
#endif /* HMI_LANGUAGE_IDENTIFIERS_H */
