/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_clut_table.h
**                                                                            
** Description:    This file contains the CLUT header autogenerated by        
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 7/11/2018
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_CLUT_TABLE_H
#define HMI_GFX_MGR02_CLUT_TABLE_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
#include "hmi_gfx_mgr02_clut_table.cfg"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** CLUT table ID's.
*/
#define GFX_IMG_2BPP_NANIM_CLUT                              (0)
#define GFX_IMG_8BPP_NANNIM_CLUT                             (1)
#define GFX_IMG_4BPP_NANIM_CLUT                              (2)
#define GFX_IMG_APAL_NANIM_CLUT                              (3)
#define GFX_IMG_1BPP_NANIM_CLUT                              (4)
#define GFX_IMG_1BPP_NANIM_0_CLUT                            (5)
#define GFX_IMG_2BPP_NANIM_0_CLUT                            ( GFX_IMG_2BPP_NANIM_CLUT)
#define GFX_IMG_4BPP_NANIM_0_CLUT                            ( GFX_IMG_4BPP_NANIM_CLUT)
#define GFX_IMG_8BPP_NANNIM_0_CLUT                           ( GFX_IMG_8BPP_NANNIM_CLUT)
#define GFX_IMG_APAL_NANIM_0_CLUT                            (6)
#define GFX_FILL_NORMAL_CLUT                                 (7)
#define GFX_MGR02_NUM_OF_CLUTS                               (8U+ GFX_MGR02_PROD_SPEC_CLUT_TABLE_NUM)

/*
** CLUT table size.
*/
#define GFX_IMG_2BPP_NANIM_CLUT_SIZE                         (2)
#define GFX_IMG_8BPP_NANNIM_CLUT_SIZE                        (247)
#define GFX_IMG_4BPP_NANIM_CLUT_SIZE                         (12)
#define GFX_IMG_APAL_NANIM_CLUT_SIZE                         (253)
#define GFX_IMG_1BPP_NANIM_CLUT_SIZE                         (1)
#define GFX_IMG_1BPP_NANIM_0_CLUT_SIZE                       (1)
#define GFX_IMG_2BPP_NANIM_0_CLUT_SIZE                       ( GFX_IMG_2BPP_NANIM_CLUT_SIZE)
#define GFX_IMG_4BPP_NANIM_0_CLUT_SIZE                       ( GFX_IMG_4BPP_NANIM_CLUT_SIZE)
#define GFX_IMG_8BPP_NANNIM_0_CLUT_SIZE                      ( GFX_IMG_8BPP_NANNIM_CLUT_SIZE)
#define GFX_IMG_APAL_NANIM_0_CLUT_SIZE                       (193)
#define GFX_FILL_NORMAL_CLUT_SIZE                            (1)

/*
** externs for all the palette's generated.
*/
extern UINT32 const img_2BPP_NAnim_clut[2];
extern UINT32 const img_8BPP_NANnim_clut[247];
extern UINT32 const img_4BPP_NAnim_clut[12];
extern UINT32 const img_APAL_NAnim_clut[253];
extern UINT32 const img_1BPP_NAnim_clut[1];
extern UINT32 const img_1BPP_NAnim_0_clut[1];
/* img_2BPP_NAnim_0 Palette Optimized with img_2BPP_NAnim_clut */
/* img_4BPP_NAnim_0 Palette Optimized with img_4BPP_NAnim_clut */
/* img_8BPP_NANnim_0 Palette Optimized with img_8BPP_NANnim_clut */
extern UINT32 const img_APAL_NAnim_0_clut[193];

#if GFX_MGR02_NUM_OF_CLUTS > 0
  extern GFX_MGR02_CLUT_DATA const lc_gfx_mgr02_clut_array[GFX_MGR02_NUM_OF_CLUTS];
#endif

/*
** mapping for Palette data which is repeating
*/
#define img_2BPP_NAnim_0_clut                                (img_2BPP_NAnim_clut)
#define img_4BPP_NAnim_0_clut                                (img_4BPP_NAnim_clut)
#define img_8BPP_NANnim_0_clut                               (img_8BPP_NANnim_clut)


/*
** CLUT Index definitions for the widget background color
*/
/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_CLUT_TABLE_H */
