/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_clut_table.c
**                                                                            
** Description:    This file contains the CLUT table autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 7/11/2018
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#define HMI_GFX_MGR02_CLUT_TABLE_C
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "hmi_gfx_mgr02_layout.h"
#include "hmi_gfx_mgr02_clut_table.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/
                                                                              
/*============================================================================
** M E M O R Y   A L L O C A T I O N                                          
**==========================================================================*/

UINT32 const img_2BPP_NAnim_clut[2] = 
{
/* 000-001 */   0xFFFF00FFuL,0xFF000000uL
};

UINT32 const img_8BPP_NANnim_clut[247] = 
{
/* 000-003 */   0xFF000000uL,0xFFFFFFFFuL,0xFFCE000CuL,0xFFC6000CuL
/* 004-007 */  ,0xFFBF030EuL,0xFFC90013uL,0xFFD51D30uL,0xFFD62637uL
/* 008-011 */  ,0xFFCF3D4DuL,0xFFCE5A68uL,0xFFE4AFB6uL,0xFF8D0017uL
/* 012-015 */  ,0xFF8F061AuL,0xFFD68692uL,0xFF880017uL,0xFF8A001CuL
/* 016-019 */  ,0xFF87001BuL,0xFF81122EuL,0xFF872943uL,0xFFE9D8DDuL
/* 020-023 */  ,0xFF7D2B47uL,0xFFD2B2BDuL,0xFF7D415BuL,0xFF844E67uL
/* 024-027 */  ,0xFFEADFE4uL,0xFF79526DuL,0xFFCEC5CDuL,0xFF7F6B84uL
/* 028-031 */  ,0xFFE9E6EAuL,0xFFEBE9EDuL,0xFF6D627DuL,0xFFECEBEEuL
/* 032-035 */  ,0xFFEBEAEDuL,0xFF6D6580uL,0xFFE4E3E8uL,0xFFE2E1E6uL
/* 036-039 */  ,0xFF9896A9uL,0xFFA4A2B3uL,0xFF6D6B84uL,0xFF767489uL
/* 040-043 */  ,0xFF75748CuL,0xFF7C7B90uL,0xFF7E7D92uL,0xFF848396uL
/* 044-047 */  ,0xFF000017uL,0xFF000014uL,0xFF000012uL,0xFF000010uL
/* 048-051 */  ,0xFF00000EuL,0xFF00000CuL,0xFF00000BuL,0xFF000009uL
/* 052-055 */  ,0xFF000007uL,0xFF000005uL,0xFF000002uL,0xFF000001uL
/* 056-059 */  ,0xFF030314uL,0xFF030312uL,0xFF030310uL,0xFF06061CuL
/* 060-063 */  ,0xFF04040FuL,0xFF020207uL,0xFF0B0B1FuL,0xFF19192EuL
/* 064-067 */  ,0xFF232337uL,0xFF2C2C41uL,0xFF35354DuL,0xFF3B3B52uL
/* 068-071 */  ,0xFF45455BuL,0xFF666681uL,0xFF4F4F63uL,0xFF6B6B85uL
/* 072-075 */  ,0xFF6C6C86uL,0xFF6E6E88uL,0xFF5A5A6FuL,0xFF353541uL
/* 076-079 */  ,0xFF75758EuL,0xFF73738CuL,0xFF717189uL,0xFF65657AuL
/* 080-083 */  ,0xFF212128uL,0xFF77778FuL,0xFF7D7D95uL,0xFF6C6C81uL
/* 084-087 */  ,0xFF454552uL,0xFF3A3A45uL,0xFF6E6E82uL,0xFF585868uL
/* 088-091 */  ,0xFF41414DuL,0xFF32323BuL,0xFF828299uL,0xFF494956uL
/* 092-095 */  ,0xFF3E3E49uL,0xFF808096uL,0xFF6A6A7CuL,0xFF636374uL
/* 096-099 */  ,0xFF35353EuL,0xFF86869CuL,0xFF79798DuL,0xFF555563uL
/* 100-103 */  ,0xFF5E5E6DuL,0xFF88889DuL,0xFF858599uL,0xFF8F8FA3uL
/* 104-107 */  ,0xFF8C8CA0uL,0xFF4E4E59uL,0xFF9595A9uL,0xFF9292A6uL
/* 108-111 */  ,0xFF9191A4uL,0xFF747483uL,0xFF53535EuL,0xFF9898AAuL
/* 112-115 */  ,0xFF9B9BADuL,0xFF9A9AACuL,0xFF8B8B9BuL,0xFF09090AuL
/* 116-119 */  ,0xFFA1A1B1uL,0xFF9E9EAEuL,0xFF5B5B64uL,0xFFA7A7B7uL
/* 120-123 */  ,0xFFA5A5B5uL,0xFFA3A3B3uL,0xFF151517uL,0xFFAAAAB9uL
/* 124-127 */  ,0xFFAEAEBCuL,0xFFACACBAuL,0xFF92929EuL,0xFF6C6C75uL
/* 128-131 */  ,0xFFB5B5C2uL,0xFFB3B3C0uL,0xFFB1B1BEuL,0xFFBDBDCAuL
/* 132-135 */  ,0xFFB9B9C6uL,0xFFB7B7C4uL,0xFF64646BuL,0xFFBCBCC8uL
/* 136-139 */  ,0xFF9E9EA8uL,0xFF84848CuL,0xFFC2C2CDuL,0xFFA3A3ACuL
/* 140-143 */  ,0xFF8C8C94uL,0xFF7C7C83uL,0xFFC6C6D0uL,0xFFC0C0CAuL
/* 144-147 */  ,0xFFAAAAB3uL,0xFF9A9AA2uL,0xFFCDCDD6uL,0xFFCBCBD4uL
/* 148-151 */  ,0xFFC9C9D2uL,0xFF919197uL,0xFF89898FuL,0xFFD2D2DAuL
/* 152-155 */  ,0xFF828287uL,0xFF6A6A6EuL,0xFF4C4C4FuL,0xFFD7D7DEuL
/* 156-159 */  ,0xFFD4D4DBuL,0xFFCCCCD3uL,0xFFDADAE1uL,0xFFC8C8CEuL
/* 160-163 */  ,0xFF626265uL,0xFFDDDDE3uL,0xFFC2C2C7uL,0xFF767679uL
/* 164-167 */  ,0xFF717174uL,0xFFD3D3D8uL,0xFFBFBFC3uL,0xFFBCBCC0uL
/* 168-171 */  ,0xFF8D8D90uL,0xFF616163uL,0xFF5C5C5EuL,0xFFE8E8ECuL
/* 172-175 */  ,0xFFE6E6EAuL,0xFFB9B9BCuL,0xFFA5A5A8uL,0xFFA3A3A6uL
/* 176-179 */  ,0xFF7B7B7DuL,0xFF6E6E70uL,0xFFEFEFF2uL,0xFFEEEEF1uL
/* 180-183 */  ,0xFFEDEDF0uL,0xFFECECEFuL,0xFFEBEBEEuL,0xFFC5C5C8uL
/* 184-187 */  ,0xFFF6F6F8uL,0xFFF2F2F4uL,0xFFB4B4B6uL,0xFFFEFEFFuL
/* 188-191 */  ,0xFFDFDFE0uL,0xFF9B9B9CuL,0xFF797A91uL,0xFF9D9EB0uL
/* 192-195 */  ,0xFF6B6D88uL,0xFF7A7D96uL,0xFFC4C5CFuL,0xFF81849BuL
/* 196-199 */  ,0xFF71758FuL,0xFF757992uL,0xFFCACCD6uL,0xFF868BA1uL
/* 200-203 */  ,0xFFCED0D8uL,0xFFDFE0E4uL,0xFF7C8299uL,0xFF80869CuL
/* 204-207 */  ,0xFF8E93A6uL,0xFFC6C9D4uL,0xFFA5AABBuL,0xFFAFB4C2uL
/* 208-211 */  ,0xFFD2D7DFuL,0xFFCDD3DCuL,0xFFD7DEE5uL,0xFFDBE2E8uL
/* 212-215 */  ,0xFFE2E8EDuL,0xFFEAEFF3uL,0xFFE5ECF0uL,0xFFEDF3F5uL
/* 216-219 */  ,0xFFF7FEFFuL,0xFFF5FCFDuL,0xFF979795uL,0xFF919190uL
/* 220-223 */  ,0xFFFDFDFDuL,0xFFDEDEDEuL,0xFFD8D8D8uL,0xFFD4D4D4uL
/* 224-227 */  ,0xFFD1D1D1uL,0xFFC5C5C5uL,0xFFAFAFAFuL,0xFFACACACuL
/* 228-231 */  ,0xFFAAAAAAuL,0xFFA8A8A8uL,0xFFA7A7A7uL,0xFFA4A4A4uL
/* 232-235 */  ,0xFF9F9F9FuL,0xFF9E9E9EuL,0xFF9B9B9BuL,0xFF979797uL
/* 236-239 */  ,0xFF959595uL,0xFF8C8C8CuL,0xFF898989uL,0xFF696969uL
/* 240-243 */  ,0xFF656565uL,0xFF535353uL,0xFF434343uL,0xFF3C3C3CuL
/* 244-246 */  ,0xFF373737uL,0xFF060606uL,0xFF030303uL
};

UINT32 const img_4BPP_NAnim_clut[12] = 
{
/* 000-003 */   0xFFFFFFFFuL,0xFF328D00uL,0xFF58F400uL,0xFF50DF00uL
/* 004-007 */  ,0xFF50DE00uL,0xFF4CD500uL,0xFF4BD000uL,0xFF56F000uL
/* 008-011 */  ,0xFF47C500uL,0xFF2C7B00uL,0xFF42B800uL,0xFF57F300uL
};

UINT32 const img_APAL_NAnim_clut[253] = 
{
/* 000-003 */   0xFF000000uL,0xFFFFFFFFuL,0xFFCE000CuL,0xFFC6000CuL
/* 004-007 */  ,0xFFBF030EuL,0xFFC90013uL,0xFFD51D30uL,0xFFD62637uL
/* 008-011 */  ,0xFFCF3D4DuL,0xFFCE5A68uL,0xFFE4AFB6uL,0xFF8D0017uL
/* 012-015 */  ,0xFF8F061AuL,0xFFD68692uL,0xFF880017uL,0xFF8A001CuL
/* 016-019 */  ,0xFF87001BuL,0xFF81122EuL,0xFF872943uL,0xFFE9D8DDuL
/* 020-023 */  ,0xFF7D2B47uL,0xFFD2B2BDuL,0xFF7D415BuL,0xFF844E67uL
/* 024-027 */  ,0xFFEADFE4uL,0xFF79526DuL,0xFFCEC5CDuL,0xFF7F6B84uL
/* 028-031 */  ,0xFFE9E6EAuL,0xFFEBE9EDuL,0xFF6D627DuL,0xFFECEBEEuL
/* 032-035 */  ,0xFFEBEAEDuL,0xFF6D6580uL,0xFFE4E3E8uL,0xFFE2E1E6uL
/* 036-039 */  ,0xFF9896A9uL,0xFFA4A2B3uL,0xFF6D6B84uL,0xFF767489uL
/* 040-043 */  ,0xFF75748CuL,0xFF7C7B90uL,0xFF7E7D92uL,0xFF848396uL
/* 044-047 */  ,0xFF000017uL,0xFF000014uL,0xFF000012uL,0xFF000010uL
/* 048-051 */  ,0xFF00000EuL,0xFF00000CuL,0xFF00000BuL,0xFF000009uL
/* 052-055 */  ,0xFF000007uL,0xFF000005uL,0xFF000002uL,0xFF000001uL
/* 056-059 */  ,0xFF030314uL,0xFF030312uL,0xFF030310uL,0xFF06061CuL
/* 060-063 */  ,0xFF04040FuL,0xFF020207uL,0xFF0B0B1FuL,0xFF19192EuL
/* 064-067 */  ,0xFF232337uL,0xFF2C2C41uL,0xFF35354DuL,0xFF3B3B52uL
/* 068-071 */  ,0xFF45455BuL,0xFF666681uL,0xFF4F4F63uL,0xFF6B6B85uL
/* 072-075 */  ,0xFF6C6C86uL,0xFF6E6E88uL,0xFF5A5A6FuL,0xFF353541uL
/* 076-079 */  ,0xFF75758EuL,0xFF73738CuL,0xFF717189uL,0xFF65657AuL
/* 080-083 */  ,0xFF212128uL,0xFF77778FuL,0xFF7D7D95uL,0xFF6C6C81uL
/* 084-087 */  ,0xFF454552uL,0xFF3A3A45uL,0xFF6E6E82uL,0xFF585868uL
/* 088-091 */  ,0xFF41414DuL,0xFF32323BuL,0xFF828299uL,0xFF494956uL
/* 092-095 */  ,0xFF3E3E49uL,0xFF808096uL,0xFF6A6A7CuL,0xFF636374uL
/* 096-099 */  ,0xFF35353EuL,0xFF86869CuL,0xFF79798DuL,0xFF555563uL
/* 100-103 */  ,0xFF5E5E6DuL,0xFF88889DuL,0xFF858599uL,0xFF8F8FA3uL
/* 104-107 */  ,0xFF8C8CA0uL,0xFF4E4E59uL,0xFF9595A9uL,0xFF9292A6uL
/* 108-111 */  ,0xFF9191A4uL,0xFF747483uL,0xFF53535EuL,0xFF9898AAuL
/* 112-115 */  ,0xFF9B9BADuL,0xFF9A9AACuL,0xFF8B8B9BuL,0xFF09090AuL
/* 116-119 */  ,0xFFA1A1B1uL,0xFF9E9EAEuL,0xFF5B5B64uL,0xFFA7A7B7uL
/* 120-123 */  ,0xFFA5A5B5uL,0xFFA3A3B3uL,0xFF151517uL,0xFFAAAAB9uL
/* 124-127 */  ,0xFFAEAEBCuL,0xFFACACBAuL,0xFF92929EuL,0xFF6C6C75uL
/* 128-131 */  ,0xFFB5B5C2uL,0xFFB3B3C0uL,0xFFB1B1BEuL,0xFFBDBDCAuL
/* 132-135 */  ,0xFFB9B9C6uL,0xFFB7B7C4uL,0xFF64646BuL,0xFFBCBCC8uL
/* 136-139 */  ,0xFF9E9EA8uL,0xFF84848CuL,0xFFC2C2CDuL,0xFFA3A3ACuL
/* 140-143 */  ,0xFF8C8C94uL,0xFF7C7C83uL,0xFFC6C6D0uL,0xFFC0C0CAuL
/* 144-147 */  ,0xFFAAAAB3uL,0xFF9A9AA2uL,0xFFCDCDD6uL,0xFFCBCBD4uL
/* 148-151 */  ,0xFFC9C9D2uL,0xFF919197uL,0xFF89898FuL,0xFFD2D2DAuL
/* 152-155 */  ,0xFF828287uL,0xFF6A6A6EuL,0xFF4C4C4FuL,0xFFD7D7DEuL
/* 156-159 */  ,0xFFD4D4DBuL,0xFFCCCCD3uL,0xFFDADAE1uL,0xFFC8C8CEuL
/* 160-163 */  ,0xFF626265uL,0xFFDDDDE3uL,0xFFC2C2C7uL,0xFF767679uL
/* 164-167 */  ,0xFF717174uL,0xFFD3D3D8uL,0xFFBFBFC3uL,0xFFBCBCC0uL
/* 168-171 */  ,0xFF8D8D90uL,0xFF616163uL,0xFF5C5C5EuL,0xFFE8E8ECuL
/* 172-175 */  ,0xFFE6E6EAuL,0xFFB9B9BCuL,0xFFA5A5A8uL,0xFFA3A3A6uL
/* 176-179 */  ,0xFF7B7B7DuL,0xFF6E6E70uL,0xFFEFEFF2uL,0xFFEEEEF1uL
/* 180-183 */  ,0xFFEDEDF0uL,0xFFECECEFuL,0xFFEBEBEEuL,0xFFC5C5C8uL
/* 184-187 */  ,0xFFF6F6F8uL,0xFFF2F2F4uL,0xFFB4B4B6uL,0xFFFEFEFFuL
/* 188-191 */  ,0xFFDFDFE0uL,0xFF9B9B9CuL,0xFF797A91uL,0xFF9D9EB0uL
/* 192-195 */  ,0xFF6B6D88uL,0xFF7A7D96uL,0xFFC4C5CFuL,0xFF81849BuL
/* 196-199 */  ,0xFF71758FuL,0xFF757992uL,0xFFCACCD6uL,0xFF868BA1uL
/* 200-203 */  ,0xFFCED0D8uL,0xFFDFE0E4uL,0xFF7C8299uL,0xFF80869CuL
/* 204-207 */  ,0xFF8E93A6uL,0xFFC6C9D4uL,0xFFA5AABBuL,0xFFAFB4C2uL
/* 208-211 */  ,0xFFD2D7DFuL,0xFFCDD3DCuL,0xFFD7DEE5uL,0xFFDBE2E8uL
/* 212-215 */  ,0xFFE2E8EDuL,0xFFEAEFF3uL,0xFFE5ECF0uL,0xFFEDF3F5uL
/* 216-219 */  ,0xFFF7FEFFuL,0xFFF5FCFDuL,0xFF979795uL,0xFF919190uL
/* 220-223 */  ,0xFFFDFDFDuL,0xFFDEDEDEuL,0xFFD8D8D8uL,0xFFD4D4D4uL
/* 224-227 */  ,0xFFD3D3D3uL,0xFFD1D1D1uL,0xFFCECECEuL,0xFFCDCDCDuL
/* 228-231 */  ,0xFFCACACAuL,0xFFC9C9C9uL,0xFFC5C5C5uL,0xFFC1C1C1uL
/* 232-235 */  ,0xFFAFAFAFuL,0xFFACACACuL,0xFFAAAAAAuL,0xFFA8A8A8uL
/* 236-239 */  ,0xFFA7A7A7uL,0xFFA4A4A4uL,0xFF9F9F9FuL,0xFF9E9E9EuL
/* 240-243 */  ,0xFF9B9B9BuL,0xFF979797uL,0xFF959595uL,0xFF8C8C8CuL
/* 244-247 */  ,0xFF898989uL,0xFF696969uL,0xFF656565uL,0xFF535353uL
/* 248-251 */  ,0xFF434343uL,0xFF3C3C3CuL,0xFF373737uL,0xFF060606uL
/* 252-252 */  ,0xFF030303uL
};

UINT32 const img_1BPP_NAnim_clut[1] = 
{
/* 000-000 */   0xFF000000uL
};

UINT32 const img_1BPP_NAnim_0_clut[1] = 
{
/* 000-000 */   0xFF000000uL
};

/* img_2BPP_NAnim_0 Palette Optimized with img_2BPP_NAnim_clut */

/* img_4BPP_NAnim_0 Palette Optimized with img_4BPP_NAnim_clut */

/* img_8BPP_NANnim_0 Palette Optimized with img_8BPP_NANnim_clut */

UINT32 const img_APAL_NAnim_0_clut[193] = 
{
/* 000-003 */   0xFF000000uL,0xFFFACC89uL,0xFFE8E8E8uL,0xFF060605uL
/* 004-007 */  ,0xFF070706uL,0xFF080807uL,0xFF0C0A06uL,0xFF060503uL
/* 008-011 */  ,0xFF24221EuL,0xFF1A160FuL,0xFF231D13uL,0xFF1D1810uL
/* 012-015 */  ,0xFF292217uL,0xFF15110BuL,0xFF413523uL,0xFF766040uL
/* 016-019 */  ,0xFF4A3C28uL,0xFF3B3020uL,0xFF32291BuL,0xFFF7CA87uL
/* 020-023 */  ,0xFFE0B67AuL,0xFFDAB277uL,0xFFCBA66FuL,0xFFAE8E5FuL
/* 024-027 */  ,0xFFA5865AuL,0xFF9C7F55uL,0xFF967A52uL,0xFF675438uL
/* 028-031 */  ,0xFF614F35uL,0xFF584830uL,0xFFF4C786uL,0xFFF1C584uL
/* 032-035 */  ,0xFFEEC283uL,0xFFEBC081uL,0xFFE8BE7FuL,0xFFE5BB7EuL
/* 036-039 */  ,0xFFE2B97CuL,0xFFD7AF76uL,0xFFCEA871uL,0xFFC5A16CuL
/* 040-043 */  ,0xFFB69564uL,0xFFB39262uL,0xFFA28459uL,0xFF9F8257uL
/* 044-047 */  ,0xFF997D54uL,0xFF90764FuL,0xFF7E6745uL,0xFF7C6544uL
/* 048-051 */  ,0xFF735E3FuL,0xFF6D593CuL,0xFF645237uL,0xFF473A27uL
/* 052-055 */  ,0xFFB99766uL,0xFF937851uL,0xFF4C3E2AuL,0xFF261F15uL
/* 056-059 */  ,0xFF4F412CuL,0xFF0F0C08uL,0xFF443725uL,0xFF5B4A32uL
/* 060-063 */  ,0xFF352B1DuL,0xFF2F261AuL,0xFF201A12uL,0xFF322F2BuL
/* 064-067 */  ,0xFF18130DuL,0xFF120E0AuL,0xFF090705uL,0xFF0E0D0CuL
/* 068-071 */  ,0xFF11100FuL,0xFF121110uL,0xFF131211uL,0xFF151413uL
/* 072-075 */  ,0xFF181716uL,0xFF1C1B1AuL,0xFF1D1C1BuL,0xFF222120uL
/* 076-079 */  ,0xFF21201FuL,0xFF201F1EuL,0xFF313030uL,0xFF302F2FuL
/* 080-083 */  ,0xFFE7E7E7uL,0xFFE4E4E4uL,0xFFE3E3E3uL,0xFFE0E0E0uL
/* 084-087 */  ,0xFFDEDEDEuL,0xFFDCDCDCuL,0xFFDADADAuL,0xFFD8D8D8uL
/* 088-091 */  ,0xFFD6D6D6uL,0xFFD4D4D4uL,0xFFD2D2D2uL,0xFFD1D1D1uL
/* 092-095 */  ,0xFFCECECEuL,0xFFCDCDCDuL,0xFFCBCBCBuL,0xFFC9C9C9uL
/* 096-099 */  ,0xFFC6C6C6uL,0xFFC5C5C5uL,0xFFC2C2C2uL,0xFFC0C0C0uL
/* 100-103 */  ,0xFFBEBEBEuL,0xFFBCBCBCuL,0xFFBABABAuL,0xFFB8B8B8uL
/* 104-107 */  ,0xFFB6B6B6uL,0xFFB4B4B4uL,0xFFB3B3B3uL,0xFFB1B1B1uL
/* 108-111 */  ,0xFFAFAFAFuL,0xFFADADADuL,0xFFABABABuL,0xFFA9A9A9uL
/* 112-115 */  ,0xFFA6A6A6uL,0xFFA5A5A5uL,0xFFA2A2A2uL,0xFFA0A0A0uL
/* 116-119 */  ,0xFF9E9E9EuL,0xFF9C9C9CuL,0xFF9A9A9AuL,0xFF999999uL
/* 120-123 */  ,0xFF969696uL,0xFF959595uL,0xFF929292uL,0xFF919191uL
/* 124-127 */  ,0xFF8F8F8FuL,0xFF8D8D8DuL,0xFF8B8B8BuL,0xFF888888uL
/* 128-131 */  ,0xFF878787uL,0xFF848484uL,0xFF828282uL,0xFF808080uL
/* 132-135 */  ,0xFF7E7E7EuL,0xFF7D7D7DuL,0xFF7B7B7BuL,0xFF787878uL
/* 136-139 */  ,0xFF777777uL,0xFF757575uL,0xFF737373uL,0xFF707070uL
/* 140-143 */  ,0xFF6F6F6FuL,0xFF6D6D6DuL,0xFF6A6A6AuL,0xFF676767uL
/* 144-147 */  ,0xFF656565uL,0xFF626262uL,0xFF606060uL,0xFF5E5E5EuL
/* 148-151 */  ,0xFF5D5D5DuL,0xFF5A5A5AuL,0xFF595959uL,0xFF575757uL
/* 152-155 */  ,0xFF555555uL,0xFF525252uL,0xFF515151uL,0xFF4F4F4FuL
/* 156-159 */  ,0xFF4C4C4CuL,0xFF4A4A4AuL,0xFF494949uL,0xFF474747uL
/* 160-163 */  ,0xFF444444uL,0xFF424242uL,0xFF414141uL,0xFF3F3F3FuL
/* 164-167 */  ,0xFF3C3C3CuL,0xFF3A3A3AuL,0xFF393939uL,0xFF373737uL
/* 168-171 */  ,0xFF353535uL,0xFF343434uL,0xFF333333uL,0xFF2F2F2FuL
/* 172-175 */  ,0xFF2E2E2EuL,0xFF2D2D2DuL,0xFF2B2B2BuL,0xFF292929uL
/* 176-179 */  ,0xFF262626uL,0xFF252525uL,0xFF232323uL,0xFF212121uL
/* 180-183 */  ,0xFF1E1E1EuL,0xFF1D1D1DuL,0xFF1B1B1BuL,0xFF191919uL
/* 184-187 */  ,0xFF161616uL,0xFF131313uL,0xFF121212uL,0xFF101010uL
/* 188-191 */  ,0xFF0E0E0EuL,0xFF0B0B0BuL,0xFF080808uL,0xFF050505uL
/* 192-192 */  ,0xFF030303uL
};

#if GFX_MGR02_NUM_OF_CLUTS > 0
GFX_MGR02_CLUT_DATA const lc_gfx_mgr02_clut_array[GFX_MGR02_NUM_OF_CLUTS] =
{
   { &img_2BPP_NAnim_clut[0]                                      , 2   , 0 }
  ,{ &img_8BPP_NANnim_clut[0]                                     , 247 , 0 }
  ,{ &img_4BPP_NAnim_clut[0]                                      , 12  , 0 }
  ,{ &img_APAL_NAnim_clut[0]                                      , 253 , 0 }
  ,{ &img_1BPP_NAnim_clut[0]                                      , 1   , 0 }
  ,{ &img_1BPP_NAnim_0_clut[0]                                    , 1   , 0 }
  ,{ &img_APAL_NAnim_0_clut[0]                                    , 193 , 0 }
#ifdef GFX_MGR02_NEED_CLUT_CREATION_FOR_NORMAL_FILLSCREEN
  ,{ &lc_nfill_color_FF008080_CLUT[0]                             , 1   , 0 }
#endif /* GFX_MGR02_NEED_CLUT_CREATION_FOR_NORMAL_FILLSCREEN */
#if GFX_MGR02_PROD_SPEC_CLUT_TABLE_NUM > 0
  ,GFX_MGR02_PROD_SPEC_CLUT_TABLE
#endif
};
#endif /* #if GFX_MGR02_NUM_OF_CLUTS > 0 */

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
