/******************************************************************************
**              CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2012. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have  jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation
**
******************************************************************************/

/******************************************************************************

File Name        :  osStacks.h
Module Short Name:  osStacks.h
VOBName          :  
Author           :  
Description      :  Generated File
Organization     :  Driver Information Software Section,
                    Visteon Corporation

******************************************************************************/

#ifndef OSSTACKS_H
#define OSSTACKS_H
/* file: C:\RTE\S2dot8\27_11\05_12_Update\os_Working/osStacks.ld */
/* automatically generated by mOS Configurator xls v1.0 */
/* Generation time: 12/6/2023 9:54:58 PM */
/* vAutosar SIP Stack Generation */
/* Implementation: S6J3xx */


#include "Os.h"


#define osdInitTask_BOT osBottomOfStack(osTaskStackOsApplication0)
#define osdInitTask_TOP osAssignStack(osTaskStackOsApplication0)

#define osdOsTask_IdleTask_BOT osBottomOfStack(osTaskStackOsApplication1)
#define osdOsTask_IdleTask_TOP osAssignStack(osTaskStackOsApplication1)

#define osdOsTask_BswCtrl_EventPeriodic_BOT osBottomOfStack(osTaskStackOsApplication2)
#define osdOsTask_BswCtrl_EventPeriodic_TOP osAssignStack(osTaskStackOsApplication2)

#define osdOsTask_Bsw_EventPeriodic_0_BOT osBottomOfStack(osTaskStackOsApplication3)
#define osdOsTask_Bsw_EventPeriodic_0_TOP osAssignStack(osTaskStackOsApplication3)

#define osdOsTask_Bsw_EventPeriodic_1_BOT osBottomOfStack(osTaskStackOsApplication4)
#define osdOsTask_Bsw_EventPeriodic_1_TOP osAssignStack(osTaskStackOsApplication4)

#define osdOsTask_NvmSpeedup_BOT osBottomOfStack(osTaskStackOsApplication5)
#define osdOsTask_NvmSpeedup_TOP osAssignStack(osTaskStackOsApplication5)

#define osdOsTask_SWCEventPeriodic_0_BOT osBottomOfStack(osTaskStackOsApplication6)
#define osdOsTask_SWCEventPeriodic_0_TOP osAssignStack(osTaskStackOsApplication6)

#define osdOsTask_SWCEventPeriodic_1_BOT osBottomOfStack(osTaskStackOsApplication7)
#define osdOsTask_SWCEventPeriodic_1_TOP osAssignStack(osTaskStackOsApplication7)

#define osdOsTask_SWCEventPeriodic_2_BOT osBottomOfStack(osTaskStackOsApplication8)
#define osdOsTask_SWCEventPeriodic_2_TOP osAssignStack(osTaskStackOsApplication8)

#define osdOsTask_SWCEventPeriodic_3_BOT osBottomOfStack(osTaskStackOsApplication9)
#define osdOsTask_SWCEventPeriodic_3_TOP osAssignStack(osTaskStackOsApplication9)

#define osdOsTask_SWCEventPeriodic_4_BOT osBottomOfStack(osTaskStackOsApplication10)
#define osdOsTask_SWCEventPeriodic_4_TOP osAssignStack(osTaskStackOsApplication10)

#define osdOsTask_SWCEventPeriodic_5_BOT osBottomOfStack(osTaskStackOsApplication11)
#define osdOsTask_SWCEventPeriodic_5_TOP osAssignStack(osTaskStackOsApplication11)

#define osdOsTask_SWCEventPeriodic_6_BOT osBottomOfStack(osTaskStackOsApplication12)
#define osdOsTask_SWCEventPeriodic_6_TOP osAssignStack(osTaskStackOsApplication12)

#define osdOsTask_SWCEventPeriodic_7_BOT osBottomOfStack(osTaskStackOsApplication13)
#define osdOsTask_SWCEventPeriodic_7_TOP osAssignStack(osTaskStackOsApplication13)

#define osdOsTask_SWCEventPeriodic_8_BOT osBottomOfStack(osTaskStackOsApplication14)
#define osdOsTask_SWCEventPeriodic_8_TOP osAssignStack(osTaskStackOsApplication14)

#define osdOsTask_SWCEventPeriodic_10_BOT osBottomOfStack(osTaskStackOsApplication15)
#define osdOsTask_SWCEventPeriodic_10_TOP osAssignStack(osTaskStackOsApplication15)

#define osdOsTask_SWCEventPeriodic_11_BOT osBottomOfStack(osTaskStackOsApplication16)
#define osdOsTask_SWCEventPeriodic_11_TOP osAssignStack(osTaskStackOsApplication16)

#define osdOsTask_SWCEventPeriodic_12_BOT osBottomOfStack(osTaskStackOsApplication17)
#define osdOsTask_SWCEventPeriodic_12_TOP osAssignStack(osTaskStackOsApplication17)

#define osdOsTask_SWCEventPeriodic_13_BOT osBottomOfStack(osTaskStackOsApplication18)
#define osdOsTask_SWCEventPeriodic_13_TOP osAssignStack(osTaskStackOsApplication18)

#define osdOsTask_SafeSWCEventPeriodic_0_BOT osBottomOfStack(osTaskStackOsApplication19)
#define osdOsTask_SafeSWCEventPeriodic_0_TOP osAssignStack(osTaskStackOsApplication19)

#define osdOsTask_SafeBsw_0_BOT osBottomOfStack(osTaskStackOsApplication20)
#define osdOsTask_SafeBsw_0_TOP osAssignStack(osTaskStackOsApplication20)

#define osdOsTask_SafeBsw_1_BOT osBottomOfStack(osTaskStackOsApplication21)
#define osdOsTask_SafeBsw_1_TOP osAssignStack(osTaskStackOsApplication21)

#define osdOsTask_UclProxyEvent_0_BOT osBottomOfStack(osTaskStackOsApplication22)
#define osdOsTask_UclProxyEvent_0_TOP osAssignStack(osTaskStackOsApplication22)

#define osdOsTask_UclProxyEvent_1_BOT osBottomOfStack(osTaskStackOsApplication23)
#define osdOsTask_UclProxyEvent_1_TOP osAssignStack(osTaskStackOsApplication23)

#define osdOsTask_Cdd_EventPeriodic_0_BOT osBottomOfStack(osTaskStackOsApplication24)
#define osdOsTask_Cdd_EventPeriodic_0_TOP osAssignStack(osTaskStackOsApplication24)

#define osdOsTask_Cdd_EventPeriodic_1_BOT osBottomOfStack(osTaskStackOsApplication25)
#define osdOsTask_Cdd_EventPeriodic_1_TOP osAssignStack(osTaskStackOsApplication25)

#define osdOsTask_SWCEventPeriodic_9_BOT osBottomOfStack(osTaskStackOsApplication26)
#define osdOsTask_SWCEventPeriodic_9_TOP osAssignStack(osTaskStackOsApplication26)

#define osdFIQStack_BOT osBottomOfStack(osFIQStack)
#define osdFIQStack_TOP osAssignStack(osFIQStack)


#define osdIRQCat1Stack_BOT osBottomOfStack(osIRQCat1Stack)
#define osdIRQCat1Stack_TOP osAssignStack(osIRQCat1Stack)


#define osdSystemStack_BOT osBottomOfStack(osSystemStack)
#define osdSystemStack_TOP osAssignStack(osSystemStack)


#define osdSystemTimerISR_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdSystemTimerISR_TOP osAssignStack(osLevelStackCore0Level1)

#define osdCan_ISR_B_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdCan_ISR_B_TOP osAssignStack(osLevelStackCore0Level1)

#define osdADC0_ISR_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdADC0_ISR_TOP osAssignStack(osLevelStackCore0Level1)

#define osdGPT_2_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdGPT_2_TOP osAssignStack(osLevelStackCore0Level1)

#define osdGPT_3_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdGPT_3_TOP osAssignStack(osLevelStackCore0Level1)

#define osdSPI0_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdSPI0_TOP osAssignStack(osLevelStackCore0Level1)

#define osdSPI2_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdSPI2_TOP osAssignStack(osLevelStackCore0Level1)

#define osdGPT_LPIT_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdGPT_LPIT_TOP osAssignStack(osLevelStackCore0Level1)

#define osdGPT_4_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdGPT_4_TOP osAssignStack(osLevelStackCore0Level1)

#define osdGPIO0_INT_BOT osBottomOfStack(osLevelStackCore0Level1)
#define osdGPIO0_INT_TOP osAssignStack(osLevelStackCore0Level1)



osqStack1 extern osqStack2 osStackDataType osqStack3 osFIQStack [64]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osIRQCat1Stack [128]; /* PRQA S 777 */ /* PRQA S 4152 */


osqStack1 extern osqStack2 osStackDataType osqStack3 osSystemStack [64]; /* PRQA S 777 */ /* PRQA S 4152 */
osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level0 [128]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osLevelStackCore0Level1 [256]; /* PRQA S 777 */ /* PRQA S 4152 */



osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication0 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication1 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication2 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication3 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication4 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication5 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication6 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication7 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication8 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication9 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication10 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication11 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication12 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication13 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication14 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication15 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication16 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication17 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication18 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication19 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication20 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication21 [512]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication22 [1024]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication23 [1024]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication24 [1024]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication25 [1024]; /* PRQA S 777 */ /* PRQA S 4152 */

osqStack1 extern osqStack2 osStackDataType osqStack3 osTaskStackOsApplication26 [1024]; /* PRQA S 777 */ /* PRQA S 4152 */




#endif    /* */
/* end of file */
/****************************************************************
Created Time: 12/6/2023 9:54:58 PM
****************************************************************/
