///////////////////////////////////////////////////////////////////////////////
//
//                     CONFIDENTIAL VISTEON CORPORATION
//
// This is an unpublished work of authorship, which contains trade secrets,
// created in 2018. Visteon Corporation owns all rights to this work and
// intends to maintain it in confidence to preserve its trade secret status.
// Visteon Corporation reserves the right, under the copyright laws of the
// United States or those of any other country that may have jurisdiction,
// to protect this work as an unpublished work, in the event of an
// inadvertent or deliberate unauthorized publication. Visteon Corporation
// also reserves its rights under all copyright laws to protect this work as
// a published work, when appropriate. Those having access to this work may
// not copy it, use it, modify it or disclose the information contained in
// it without the written authorization of Visteon Corporation.
//
//  Description : classes to describe the graphics project.
//  Created on  : 02-Jan-2019 by emanoj1@visteon.com
///////////////////////////////////////////////////////////////////////////////

//Include Files ...
#include "rdf_mesh.h"
//Macro Definitions ...

namespace rendercore_engine
{

//Variable declarations ...

//Class data declarations ...
rdf_mesh const mdl_mesh_meshes_disp0[99] =
{
  {
    nullptr,
    primitives_mdl_mesh_frame_47_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_bg,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_warn_amber_outline,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_warn_check_fuel_cap,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_42,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_43,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_44,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_45,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_warning_red_outline,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_check_airbag,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_layer_1_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_2,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_3,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_4,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_menu_bg,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_menu_focus_bar,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_menu_drive_info,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_menu_vehicle_info,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_menu_adas,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_menu_navigation,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_menu_alert_history,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_menu_title,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_menu_line_1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_menu_line_2,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_menu_line_3,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_menu_line_4,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_56,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_57,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_52,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_47,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_59,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_60,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_61,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_55,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_58,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_49,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_53,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_51,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_58,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_59,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_56,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_61,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_57,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_60,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_main_digital_speedo,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_3,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_4,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_5,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_fuel_icon_5_1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_polygon_27,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_56_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_57_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_52_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_47_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_59_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_60_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_61_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_55_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_62,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_49_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_53_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_ellipse_51_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_58_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_59_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_56_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_61_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_57_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_60_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_6,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_7,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_gear_value,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_tacho_unit,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_gear_title,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_17,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_18,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_default_0,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_inst1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_0_inst1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_1_inst1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_vector_2_inst1,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_odo_unit,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_odo_value,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_odo_title,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_dte_title,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_dte_value,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_dte_unit,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_25,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_26,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_27,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_28,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_29,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_digital_speedo_day_30,
    1U,
    0U
  },
  {
    nullptr,
    primitives_mdl_mesh_txt_tacho_value,
    1U,
    0U
  }
};

//Methods ...

}
