/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_button.h                                 
**                                                                            
** Description:    This file contains the language identifier interfaces      
**                 Autogenerated by LanguageEncoder.exe Version 1.7.          
**                 Do not handmodify this file								  
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_BUTTON_H
#define HMI_BUTTON_H
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/

/*============================================================================
** T Y P E   D E F I N I T I O N S                                                  
**==========================================================================*/

enum
{
   ButtonID_OK,
   ButtonID_UP,
   ButtonID_DOWN,
   ButtonID_LEFT,
   ButtonID_RIGHT,
   ButtonID_0,
   ButtonID_1,
   ButtonID_2,
   ButtonID_3,
   ButtonID_4,
   ButtonID_5,
   ButtonID_6,
   ButtonID_7,
   ButtonID_8,
   ButtonID_9,
   ButtonID_A,
   ButtonID_B,
   ButtonID_C,
   ButtonID_D,
   ButtonID_E,
   ButtonID_F,
   ButtonID_G,
   ButtonID_H,
   ButtonID_I,
   ButtonID_J,
   ButtonID_K,
   ButtonID_L,
   ButtonID_M,
   ButtonID_N,
   ButtonID_O,
   ButtonID_P,
   ButtonID_Q,
   ButtonID_R,
   ButtonID_S,
   ButtonID_T,
   ButtonID_U,
   ButtonID_V,
   ButtonID_W,
   ButtonID_X,
   ButtonID_Y,
   ButtonID_Z
};

enum
{
   ButtonState_Inactive,
   ButtonState_Pressed,
   ButtonState_Held
};


/*============================================================================ 
**                                                                             
**============================================================================ 
** C M S    R E V I S I O N    N O T E S                                       
**============================================================================ 
**                                                                             
** For each change to this file, be sure to record:                            
** 1.  Who made the change and when the change was made.                       
** 2.  Why the change was made and the intended result.                        
**                                                                             
** CMS Rev #        Date         By                                            
** CMS Rev X.X      mm/dd/yy     CDSID                                         
**                                                                             
**============================================================================ 
**                                                                             
** CMS Rev 1        08/12/09     JKANOZA                                       
** Initial revision.                                                           
**                                                                             
**==========================================================================*/ 
                                                                               
/* end of file =============================================================*/ 
#endif /* HMI_LANGUAGE_IDENTIFIERS_H */
