/*============================================================================
**
**                     CONFIDENTIAL VISTEON CORPORATION
**
** This is an unpublished work of authorship, which contains trade secrets,
** created in 2010. Visteon Corporation owns all rights to this work and
** intends to maintain it in confidence to preserve its trade secret status.
** Visteon Corporation reserves the right, under the copyright laws of the
** United States or those of any other country that may have jurisdiction,
** to protect this work as an unpublished work, in the event of an
** inadvertent or deliberate unauthorized publication. Visteon Corporation
** also reserves its rights under all copyright laws to protect this work as
** a published work, when appropriate. Those having access to this work may
** not copy it, use it, modify it or disclose the information contained in
** it without the written authorization of Visteon Corporation.
**
**============================================================================
**
** Name:           gdg02_image_data.c
**
** Description:    This file is used by the application code to determine
**                 where graphic pixel data generated by the GDT tool
**                 should reside in memory.  The two choices are internal
**                 flash or external flash (accessed via the QSPI
**                 peripheral).  Details on how to make the selection are
**                 available below.
**
** Organization:   Driver Information Software Section,
**                 DI Core Engineering Department
**
**============================================================================
**
**==========================================================================*/
#define GDG02_IMAGE_DATA_C

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "system.h"
#include "hmi_gfx_mgr02_layout.h"

/*
** For files in external flash memory, #include them as in the example below.
** Note the use of #pragmas.
*/
#ifndef WIN32
   typedef UINT8  GFX_IMG_DATA_T    __attribute__ ((aligned (8)));
   typedef UINT16 GFX_IMG_DATA16_T  __attribute__ ((aligned (8)));
   typedef UINT32 GFX_IMG_DATA32_T  __attribute__ ((aligned (8)));
#else
   typedef UINT8  GFX_IMG_DATA_T;
   typedef UINT16 GFX_IMG_DATA16_T;
   typedef UINT32 GFX_IMG_DATA32_T;
#endif

#define GFX_IMG_DATA_PREFIX
#define GFX_IMG_DATA_SUFFIX 

#if 0
/*
** For files in internal flash memory, #include them as in the example below.
** Note that nothing special needs to be done.
*/
#include "img_welcome_animation_56_ovg.dat"
#include "img_welcome_animation_1_ovg.dat"
#include "img_welcome_animation_2_ovg.dat"
#include "img_welcome_animation_3_ovg.dat"
#include "img_welcome_animation_4_ovg.dat"
#include "img_welcome_animation_5_ovg.dat"
#include "img_welcome_animation_6_ovg.dat"
#include "img_welcome_animation_7_ovg.dat"
#include "img_welcome_animation_8_ovg.dat"
#include "img_welcome_animation_9_ovg.dat"
#include "img_welcome_animation_10_ovg.dat"
#include "img_welcome_animation_11_ovg.dat"
#include "img_welcome_animation_12_ovg.dat"
#include "img_welcome_animation_13_ovg.dat"
#include "img_welcome_animation_14_ovg.dat"
#include "img_welcome_animation_15_ovg.dat"
#include "img_welcome_animation_16_ovg.dat"
#include "img_welcome_animation_17_ovg.dat"
#include "img_welcome_animation_18_ovg.dat"
#include "img_welcome_animation_19_ovg.dat"
#include "img_welcome_animation_20_ovg.dat"
#include "img_welcome_animation_21_ovg.dat"
#include "img_welcome_animation_22_ovg.dat"
#include "img_welcome_animation_23_ovg.dat"
#include "img_welcome_animation_24_ovg.dat"
#include "img_welcome_animation_25_ovg.dat"
#include "img_welcome_animation_26_ovg.dat"
#include "img_welcome_animation_27_ovg.dat"
#include "img_welcome_animation_28_ovg.dat"
#include "img_welcome_animation_29_ovg.dat"
#include "img_welcome_animation_30_ovg.dat"
#include "img_welcome_animation_31_ovg.dat"
#include "img_welcome_animation_32_ovg.dat"
#include "img_welcome_animation_33_ovg.dat"
#include "img_welcome_animation_34_ovg.dat"
#include "img_welcome_animation_35_ovg.dat"
#include "img_welcome_animation_36_ovg.dat"
#include "img_welcome_animation_37_ovg.dat"
#include "img_welcome_animation_38_ovg.dat"
#include "img_welcome_animation_39_ovg.dat"
#include "img_welcome_animation_40_ovg.dat"
#include "img_welcome_animation_41_ovg.dat"
#include "img_welcome_animation_42_ovg.dat"
#include "img_welcome_animation_43_ovg.dat"
#include "img_welcome_animation_44_ovg.dat"
#include "img_welcome_animation_45_ovg.dat"
#include "img_welcome_animation_46_ovg.dat"
#include "img_welcome_animation_47_ovg.dat"
#include "img_welcome_animation_48_ovg.dat"
#include "img_welcome_animation_49_ovg.dat"
#include "img_welcome_animation_50_ovg.dat"
#include "img_welcome_animation_51_ovg.dat"
#include "img_welcome_animation_52_ovg.dat"
#include "img_welcome_animation_53_ovg.dat"
#include "img_welcome_animation_54_ovg.dat"
#include "img_welcome_animation_55_ovg.dat"
#include "img_source_popup_bg_ovg.dat"
#include "img_source_bg_ovg.dat"
#include "img_source_close_active_ovg.dat"
#include "img_source_close_press_ovg.dat"
#include "img_source_tuner_active_ovg.dat"
#include "img_source_tuner_press_ovg.dat"
#include "img_bg_ovg.dat"
#include "img_footer_static_ovg.dat"
#include "img_tuner_btn_active_ovg.dat"
#include "img_tuner_btn_press_ovg.dat"
#include "img_source_active_ovg.dat"
#include "img_source_press_ovg.dat"
#include "img_phone_active_ovg.dat"
#include "img_phone_press_ovg.dat"
#include "img_phone_inactive_ovg.dat"
#include "img_nav_active_ovg.dat"
#include "img_nav_press_ovg.dat"
#include "img_nav_inactive_ovg.dat"
#include "img_settings_active_ovg.dat"
#include "img_settings_press_ovg.dat"
#include "img_settings_inactive_ovg.dat"
#include "img_band_active_ovg.dat"
#include "img_band_press_ovg.dat"
#include "img_preset_active_ovg.dat"
#include "img_preset_press_ovg.dat"
#include "img_seek_backward_active_ovg.dat"
#include "img_seek_backward_press_ovg.dat"
#include "img_seek_forward_active_ovg.dat"
#include "img_seek_forward_press_ovg.dat"
#include "img_scan_next_active_ovg.dat"
#include "img_scan_next_press_ovg.dat"
#include "img_scan_previous_active_ovg.dat"
#include "img_scan_previous_press_ovg.dat"
#include "img_scan_backward_active_ovg.dat"
#include "img_scan_backward_press_ovg.dat"
#include "img_scan_forward_active_ovg.dat"
#include "img_scan_forward_press_ovg.dat"
#include "img_source_dlna_player_active_ovg.dat"
#include "img_source_dlna_player_press_ovg.dat"
#include "img_source_dlna_player_inactive_ovg.dat"
#include "img_source_dlna_control_active_ovg.dat"
#include "img_source_dlna_control_press_ovg.dat"
#include "img_source_dlna_control_inactive_ovg.dat"
#include "img_source_dlna_watch_active_ovg.dat"
#include "img_source_dlna_watch_press_ovg.dat"
#include "img_source_dlna_watch_inactive_ovg.dat"
#include "img_source_tunein_active_ovg.dat"
#include "img_source_tunein_press_ovg.dat"
#include "img_source_tunein_inactive_ovg.dat"
#include "img_source_pandora_active_ovg.dat"
#include "img_source_pandora_press_ovg.dat"
#include "img_source_pandora_inactive_ovg.dat"
#include "img_source_usb_1_active_ovg.dat"
#include "img_source_usb_1_press_ovg.dat"
#include "img_source_usb_1_inactive_ovg.dat"
#include "img_source_usb_2_active_ovg.dat"
#include "img_source_usb_2_inactive_ovg.dat"
#include "img_source_usb_2_press_ovg.dat"
#include "img_source_bt_active_ovg.dat"
#include "img_source_bt_press_ovg.dat"
#include "img_source_bt_inactive_ovg.dat"
#include "img_source_aux_active_ovg.dat"
#include "img_source_aux_press_ovg.dat"
#include "img_source_aux_inactive_ovg.dat"
#include "img_source_sdcard_press_ovg.dat"
#include "img_source_sdcard_inactive_ovg.dat"
#include "img_source_ipod_1_active_ovg.dat"
#include "img_source_ipod_1_press_ovg.dat"
#include "img_source_ipod_1_inactive_ovg.dat"
#include "img_source_ipod_2_active_ovg.dat"
#include "img_source_ipod_2_press_ovg.dat"
#include "img_source_ipod_2_inactive_ovg.dat"
#include "img_source_sdcard_active_ovg.dat"
#endif

#undef GFX_IMG_DATA_PREFIX
#if defined(MATLAB_MEX_FILE)||defined(WIN32)
	#define GFX_IMG_DATA_PREFIX
#else
	#pragma push
	#pragma section "QSPI0_FLASH"
	#define GFX_IMG_DATA_PREFIX   __declspec(section "QSPI0_FLASH")
#endif


/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** CMS Rev 1        01/13/10     JKANOZA
** Initial revision.
**
**==========================================================================*/

/* end of file =============================================================*/
