/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_gfx_mgr02_image_data.h
**                                                                            
** Description:    This file contains the image data autogenerated by         
**                 the GDT . Do not handmodify this file.              
**                 Autogenerated on MM/DD/YYYY - 11/2/2023
**                 Total Image ROM size = [12477704 bytes]   
**                 Total RLE Savings    = [0 bytes]
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#ifndef HMI_GFX_MGR02_IMAGE_DATA_H
#define HMI_GFX_MGR02_IMAGE_DATA_H
                                                                              
/*============================================================================
** I N C L U D E   F I L E S                                                  
**==========================================================================*/
#include "system.h"
                                                                              
/*============================================================================
** T Y P E   D E F I N I T I O N S                                            
**==========================================================================*/


/*
** externs for all the image tables generated.
*/
extern UINT32 const lc_img_opening_anim_0_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_1_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_2_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_3_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_4_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_5_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_6_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_7_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_8_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_9_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_10_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_11_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_12_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_13_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_14_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_15_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_16_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_17_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_18_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_19_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_20_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_21_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_22_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_23_ovg_data[78400];
extern UINT32 const lc_img_opening_anim_24_ovg_data[78400];
extern UINT16 const lc_img_info_popup_border_data[81168];
extern UINT16 const lc_img_info_popup1_data[2400];
extern UINT16 const lc_img_ack_popup_border_data[81168];
extern UINT16 const lc_img_ack_popup1_data[4125];
extern UINT32 const lc_img_hardwrng_border_ovg_data[150000];
extern UINT32 const lc_img_hardwrng1_ovg_data[6004];
extern UINT32 const lc_img_softwrng_border_ovg_data[150000];
extern UINT32 const lc_img_infowrng1_ovg_data[5456];
extern UINT32 const lc_img_infowrng_border_ovg_data[150000];
extern UINT32 const lc_img_softwrng1_ovg_data[4096];
extern UINT32 const lc_img_hardwng_1_ovg_data[16380];
extern UINT16 const lc_img_progress1_data[4800];
extern UINT32 const lc_img_progress2_ovg_data[4800];
extern UINT32 const lc_img_progress3_ovg_data[4800];
extern UINT32 const lc_img_progress4_ovg_data[4800];
extern UINT32 const lc_img_progress5_ovg_data[4800];
extern UINT32 const lc_img_progress6_ovg_data[4800];
extern UINT32 const lc_img_progress7_ovg_data[4800];
extern UINT32 const lc_img_progress8_ovg_data[4800];
extern UINT32 const lc_img_progress9_ovg_data[4800];
extern UINT32 const lc_img_progress10_ovg_data[4800];
extern UINT32 const lc_img_progress11_ovg_data[4800];
extern UINT32 const lc_img_progress12_ovg_data[4800];
extern UINT32 const lc_img_progress13_ovg_data[4800];
extern UINT32 const lc_img_progress14_ovg_data[4800];
extern UINT32 const lc_img_progress15_ovg_data[4800];
extern UINT32 const lc_img_progress16_ovg_data[4800];
extern UINT32 const lc_img_progress17_ovg_data[4800];
extern UINT32 const lc_img_progress18_ovg_data[4800];
extern UINT32 const lc_img_progress19_ovg_data[4800];
extern UINT32 const lc_img_progress20_ovg_data[4800];
extern UINT32 const lc_img_progress21_ovg_data[4800];
extern UINT32 const lc_img_progress22_ovg_data[4800];
extern UINT32 const lc_img_progress23_ovg_data[4800];
extern UINT8 const lc_img_menu_media_data[1665];
extern UINT8 const lc_img_menu_phone_data[1665];
extern UINT8 const lc_img_menu_settings_data[1665];
extern UINT8 const lc_img_menu_arrow_data[1665];
extern UINT32 const lc_img_opening_ovg_data[384000];
extern UINT8 const lc_new_images_5_data[1665];
extern UINT8 const lc_new_images_6_data[1665];
extern UINT32 const lc_img_warn1_border_ovg_data[74550];
extern UINT16 const lc_img_warning1_data[16008];
extern UINT16 const lc_img_warning2_data[16008];
extern UINT16 const lc_img_warning3_data[16008];

/*
** mapping for image data which is repeating
*/
#define lc_img_1_data                                        (lc_img_menu_arrow_data)
#define lc_img_2_data                                        (lc_img_menu_media_data)
#define lc_img_3_data                                        (lc_img_menu_phone_data)
#define lc_new_images_4_data                                 (lc_img_menu_settings_data)
#define lc_img_progress1_0_data                              (lc_img_progress1_data)
#define lc_img_warn2_border_data                             (lc_img_warn1_border_ovg_data)
#define lc_img_warn3_border_data                             (lc_img_warn1_border_ovg_data)

/*============================================================================
** E N T R Y   P O I N T S                                                    
**==========================================================================*/
                                                                              
/*============================================================================
**                                                                            
**============================================================================
** C M S    R E V I S I O N    N O T E S                                      
**============================================================================
**                                                                            
** For each change to this file, be sure to record:                           
** 1.  Who made the change and when the change was made.                      
** 2.  Why the change was made and the intended result.                       
**                                                                            
** CMS Rev #        Date         By                                           
** CMS Rev X.X      mm/dd/yy     CDSID                                        
**                                                                            
**============================================================================
**                                                                            
** CMS Rev 1        08/12/09     JKANOZA                                      
** Initial revision.                                                          
**                                                                            
**==========================================================================*/
                                                                              
/* end of file =============================================================*/
#endif /* HMI_GFX_MGR02_IMAGE_DATA_H */
