/*============================================================================
**                                                                            
**                     CONFIDENTIAL VISTEON CORPORATION                       
**                                                                            
** This is an unpublished work of authorship, which contains trade secrets,   
** created in 2009. Visteon Corporation owns all rights to this work and      
** intends to maintain it in confidence to preserve its trade secret status.  
** Visteon Corporation reserves the right, under the copyright laws of the    
** United States or those of any other country that may have jurisdiction,    
** to protect this work as an unpublished work, in the event of an            
** inadvertent or deliberate unauthorized publication. Visteon Corporation    
** also reserves its rights under all copyright laws to protect this work as  
** a published work, when appropriate. Those having access to this work may   
** not copy it, use it, modify it or disclose the information contained in    
** it without the written authorization of Visteon Corporation.               
**                                                                            
**============================================================================
**                                                                            
** Name:           hmi_language_1.c
**                                                                            
** Description:    This file contains the language database                   
**                 Autogenerated by LanguageEncoder.exe Version : 1.1.0.7.          
**                 Do not handmodify this file						   	     
**                                                                            
**                 See the Language Encoder information in Clearcase at       
**                 <\sw_methods_tools\tools\hmi\languge_encoder_01>           
**                 <\sw_hmi_ss\hmi_language_01>                               
**                 on the design and usage.                                   
**                                                                            
** Organization:   Driver Information Software Section,                       
**                 DI Core Engineering Department                             
**                                                                            
**============================================================================
**                                                                            
**==========================================================================*/
#define HMI_LANGUAGE_1_C

/*============================================================================
** I N C L U D E   F I L E S
**==========================================================================*/
#include "hmi_language_interface.h"

/*============================================================================
** T Y P E   D E F I N I T I O N S
**==========================================================================*/

/*============================================================================
** I N T E R N A L   F U N C T I O N   P R O T O T Y P E S
**==========================================================================*/

/*============================================================================
** M E M O R Y   A L L O C A T I O N
**==========================================================================*/

#if defined(__COSMIC_SYSTEMS_ICC)
  #pragma section const {HMI_STN_1}
#endif

#if defined(__IAR_SYSTEMS_ICC)
  #pragma memory=constseg(HMI_LNG_1_CONST)
#endif

#if defined(__CWCC__)
   #pragma push
   #pragma section "HMI_LNG_1_CONST" "HMI_LNG_1_CONST"
   #define LNG_DATA_DATA_PREFIX __declspec(section "HMI_LNG_1_CONST")
#else
   #define LNG_DATA_DATA_PREFIX
#endif
LNG_DATA_DATA_PREFIX static UINT8 const HmStrLngTable1[] = { 
/*0x0000      */ 0x05, 0x57, 0x4F, 0x52, 0x4C, 0x44
/*0x0006      */, 0x0D, 0x42, 0x72, 0x61, 0x6B, 0x65, 0x20, 0x46, 0x61, 0x69, 0x6C, 0x75, 0x72, 0x65
/*0x0014      */, 0x08, 0x4C, 0x6F, 0x77, 0x20, 0x46, 0x75, 0x65, 0x6C
/*0x001D      */, 0x0C, 0x48, 0x65, 0x61, 0x64, 0x6C, 0x69, 0x67, 0x68, 0x74, 0x20, 0x4F, 0x4E
/*0x002A      */, 0x08, 0x41, 0x75, 0x64, 0x69, 0x6F, 0x20, 0x4F, 0x4E
/*0x0033      */, 0x09, 0x57, 0x69, 0x70, 0x65, 0x72, 0x20, 0x4F, 0x46, 0x46
/*0x003D      */, 0x0C, 0x45, 0x6E, 0x74, 0x65, 0x72, 0x20, 0x4E, 0x75, 0x6D, 0x62, 0x65, 0x72
/*0x004A      */, 0x10, 0x53, 0x63, 0x61, 0x6E, 0x20, 0x49, 0x6E, 0x20, 0x50, 0x72, 0x6F, 0x67, 0x72, 0x65, 0x73, 0x73
/*0x005B      */, 0x04, 0x4D, 0x65, 0x6E, 0x75
/*0x0060      */, 0x01, 0x20
/*0x0062      */, 0x04, 0x4C, 0x6F, 0x63, 0x6B
/*0x0067      */, 0x0B, 0x52, 0x61, 0x69, 0x6E, 0x20, 0x73, 0x65, 0x6E, 0x73, 0x6F, 0x72
/*0x0073      */, 0x0B, 0x44, 0x69, 0x61, 0x67, 0x6E, 0x6F, 0x73, 0x74, 0x69, 0x63, 0x73
/*0x007F      */, 0x05, 0x53, 0x70, 0x65, 0x65, 0x64
/*0x0085      */, 0x0D, 0x48, 0x45, 0x4C, 0x4C, 0x4F, 0x20, 0x57, 0x61, 0x72, 0x6E, 0x69, 0x6E, 0x67
/*0x0093      */, 0x05, 0x48, 0x45, 0x4C, 0x4C, 0x4F
/*0x0099      */, 0x1F, 0x00, 0x93
/*0x009C      */, 0x04, 0x52, 0x6F, 0x6F, 0x74
/*0x00A1      */, 0x1F, 0x00, 0x9C
/*0x00A4      */, 0x0A, 0x46, 0x6F, 0x72, 0x64, 0x20, 0x52, 0x61, 0x64, 0x69, 0x6F
/*0x00AF      */, 0x0E, 0x41, 0x75, 0x64, 0x69, 0x6F, 0x20, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6E, 0x67, 0x73
/*0x00BE      */, 0x0E, 0x52, 0xE9, 0x67, 0x6C, 0x61, 0x67, 0x65, 0x73, 0x20, 0x61, 0x75, 0x64, 0x69, 0x6F
/*0x00CD      */, 0x0E, 0x41, 0x75, 0x64, 0x69, 0x6F, 0x20, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6E, 0x67, 0x73
/*0x00DC      */, 0x10, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6C, 0x65, 0x20, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6E, 0x67, 0x73
/*0x00ED      */, 0x11, 0x52, 0xE9, 0x67, 0x6C, 0x61, 0x67, 0x65, 0x73, 0x20, 0x76, 0xE9, 0x68, 0x69, 0x63, 0x75, 0x6C, 0x65
/*0x00FF      */, 0x10, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6C, 0x65, 0x20, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6E, 0x67, 0x73
/*0x0110      */, 0x0D, 0x41, 0x6D, 0x62, 0x69, 0x65, 0x6E, 0x74, 0x20, 0x6C, 0x69, 0x67, 0x68, 0x74
/*0x011E      */, 0x0D, 0x4C, 0x75, 0x6D, 0x2E, 0x20, 0x61, 0x6D, 0x62, 0x69, 0x61, 0x6E, 0x74, 0x65
/*0x012C      */, 0x0D, 0x41, 0x6D, 0x62, 0x69, 0x65, 0x6E, 0x74, 0x20, 0x4C, 0x69, 0x67, 0x68, 0x74
/*0x013A      */, 0x10, 0x44, 0x65, 0x66, 0x6C, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x20, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74
/*0x014B      */, 0x10, 0x43, 0x6F, 0x6E, 0x74, 0x72, 0x2E, 0x20, 0x70, 0x72, 0x2E, 0x20, 0x70, 0x6E, 0x65, 0x75, 0x73
/*0x015C      */, 0x10, 0x44, 0x65, 0x66, 0x6C, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x20, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74
/*0x016D      */, 0x03, 0x45, 0x53, 0x43
/*0x0171      */, 0x1F, 0x01, 0x6D
/*0x0174      */, 0x0B, 0x41, 0x64, 0x76, 0x61, 0x6E, 0x63, 0x65, 0x54, 0x72, 0x61, 0x63
/*0x0180      */, 0x11, 0x50, 0x61, 0x72, 0x6B, 0x20, 0x6C, 0x6F, 0x63, 0x6B, 0x20, 0x63, 0x6F, 0x6E, 0x74, 0x72, 0x6F, 0x6C
/*0x0192      */, 0x0E, 0x43, 0x74, 0x72, 0x6C, 0x20, 0x70, 0x61, 0x72, 0x6B, 0x20, 0x6C, 0x6F, 0x63, 0x6B
/*0x01A1      */, 0x0E, 0x50, 0x61, 0x72, 0x6B, 0x20, 0x4C, 0x6F, 0x63, 0x6B, 0x20, 0x43, 0x74, 0x72, 0x6C
/*0x01B0      */, 0x0A, 0x53, 0x59, 0x4E, 0x43, 0x2D, 0x4D, 0x65, 0x64, 0x69, 0x61
/*0x01BB      */, 0x0A, 0x53, 0x59, 0x4E, 0x43, 0x2D, 0x4D, 0xE9, 0x64, 0x69, 0x61
/*0x01C6      */, 0x1F, 0x01, 0xB0
/*0x01C9      */, 0x0A, 0x53, 0x59, 0x4E, 0x43, 0x2D, 0x50, 0x68, 0x6F, 0x6E, 0x65
/*0x01D4      */, 0x0E, 0x53, 0x59, 0x4E, 0x43, 0x2D, 0x54, 0xE9, 0x6C, 0xE9, 0x70, 0x68, 0x6F, 0x6E, 0x65
/*0x01E3      */, 0x1F, 0x01, 0xC9
/*0x01E6      */, 0x0C, 0x41, 0x6C, 0x61, 0x72, 0x6D, 0x20, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6D
/*0x01F3      */, 0x06, 0x41, 0x6C, 0x61, 0x72, 0x6D, 0x65
/*0x01FA      */, 0x0C, 0x41, 0x6C, 0x61, 0x72, 0x6D, 0x20, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6D
/*0x0207      */, 0x0C, 0x54, 0x79, 0x72, 0x65, 0x20, 0x6D, 0x6F, 0x6E, 0x69, 0x74, 0x6F, 0x72
/*0x0214      */, 0x0F, 0x53, 0x75, 0x72, 0x76, 0x2E, 0x20, 0x70, 0x72, 0x2E, 0x20, 0x70, 0x6E, 0x65, 0x75, 0x73
/*0x0224      */, 0x1F, 0x02, 0x07
};
#if defined(__COSMIC_SYSTEMS_ICC)  
#pragma section const {}           
#endif                             

#if defined(__IAR_SYSTEMS_ICC)     
#pragma memory=default             
#endif                             

#if defined(__CWCC__)
   #pragma pop
#endif
/*============================================================================
** E N T R Y   P O I N T S
**==========================================================================*/
#if defined(__IAR_SYSTEMS_ICC)     
#pragma codeseg(HMI_LNG_1_CODE)     
#endif                             

#if defined(__COSMIC_SYSTEMS_ICC)  
#pragma section(HMI_LNG_1C)         
#endif                             

#if defined(__IAR_SYSTEMS_ICC)
  #pragma memory=default
#endif
/*============================================================================
** Function Name:    HmLanguage1GetStringLen
** Visibility:		 local
** Description:		 Returns the string length for the passed SID
** Invocation:		 By HmLanguage1GetString
** Inputs/Outputs:	 SID
** Critical Section: String Length
** Created:          16-Aug-2010 by EMANOJ1
** Updated:          16-Aug-2010 by EMANOJ1
**==========================================================================*/
static UINT8 HmLanguage1GetStringLen(LANG_SID_T p_sid)
{
   UINT8 const *p_lang_db_U8P      = (UINT8 const *)&HmStrLngTable1[p_sid];
   UINT8 fl_string_length_U8 = 0;
   UINT8 fl_temp_U8;
   UINT8 fl_command_byte_U8;

   do
   {
      fl_command_byte_U8 = *p_lang_db_U8P;
      fl_temp_U8         = (fl_command_byte_U8  & HMI_LNG_CMD_LENGTH_MASK);
      fl_string_length_U8++;
      if(fl_temp_U8 == HMI_LNG_CMD_LENGTH_MASK)
      {
         /* We got another SID */
         if((fl_command_byte_U8 & HMI_LNG_CMD_EXT_ESID_BIT) != 0)
         {
            fl_temp_U8 = 3;
         }
         else
         {
            fl_temp_U8 = 2;
         }
      }
      p_lang_db_U8P++;
      fl_string_length_U8 += fl_temp_U8;
      p_lang_db_U8P        = &p_lang_db_U8P[fl_temp_U8];
   }
   while((fl_command_byte_U8 & HMI_LNG_CMD_LINK_BIT) != 0);

   return(fl_string_length_U8);
}

/*============================================================================
** Function Name:    HmLanguage1GetString
** Visibility:		 Global
** Description:		 Returns the SID if the requested SID is mapped to another
**                   one (SID linking)
**                   If the requested SID is not linked to another SID, then
**					 writes the string in p_str_dest_P and returns HM_END_OF_SID
** Invocation:		 Invoked by hmi_language_interface.c
** Inputs/Outputs:	 sid, pointer to buffer where the string needs to be returned
**                   and current language as inputs. Returns linked SID if any
** Critical Section: None
** Created:          16-Aug-2010 by EMANOJ1
** Updated:          16-Aug-2010 by EMANOJ1
**==========================================================================*/
#ifdef HM_LANG_USE_INERNAL_STRING_BUFFER
LANG_SID_T HmLanguage1GetString(LANG_SID_T p_sid, HMI_CHAR * p_str_dest_P, UINT8 p_cur_language_U8)
#else
LANG_SID_T HmLanguage1GetString(LANG_SID_T p_sid, HMI_CHAR * p_str_dest_P, UINT8 p_req_length, UINT8 p_cur_language_U8)
#endif
{
   UINT8 const * fl_lang_db_U8P;
#ifdef LNG_UNICODE
   UINT8   fl_codepage_U8;
#endif
   UINT8   fl_str_length_U8;
   UINT8   i;
   UINT8   fl_command_byte_U8;

#ifdef HM_LANG_MAX_SID
	if( p_sid <= HM_LANG_MAX_SID)
 {
#endif
#ifdef HM_LANG_COMMON_MAX_SID
		if( p_sid > HM_LANG_COMMON_MAX_SID)
#endif
		{
#if HM_LANG_MAX_PAGE > 1
			p_sid = (p_sid & HMI_LNG_SID_INDEX_MASK);
#endif
			for (i = 0; i < p_cur_language_U8; i++)
			{
				p_sid += HmLanguage1GetStringLen(p_sid);
			}
		}
	#ifdef HM_LANG_COMMON_MAX_SID
	#if HM_LANG_MAX_PAGE > 1
		else
		{
			p_sid = p_sid & HMI_LNG_SID_INDEX_MASK;
		}
	#endif
	#endif

#ifndef HM_LANG_USE_INERNAL_STRING_BUFFER
   /*
   ** Last location is reserved for null termination so reduce one from
   ** the input buffer length
   */
   if(p_req_length > 0)
   {
      p_req_length--;
   }
#endif

   fl_lang_db_U8P = (UINT8 const *)&HmStrLngTable1[p_sid];
   p_sid          = HM_END_OF_SID;

   do
   {
      fl_command_byte_U8 = *fl_lang_db_U8P;
      fl_lang_db_U8P++;
      fl_str_length_U8    = (fl_command_byte_U8  & HMI_LNG_CMD_LENGTH_MASK);

      if(fl_str_length_U8 == HMI_LNG_CMD_LENGTH_MASK)
      {
         /* We got another SID */
         p_sid   = *fl_lang_db_U8P;
         fl_lang_db_U8P++;
         p_sid <<= 8;
         p_sid  |= *fl_lang_db_U8P;
         if((fl_command_byte_U8 & HMI_LNG_CMD_EXT_ESID_BIT) != 0)
         {
            /*extended p_sid - 3byte coding */
            fl_lang_db_U8P++;
            p_sid <<= 8;
            p_sid  |= *fl_lang_db_U8P;
         }
         /* exit the loop */
         fl_command_byte_U8 = 0;
      }
      else
      {
      #ifdef LNG_UNICODE
         fl_codepage_U8 = (fl_command_byte_U8 & HMI_LNG_CMD_CPAGE_MASK) >> 5;
         if (fl_codepage_U8 == 0x2)
         {
             /* Page 4 */
             fl_codepage_U8 = 4;
         }
         else if(fl_codepage_U8 == 3)
         {
             fl_codepage_U8 = *fl_lang_db_U8P;
             fl_lang_db_U8P++;
             fl_str_length_U8--;
         }
         else
         {
         }
      #endif
      #ifndef HM_LANG_USE_INERNAL_STRING_BUFFER
         if(fl_str_length_U8 > p_req_length)
         {
            fl_str_length_U8 = p_req_length;
            p_req_length     = 0;
         }
         else
         {
            p_req_length -= fl_str_length_U8;
         }
         if(p_req_length == 0)
         {
            /*
            ** We can exit the loop after copying the required length
            */
            fl_command_byte_U8 = 0;
         }
      #endif
         for(i = 0; i < fl_str_length_U8; i++)
         {
         #ifdef LNG_UNICODE
            HMI_CHAR fl_codepage_hmi_char = (HMI_CHAR)(fl_codepage_U8);
            *p_str_dest_P = (fl_codepage_hmi_char << 8);
            *p_str_dest_P|= (HMI_CHAR)(*fl_lang_db_U8P);
            fl_lang_db_U8P++;
         #else
            *p_str_dest_P = *fl_lang_db_U8P;
            fl_lang_db_U8P++;
         #endif
            p_str_dest_P++;
         }
      }
   }
   while((fl_command_byte_U8 & HMI_LNG_CMD_LINK_BIT) != 0);
   *p_str_dest_P = 0;
#ifdef HM_LANG_MAX_SID
   }
   else
   {
			*p_str_dest_P = 0;
   }
#endif
   return(p_sid);
}

#if defined(__COSMIC_SYSTEMS_ICC)
#pragma section {}
#endif

#if defined(__IAR_SYSTEMS_ICC)
#pragma memory=default
#endif

/*============================================================================
**
**============================================================================
** C M S    R E V I S I O N    N O T E S
**============================================================================
**
** For each change to this file, be sure to record:
** 1.  Who made the change and when the change was made.
** 2.  Why the change was made and the intended result.
**
** CMS Rev #        Date         By
** CMS Rev X.X      mm/dd/yy     CDSID
**
**============================================================================
**
** Rev 1.2          23-Jul-2015 by ARAJASE2
** Changes done to fix the following QAC Warnings.
** 1.++ WARNING ++: <=4=(5209) Use of basic type 'unsigned char'.
**		Changes: 'unsigned char' is changed as UINT8
** 2.++ WARNING ++: <=7=(2212) Body of control statement is not enclosed within braces.
**		Changes: Added open and close braces for else loop
** 3.++ WARNING ++: <=7=(5133) Comment delimiter found within comment. 
**
**============================================================================
**
** Rev 1.1          29-Jan-2015 by ARAJASE2
** Changes done to fix the following QAC Warnings.
** 1.++ WARNING ++: <=7=(0311) Dangerous pointer cast results in loss of const qualification.
**		Changes: UINT8       *p_lang_db_U8P	 = (UINT8       *)&HmStrLngTable1[p_sid]; is changed as 
**            UINT8 const *p_lang_db_U8P  = (UINT8 const *)&HmStrLngTable1[p_sid];
** 2.++ WARNING ++: <=5=(3440) Using the value resulting from a ++ or -- operation.
**		Changes: x = *ptr++ changed as x = *p; p++;
** http:/stackoverflow.com/questions/859770/on-a-dereferenced-pointer-in-c
**
**============================================================================
** Rev 1.0          16-Aug-2010 by EMANOJ1
** Initial revision.
**
**==========================================================================*/

/* end of file =============================================================*/
