/***************************************************************************** 
*                                                                            * 
*              CONFIDENTIAL VISTEON CORPORATION                              * 
*                                                                            * 
* This is an unpublished work of authorship, which contains trade            * 
* secrets, created in 2009. Visteon Corporation owns all rights to           * 
* this work and intends to maintain it in confidence to preserve             * 
* its trade secret status. Visteon Corporation reserves the right,           * 
* under the copyright laws of the United States or those of any              * 
* other country that may have jurisdiction, to protect this work             * 
* as an unpublished work, in the event of an inadvertent or                  * 
* deliberate unauthorized publication. Visteon Corporation also              * 
* reserves its rights under all copyright laws to protect this               * 
* work as a published work, when appropriate. Those having access            * 
* to this work may not copy it, use it, modify it or disclose the            * 
* information contained in it without the written authorization              * 
* of Visteon Corporation.                                                    * 
*                                                                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
File Name:          hmi_gfx_mgr_font.h                                         
Module Short Name:  GFX_MGR                                                    
VOBName:            sw_hmi_ss                                                  
Author:             emanoj1                                                    
Description:        Graphics Manager                                           
                    Autogenerated by GDT v1.0.41. Do not handmodify this file. 
                    Generated on MM/DD/YYYY - 6/19/2011
Organization     :  Driver Information Software Section,                       
                    Visteon Corporation                                        
List the compiler name with the ersion number                                  
List the Target processor with the variant information                         
----------------------------------------------------------------------------   
Compiler Name:      ANSI C                                                     
Target Processor :  ANY                                                        
******************************************************************************/
#ifndef HMI_GFX_MGR_FONT_H
#define HMI_GFX_MGR_FONT_H
                                                                               
/***************************************************************************** 
*                                 System Includes                            * 
******************************************************************************/
#include "hmi_gfx_manager.h"
                                                                               
/***************************************************************************** 
*                                 Project Includes                           * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                 Manifest Constants                         * 
*----------------------------------------------------------------------------* 
* Definition of constant shall be followed by a comment that explains the    * 
* purpose of the constant.                                                   * 
******************************************************************************/
                                                                               
#define GFX_FONT_SEARCH_MODE_TLUP    0x01
#define GFX_FONT_SEARCH_MODE_DIRECT  0x02
#define GFX_FONT_ENCODING_1BPP       0x04
#define GFX_FONT_ENCODING_2BPP       0x08
#define GFX_FONT_ENCODING_4BPP       0x0C

#define GFX_LUP_LINEAR               (0)
#define GFX_LUP_BINARY               (1)
#define GFX_LUP_HYBRID               (2)

/***************************************************************************** 
*                                 Macro Definitions                          * 
*----------------------------------------------------------------------------* 
* Definition of macro shall be followed by a comment that explains the       * 
* purpose of the macro.                                                      * 
******************************************************************************/

#define GFX_FID_METABOOK_CAPS_12 (0)
#define GFX_FID_METABOOKLF_CAPS_10 (1)
#define GFX_FID_METABOOK_CAPS_24 (2)
#define GFX_FID_METABOOK_ROMAN_20 (3)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_CN_9 (4)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_12 (5)
#define GFX_FID_MYRIAD_PRO_18 (6)
#define GFX_FID_MYRIAD_PRO_BOLD_16 (7)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_LT_10 (8)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_11 (9)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_LT_8 (10)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_LT_14 (11)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_20 (12)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_BOLD_CN_10 (13)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_BOLD_CN_14 (14)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_CN_12 (15)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_CN_8 (16)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_BOLD_CN_19 (17)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_CN_16 (18)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_CN_20 (19)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_CN_30 (20)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_BOLD_CN_12 (21)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_CN_14 (22)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_CN_14 (23)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_LT_CN_12 (24)
#define GFX_FID_MYRIAD_PRO_16 (25)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_BOLD_MD_12 (26)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_12 (27)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_BOLD_9 (28)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_LT_13 (29)
#define GFX_FID_MYRIAD_PRO_24 (30)
#define GFX_FID_MYRIAD_PRO_14 (31)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_18 (32)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_20 (33)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_14 (34)
#define GFX_FID_MYRIAD_PRO_12 (35)
#define GFX_FID_BERTHOLD_AKZIDENZ_GROTESK_MD_CN_14_ITALIC (36)
#define GFX_CHAR_SEARCH_MODE        (GFX_LUP_LINEAR)
/***************************************************************************** 
*                                 Type Declarations                          * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                                Globally  accessed Variable Declarations    * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the variable.                                                        * 
* purpose, critical section, unit, and resolution                            * 
******************************************************************************/
                                                                               
extern GFX_FONT const lc_gfx_font_table[37];
                                                                               
/***************************************************************************** 
*                                 Locally used Variable Declarations         * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the variable.                                                        * 
* purpose, critical section, unit, and resolution                            * 
******************************************************************************/
                                                                               
/***************************************************************************** 
*                       Locally used Constant Declarations                   * 
*----------------------------------------------------------------------------* 
* Declaration shall be followed by a comment that gives the following info.  * 
* about the constant.                                                        * 
* purpose, unit, and resolution                                              * 
******************************************************************************/
                                                                               

#endif
